### ISSUE TITLE
Is there any functional difference between AVS on RPI3 and Amazon Echo?

### ISSUE THREAD

**Issue by Hakalon** [alexa/alexa-skills-kit-sdk-for-nodejs#100]
I just built AVS(Amazon Voice Service) on RPI3 and made some skills through ASK(Amazon Skills Kit) recently, and found the bluetooth can't be activated on RPI3.

This is different from Amazon Echo (I can ask Echo to connect to my phone through bluetooth and play my music).

So I wonder is there any functional difference between them except bluetooth?

If it's not, maybe I can use RPI3 with microphone and speaker to replace Amazon Echo.

**Comment by michaelborchardt** [comment]
Raspberry Pi's are incredibly fun to build onto, from a hardware and software perspective. Echo has stock software that is integrated into the hardware, it's always going to be superior to a homemade RPI3 turned into an echo, with regards to the intent Amazon had for the function of the product. Albeit, with enough time and careful dedication, you could easily turn your RPI3 into something much cooler than what a stock Echo would be. For example, break down the walls of the Node.js Skills SDK and use the AVS in combination, then find a way to connect the RPI3 to a communications channel and train the RPI3 with ML and custom skills to monitor and react to the communication passing through the channel. An echo will always be an echo, an RPI3 could be some much, much cooler. RPI3's aren't constrained to legality and safety, they're meant for experimenting. I say keep the echo and go experiment man.

**Comment by KrishFuriaAmazon** [comment]
This issue not relevant to skills-kit alexa-sdk. Please use [AVS Forums](https://forums.developer.amazon.com/topics/alexa+voice+service.html) for this kind of discussions.
