### ISSUE TITLE
Question or Issue about State and Saving to DynamoDB

### ISSUE THREAD

**Issue by EJAtPhunWare** [alexa/alexa-skills-kit-sdk-for-nodejs#102]
v 1.0.8
Currently when state is removed, i.e. `this.handler.state = ""; `the new value is not reflected in DynamoDB due to the following check:  response.js:122 -> `if(forceSave && this.handler.state)` is this a bug? or, is this working as designed? meaning, after you set a state, there is no possible way to reset it, forcing any subsequent request to be subject to the last saved state?

**Comment by michaelborchardt** [comment]
In the implementation of the state object, the value of the object is set to null each time a request is called. You could think of the requests as running in independent cycles. Since two requests will never be ran at any given time, the value for state will always be reset before the next request is processed,

**Comment by EJAtPhunWare** [comment]
Hello Michael, thanks for responding. That makes perfect sense, I'll continue investigating, but somehow the behavior I'm seen does not match what you stated. I see things like, next brand new session requests been sent to the previous state specific NewSession handler, while session attributes contain "STATE" having the last cycle state. 

Thanks for replying, sincerely hope is an issue on my side.

**Comment by michaelborchardt** [comment]
I've honestly only studied the architecture and documentation on Alexa; I haven't gone through a build sequence yet. So my inferences are based on what I know about the components and how they should behave. If I had to take a guess, I'd make sure that the second request isn't getting invoked before the thread has terminated the first. That sounds like a threading issue to me.

**Comment by EJAtPhunWare** [comment]
I hear you, I thought the same and still think that should be the case. When I reference "next request" I'm not talking about emit to a different handler (function), I'm only referring to a user invoking the skill, completing a session (":tell"), then same user opening the app again and seen on logs that previous state was loaded for that user. Again I'm going from what I see in the request payload attributes, but I'll debug and try to analyze these cycles a little more. Will share my findings, still hoping is a bug on my side or that I'm not logging out the right key information.

**Comment by michaelborchardt** [comment]
I have to go work on flashing some iso images to a server and then fix a hard drive for the rest of the day, but I'll look into the issue more when I get back. The guy who maintains this repository is excellent at diagnosing these matters; I'm sure he'll probably pop in some time tonight with a better solution than I can offer. Good luck!

**Comment by EJAtPhunWare** [comment]
Thanks you,

I just added a few logs, and I can confirm that the last previous saved state stored in dynamo-DB for a user is been loaded for a brand new session.

**Comment by knowlsie** [comment]
This is actually a feature - you see DynamoDB has no way to store empty strings as attributes. If you want to reset the state, you need to totally remove that from the attributes, then save. You can do this manually by doing `this.attributes.STATE = undefined` (or `this.attributes['STATE'] = undefined`) before you save the state.

**Comment by michaelborchardt** [comment]
Okay, real quick, try implementing a custom event at the end of your request invocation cycle that calls the state object and resets the value, so at the threads context switch to a new process the state is cleared and your implementation isn't relying on the current implementation.

**Comment by knowlsie** [comment]
Yo @michaelborchardt - from my knowledge/use of Lambda, it can run a ton of requests to the same code at the same time, and all on totally separate threads. It's really unlikely to be a threading issue.

**Comment by michaelborchardt** [comment]
@knowlsie 

AWS Lambda is an elastic service that is designed to handle and process large amounts of requests. I was more concerned that his problem was doing the majority of his computations on the main thread, and that's why it wasn't executing correctly.

**Comment by EJAtPhunWare** [comment]
Wow thanks a lot  guys, I was kind of tempted to remove the attribute myself (delete attribute), will do so to clear state. I'm glad that now I understand why this behavior is like this. I'm new to DynamoDB, didn't know empty strings couldn't be stored, to me is not intuitive coming from other document databases (**not saying this behavior is bad or anything, just not aligned with my experience**), thanks a million!! Thanks @knowlsie
