### ISSUE TITLE
Error: Process exited before completing request

### ISSUE THREAD

**Issue by shyam-dhanotiya** [alexa/alexa-skills-kit-sdk-for-nodejs#105]
I am new to Alexa skill and nodejs. I am accessing some file from S3 bucket with following code snippet.
```javascript
'use strict';

const Alexa = require('alexa-sdk');
const AWS = require('aws-sdk'); 
const s3 = new AWS.S3({httpOptions: { timeout: 2000 }});

const APP_ID = undefined; // TODO replace with your app ID (OPTIONAL).

const handlers = {
    'NewSession': function(event, context) {
        setTimeout(() => {
            s3.getObject({
                Bucket: 'bucket1',
                Key: 'file1.txt',
            }, function (err, data) {
                console.log('this is happening!');
                console.log(err);
                
                console.log(data.Body.toString('ascii'));
            
              
                this.attributes.speechOutput = "file accessed successfully"; 
                this.attributes.repromptSpeech = "file accessed successfully";
                this.emit(':ask', this.attributes.speechOutput, this.attributes.repromptSpeech); 
              
              context.done();
            }); 
        }, 1000);
}

 exports.handler = (event, context) => {
    const alexa =   Alexa.handler(event, context);
    alexa.registerHandlers(handlers);
    alexa.execute(); 
};
```
showing filedata in log but I am getting error message RequestId: 0c1fc82b-1c9a-11e7-bbee-b3d367e0b34e Process exited before completing request"

Also if settimeout is removed and only s3.getobject used then unable to access s3. Please help.

Edit: formatting

**Comment by rmtuckerphx** [comment]
Check out this starter template that also calls S3 (see translations.js). Hope it helps:
https://github.com/rmtuckerphx/alexa-skill-serverless-starter-template

**Comment by feedm3** [comment]
You should not call `context.done()` as this is done in the `this.emit(...)` call. So the problem could be that you end the context before the emit call handled the response.

```
const handlers = {
    'NewSession': function() {
            s3.getObject({
                Bucket: 'bucket1',
                Key: 'file1.txt',
            }, function (err, data) {
                console.log('this is happening!');
                console.log(err);
                
                console.log(data.Body.toString('ascii'));

                this.attributes.speechOutput = "file accessed successfully"; 
                this.attributes.repromptSpeech = "file accessed successfully";
                this.emit(':ask', this.attributes.speechOutput, this.attributes.repromptSpeech); 
            }); 
}
```

**Comment by knowlsie** [comment]
Hey @shyam-dhanotiya can you possibly close this issue down if your problem is fixed? Thanks!

**Comment by shyam-dhanotiya** [comment]
Found a solution. Actually I was not getting file data because I have not added call back and due to this it passes to emit when it goes for reading file.

here is the solution:


    'NewSession': function(event, context) {
 var myParams = {
                Bucket: 'bucketname',
                Key: 'users.txt',
            };
  getUserinfo(myParams, myResult => { 
                var obj = JSON.parse(myResult);
                var isValidPassCode = false;
                if(obj !== null && obj.User !== null)
                {
                       this.attributes['isValidPassCode'] = true; 
                        this.attributes.speechOutput = this.t('PASSCODE_VERIFIED');
                        this.attributes.repromptSpeech = this.t('PASSCODE_VERIFIED_REPROMPT');
                    }
                    else {
                        this.attributes.speechOutput = this.t('PASSCODE_NOTVERIFIED');
                        this.attributes.repromptSpeech = this.t('PASSCODE_NOTVERIFIED');
                        //Need to end session.
                    }
                this.emit(':ask', this.attributes.speechOutput, this.attributes.repromptSpeech); 
            });  }


function getUserinfo(params, callback) {
    // call AWS S3
    var AWS = require('aws-sdk');
    var s3 = new AWS.S3();

    s3.getObject(params, function(err, data) {
        if(err) { console.log(err, err.stack); }
        else {

            var fileText = data.Body.toString();  // this is the complete file contents
            callback(fileText);
        }
    });
}
