### ISSUE TITLE
SOAP Web Request -- inside an intent of a state

### ISSUE THREAD

**Issue by batuhangundogdu** [alexa/alexa-skills-kit-sdk-for-nodejs#106]
Hello,

I'm trying to make a SOAP web request to a WebService. I have 4 states and I'm making the request if parameters from first three states are succesfully got from user. I use 'request' npm module using the request. 
When I make the request seperately inside a lambda function, service returns me a valid response.  But  when I make the request inside the alexa-sdk powered code, the same working request code returns me 'undefined' response. I could not figure it out why.

**Comment by knowlsie** [comment]
Hey. I have something like this working, so this is a non-SDK issue. The first thing that comes to mind is kinda basic, but a fairly likely issue. If you're getting an `undefined`, the API you're making requests to may not be getting time to send a response, before you send your response to Alexa. This would mean your variable isn't even being set before `context.succeed()` is called. Make sure that you're only emitting to Alexa after you've done your request, as it may be exiting the process before your request is complete - the code that emits your response (which then calls `context.succeed()`) should be in a callback of the request, or a `.then()` if you're using promises.

**Comment by batuhangundogdu** [comment]
this.emit('getRes', (response) => {
             var myvar = response["S:Envelope"]["S:Body"]["blabla"];
             this.emit(":tell", "words that alexa will say");
         });

is the code that I call the function inside an intent.

        var requestHandler = {
       'getRes': function(callback) {
        try {
             request.post({
                     url: 'https://theEndpoint',
                     body: requestData,
                     'auth': {
                         'user': 'user',
                         'pass': 'pass'
                     },
                     headers: { 'Content-Type': 'text/xml' }
                 },
                 function(error, response, body) {
                     if (true) {
                         console.log("request : ", requestData);
                         parser.parseString(body, function(err, result) {
                             var dom = result;
                             callback(dom);
                         });
                     } else {
                         console.log('error');
                     }
                 }
             );
         } catch (err) {
             console.log(err);
         }
       }
      }

is the function that I make the request. The function itself works great when I use it in a seperate lambda function. But the log output is 

`request : undefined`

I am using a callback structure, but what is the chance that I'm using it in a wrong way ?

**Comment by knowlsie** [comment]
Ah, looks like the request data is undefined, not the response - that wasn't clear. I cannot think of a good reason why that would happen, unless it was defined in a way that wasn't accessible to the handler scoping.

**Comment by knowlsie** [comment]
Hey @batuhangundogdu let me know if this resolved your issue or not. If it did, can you please close this issue down? Thanks.

**Comment by batuhangundogdu** [comment]
hello, it seems it was my fault, that I was creating the request invalid; I was getting the request Strings as parameters from outside scope but they were coming undefined. So I worked that problem out and problem solved :)

**Comment by knowlsie** [comment]
Great to hear! (Can you just click 'Close issue' now this is solved?)
