### ISSUE TITLE
can't run npm install --save alexa-sdk

### ISSUE THREAD

**Issue by mingxino** [alexa/alexa-skills-kit-sdk-for-nodejs#108]
I copied the package.json to my directory and run npm install --save alexa-sdk in my node.js environment. I got the error "Refusing to install alexa-sdk as a dependency of itself"

**Comment by benedekh** [comment]
This repository contains the source code of the `alexa-sdk` module. If you would like to use this module, just add it as a dependency in your package.json file (don't copy the file itself from this repository) and run the `npm install --save alexa-sdk` command in your project.

**Comment by mingxino** [comment]
It helps a lot. Thanks so much!!
