### ISSUE TITLE
TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by RobertCazaciuc** [alexa/alexa-skills-kit-sdk-for-nodejs#109]
Hi guys,

I am trying to get a very basic set-up working and I've encoutered a problem that I can't seem to find a solution for. I am testing my handler locally using aws-lambda-local with the following syntax.

`lambda-local -f index.js -e intent_schema/event_launch_rob_test.json`

Everything seems to be working fine on my machine. But after I zip the folder and upload it to AWS and press test i get the following error. Does anyone know what I am doing wrong?

`START RequestId: 39cf8bcb-2043-11e7-aa8b-b9609797fdc5 Version: $LATEST
2017-04-13T12:17:57.389Z	39cf8bcb-2043-11e7-aa8b-b9609797fdc5	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:103:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:92:31)
    at exports.handler (/var/task/index.js:7:11)
END RequestId: 39cf8bcb-2043-11e7-aa8b-b9609797fdc5
REPORT RequestId: 39cf8bcb-2043-11e7-aa8b-b9609797fdc5	Duration: 56.48 ms	Billed Duration: 100 ms 	Memory Size: 320 MB	Max Memory Used: 27 MB	
RequestId: 39cf8bcb-2043-11e7-aa8b-b9609797fdc5 Process exited before completing request`

I am attaching my handler and my intent schema. I have also posted the question [here](https://forums.developer.amazon.com/questions/48212/typeerror-cannot-read-property-locale-of-undefined.html)

[event_launch_rob_test.json.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/files/920299/event_launch_rob_test.json.txt)
[index.js.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/files/920300/index.js.txt)

**Comment by RobertCazaciuc** [comment]
I should add that since I've posted this I realised that actually the handler works when I test it end-to-end with the alexa skill set that I have defined.

So if I request LaunchRequest from the alexa skill set portal I get the response back!!

So the error above is even more confusing - why would this be returned in the lambda test portal?

**Comment by knowlsie** [comment]
I can tell you this is working in the other (better supported) [lambda-local](https://github.com/ashiina/lambda-local). It's likely something to do with aws-lambda-local not getting the request correctly, as the locale is just the first thing it happens to get the request.

**Comment by RobertCazaciuc** [comment]
Hi there. Maybe I didn't explain the problem correctly. The above code works with aws-lambda-local when I test it on my local machine. The error that I get is on Amazon's website when I upload the zip file to the lambda management console - please see the 2 photos attached.

![aws zip error](https://cloud.githubusercontent.com/assets/11447682/25084393/18e69010-2354-11e7-94aa-f407685e3a8e.PNG)
[aws error.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/files/925231/aws.error.txt)

**Comment by knowlsie** [comment]
My bad, I misread that top bit. To check some basics first: have you appropriately edited the event in Lambda, by clicking 'Actions' then 'Configure Event'? Just copy your request in there.

**Comment by RobertCazaciuc** [comment]
Hey there. I have found the issue with your help. I wasn't aware that the test can be configured. I thought that the test was a modular test that didn't require an input to be passed it to it - more like a basic/logic syntax check. I was able to pass the same json formatted utterance as from the aws portal and the function worked correctly. I think this can be marked as solved

**Comment by sah2ed** [comment]
I encountered a similar error while testing a sample skill with Postman: 
```TypeError: Cannot read property 'locale' of undefined``` 

It turns out that invocation of the lambda function worked just fine within AWS using either:
- the `Actions` -> `Configure test event` screen of AWS Lambda;
- the Service Simulator screen of [Alexa skills](https://developer.amazon.com/edw/home.html) or;
- API Gateway; 

but not from my machine or from a Digital Ocean VM. The fix was to relax the Lambda function policy to be more permissive. 

### Relaxing the policy (**This was done for testing purposes!**)
From the `Lambda` -> `Functions` -> `<Funtion Name>` screen of AWS [Lambda dashboard](https://console.aws.amazon.com/lambda/home?region=us-east-1#/),  add a new trigger via the `+ Add trigger` button. In the modal dialog that appears, click inside the dotted square (with rounded corners) then choose `API Gateway`. Complete the from by selecting the name of the lambda function then choose a less restrictive policy like `Open` in the drop down for *Security* instead of `AWS IAM`, or `Open with access key` policies. 

The following less restrictive entries were added to the lambda's function policy:
```
 {
            "Sid": "<sid>",
            "Effect": "Allow",
            "Principal": {
                "Service": "apigateway.amazonaws.com"
            },
            "Action": "lambda:InvokeFunction",
            "Resource": "arn:aws:lambda:us-east-1:<account-id>:function:LambdaNameSkill",
            "Condition": {
                "ArnLike": {
                    "AWS:SourceArn": "arn:aws:execute-api:us-east-1:<account-id>:<api-id>/Test/ANY/LambdaNameSkill"
                }
            }
        },
        {
            "Sid": "<sid>",
            "Effect": "Allow",
            "Principal": {
                "Service": "apigateway.amazonaws.com"
            },
            "Action": "lambda:InvokeFunction",
            "Resource": "arn:aws:lambda:us-east-1:<account-id>:function:LambdaNameSkill",
            "Condition": {
                "ArnLike": {
                    "AWS:SourceArn": "arn:aws:execute-api:us-east-1:<account-id>:<api-id>/*/*/LambdaNameSkill"
                }
            }
        }
```
