### ISSUE TITLE
with new sdk, how to do one-shot intent as well as dialog model in same app

### ISSUE THREAD

**Issue by marcejohnson** [alexa/alexa-skills-kit-sdk-for-nodejs#110]
Quick question/request (hopefully) ... With previous codebase the "scorekeeper" example demonstrated the ability to do one-shot and dialog in the same app:
https://forums.developer.amazon.com/questions/41083/sample-code-for-demonstrating-howto-with-one-shot.html

What example code demonstrates this with the newer sdk for nodejs?  If there is no sample code, what would be the call sequence/handler structure via alexa-skills-kit-sdk-for-nodejs?

THANKS  and please advise,
Marc

**Comment by McGern** [comment]
What was your resolution for this? I am also wondering what the correct pattern to use for the new sdk.
