### ISSUE TITLE
elicitSlot returning null when testing lambda

### ISSUE THREAD

**Issue by JCallico** [alexa/alexa-skills-kit-sdk-for-nodejs#111]
Any idea why :elicitSlot returns null? If I replace it with :tellWithCard it works.

```
if (!intent.slots.Year.value) {
  let slotToElicit = 'Year';
  let speechOutput = this.t('ELICIT_YEAR_MESSAGE');
  let repromptSpeech = speechOutput;
  this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech); // returns null when testing  
  // this.emit(':tellWithCard', speechOutput, this.t('SKILL_NAME'));	// returns expected response
}
```

**Comment by knowlsie** [comment]
I've not had any issues with :elicitSlot. Just checking, is your alexa-sdk at version 1.09?

**Comment by JCallico** [comment]
I was experiencing the problem when running the lambda on Amazon, when I switched the Skill to use a proxy running the lambda locally everything started working as expected.

**Comment by knowlsie** [comment]
OK. I've been using it on Amazon just fine. Are you uploading a `.zip` file (or uploading via S3) in a way which includes the `node_modules` folder, or are you just uploading a `.js` file?

**Comment by knowlsie** [comment]
I'm guessing you're just uploading/copying in a `.js` file because that won't work for me either. I guess they haven't updated the version of alexa-sdk pre-installed in Lambda. If you upload a deployment package with your own version of the alexa-sdk at v1.09 then it works.

**Comment by JCallico** [comment]
You are correct. Initially I was using the "inline code" option and it was not working. When I tried uploading a .zip file containing all my project's files it worked as expected.

**Comment by stormbytes** [comment]
My question is tangential. I have found having to use the Builder for the turn-by-turn stuff (Dialog models) and coding intentHanlders really confusing. I'm trying to use the Alexa-SDK (v.1.0.10 zipped into deployment pkg) along with the code example showing the use of :elicitSlot and :confirmSlot directives. It tests out fine in the console but produces an error when testing on the Echo device. In short, does the code example in the Alexa-SDK docs rely on some sort of Builder beta dialog model? Spent 2 days on this issue so far....

**Comment by JCallico** [comment]
I remember having some similar issues. 

Did you build your interaction model using the Interaction Model Builder (Beta)? If you did, then check your interaction model code and see if it includes a prompts and a dialog section. I remember having to add a "dummy" prompt to make the builder generate a dialog section. Without the dialog section any Elicit action returned from your lambda will fail.

```
  "prompts": [
    {
      "id": "Elicit.Intent-TopSector.IntentSlot-Sector",
      "promptVersion": "1.0",
      "definitionVersion": "1.0",
      "variations": [
        {
          "type": "PlainText",
          "value": "Which sector are you interested in"
        }
      ]
    }
  ],
  "dialog": {
    "version": "1.0",
    "intents": [
      {
        "name": "TopSector",
        "confirmationRequired": false,
        "prompts": {},
        "slots": [
          {
            "name": "Sector",
            "type": "SectorTypes",
            "elicitationRequired": true,
            "confirmationRequired": false,
            "prompts": {
              "elicit": "Elicit.Intent-TopSector.IntentSlot-Sector"
            }
          }
        ]
      }
    ]
  }
```

**Comment by stormbytes** [comment]
That's pretty much what I have...

https://gist.github.com/stormbytes/9e220f1af8a2ed8e17c69542a3a9d38d

**Comment by NealWalters** [comment]
Did you ever solve?  I think I'm in the same boat now. 
Thanks,
Neal

**Comment by JCallico** [comment]
Hi @NealWalters 

In my case switching from "inline code" to uploading a .zip file containing all the files in my local project did the trick.

It seems that the default packages installed by Amazon were not up-to-date and didn't support the elicitSlot functionality.

**Comment by NealWalters** [comment]
Ok, thanks.  I'm already doing that with version 1.0.18.
Started a thread here: https://forums.developer.amazon.com/questions/95094/elicitslot-results-in-there-was-a-problem-with-the.html

Neal
