### ISSUE TITLE
alexa-skill-kit-sdk-factskill is not bundled with the right version of alexa-sdk

### ISSUE THREAD

**Issue by knowlsie** [alexa/alexa-skills-kit-sdk-for-nodejs#114]
As https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/111 showed, the version of alexa-sdk bundled with alexa-skill-kit-sdk-factskill is not 1.09. I'm not totally sure where to report this, so I figured it'd make most sense to put it here. The [alexa-cookbook](https://github.com/alexa/alexa-cookbook/tree/master/tools) claims it's bundled with alexa-sdk, so you should resolve this ASAP for the sake of beginners.

If you want to resolve this, make a [deployment package](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-create-deployment-pkg.html) with your own of alexa-sdk at version 1.09, and upload the .zip file, rather than using the in-line editor.

**Comment by KrishFuriaAmazon** [comment]
Thanks, @knowlsie, I will be taking a look at this one!

**Comment by knowlsie** [comment]
Awesome, you're the best @KrishFuriaAmazon. Just to note I haven't checked this since I made the issue 2 weeks ago, so someone on the Lambda side could have solved it already.

**Comment by TestMannequin** [comment]
This issue still exists, it has not been resolved alredy.

**Comment by rszarek** [comment]
Is there a template somewhere? I'm new and not quite sure where or how it insert, intent or response!!!! Please help please!!! If I could get anyone who would be interested in helping a girl out would be greatly appreciated!! If you could please message me and I could explain what I'm trying to do would be allot more informative than trying to do it over this blog...fb.. Rhonda aszarek. Thank you

**Comment by kcrosley-leisurelabs** [comment]
AFAICT, this is still an issue.  Been banging my head against the wall about this.emit(':delegate'); not doing anything (and dialog model stuff seemingly not working)... and then found this.

If there's anybody with the power to correct this issue, "that'd be great." ;)

**Comment by knowlsie** [comment]
Yup, still an issue. Just checking, is everything working for you now @kcrosley-leisurelabs ?

**Comment by kcrosley-leisurelabs** [comment]
Hi @knowlsie - thanks for your response!  Not clear on what your question is?  (Are you saying this has just now been fixed and to test??)

In general, this sdk is awesome, but I do like taking advantage of the inline code editor of AWS Lambda (so, need the correct basic functionality to be supported w/o requiring a Zip upload).  Have been creating (what to me is) a very slick custom chatbot and this sdk supported natively in AWS Lambda has been a godsend.  Went from absolute beginner (WRT Alexa) to extremely functional skill in a matter of a few hours yesterday.

Hit my first serious problem when trying to take advantage of delegating multi-turn convos to Alexa and discovered that (like others) it seems that those features are not possible at the moment...

Cheers,
Keith

**Comment by kcrosley-leisurelabs** [comment]
(And, NOPE, I still get "there was a problem with the requested skill's response as soon as this.emit(':delegate'); is called.)

**Comment by knowlsie** [comment]
My bad on the unclear message, I basically just meant to ask if dialog models and associated events are working now you're using the .zip upload? (Sorry, I can't fix the root issue as I'm not with Amazon or anything.)

**Comment by kcrosley-leisurelabs** [comment]
No worries!  I've not tried the multi-turn dialog stuff using Zip upload.  Figured I might just punt on the multi-turn/delegated stuff that for a bit.  I'm finding it very helpful to be able to code/debug/build-out-content in the AWS "interpreter-like" environment, testing live on an "Amazon Dash Wand with Alexa" as I go!

Here's a lil video of my work in progress (no multi-turn stuff shown here as it's not functional). This is a custom chatbot for my vacation rental in Palm Springs:

https://vimeo.com/222426000

**Comment by bclement-amazon** [comment]
The blueprints on lambda have been updated. If you create a new lambda blueprint, you'll get alexa-SDK 1.0.10 which includes support for dialog management directives.

On another note, This took way too long to get updated and I'm working with teams internally to streamline this process so that lambda console users can have the same user experience as those developing on their local machine.

**Comment by NealWalters** [comment]
And now (Nov 2017) the SDK on GitHub is 1.0.18 and the one from the Lamba install is 1.0.10. 
I'm still stuck with this https://forums.developer.amazon.com/questions/94391/using-alexa-sdk-unable-to-import-module-index-erro.html when trying to upload.  But no such problem when using the default SDK, but I think I'm hitting other issues now related to the older release. 
Neal
