### ISSUE TITLE
No Intent Schema

### ISSUE THREAD

**Issue by madrhatter** [alexa/alexa-skills-kit-sdk-for-nodejs#117]
There's no sample intent schema for this project.

**Comment by rmtuckerphx** [comment]
This is the SDK that can be used in a starter template but it is not a starter template or sample. 

For samples of starter templates, click this [link](https://github.com/alexa) and then look for:
- skill-sample-nodejs-team-lookup
- skill-sample-nodejs-trivia
- skill-sample-nodejs-quiz-game
- skill-sample-nodejs-highlowgame
- skill-sample-nodejs-howto
- skill-sample-nodejs-fact
- etc.

Or you can use a more advanced starter template, such as:
https://github.com/rmtuckerphx/alexa-skill-serverless-starter-template

Best wishes in your skill development.

Mark

**Comment by KrishFuriaAmazon** [comment]
Thank @rmtuckerphx! Closing issue for now, feel free to re-open if you need more help.
