### ISSUE TITLE
What is the correlation between the code in this repo and what is published on npm?

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-skills-kit-sdk-for-nodejs#118]
The code published on npm is version 1.0.9 whereas the last release of this project was 1.0.6. If there is code in the 1.0.9 version that is not in this repo and if there are accepted PRs in this repo that are not in the 1.0.9 release then how do we really know the state of where this SDK is? How do I know which pull requests are part of which releases? Am I missing something?

**Comment by knowlsie** [comment]
I'm in agreement; in case you want the current state of play, the repo is ahead of 1.09, and to my knowledge has everything that 1.09 has.

**Comment by KrishFuriaAmazon** [comment]
Thanks @knowlsie. We usually publish the new npm version if there is a code or a functionality change to the sdk. Since last PR's which were accepted were mostly Readme updates, it does not make sense to update npm to a new version as most devs will look at readme on the GitHub and not in node_modules. Does this make sense?

**Comment by benedekh** [comment]
@KrishFuriaAmazon I think what @knowlsie tries to point out is, on the [Releases](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/releases) tab of the repository the latest release is said to be 1.0.6 (that is basically a tag). However, the `package.json` on the main branch contains 1.0.9, which conforms to npm.

**Comment by rmtuckerphx** [comment]
@benedekh that is exactly what I was trying to point out. @KrishFuriaAmazon  Because tags and releases have not been used since 1.0.6 (Sep 14, 2016) there is no easy way to see what changes were committed in a specific version/release. What I am asking, is can you please start using tags and releases again starting with 1.0.10?

**Comment by KrishFuriaAmazon** [comment]
Thanks @benedekh and @rmtuckerphx. Yes, I will make sure we update the releases and tags too!
