### ISSUE TITLE
JSON after account linking

### ISSUE THREAD

**Issue by tarekzaibet** [alexa/alexa-skills-kit-sdk-for-nodejs#119]
Hello, I am currently working on linking my Alexa skill with google calendar api. I set up the account linking in the developer portal etc and I was able to link my account to the google api. However In order to use the google API, I need to have an accessToken.

From what I have seen in this forum, Once the account is linked, I can get the accessToken in the JSON response in "this.event.session.user.accessToken" . 

However when testing my skill (already linked with google ) in the amazon developer portal, in the JSON response there is no accessToken field but only userId. 

Does anybody have a solution to this ? or any Idea to help dealing with account linking testing ? 

Thank you in advance !

**Comment by KrishFuriaAmazon** [comment]
If you are not getting accessToken you have mostly likely not linked your account correctly. However, if you are using this sdk you can check if accessToken is missing you can emit 'tellWithLinkAccountCard' to relink your account.

**Comment by knowlsie** [comment]
@KrishFuriaAmazon Could you possibly check whether you're meant to get the accessToken in the Alexa Skill testing portal (i.e. the one on the Alexa Skill config page)? If I remember correctly, I didn't get an accessToken in that portal either, even when the account linking was all set up and working on the Echo itself. As a result, I now don't use the testing portal, and just test entirely locally, or on an actual Echo/Echosim. (While this therefore doesn't affect me much, it might be confusing for new devs, so it's worth looking into.)

**Comment by bclement-amazon** [comment]
@knowlsie has a good point. But I ran a test in the simulator with one of my account-linked skills and the access token is being sent correctly.

Do you have the same issue when testing with another endpoint, like a real device or https://echosim.io ?

**Comment by eercanayar** [comment]
Also you can check the skill page if it says 'account linking required'. If the linking is done completely, the request **should** contain the accessToken.

**Comment by Amazon-tianrenz** [comment]
Closing this for now. Please feel free to reopen the issue if problem persists.
