### ISSUE TITLE
Cannot find module 'i18next'

### ISSUE THREAD

**Issue by kevinkey619b** [alexa/alexa-skills-kit-sdk-for-nodejs#121]
I'm trying to make this work, but I keep getting this error:

Cannot find module 'i18next'

How do I get Linux to pull in all required modules?

**Comment by knowlsie** [comment]
Get [npm](https://www.npmjs.com) then run `npm install alexa-sdk`.

**Comment by kevinkey619b** [comment]
@knowlsie I finally got this part working. Thanks.
