### ISSUE TITLE
TypeError: Alexa.handler is not a function at exports.handler (/var/task/index.js:24:23)

### ISSUE THREAD

**Issue by kevinkey619b** [alexa/alexa-skills-kit-sdk-for-nodejs#122]
How is this supposed to work? alexa or alexa-sdk?

TypeError: Alexa.handler is not a function
at exports.handler (/var/task/index.js:24:23)

**Comment by kevinkey619b** [comment]
And then AlexaLambdaHandler is not defined
at exports.handler (/var/task/index.js:26:5)

What is the deal with this SDK?

**Comment by kevinkey619b** [comment]
And now Alexa.execute is not a function
at exports.handler (/var/task/index.js:31:11)

**Comment by knowlsie** [comment]
Sounds like you resolved this one, so it'd be great if you can close this issue 🙂

**Comment by benedekh** [comment]
@kevinkey619b What's the matter? Take a look at the examples on how to use this library. E.g. [Alexa Fact Skill](https://github.com/alexa/skill-sample-nodejs-fact/blob/master/src/index.js)

**Comment by kevinkey619b** [comment]
I finally figured it out. Closing now.

**Comment by sunnyMiglani** [comment]
What was the solution? @kevinkey619b

**Comment by refatalsakka** [comment]
solution???????
