### ISSUE TITLE
Still can't read from DynamoDB

### ISSUE THREAD

**Issue by kevinkey619b** [alexa/alexa-skills-kit-sdk-for-nodejs#124]
What exactly do I need to do to enable READING from DynamoDB? I've finally been able to get this SDK to write to the DB, but can't find any instructions regarding how to READ FROM DynamoDB.

**Comment by kevinkey619b** [comment]
State1Handlers and State2Handlers undefined. What are these?

**Comment by knowlsie** [comment]
Can we keep this under one issue please...? Let us try to respond, I can't work on four issues at the same time. This does work (including DynamoDB), and people use it everyday to make skills.

**Comment by knowlsie** [comment]
By default if you set a table name, the SDK will write all the user's attributes to DynamoDB at the end of the session. Then, at the beginning of the next session, it will read all those attributes (for the particular user) from DynamoDB and store them where the attributes are usually stored, under `this.attributes`. This gives the effect of persisting attributes across sessions. The SDK itself gives pretty much no further functionality for reading and writing to and from DynamoDB (that'd be kinda excessive, it's just meant to be boilerplate). If you want to read and write other stuff, you should read the [aws-sdk docs](http://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/getting-started-nodejs.html) or [dynamodb-doc](https://github.com/awslabs/dynamodb-document-js-sdk). It may also help to have a look a the code in [DynamoAttributesHelper.js](../lib/DynamoAttributesHelper.js) to understand how the sdk is currently storing user attributes.

**Comment by knowlsie** [comment]
I missed the bit on `State1Handlers` and `State2Handlers`. Ignore those and just replace them with the name of the handlers object you are actually using. [Here's a super-super-simple example](https://github.com/knowlsie/favourite-places-alexa-skill/blob/master/lambda/index.js) I made like a month ago to demonstrate the `:delegate` feature, but also uses DynamoDB to store your favourite cities across sessions. As you can see, there's pretty much no actual code referring to DynamoDB, the SDK handles the stored attributes for you.

**Comment by kevinkey619b** [comment]
@knowlsie Thanks. Finally got it working. I think I had some bad data in my table. Deleted all older data, started fresh, and all works well now.
