### ISSUE TITLE
bump version please....

### ISSUE THREAD

**Issue by acinader** [alexa/alexa-skills-kit-sdk-for-nodejs#13]
we had to rediscover #1 ourselves.  Would be nice to get the fix out there for users of the lib?

**Comment by deegles** [comment]
We release version 1.0.5 yesterday, should be up to date now.

**Comment by acinader** [comment]
can you push the tag for 1.0.5 to github so we can see what changed?

**Comment by acinader** [comment]
thanks

**Comment by jchiversAMZN** [comment]
Sorry about that, we should have bumped the version with the update. Definitely let us know if you experience any further issues with the SDK.
