### ISSUE TITLE
Code example using :elicitSlot and :confirmSlot don't work

### ISSUE THREAD

**Issue by stormbytes** [alexa/alexa-skills-kit-sdk-for-nodejs#133]
I think there's something missing in the code about needing to create a dialog model (Builder beta) or perhaps something else. I tried adapting the example code (travel planning scenario) in the docs. It tests out fine but doesn't work on the echo.

**Comment by kcrosley-leisurelabs** [comment]
This seems to be because the alexa-sdk pre-installed in Lambda is not updated to the latest version.  It's VERY frustrating for those just learning to code Alexa skills for sure.  I just ran into this in the past 24 hours or so as I started to create some multi-turn dialogs for a skill I'm working on.

I'm not sure who to go to get that fixed (I guess it's an AWS Lambda issue).  I was going to report this issue through AWS.  Might be good to do the same!  I can't imagine that this would be very difficult for AWS to fix and I'm puzzled as to why it's been broken for so long.  

Variations on this problem are reported in #111  #114 and #128

**Comment by stormbytes** [comment]
I'm not using the Alexa-SDK pre-installed on Lambda. I didn't even realize there was an option to reference any package other than AWS SDK and have always gone the deployment package route (uploading a zip w/all deps).

**Comment by stormbytes** [comment]
Found the culprit. Apparently this.emit(:elicitSlot... or :elicitConfirmation need to be *returned explicitly* (eg. return this.emit('elicitSlot', foo, bar, etc).

Updated code example. 
https://gist.github.com/stormbytes/7ee3a05aa03c0ada0621dde746f2a6f9

**Comment by kcrosley-leisurelabs** [comment]
In my case (where I was having trouble getting "this.emit(':delegate')" function to work (it always seems to throw an error when called), I ended up using the technique illustrated in this example:

https://github.com/alexa/alexa-cookbook/blob/master/handling-responses/dialog-directive-delegate/sample-nodejs-fact/src/index.js

It initiates delegation by issuing this command:

this.context.succeed({
                "response": {
                    "directives": [
                        {
                            "type": "Dialog.Delegate"
                        }
                    ],
                    "shouldEndSession": false
                },
                "sessionAttributes": {}
            });

The one thing that example *doesn't* illustrate is how to pass an updated intent (e.g., if you wanted to reset slot values or something).  I've read the documentation and can't quite get the syntax correct...

**Comment by stormbytes** [comment]
Most of the docs for Alexa are worthless in any practical sense

**Comment by odintsovamz** [comment]
@stormbytes Daniel, could I get more information on what your critique around docs is so we could improve it to everyone's benefit? Feel free to reach out directly to my email odintsov at amazon com, my email is also available in my profile.

**Comment by stormbytes** [comment]
@odintsovamz documentation should typically be either (1) instructional  or (2) for reference. The docs on ASK are neither. It's like some abstract blob of words where the author "talks a lot, but _says_ nothing". The specific issues I have with the documentation: 

- Redundancy and needless repetition of simple concepts
- Poor organization of information and lack of logical flow
- Use of (domain specific) technical terms where these have not been properly defined
- Abstract, inactionable descriptions of technical constructs
- Utter lack of of code examples!
- Disconnection from other resources (eg. ASK NodeJS SDK) 

Its obvious this documentation was written in pieces, possibly by several authors. Disappointment is an understatement. If Amazon's goal is far reaching adoption they have grossly missed the mark here.

 I'm including links of several examples of excellent, well made and **useful** documentation. I hope Amazon might actually spend the time and take some directional cues:

1. CodeIgniter
https://www.codeigniter.com/user_guide/

2. Electron (Github) 
https://electron.atom.io/docs/

3. Angular
https://angular.io/guide/architecture
