### ISSUE TITLE
:tellWithPermissionCard creates card object incorrectly

### ISSUE THREAD

**Issue by cnorick** [alexa/alexa-skills-kit-sdk-for-nodejs#135]
The ```:tellWithPermissionCard``` handler creates a card with property ```cardType```. Property should instead be named ```type```.

[Link to the line broken line](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blame/3c91133e99ab404d7aeb6765cb01ecb2100494da/lib/response.js#L97)

**Comment by bclement-amazon** [comment]
The builder function buildSpeechletResponse expects a property name of cardType.

Do you have a code snippet that you could share which causes the SDK to send an invalid response?

**Comment by Amazon-tianrenz** [comment]
I've tested the ``:tellWithPermissionCard`` with sample skill and verified it to be working. 
I'm closing this issue for now. Please feel free to reopen if future questions appear.
