### ISSUE TITLE
Utterances trigger built-in skills instead of custom skill

### ISSUE THREAD

**Issue by adrianhara** [alexa/alexa-skills-kit-sdk-for-nodejs#137]
I'm playing with ASK and I have a skill and intent for crowdsourcing help. One utterance is for example "I need help to {serviceType} my {product} {serviceDate} at {serviceTime}". However, when testing it I can never get my utterance to be recognized, instead Alexa tells me it added stuff to the shopping list.

What I don't understand is...why?
- I'm already in my skill: "Alexa open <my skill name>"
- Simpler utterances and a dialog flow in which all the 4 (required) slots get filled separately work fine
- Why doesn't this one-shot utterance work and why does Alexa recognize one from the shopping list, since I'm obviously in a Dialog flow in my skill?

I noticed this also happens with other utterances. For example some utterances instead of matching my intent cause alexa to say "discovery is complete, i couldn't find any smarthome devices". Any idea why this happens and how I can prevent it, i.e. if alexa can't match an utterance to my intent, while i'm in my skill, to just invoke the Unhandled intent?

In case of simpler utterances, which don't include all the required slots, it works fine, i.e. alexa will go recognize the intent and fill in the supplied parameters, then (after my code delegates) will ask for the missing ones. It's just the longer utterances that seem to conflict with built-in ones and cause them to trigger.

**Comment by eercanayar** [comment]
If it says about another skill, it means that your session with your custom skill is ended. Check your intent responses' shouldEndSession parameters. It's the only explanation if the request goes to outside of your skill.

**Comment by adrianhara** [comment]
I think that is incorrect. My session is not ended because the echo light stays on and I can say stuff and it works for other utterances. Just for this one not...

**Comment by Amazon-tianrenz** [comment]
Hi, sorry for replying late. Were you able to figure out the problem described above? I tried but could not reproduce the same issue. Would you please send a code snippet that handles the corresponding intent?
