### ISSUE TITLE
Local testing with Dynamo DB

### ISSUE THREAD

**Issue by daemonsy** [alexa/alexa-skills-kit-sdk-for-nodejs#139]
Hey Amazon, thanks for the ASK SDK. It made skill development much nicer. 

I made a skill for [NYC's subway](https://github.com/daemonsy/nyc-subway) and implemented some tests. 

The next feature I wanted to add was persisting state and it seems that I should be able to write some tests using DynamoDB local. I was wondering if there's any way to expose the dynamo client so we can use a local client by via something like `new AWS.DynamoDB({ endpoint: <local endpoint> })`. This will make the skill testing much more meaningful. 

Also, if you're willing to accept PRs, happy to take a stab at this.

**Comment by daemonsy** [comment]
Hi, I added a very naive PR for this. 

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/140

**Comment by daemonsy** [comment]
Anyone had a chance to take a look at this?

**Comment by abhilash1in** [comment]
@daemonsy Does the official SDK support `alexa.dynamoDBClient`?

**Comment by daemonsy** [comment]
The official one doesn't, this is the PR to attempt to add the support

**Comment by jhurliman** [comment]
Allowing a custom AWS client to be passed in would also make this library compatible with AWS X-Ray (see https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-nodejs-awssdkclients.html).

**Comment by daemonsy** [comment]
hi, thanks everyone for the interest on this. I haven't heard anything from Amazon yet. It originally came with a PR, but now so much time's passed, not sure if the PR still works anymore. 

I will strongly advise not to use my branch. 

Adding another ping for Amazon here. @Amazon-tianrenz

**Comment by Amazon-tianrenz** [comment]
Hi all, 

thanks for all the discussion on this thread. The latest SDK release 1.0.25 has enabled developer to inject their own dynamoDB client. 

Regards

**Comment by Amazon-tianrenz** [comment]
Hi @adamgruber, 

We currently do not have such a sample. But now it's very easy to inject your own DynamoDB client into the `DynamoDBPersistenceAdapter` (see [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-dynamodb-persistence-adapter/lib/attributes/persistence/DynamoDbPersistenceAdapter.ts#L42)). You can setup your local DynamoDB follow this [link](https://aws.amazon.com/blogs/aws/dynamodb-local-for-desktop-development/). And then in your DynamoDBClient, just set the endpoint to point to local host. 

Regards
