### ISSUE TITLE
How to override built in functions?

### ISSUE THREAD

**Issue by lbj417** [alexa/alexa-skills-kit-sdk-for-nodejs#14]
The documentation says you have the `Ability to override built-in functions` but I cannot find any documentation for how to do so.

I am looking to post data to mobile analytics with each intent that comes in.  I would rather do this once instead of having to wrap it around each individual intent handler.

Thanks in advance.

**Comment by deegles** [comment]
To override a built-in function such as `:ask`, simply register a handler with the same name.

For metrics logging, I would recommend simply logging it in your `exports.handler` function in `index.js` before your function code is executed.

E.g.

```javascript
exports.handler = function(event, context, callback) {

    // Log incoming event or just the intent
    console.log('event:\n' + JSON.stringify(event, null, 4));

    var alexa = Alexa.handler(event, context);
    alexa.registerHandlers(...)

    // Log with a callback
    LogEventAsync(event, function() {
        alexa.execute();
    });
}

function LogEventAsync(event, callback) {
    // Async call to emit metric 
    callback();
}
```

**Comment by acinader** [comment]
@deegles so i want to log the response in addition to the event.

I was figuring that I would need to override :responseReady.  Got a better suggestion?

**Comment by deegles** [comment]
Hi Acinader,

One approach is to wrap your `context.succeed` function. Try the following in your `exports.handler` function, before calling `alexa.execute()`. 

You can do the same with `context.fail`

```javascript
var succeed = context.succeed;
context.succeed = function (response) {
    console.log('Response:\n' + JSON.stringify(response, null, 4));
    succeed(response);
}
```

**Comment by acinader** [comment]
👍 thanks
