### ISSUE TITLE
Access Token Undefined

### ISSUE THREAD

**Issue by surbhit4** [alexa/alexa-skills-kit-sdk-for-nodejs#141]
Hi,
I am using "this.event.session.user.accessToken" in my "IntentRequest" to get the value of 'accessToken'. But I get the value to be "undefined" even though my account is linked and I can see the access token being sent, in the request.
I want to use accessToken to make a few API calls. Why does it say "undefined" when I know that it is not?

**Comment by MKirkD** [comment]
Hello @surbhit4 , so what was your solution to this?  I have the same/similar issue.
