### ISSUE TITLE
KeyError: 'accessToken' when trying to get the accessToken from the request

### ISSUE THREAD

**Issue by Sandhu412** [alexa/alexa-skills-kit-sdk-for-nodejs#143]
Hi There, 

I have successfully linked the account and the Alexa request does show the accessToken information as shown below: 

`{`
  `"session": {`
    "sessionId": "SessionId.73fdade4-8c3b-4a16-9487-f8539ba6a24a",
    "application": {
      "applicationId": "amzn1.ask.skill.4e11fe6c-8ce4-4aa9-9210-52e6c64dbc83"
    },`
   ` "attributes": {},`
   ` "user": {`
      `"userId":` `"amzn1.ask.account.AGAF5F6B3CSZYXODZ4C4N24LDFJWBDKDPJ2H6I6WOC23KQLPUSMOQRZQ3EEZQLDOL63UKFUMKA2XOIMI3K7CIIUU3ZBCXD6F5BIJG2OR2VVNPUTAHUD2M3PFOWQRSJSGXFNVYOVX43JZITCM7QHVEGOJQ33BSQPURYCLNESPRAURWXAIVQPZGC34BPR7WFNHNYB47BROPMC72CI",`
     ` "accessToken": "5e212f0b-e539-4dd8-ae36-1d5047ac512f"`
    },`
    `"new": true`
 },

In my lambda function, all I am trying is to read the accessToken from the event in python code as shown below: 
***************
`def lambda_handler(event, context):`
   ` """ Route the incoming request based on type (LaunchRequest, IntentRequest,`
   ` etc.) The JSON body of the request is provided in the event parameter.`
   ` """`
  `  print("event.session.application.applicationId=" +`
          `event['session']['application']['applicationId'])`
 `print(event['session']['user']['accessToken'])`
***************

the above code throws an error saying:
`Traceback (most recent call last):`
  `File "/var/task/lambda_function.py", line 13, in lambda_handler`
    `print(event['session']['user']['accessToken'])`
`KeyError: 'accessToken'`

*************
Could anyone please help me point out what is the issue here please? I am unable to figure out why there is a key error because I am traversing down the JSON structure correctly: event.session.user.accessToken. 

Any help will be greatly appreciated. 

Thanks
Sandeep

**Comment by hoegertn** [comment]
Hi,

maybe you want to repost this question in the Python SDK as this is the issue tracker for the NodeJS SDK.

**Comment by bclement-amazon** [comment]
Closing as this pertains to a third party SDK

@sandhu412 - its possible the accessToken field to not be populated (though only when the account is not linked) which could explain the keyError.
