### ISSUE TITLE
Support VideoApp.Launch directive

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-skills-kit-sdk-for-nodejs#144]
This directive was added for the Echo Show. Needs to be added to ASK.

**Comment by bclement-amazon** [comment]
Agreed! We're working on supporting this in alexa-sdk.

**Comment by Amazon-tianrenz** [comment]
The current sdk has added support for VideoApp.Launch directive in the ``responseBuilder``. 
I'm closing this issue for now. Please feel free to reopen this if further questions rise
