### ISSUE TITLE
Support Display.RenderTemplate directive

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-skills-kit-sdk-for-nodejs#145]
This directive was added for the Echo Show. Needs to be added to ASK.

**Comment by bclement-amazon** [comment]
Agreed! We're working on supporting this in alexa-sdk.

**Comment by fishhelper** [comment]
I can offer https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/146 from a fork, if it is helpful. Feel free to ask any questions you may have or offer comments.

**Comment by Amazon-tianrenz** [comment]
The feature requested in this issue has been added to Alexa NodeJS SDK. Issue closed. Please feel free to reopen if still have questions. Thanks!
