### ISSUE TITLE
confirmIntentWithCard works, but not confirmIntent

### ISSUE THREAD

**Issue by klunghamer** [alexa/alexa-skills-kit-sdk-for-nodejs#149]
Hi,
I was working the confirm intent directive, and could only get the ':confirmIntentWithCard' directive to work, not ':confirmIntent'. The speechOutput and repromptSpeech were identical between the two tries.

the format that was not working was: this.emit(':confirmIntent', speechOutput, repromptSpeech, updatedIntent);
I tried using this.event.request.intent for updatedIntent, as well as the intent name as a string.

please let me know if you have any questions with my issue.

**Comment by ysak-y** [comment]
In SDK, `confirmIntent` has no problem.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/response.js#L172-L184

Please tell me invalid response or error message if you can.
