### ISSUE TITLE
Access interaction model json?

### ISSUE THREAD

**Issue by pursual** [alexa/alexa-skills-kit-sdk-for-nodejs#154]
Is there a way to access the JSON definition of the skill interaction model from the node sdk?

**Comment by eercanayar** [comment]
Nope. The interaction model is about parsing user's input by alexa engine, then the request is generated for your skill. SDK is just for creating proper and valid JSON responses to requests. Nothing more.
Why do you want to access the skill interaction model? May be there is another option to do.

**Comment by pursual** [comment]
The reason is to resolve synonyms to the original slot value. I know you can do this from a nasty looking "resolutions" array that comes with the intent, but it is overly complicated, and also doesn't get sent from the test emulator. Being able to access the interaction model would let me look at the intent, then the slots, and find the value that matched the synonym,  regardless of whether the test tool was used or not.

**Comment by gadgetchnnel** [comment]
This doesn't help with the simulator not including "resolutions", but I wrote this helper method which I use to get the slot value (falling back to the raw value if "resolutions" is not present):

`function slotValue(slot, useId){
    let value = slot.value;
    let resolution = (slot.resolutions && slot.resolutions.resolutionsPerAuthority && slot.resolutions.resolutionsPerAuthority.length > 0) ? slot.resolutions.resolutionsPerAuthority[0] : null;
    if(resolution && resolution.status.code == 'ER_SUCCESS_MATCH'){
        console.log(slot.resolutions.resolutionsPerAuthority);
        console.log(resolution.values);
        let resolutionValue = resolution.values[0].value;
        value = resolutionValue.id && useId ? resolutionValue.id : resolutionValue.name;
    }
    return value;
}`

You can call it like **slotValue(this.event.request.intent.slots.SlotName)** or **slotValue(this.event.request.intent.slots.SlotName,true)** if you want the id of the slot value to be returned instead of the text.

**Comment by shad00m** [comment]
I'm going crazy I've seen @gadgetchnnel 's way a couple of times already but it doesnt seem to work for me.
The JSON never has a resolution request... am I missing something obvious? Or could someone direct me to a synonym/entity resolution tutorial for node.js?

**Comment by Amazon-tianrenz** [comment]
Hi @shad00m 
In order to receive entity resolution in your request, you need to define synonyms and IDs for slot values in the skill builder. See this [documentation](https://developer.amazon.com/docs/custom-skills/define-synonyms-and-ids-for-slot-type-values-entity-resolution.html) for more details.
Regards

**Comment by GitKilla** [comment]
I have defined IDs and synonyms for my slot type values, but regardless the ids are never sent in a resolutions array to my lambda function. What is going on here? Is there something else I have to do other than add IDs? They show up in my interaction model code, but not in the IntentRequest. Here is the intent request i get:

"request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.717c7447-ed8c-465d-b11e-378e8645e49f",
    "intent": {
      "name": "GetCoinPrice",
      "slots": {
        "Coin": {
          "name": "Coin",
          "value": "bitcoin"
        }
      }
    },

I see no IDs in here

**Comment by Amazon-tianrenz** [comment]
@GitKilla,

Here are a couple things you can check:
1. make sure you are defining the synonyms using the Code Editor in Skill Builder (beta)
2. make sure you can calling the correct intent that has resolution defined.

Regards

**Comment by Amazon-tianrenz** [comment]
Hi @DanLaufer, 

Could you please post the language model json that's generated in the skill builder beta?

Thanks, 
Tianren Zhang

**Comment by DanLaufer** [comment]
@Amazon-tianrenz Sure. Here it is:

```
{
  "languageModel": {
    "types": [
      {
        "name": "Procedure",
        "values": [
          {
            "id": "line-flushing",
            "name": {
              "value": "Line Flushing",
              "synonyms": [
                "line flushing",
                "line-flushing",
                "line flush",
                "flush the line",
                "flushing",
                "flush line",
                "flush",
                "line"
              ]
            }
          },
          {
            "id": "test-blood-sugar",
            "name": {
              "value": "Blood Sugar Test",
              "synonyms": [
                "check blood sugar",
                "blood sugar",
                "test glucose",
                "blood glucose",
                "blood sugar test",
                "blood glucose test",
                "test blood glucose",
                "test blood sugar",
                "check blood glucose",
                "glucose",
                "sugar"
              ]
            }
          }
        ]
      }
    ],
    "intents": [
      {
        "name": "AMAZON.CancelIntent",
        "samples": []
      },
      {
        "name": "AMAZON.HelpIntent",
        "samples": []
      },
      {
        "name": "AMAZON.StopIntent",
        "samples": []
      },
      {
        "name": "MedAssistSelect",
        "samples": [
          "{Procedure}",
          "{Procedure} procedure"
        ],
        "slots": [
          {
            "name": "Procedure",
            "type": "Procedure"
          }
        ]
      },
      {
        "name": "GetCurrentStep",
        "samples": [
          "What",
          "repeat",
          "can you repeat that",
          "say that again",
          "what was that",
          "no",
          "i didn't",
          "not ready",
          "not done"
        ],
        "slots": []
      },
      {
        "name": "GetNextStep",
        "samples": [
          "Yes",
          "Ok",
          "Done",
          "Complete",
          "Finished",
          "Continue",
          "Forward",
          "Next",
          "Next Step",
          "go forward",
          "I did",
          "Indeed",
          "I think so",
          "I've done it",
          "alright"
        ],
        "slots": []
      },
      {
        "name": "GetPreviousStep",
        "samples": [
          "Last Step",
          "Backwards",
          "Previous",
          "Go Back",
          "Previous Step"
        ],
        "slots": []
      },
      {
        "name": "Menu",
        "samples": [
          "menu",
          "main menu",
          "return to menu",
          "back to menu"
        ],
        "slots": []
      },
      {
        "name": "Restart",
        "samples": [
          "Start Over",
          "Begin Again",
          "restart"
        ],
        "slots": []
      }
    ],
    "invocationName": "med assistant"
  }
}
```

**Comment by druelie** [comment]
Hi!

I have the same issue as DanLaufer.
`this.event.request.intent.slots.MySlot.value` will give me back the spoken word.
But how do I get the value or ID that I have entered for the slot type?

My language model looks similar to the one above.

Thanks, druelie
