### ISSUE TITLE
Issues with skill endpoint validation

### ISSUE THREAD

**Issue by vandykew** [alexa/alexa-skills-kit-sdk-for-nodejs#155]
In certifying my Skill I'm failing because of this, Anyone else run across this?

Issues with skill endpoint validation

Future versions of the Alexa Skills Kit may add new properties to the JSON request and response formats, while maintaining backward compatibility for the existing properties.  When we invoke the skill with additional parameters, the skill is rejecting it when we expect this to be accepted.  Your code must be resilient to these types of changes. For example, your code for de-serializing a JSON request must not break when it encounters a new, unknown property.

**Comment by eercanayar** [comment]
Don't you use alexa-sdk to decode json requests? Or are you handling the requests manually?

**Comment by vandykew** [comment]
Yes i do This is the top of my app 

var Alexa = require('alexa-sdk');

exports.handler = function(event, context, callback) {
    console.log(JSON.stringify(event));
    var alexa = Alexa.handler(event, context);

    // alexa.appId = 'XXXXXXXXXXXXXXXX';


    alexa.registerHandlers(handlers);
    alexa.execute();
};

**Comment by eercanayar** [comment]
I don't what kind of intent structure you developed but as a general recommendation; always reply any request even if totally invalid. Such as, if the request contains an invalid intentname or some invalid parameter; instead of throwing an error; just response them like (":tell", "Sorry, I coulnt recognize your request")

**Comment by vandykew** [comment]
What would a defualt handler look like ?

**Comment by vandykew** [comment]
Any ideas ?

**Comment by eercanayar** [comment]
Yours is the right one.

**Comment by Amazon-tianrenz** [comment]
Issue closed. Please feel free to reopen if problem persists

**Comment by jindalvikas11** [comment]
I got the same issue in certification. I am not doing anything special to parse json.

Please let me know what can i do.
