### ISSUE TITLE
Releases need to follow semver protocol!

### ISSUE THREAD

**Issue by baq** [alexa/alexa-skills-kit-sdk-for-nodejs#156]
The commit that was tagged as 1.0.10 introduced a backwards-incompatible change!  I was calling emit(:saveState) expecting my callback to be invoked once the state was saved so that I can submit my own custom tracking events to our underlying infrastructure, but that no longer works after 1.10 (see line 253 in commit bc58e3ae5024c6a9c053879b8295fc5b88ccb357)!  It took me a whole day to track down the bug because I didn't assume a backwards-incompatible change was made to the underlying code. I had to change my code to do an 'emit(:responseReady)' so that my code once again worked as before. 

This release introduced by this change should have followed proper semver protocols and had the 'major' version upgraded, so that the library was then 2.0.0.  npm then would not have pulled down this new version in my case (for either '~' or '^') and my code would have continued working.  Please carefully consider any and all behavioral changes to the implementation before releasing and appropriately upgrade the version!

**Comment by bclement-amazon** [comment]
We've reverted the behaviour change in bc58e3a to fix this backwards-incompatibility. We will follow proper semver protocols on future behavioural changes!
