### ISSUE TITLE
Reset current state

### ISSUE THREAD

**Issue by ysak-y** [alexa/alexa-skills-kit-sdk-for-nodejs#159]
## Overview

I use DynamoDB in this sdk. This saves current state to DynamoDB if I set state to `this.handler.state`.
But I can't find how reset state because when I set empty string(`''`) to `this.handler.state`, sdk ignore to update.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/response.js#L206
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/response.js#L225

What should I do if I want to reset current state. If there are no ways, I'll implement.

**Comment by benedekh** [comment]
Empty string is a _falsy_ (evaluates to false) value in JS. See https://dorey.github.io/JavaScript-Equality-Table/

**Comment by ysak-y** [comment]
Yes, I know, so how do I reset state ?
Delete `STATE` key & value in DynamoDB directory?

**Comment by valentinkostadinov** [comment]
I'm having the exact same problem. Any updates on this?

How do I reset state? This is especially bothering since the official README makes an example out of it:

`var guessModeHandlers = Alexa.CreateStateHandler(states.GUESSMODE, {

    'NewSession': function () {
        this.handler.state = '';
        this.emitWithState('NewSession'); // Equivalent to the Start Mode NewSession handler
    },
`
And under Tips, it says:

> If the target state is "", then this.emit("TargetHandlerName") should be called.

**Comment by ysak-y** [comment]
> If the target state is "", then this.emit("TargetHandlerName") should be called.

This sample is correct if you call `TargetHandlerName` with no STATE. But after response, current state will back to current state(not empty state).

Now we don't have a way to reset current state.

**Comment by allthepies** [comment]
I've having the same problem, an attempt to reset state to "empty" is ignored by the ASK.
The following workaround does work for me:

      this.handler.state = constants.states.START_MODE;
      this.attributes.STATE = null;

where constants.states is
  states: {
    START_MODE: '',
    DETAIL_DECISION_MODE: '_DETAIL_DECISION_MODE'
  }

I have found that I need both of the "reset" code lines, the first used the documented approach and the second sets the state entry ("STATE") in the session attributes to NULL directly.  This works for me.

**Comment by Amazon-tianrenz** [comment]
issue closed. 
future discussion please refer to issue #69
