### ISSUE TITLE
Support for elicitSlot from different intent?

### ISSUE THREAD

**Issue by GomuGomuMan** [alexa/alexa-skills-kit-sdk-for-nodejs#162]
Suppose I have 2 intents A and B. Intent A uses [`Dialog Interface`](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/dialog-interface-reference). Intent B is an `AMAZON.HelpIntent`.

What I want to do is a way to elicitSlot of intent A from intent B (I save intent and slot information on sessionAttributes). When I try to apply 
`this.emit(':elicitSlot', slot, prompt, reprompt, updatedIntent);` 
method with an updated Intent (with changed intentName). It gives me this error: 

![error](https://user-images.githubusercontent.com/11905848/28891874-cc64ce24-7780-11e7-95d1-d48011e86a2e.png)

However, this functionality is supported on Amazon Lex as specified [here](http://docs.aws.amazon.com/lex/latest/dg/lambda-input-response-format.html#using-lambda-response-format) on the **elicitSlot** section

**Comment by Amazon-tianrenz** [comment]
Hi, 
Please make sure the updatedIntent matches exactly with the intent that your skill receives. 
Please see [here](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html#elicitslot) for more information on ``elicitSlot``. 

Regards

**Comment by khanh-nguyen** [comment]
It looks like it’s not supported :(

> Note that you cannot change intents when returning a Dialog directive, so the intent name and set of slots must match the intent sent to your skill.

**Comment by tobias74** [comment]
Is there any workaround? 

Multi-Turn dialogs often elecit specific slots which are then answered by a single word. In case the user triggered the HelpIntent during a multi-turn dialog I need a way to re-elicit that very specific slot on that very intent. I cannot rely on the user saying a complete sentence to trigger that specific intent again.
 
The user is more likely to say just that one-word-answer I tried to elicit in the first place. But this one word abviously cannot trigger the correct intent. The wanted intent, for which I try to re-elicit a slot, has to be provided from within the HelpIntent like so:

`this.emit(':elicitSlot','slotName','intentName');
`

**Comment by b11n** [comment]
+1

**Comment by patjackson52** [comment]
+1.  shame the issue was closed without considering this as a feature request

**Comment by tianrenz** [comment]
@patjackson52 , please go to [alexa voice forum](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote) and post the feature request there, as this is not a SDK related issue.
