### ISSUE TITLE
Setting appId causes error.

### ISSUE THREAD

**Issue by richburdon** [alexa/alexa-skills-kit-sdk-for-nodejs#165]
I'm just getting start, but have a simple skill working in test. However if I set the appId (to be the ID from the dev portal), then I get the error below. If I omit setting the ID, things work again.

NOTE, the ID that I'm setting does match the applicationId passed in with the `event.session`.

```
The applicationIds don't match: applicationId and amzn1.ask.skill.XXX

{"errorMessage":"Invalid ApplicationId: amzn1.ask.skill.XXX","errorType":"Error","stackTrace":["AlexaRequestEmitter.ValidateRequest (/var/task/handler.js:8800:25)","AlexaRequestEmitter.HandleLambdaEvent (/var/task/handler.js:8769:25)","AlexaRequestEmitter.value (/var/task/handler.js:8744:31)","alexa (/var/task/handler.js:8626:11)"]}
```

**Comment by cjinpheow** [comment]
There seems to be an issue with the alexa-sdk/lib/alexa.js file. If you patch line 131 as follows, it should work:

     if (event.context && event.context.System.application.applicationId!="applicationId") {

instead of 

     if (event.context) {

--cp

**Comment by bclement-amazon** [comment]
Hi Rich,
I don't think there is a problem with the SDK here.  Are you using the simulator? Do you get the same error on a physical device?

**Comment by kyle-wrenn** [comment]
How should the appId be set and validated? I'm trying to set it manually, but still get the warning saying it hasn't been set. Also, what is the ID validated against?

**Comment by avaadi** [comment]
Set the app id in the test configure event also. It should take care of this error.
BR,Avaadi 

    On Monday, August 7, 2017 10:20 PM, Rich Burdon <notifications@github.com> wrote:
 

 I'm just getting start, but have a simple skill working in test. However if I set the appId (to be the ID from the dev portal), then I get the error below. If I omit setting the ID, things work again.NOTE, the ID that I'm setting does match the applicationId passed in with the event.session.The applicationIds don't match: applicationId and amzn1.ask.skill.XXX

{"errorMessage":"Invalid ApplicationId: amzn1.ask.skill.XXX","errorType":"Error","stackTrace":["AlexaRequestEmitter.ValidateRequest (/var/task/handler.js:8800:25)","AlexaRequestEmitter.HandleLambdaEvent (/var/task/handler.js:8769:25)","AlexaRequestEmitter.value (/var/task/handler.js:8744:31)","alexa (/var/task/handler.js:8626:11)"]}

**Comment by Amazon-tianrenz** [comment]
@kyle-wrenn appId can be set the following way: 
````
const alexa = Alexa.handler(event, context, callback);
alexa.appId = APP_ID;
````
It's used to validate against the application id included in the event that your skill service receives. 

I'm closing this issue now. Please feel free to reopen if more questions appear

**Comment by CoreyCole** [comment]
@tianrenz I'm getting this error in version 1.0.25:
```
2018-04-26T19:06:21.103Z
e74e5009-4984-11e8-80ed-ed6c903c536e
The applicationIds don't match: amzn1.ask.skill.x-x-x-x-1 and amzn1.ask.skill.x-x-x-x-2
```

I just moved my skill/lambda function over to a new aws organization and now I'm running into this. 

In order for my application to work in the simulator, I must set my `alexa.appId` to be the skill id from my old aws organization.

In order for my application to work on a real device, I must set my `alexa.appId` to `undefined` as suggested [here](https://forums.developer.amazon.com/questions/79882/the-applicationids-dont-match.html)

**Comment by CoreyCole** [comment]
For anyone else facing this issue: Deploying to lambda with `APP_ID = undefined`, testing on a real device, and then re-deploying with my *new* application id fixed the issue for me
