### ISSUE TITLE
:askWithCard crashes

### ISSUE THREAD

**Issue by Sketusky** [alexa/alexa-skills-kit-sdk-for-nodejs#166]
When I use `:askWithCard`, skill works correctly only with Amazon Device, when trying to use it on Android app it doesn't.

I've solved the problem on Android when I switched to simple `:ask` but still I can't send cards.

The problem occurred yesterday, before Thursday everything was working with cards.

**Comment by ysak-y** [comment]
Do you have any error message? Does Android IDE print any logs?

**Comment by bclement-amazon** [comment]
How are you invoking your skill on Android?

**Comment by shrobon** [comment]
I am facing the same issue. 
tellWithCards works fine , but askWithCards does not work.

**Comment by shrobon** [comment]
Thanks @bclement-amazon ! 👍 
I got it to work 🥇

**Comment by Amazon-tianrenz** [comment]
Close this as the issue is resolved. Please feel free to reopen if further problems appear
