### ISSUE TITLE
Impossible to fullfill voice interface guidelines with dialog skill

### ISSUE THREAD

**Issue by datenstrudel** [alexa/alexa-skills-kit-sdk-for-nodejs#167]
Hello,

in order to pass the audit for skill release, the [user experience guide](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-voice-interface-and-user-experience-testing?ref_=pe_679090_102923190#providing-help) demands the skill to fulfill the following requirements when a HelpIntent is called while some intent is currently running: 

> * Ends with a question prompting the user to complete their request.
> * Leaves the session open to get a response from the user.

It seems impossible for me to fullfill these requirements, because due to I am working on a dialog skill, I cannot use the build in Yes/NoIntents. To clarify the situation let's suppose the following journey:

User Calls MyMagicIntent with slot -> User didn't give the slot, so my skill emits :delegate in order to elicit slot -> Now the user calls for Help -> The HelpIntent is executed and handled by my skill.

Being in the HelpIntent now, I shall not just explain what the skill does, but explain to the user in more detail about the capabilities of the intent and ask for a response of the user, while leaving the session open.

What are my options now:
 * I could emit an :ask event. -> BUT: I cannot react, as my Yes/NoIntent implementations get never called.
 * When I try to emit an :elicitSlot event it doesn't work, as I am still in the HelpIntent which of course doesn't provide the required context.
 * Implementing Custom Yes/NoIntent sends the SkillBuilder, training the model, to a journey of no return.
 * Implement yet another intent - Would require me to tell the user what to say or to do. No option either.

I am now stuck with this for quite some days :( and would greatly appreciate any kind of help,
Surely, I am missing something totally obvious (not to me but to you?).

Thanks and best regards
Tom

**Comment by Amazon-tianrenz** [comment]
Hi Tom, 
In your HelpIntent, you could try give user specific instruction on how to return to the ``MyMagicIntent``. 

For example: if ``MyMagicIntent`` was invoked when customer says "Show me a magic.". Your help intent could end with "Now you can say `show me a magic` to see a magic or 'exit' to exit the skill". And that should guide user back to MyMagicIntent. 

Hope this helps!
Regards
