### ISSUE TITLE
Get the access token off of user after account linking

### ISSUE THREAD

**Issue by jgalb** [alexa/alexa-skills-kit-sdk-for-nodejs#17]
Is this possible? The account is linked through google currently in alexa-dev, not sure how to get the access token back now that my account is linked. There is an explanation for Java in the documentation, but not javascript.

**Comment by deegles** [comment]
You can access the token at any time with `this.event.session.user.accessToken` or `this.event.context.user.accessToken`

More information here: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference

**Comment by surbhit4** [comment]
Hi, 
I had a similar doubt, the value of 'accessToken' I get is "undefined" even though my account is linked and I can see the access token being sent, in the request. I used 'this.event.session.user.accessToken'. 
I want to use accessToken to make a few API calls. Why does it say "undefined" when I know that it is not?

**Comment by mywebcompanion** [comment]
I face the same issue. Any resolution?

**Comment by surbhit4** [comment]
@mywebcompanion I followed the solution provided by deegles and its working. But the tests you are running on Lambda Function does not have access to the access token. Since, the access token is available only in your skill. You need to do the same tests using Developer Console.
Hope this helps.

**Comment by MKirkD** [comment]
Hello @surbhit4 - so into what function is the session object passed?  Within Developer Console my test events are setup to pass the session and context and other objects within the JSON.  Within exports.handler, I have this defined:  var alexa = Alexa.handler(event, context);  and have tried several ways but always see <undefined> for session.user.

**Comment by davechappell** [comment]
I just started seeing this issue yesterday.  Code that has been working for 6 months is no longer working, because the context.System.user.accessToken is no longer present in the event.  Anyone else seeing this too?

**Comment by 10-ny** [comment]
Hi guys,
it happened the same to my Skill. It was working but suddenly, the access token is not appearing in `handlerInput.requestEnvelope.session.user.accessToken` even though I have my account linking configured properly.

Any resolution ?

**Comment by trademark18** [comment]
@JonathanSarco I just experienced the exact same thing.  In Alexa for Business it shows that the account is linked and the device has access to the skill.  It just stopped working one day!
