### ISSUE TITLE
Give warnings or throw error in template builder functions when you send a plain string as value that is not an object

### ISSUE THREAD

**Issue by calvinalvin** [alexa/alexa-skills-kit-sdk-for-nodejs#170]
I spent alot of time trying to debug a very simple issue. If you look at the following code, you'll see that semantically it looks fine and the error here is not very obvious. This template rendering will not work properly with echo show, and will in fact cause an invalid response.

```js
const builder = new Alexa.templateBuilders.BodyTemplate2Builder();
let primaryText = makePlainText(`This is your primary text`);
let secondaryText = makePlainText('this is your secondary text');
let template = builder.setTitle('This is the title.')
                            .setImage('https://d3awvtnmmsvyot.cloudfront.net/api/file/Xf3ZwOHDR3G2mhtcvwHA')
                            .setTextContent(primaryText, secondaryText)
                            .build();
```

The problem here is that the `setImage` function is not passing an "image" object using the `ImageUtils.makeImage` helper. Alexa/Lambda will give no indication of what the error is so it's very frustrating as there is no visibility as to what is causing this.

I think the SDK should give some kind of console.log "WARNING" message or even throw an error when you pass an invalid argument such as a string. I am positive that this would save us devs lots of time trying to debug simple issues. Thank you!

+1 for some sort of validation ability against templates or responses.

**Comment by bclement-amazon** [comment]
@calvinalvin  - thank you for the feedback! I'll leave this open - adding a warning/exception should be doable here.

**Comment by shyamu** [comment]
+1

Spent many hours debugging because I did the following to render the title

`builder.setTitle(makePlainText('This is the title.'))`

instead of 

`builder.setTitle('This is the title.')`

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).
