### ISSUE TITLE
`shouldEndSession` should be overridable or deletable from response object 

### ISSUE THREAD

**Issue by calvinalvin** [alexa/alexa-skills-kit-sdk-for-nodejs#171]
When you are developing against an Echo Show with the template builders, `shouldEndSession` should be overridable or omitted. When you manually set `shouldEndSession = null` on the response it is not behaving according to the documentation:

https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/display-interface-reference#use-of-shouldendsession-attribute-and-session-timeouts
`When shouldEndSession is not specified, or has a value of null, and a Display.RenderTemplate directive is active, the session is kept open, and Echo Show does not expect a voice response. If the user says the wake word and a command, this utterance is recognized in the context of the skill.`

**Comment by bclement-amazon** [comment]
hi @calvinalvin - The expected behaviour is the session will be kept open and the Echo show will not open the mic -- what behaviour are you seeing if shouldEndSession is set null?

**Comment by calvinalvin** [comment]
@bclement-amazon I'm sorry it took so long for a reply. I think this was the result of something else. I will reopen with more details if it happens again. Thanks!
