### ISSUE TITLE
German skill gets terminated if using dialogs/prompts in voice model

### ISSUE THREAD

**Issue by adrenaline15** [alexa/alexa-skills-kit-sdk-for-nodejs#173]
I've created a new skill which uses following sample-project as base:

https://github.com/alexa/alexa-cookbook/tree/master/handling-responses/dialog-directive-delegate/sample-nodejs-plan-my-trip

For this special problem I created the skill for the languages
- EN(US)
- DE

Both languages share the same interaction/voice Model (copied from the github project) and the same code (lambda function).

If I invoke the skill on a echo device which is set-up in english all works as intended and if I say: 'Okay' after the welcome message it prompts the right help message without closing the skill.

However if I repeat the same test for a device which is set to german, it terminates the skill after the 'okay' input and displays the card with 'na dann ist gut' (default response from alexa in german).

[https://forums.developer.amazon.com/storage/attachments/3912-okay-card.png](url)

When I remove the dialog/prompt parts from the voice model it doesn't terminate the german skill and outputs the correct help message.

Test-devices: Echo, FireTV

Best regards and thanks in advance

BTW: I posted the same question in the amazon dev forums under this link: [https://forums.developer.amazon.com/questions/85551/nodejs-skill-gets-terminated-if-using-dialog-model.html#answer-85725](url)

**Comment by bclement-amazon** [comment]
Hi adrenaline15,

I have the back-end team looking into this. Stay tuned.

**Comment by DunjaTomas** [comment]
Hello ist there any updates? i have the same problem with my skill.

**Comment by tianrenz** [comment]
Hi @DunjaTomas ,

The issue is not related to the SDK. To help balance the maintenance load on SDK repositories, we would recommend to post this issue on [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/index.html). 

Regards
