### ISSUE TITLE
Hard to understand to call another intent from the intent.

### ISSUE THREAD

**Issue by ysak-y** [alexa/alexa-skills-kit-sdk-for-nodejs#174]
## Overview

README describes the method to call `HelloWorldIntent` from `LaunchRequest` as below.

```
var handlers = {
    'LaunchRequest': function () {
        this.emit('HelloWorldIntent');
    },

    'HelloWorldIntent': function () {
        this.emit(':tell', 'Hello World!');
    }
 };
```

This code looks fine. But for example

```
const states = {
  FOOMODE: "_FOOMODE"
}

var handlers =Alexa.CreateStateHandler(states.FOOMODE,  {
    'LaunchRequest': function () {
        this.emit('HelloWorldIntent');
    },

    'HelloWorldIntent': function () {
        this.emit(':tell', 'Hello World!');
    }
 });
```

In this code, `this.emit('HelloWorldIntent')` can't call `HelloWorldIntent`. Because `HelloWorldIntent` is registered as `HelloWorldIntent_FOOMODE` in EventEmitter.

I think this behavior is not intuitive because this fact(`${IntentName}${STATE}`) is used only in SDK, not application code. So I suggest when emit another intent in the intent, call same STATE's intent when don't indicate STATE clearly.

What do you think?

**Comment by xeladotbe** [comment]
I like the way how "emit" and "emitWithState" work, it gives you the possibility to use "emit" like "super" to call non state based intents.

**Comment by ysak-y** [comment]
Sorry,  I can't understand below

```
 it gives you the possibility to use "emit" like "super" to call non state based intents.
```

What do you mean? Please describe with example if you can.

**Comment by bclement-amazon** [comment]
calling `this.emit('HelloWorldIntent')` will dispatch a request to the default handler. Not the one specified in the state FOOMODE.  Changing the routing mechanism would be a major breaking change. 
As an alternative, i'd recommend using `this.emitWithState('HelloWorldIntent')` to dispatch a call to HelloWorldIntent from within the same state, or to another state by first setting `this.handler.state` to your desired state.  This will work in both handlers registered with a state, and one without.

**Comment by ysak-y** [comment]
OK, I got it!
