### ISSUE TITLE
Fire an emit immediately after having firing emit(':ask', ... ) ???

### ISSUE THREAD

**Issue by barryburd** [alexa/alexa-skills-kit-sdk-for-nodejs#176]
I want to tell the user that I'm going to do something, and then do it. (The "something" happens to be to make an http GET request, but that's not important.) As far as I can see, this means doing emit(':ask', ...) and not waiting for a response but then firing another emit immediately after that. Is this possible? If so, now?

**Comment by bclement-amazon** [comment]
Hi barryburd,

It sounds like you have the following scenario:
1. Ask {mySkill} to do {something}
2. `this.response.speak('OK, doing {something}');`
     `this.emit(':responseReady')`
     (equivalent to `this.emit(':tell', 'OK, doing {something}');`)
3. Dispatch HTTP Get request
4. // emit another response to the user

If this is correct:
There isn't a way to programmatically notify the user (Step 4), meaning your skill must respond to an alexa request (as in Step 2).  You can achieve this with a `this.emit(':ask', '...')` as this will open the mic and dispatch another request to your skill.

If you could provide a few more details for your scenario I may be able to suggest other options here

**Comment by barryburd** [comment]
Hi bclement,
Here's the scenario that I'm trying to achieve...
- The user says "Alexa, <SkillName>"
- The skill says "Welcome to the <SkillName> skill."
- The skill sends an http GET request somewhere.
- The skill says "I've sent a request to <whoever>."
- The skill sends a second http GET request somewhere else.
- The skill says "I've sent a request to <whoever else>."
- The skill sends a third http GET request to another place.
- The skill says "I've sent a request to <the other place>."
- The skill terminates.
All this happens with no user action other than invoking the skill.

**Comment by bclement-amazon** [comment]
Hey barryburd,
Thanks for sending the scenario. 👍 
Once your skill has dispatched the initial response (e.g. "welcome to the skill") the user will need to re-invoke your skill before you can dispatch another response (e.g. " I've sent a request to... ").
There isn't a way to programmatically dispatch a response to a user out of session.

**Comment by barryburd** [comment]
In an alternative scenario, my skill has no intents. The user says "Alexa, <SkillName>" and as part of its launch, the skill sends out an http GET request and then halts. Since there's no response from the user after invoking the skill, I don't need any intents. I can create the Stop, Cancel and Help intents artificially, but there's no opportunity for the user to trigger those intents. In addition, the Alexa Skills Kit requires that I create a fourth intent (beyond Stop, Cancel and Help) and there's no opportunity for the user to trigger such an intent. This scenario may violate the style guidelines for Alexa skills, but that's okay because the skill isn't for publication. It's for private distribution. So my question is, Is there a way to create a skill that doesn't have the Stop, Cancel, Help or fourth intent? I can add these to the skill, but it seems artificial.

**Comment by realharry** [comment]
@barryburd  What you need seems like "notification". This feature will be available soon (I hope). See "Notification for ASK" in https://developer.amazon.com/blogs/alexa/post/5bef2f03-a3ff-4042-b8ec-a1e9196169a2/the-alexa-voice-service-makes-new-notifications-feature-available-to-device-makers.

Without notification, the obvious solution is "polling". (1) The user asks for the task to be done. (2) Your skill accepts and terminates. (3) The user asks your skill later whether the job was done. (4) Your skill answers (yes or no, or more detailed progress report like "78% complete" or "3 GET requests complete out 5", etc.) and terminates.

**Comment by Amazon-tianrenz** [comment]
Issue closed as feature described above is not currently supported by Alexa skills service. Please feel free to reopen if other question rises. Thanks
