### ISSUE TITLE
Making Skill State Management Simpler Clearer

### ISSUE THREAD

**Issue by julesmoretti** [alexa/alexa-skills-kit-sdk-for-nodejs#179]
For this example could we please have the full code base for the Lambda side and the Alexa Interaction model so that we can also test it out on our side and get an end to end functional example please?

[Link to Readme](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/edit/master/Readme.md#L147-167)

**Comment by julesmoretti** [comment]
Updates on the topic, if I copy paste this code only in the examples I get the `'Welcome to High Low guessing game. You have played 0 times. Would you like to play?` but when I respond `yes` I get: `There was a problem with the requested skill response`

**Comment by julesmoretti** [comment]
@bclement-amazon > anyone can help me with this?

**Comment by julesmoretti** [comment]
I am using the dash wand to test this. And if I do not answer it does not play the next line which is `Say yes to start the game or no to quit.` Wonder why that is?

**Comment by bclement-amazon** [comment]
Hi Jules,

Would you happen to have a log from cloudwatch for your lambda function? This example uses DynamoDB to persist state across sessions. It's possible that your lambda function does not have sufficient permissions to read/write or create the table (if it wasn't manually created by you.

A log would confirm this theory.

**Comment by julesmoretti** [comment]
@bclement-amazon 

<img width="1232" alt="screen shot 2017-09-07 at 2 02 13 pm" src="https://user-images.githubusercontent.com/744300/30185153-35eb73fa-93d5-11e7-8b72-8d7da48db3ca.png">

**Comment by julesmoretti** [comment]
<img width="1440" alt="screen shot 2017-09-07 at 2 07 29 pm" src="https://user-images.githubusercontent.com/744300/30185365-ee7f707e-93d5-11e7-8b6d-8647b790588f.png">

So if it is a DynamoDB issue then please let the user know about DynamoDB when going through this tutorial, as I had no idea that it may be a dependency to your example and also what it is in the first place, and how to even set it up. Meaning what is a partition key? and how do I set up these read write access.
