### ISSUE TITLE
Reprompt delay

### ISSUE THREAD

**Issue by julesmoretti** [alexa/alexa-skills-kit-sdk-for-nodejs#181]
Is there a way to control the detail between the re-prompt?

If not is there a way to keep the Custom skill alive for longer than a few seconds? This so that a user can trigger other intents without having to reopen the skill.

Thank you.

**Comment by bclement-amazon** [comment]
The time between prompt --> reprompt --> session timeout is not configurable.
Once the session has timed out the user will need to re-open the skill.

**Comment by smititelu** [comment]
@bclement-amazon how about increasing the listening time between the prompt -> listening -> reprompt, when the prompt was too long. (and reprompt never runs)

Is that configurable?

Thank you,
Stefan

**Comment by realharry** [comment]
@smititelu You can always use <break time=""/> in your response if it suits your use case.
