### ISSUE TITLE
Hi I have written one skill in aws lambda, now I am trying to convert same code to my local server.

### ISSUE THREAD

**Issue by shishirc** [alexa/alexa-skills-kit-sdk-for-nodejs#182]
I expect following code as entry point 
--
app.post('/alexatest', function (req, res) {
   fs.readFile( __dirname + "/" + "users1.json", 'utf8', function (err, data) {
	   var datetime = new Date();

       console.log( "-------" );
	   console.log(" URL requested on "+datetime+"------------------" );
       //res.end( " URL requested on "+datetime+"------------------" );
	     res.end( data );
   });
})
------
I have following code as entry point

exports.handler = (event, context) => {
  if (event.session.application.applicationId !== "*******") {
    context.fail("Invalid Application Id");
  }else{
	  
	   context.succeed(
        buildResponse({},
        buildSpeechletResponseWithoutCard("Hello. My name is Alexa. I'm live'',false)))
  }
--------------------------------------------------------- 

confused between use of (req,res) objects vs (event,context) objects........

**Comment by Amazon-tianrenz** [comment]
Hi @shishirc, 

Here's a great [documentation](http://docs.aws.amazon.com/lambda/latest/dg/programming-model-v2.html) explaining the core concepts you might come across when building Lambda function applications. 

A short description would be :
``event`` contains the data that your lambda function receives. Different from a ``request`` object you would receive in a HTTP communication, ``event`` doesn't contain HTTP header or anything else, just the body information that's sent to your skill. 
``context`` object contains the run time information of the lambda function that your skill's running on.  Here's the [link](http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html) to all information it might contain. 

Regards

**Comment by shishirc** [comment]
Then we must be able to write a coupling code for lambda function to call another function which will a web-service(say calculator.js) and this WS should be capable of running on local machine or lambda.

**Comment by Amazon-tianrenz** [comment]
@shishirc 
Your WS should be able to parse the incoming ``req`` and call proper handler function with parameter (event, context, callback).

regards
