### ISSUE TITLE
Missing documentation for AlexaSkillEvent

### ISSUE THREAD

**Issue by alopix** [alexa/alexa-skills-kit-sdk-for-nodejs#183]
Checking the source I know which handler names to use in order to support the new out of session events (AlexaSkillEvent.*), but I think it would be nice to also add this feature to the documentation/readme, so it's easier to find which event names are supported and how to implement them.

**Comment by ryhinchey** [comment]
I made a PR for this https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/188

**Comment by TianTXie** [comment]
The documentation  is here [Skill and List Events](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#skill-and-list-events). And also the sample skill is in [alexa-cookbook-context-skill-events](https://github.com/Alexa/alexa-cookbook/tree/master/context/skill-events).

**Comment by cfischbeck** [comment]
This looks perfect! Thanks!
