### ISSUE TITLE
video app lunch

### ISSUE THREAD

**Issue by ShadananaK** [alexa/alexa-skills-kit-sdk-for-nodejs#186]
Hi team,

Its found that support for video app lunch is recently added in Alexa sdk.

Please provide a sample for the lunching the video app from our skill. 

Please help.

Regards,
Shadanana

**Comment by tianrenz** [comment]
Hi ShadananaK, 

Please refer to the [Generating your own responses](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#generating-your-own-responses) section in the readme file. 

Regards
