### ISSUE TITLE
Best practice for “looping” through tell intent

### ISSUE THREAD

**Issue by warhost** [alexa/alexa-skills-kit-sdk-for-nodejs#190]
Let’s say I have a number of messages which Alexa needs to read out, but this number can change eveytime the skill is called. 

In the past where the number was known, I simply had an array of strings it read out, but if the number is not known, what is the best practice here? Does “for looping” tell emits work?

**Comment by memodoring** [comment]
This will not work, you will have to loop through your messages prior to emitting a response to the Alexa Service.  

Once you send back a response your lambda function ends its execution successfully.

**Comment by warhost** [comment]
But how does this get done programmatically? If I have an array of 10 strings I need to emit, doing

`this.emit(':tell', array[0] + array[1] ...);` sure isn't the best way and also not dynamic.

**Comment by muttoni** [comment]
Yes, you should concat strings -- really depends on how your array is structured though (and what sort of strings you have. 

You could do something like:  

```javascript
var array = [
'red',
'blue',
'green'
var responseString = 'Your colors are:' + array.join(','); // concat strings with commas
this.emit(':tell', responseString);
```

**Comment by warhost** [comment]
Thanks, figured out this is the best way.
