### ISSUE TITLE
emit("") does not work after "Unhandled"

### ISSUE THREAD

**Issue by realharry** [alexa/alexa-skills-kit-sdk-for-nodejs#192]
I am having this weird issue. Alexa does not recognize a certain phrase, and I am trying to handle the "Unhandled" intent. Once the "Unhandled" handler is called, however, emit(":ask") does not work. The same with ":askWithCard" or ":tell", etc. Here's an example:

    "Unhandled": function () {
      console.log(">>> GAME::Unhandled");
      // No emit() works after this point...
      // this.emit(":ask", "Are you there?", "Are you alive?");
      // this.emit(":tell", "Good bye!");
      // this.emitWithState("AskQuestion");   // This handler includes emit("") directly or indirectly.
    }

The interesting thing is, ASK does not throw an error. It simply stops with "There was a problem with the requested skill's response". My lambda function does not see any exceptions. It does not even reach my code. The emit() function simply dies.

I tried it with ASK@1.0.14 and ASK@1.0.11 with the same result.

**Comment by Amazon-tianrenz** [comment]
Hi, 

I've tested this using the sample skill and the latest SDK. However, I was not able to reproduce this problem. Could you please update to the latest SDK and test again? Please make sure ``Unhandled`` is properly defined and registered by calling alexa.registerHandler();

Regards

**Comment by kimhyunj** [comment]
Hi, I'm having this same issue. 

According to the log, after Unhandled() is called, no emit() calls are working. Alexa just says "undefined" as its speech output after Unhandled() is called.
