### ISSUE TITLE
How to Handle Slot Values with Invalid Types?

### ISSUE THREAD

**Issue by realharry** [alexa/alexa-skills-kit-sdk-for-nodejs#193]
I have an intent that includes a slot. The slot value type is AMAZON.NUMBER. Here's a sample utterance:

    AnswerResponseIntent open box {FirstBoxId} and box {SecondBoxId}

Now, my skill certification failed because the tester used non-number slot values. For example, the test used the following sentence:

   "open box 1 and box blah blah blah"

Alexa did not recognize this as "AnswerResponseIntent" (presumably because the second slot value was not a number) and it fell back to "Unhandled" (which I am having another issue with, #192 ).

Now, what's the best way to handle input slot values with invalid types? Having run into this issue, I'm now thinking, is there any value of using more specific types like "number" at all? The user can say anything (I presume we cannot force the users to say only certain things) and what's the point of constraining the data type to numbers, for instance?

In my example, I should have just used literal types:

    AnswerResponseIntent open box {FirstAnything} and box {SecondAnything}

and, parse the slot values to see if they are numbers. Or, I could have used a custom slot type with predefined numbers (say, "one" through "one hundred") and check if they are numbers.

Is there any way to specify, for instance, the value should be a number but I can still accept anything? (Like {NUMBER or LITERAL}?)

**Comment by Amazon-tianrenz** [comment]
Hi, 

One possible work around is to have multiple utterances defined using different slots. 
For example: 
you can include these two utterances in the interaction mode and both will be mapped to the same intent: 
AnswerResponseIntent open box {FirstBoxId} (where FirstBoxId is a AMAZON.NUMBER slot type)
AnswerResponseIntent open box {FirstBoxName} {where FirstBoxName is a AMAZON.LITERAL slot type}
This way, your skill will be able to catch both situations. 

For more information on your skill's voice interface design, please refer to this [document](https://developer.amazon.com/docs/custom-skills/best-practices-for-sample-utterances-and-custom-slot-type-values.html). 

Regards
