### ISSUE TITLE
Need more complete type information

### ISSUE THREAD

**Issue by realharry** [alexa/alexa-skills-kit-sdk-for-nodejs#194]
Some (crucial) type information seems to be missing. For example, AlexaObject.resources and Handlers.t("") are missing in type definitions.

I'm currently using (at)types/alexa-sdk version 1.1.0. Thanks.

**Comment by Amazon-tianrenz** [comment]
Hi @realharry, 
Thanks for your interest in Alexa NodeJS SDK.

Currently, types/alexa-sdk is not managed by our team. However, i did go and checked out their latest update on [Github](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/alexa-sdk/index.d.ts). It seems that ``AlexaObject.resources`` and ``Handlers.t`` do exist in type definitions.

I'm closing this issue now. Please feel free to reopen if further questions appear. 

Regards
