### ISSUE TITLE
Considering an askWithPermissionCard?

### ISSUE THREAD

**Issue by BJCheng** [alexa/alexa-skills-kit-sdk-for-nodejs#195]
The SDK currently only provides ":tellWithPermissionCard" feature, which would end the session. I only want to notify my users to enable the permission and then continue the rest of the skill. Having an askWithPermissionCard would be much helpful. 
Since the only difference between tellWithPermissionCard and askWithPermissionCard only differ at the shouldEndSession attribute, adding it seems pretty easy, is there any other concerns of not having askWithPermissionCard? Or is there any other alternatives that I am not aware of?
Thanks!

**Comment by Amazon-tianrenz** [comment]
Hi Cheng, 

Thanks for pointing this out!
This issue is addressed in the [latest release](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/releases/tag/1.0.15). 
Have fun with your skill development!

Regards
