### ISSUE TITLE
how set alarm command actually works?

### ISSUE THREAD

**Issue by nish17** [alexa/alexa-skills-kit-sdk-for-nodejs#197]
I'm trying to build a skill which requires setting an alarm at some particular given time.
But I don't know how setting alarm command works in the background. Is there any built-in function in the alexa-sdk which sets the alarm.

**Comment by brendanclement** [comment]
Hey nish, This use case currently isn't supported.  The user can ask Alexa to set an alarm but skills are not able to set alarms programatically!
