### ISSUE TITLE
Code Editor JSON upload huge file

### ISSUE THREAD

**Issue by warhost** [alexa/alexa-skills-kit-sdk-for-nodejs#199]
I was wondering if anyone has experience with uploading big JSON files to the code editor. I am working on a skill requiring lots of slot values, and uploading a JSON via the skill builders code editor seemed most appropriate.

However, the page doesn't respond for quite a while already. Is the best thing to do to wait? Or is there a better way? Is there a max upload size for the JSON files, or a max number of values a slot can have?

Cheers

**Comment by brendanclement** [comment]
I'm not aware of any max upload size. How large is the JSON file you're trying to upload? I personally use the [ASK CLI](https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html) to manage my skill definition and source code.

**Comment by warhost** [comment]
It’s 13 MB. Will have a look at the CLI option, thanks!

**Comment by Amazon-tianrenz** [comment]
I'm closing this issue for now. Please feel free to reopen it if you encounter further issues.
