### ISSUE TITLE
issue in playing video on echo show

### ISSUE THREAD

**Issue by pollensha** [alexa/alexa-skills-kit-sdk-for-nodejs#201]
Hi Team,
Am using the same sample code for playing video on echo show which was given in alexa sdk README. 

Below is the sample code which i am using:

"PlayVideoIntent": function() {
  console.log("entering video intent");
        // VideoApp.Play directives can be added to the response
		
         if (this.event.context.System.device.supportedInterfaces.VideoApp) {
			console.log("supported interface"+this.event.context.System.device.supportedInterfaces.VideoApp);
			console.log("video supported");
            this.response.playVideo('http://www.domainname.com/video.mp4');
        }
   
		else {
			console.log("video not supported");
            this.response.speak("The video cannot be played on your device. " +
                "To watch this video, try launching the skill from your echo show device.");
        }   
	
In simulator am getting value as undefined for  this.event.context.System.device.supportedInterfaces.VideoApp 

In echo show when  it is going to unhandled intent/default handler.
Please help me out with this.

Shalak

**Comment by tianrenz** [comment]
Hi pollensha, 

could you please verify that ``this.emit(':responseReady');`` is called after you build the response?

Regards

**Comment by pollensha** [comment]
Hi tianrenz,

Thank you for the quick reply.

I have added  this.emit(':responseReady'); line of code at the end of the function but still its not working. Below is the sample:

	 "PlayVideoIntent": function() {
  console.log("entering video intent");
        // VideoApp.Play directives can be added to the response
		console.log("video app "+this.event.context.System.device.supportedInterfaces.VideoApp);
		console.log(this.event.context.System.device.supportedInterfaces);

			   if (this.event.context.System.device.supportedInterfaces.VideoApp) {
			console.log("supported interface"+this.event.context.System.device.supportedInterfaces.VideoApp );
			console.log("video supported");
            this.response.playVideo('http://www.vitalwarecloud.com/alexa/medical-video.mp4');
			    
				
        }
   
		else {
			console.log("video not supported");
            this.response.speak("The video cannot be played on your device. " +
                "To watch this video, try launching the skill from your echo show device."+this.event.context.System.device.supportedInterfaces.VideoApp );

        }   
		
		this.emit(':responseReady'); 
    }


Please help me out

Regards

**Comment by Amazon-tianrenz** [comment]
Hi, pollensha,

If the skill keeps going into ``unhandled``, could you please check if the intent name matches the name ``PlayVideoIntent``?

Regards

**Comment by pollensha** [comment]
Hi tianrenz,
Yes the intent name matches with PlayVideoIntent. Inspite of that alexa still gives a message as " there is a problem with the requested skill response".

Please help me out

Regards

**Comment by Amazon-tianrenz** [comment]
Hi @pollensha 

Before we dive deeper, could you check the cloud watch log and see if either ``console.log()`` statement is logged? We want to make sure that ``PlayVideoIntent`` is actually invoked. 

Regards

**Comment by pollensha** [comment]
Hi tianrenz,

Yes the function is been  invoked and am able to see the logs. Below is the code and its cloud logs.

 "PlayVideoIntent": function() {
                console.log("entering video intent");
		console.log("video app "+this.event.context.System.device.supportedInterfaces.VideoApp);
		console.log(this.event.context.System.device.supportedInterfaces);

 if (this.event.context.System.device.supportedInterfaces.VideoApp) {
			console.log("supportedinterface"+this.event.context.System.device.supportedInterfaces.VideoApp );
			console.log("video supported");
            this.response.playVideo('play','https://www.domainname.com/alexa/video.mp4');
	    this.emit(':responseReady'); 
	 }
   
	else {
			
           console.log("video not supported");
            this.response.speak("The video cannot be played on your device. " +
                "To watch this video, try launching the skill from your echo show device." );
			this.emit(':responseReady'); 

        }   
  }

Cloud Logs:

2017-11-15T07:10:43.847Z	186a2af3-c9d4-11e7-804c-4ba0f5d5c3b9	entering video intent
2017-11-15T07:10:43.847Z	186a2af3-c9d4-11e7-804c-4ba0f5d5c3b9	video app undefined
2017-11-15T07:10:43.848Z	186a2af3-c9d4-11e7-804c-4ba0f5d5c3b9	{ Display: { templateVersion: '1', markupVersion: '1' } }
2017-11-15T07:10:43.866Z	186a2af3-c9d4-11e7-804c-4ba0f5d5c3b9	video not supported


When i try in simulator it gives response as "The video cannot be played on your device. To watch this video, try launching the skill from your echo show device."

when i try  directly in echo show it gives response as "There is a problem with requested skill response"

Please help me out
Regards

**Comment by Amazon-tianrenz** [comment]
Hi @pollensha,

The simulator on the developer portal currently doesn't support video playing. Therefore, the event it sends out will not have ``VideoApp`` in the "supportedInterfaces", which I think is reflected by the log above. 

When launching from echo show, the skill should reach the ``if`` statement. Could you try launch from echo show again and verify if any of the following two lines are logged?
````
console.log("supportedinterface"+this.event.context.System.device.supportedInterfaces.VideoApp );
console.log("video supported");
````

Also, ``this.response.playVideo()`` should takes in the source string like the following: 
``this.response.playVideo('https://www.domainname.com/alexa/video.mp4')``

Could you try and see if this fix the problem?

Regards

**Comment by ahendo026** [comment]
I am having the same problem using the same code. Please advise. Thanks!

**Comment by Cocco17** [comment]
Having the same problem - any news on that issue?

**Comment by Amazon-tianrenz** [comment]
Hi @ahendo026 @Cocco17, 
We are tracking this issue for a while and unfortunately was not able to replicate the issue above. Could you provide more info on the problems you've encountered? Logs and code snippet would be very helpful. Thanks!

Regards

**Comment by Cocco17** [comment]
Hi @Amazon-tianrenz,

here is an example of the response building code, that I used: 
`  this.response.speak("Willkommen bei der" + '<say-as interpret-as="spell-out">ADC</say-as>' + "Phrasendreschmaschine." + '<break time="1s"/>' + "Möchtest du eine Phrase hören?")
   .playVideo("https://uni-wuppertal.sciebo.de/index.php/s/cLFGLvmzFovoJKk/download")
   .hint("nenne mir eine Phrase")
   .renderTemplate(PhraseTemplate)
   .listen('Sorry, ich habe dich nicht verstanden!');
  this.emit(':responseReady');
 },`

The response works without the .playVideo command. Hope that this example will help you to resolve the issue 👍

**Comment by Amazon-tianrenz** [comment]
Hi @Cocco17,

This link leads to a page that requires login. That would cause the skill to fail cause it can't open the video page. 

Beside, the links to the video file must meet the following requirements(see [here](https://developer.amazon.com/docs/custom-skills/videoapp-interface-reference.html) for more information) : 
>Identifies the location of video content at a remote HTTPS location. The video file must be hosted at an Internet-accessible HTTPS endpoint. HTTPS is required, and the domain hosting the files must present a valid, trusted SSL certificate. Self-signed certificates cannot be used. Many content hosting services provide this. For example, you could host your files at a service such as Amazon Simple Storage Service (Amazon S3) (an Amazon Web Services offering).

Regards

**Comment by Cocco17** [comment]
Hi @Amazon-tianrenz,

I did as you said and uploaded the video on Amazon's S3. I only changed the url in the code as it seems to be valid, however the code is still not working... 

`  this.response.speak('<say-as interpret-as="interjection">Willkommen</say-as>' + "bei der" + '<say-as interpret-as="spell-out">ADC</say-as>' + "Phrasendreschmaschine." + '<break time="1s"/>' + "Möchtest du eine Phrase hören?")
   .playVideo("https://s3-eu-west-1.amazonaws.com/cocco17/Intro_Lindner.mp4")
   .hint("nenne mir eine Phrase")
   .renderTemplate(PhraseTemplate)
   .listen('Sorry, ich habe dich nicht verstanden!');
  this.emit(':responseReady');
 },`

**Comment by Cocco17** [comment]
@Amazon-tianrenz 

I found the problem in the code. It seems to be impossible to use the listen function in combination with a video. After commenting the line out, there was no problem playing the video. 

Is this behavior desired?

Thanks again for the support.

**Comment by Cocco17** [comment]
@Amazon-tianrenz 
Is it possible to launch a skill with a video first and then play the voice and ask the user a question?

**Comment by TianTXie** [comment]
@Cocco17, I don't think so, see this [link](https://developer.amazon.com/docs/custom-skills/videoapp-interface-reference.html#videoapp-directives), when sending a VideoApp directive, the outputSpeech should be null.

**Comment by Cocco17** [comment]
@TianTXie However, it is possible to generate a response that includes .speak & .playVideo. There is just no possibility to change the order.

**Comment by Amazon-tianrenz** [comment]
Hi @Cocco17,

According to information on this [page](https://developer.amazon.com/docs/custom-skills/videoapp-interface-reference.html#videoapp-directives), the your response includes a ``VideoApp.Launch`` directive, the ``shouldEndSession`` parameter must be omitted. 

So what's happening here is that, ``listen`` will try to set the ``shouldEndSession`` parameter in the response object to ``false``, which is not desired behavior for playing videos on Echo show device.

**Comment by Cocco17** [comment]
HI @Amazon-tianrenz,

 Okay, never mind. However, it would be interesting to be able to use video snippets for introduction purposes, for example when opening the skill, first followed by the response of Alexa. Maybe there's a chance to include this possibility in the next update of the sdk.

**Comment by rtrigoso** [comment]
I can confirm that System.device.supportedInterfaces doesn't contain VideoApp, even while using an Echo Show.

Here is my console log: 
`{ Display: { templateVersion: '1', markupVersion: '1' } }`

**Comment by michaelmyers** [comment]
I am noticing the same behavior as @rtrigoso.  From requests originating from a Show, supportedInterfaces does not contain VideoApp.  It only contains Display.

**Comment by DanMittendorf** [comment]
I too am having this problem but not with the Echo Show but with the Echo Spot. Checking this.event.context.System.device.supportedInterfaces is not returning "VideoApp" NOR "Display". Anyone found a solution yet?

**Comment by DanMittendorf** [comment]
Got it to work. For future references see: https://forums.developer.amazon.com/questions/106480/echo-spot-germany-not-having-videoappdisplay-when.html
