### ISSUE TITLE
playVideo fn in responseBuilder.js does not react to metadata presence

### ISSUE THREAD

**Issue by dothework** [alexa/alexa-skills-kit-sdk-for-nodejs#204]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/responseBuilder.js#L305

line 305 is currently > `if (playVideoDirective.videoItem.metadata) {`

it should be `if (metadata) {`

as it exists now it tests the object for a property that does not exist. it should, and I've tested this, test the param named metadata.

**Comment by Amazon-tianrenz** [comment]
Hi,
Thank you for pointing this out!
This bug is addressed in the latest release 1.0.16. 
Please feel free to reopen this issue if problem persists

Regards
