### ISSUE TITLE
How To Take Date As An Input To Alexa ?

### ISSUE THREAD

**Issue by KishanIos007** [alexa/alexa-skills-kit-sdk-for-nodejs#206]
I am new in skills development so please pardon me if the question is silly :)
when user says "alexa, ask agecalculator to calculate my age ?" then alexa reply "what is your date of birth ?" and the user tell the date of birth in any format like " 12 November 1995", "November 12 1995" 

How can i get this date in nodejs variable so that i can pass this to my api .

Any kind of help or advice acceptable :)
Thanks in advance. :)

**Comment by Amazon-tianrenz** [comment]
Hi, 
Alexa Skills Kit support[ AMAZON.DATE](https://developer.amazon.com/docs/custom-skills/slot-type-reference.html#date) slot type that can convert words that represent dates into a date format. For more slot type reference, please check out this [page](https://developer.amazon.com/docs/custom-skills/slot-type-reference.html). 

Regards

**Comment by OpenDog** [comment]
I agree with Kishan. There is no way to take a full date, like "October 23 1956". The DATE slot takes only things like "last year" or "next week". We cannot ask a date with one slot. It works on Google Home.
