### ISSUE TITLE
Why is this code executing?

### ISSUE THREAD

**Issue by eileennoonan83** [alexa/alexa-skills-kit-sdk-for-nodejs#208]
My understanding is that any code after a call to `this.emit(...)` should not execute, except in certain cases. Looking at the code for [`tellWithLinkAccountCard `](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/02bf986e937371949e77b15cb6b365d622adfa08/lib/response.js#L61), it looks like like this is definitely supposed to terminate the session and that no code after it should be executed. 

So, given the following code ...

```js
      var token = this.event.session.user.accessToken

      if (!token) {
        this.emit(
          ':tellWithLinkAccountCard',
          'You need to link your account etc etc etc'
        )
        console.log('how the $%^& is this code executing???')
      }
```

... how the $%^& is that last statement getting logged? In my use case, it's not just about that statement, it's about all the other code that executes after it. API calls that depend on the token, etc.

**Comment by Amazon-tianrenz** [comment]
Hi @eileennoonan83, 

One question: Did you pass the callback method to ``Alexa.handler`` like this ``Alexa.handler(event, context, callback)``

**Comment by eileennoonan83** [comment]
Yeah it goes a little something like this:

```js
const createLambdaHandler = function (config, handlers) {
  return function (event, context, callback) {
    var alexa = Alexa.handler(event, context, callback)
    alexa.appId = config.APP_ID
    alexa.registerHandlers(handlers)
    alexa.execute()
  }
}
```

```js
myHandlers = { ... }
exports.handler = createLambdaHandler(config, myHandlers)
```

**Comment by Amazon-tianrenz** [comment]
While ``this.emit()`` calls context.succeed() / callback(response) internally, it won't end the lambda execution immediately. NodeJS runs as asynchronously, which means although code gets executed line by line, it will not wait for function to finish. Therefore, what might happened here is that ``console.log()`` is executed before ``this.emit()`` could finish, which is supposed to terminate the lambda execution.

**Comment by eileennoonan83** [comment]
Thank you for that clarification.
