### ISSUE TITLE
Errors out when user doesn't respond on .listen()

### ISSUE THREAD

**Issue by craig-o-curtis** [alexa/alexa-skills-kit-sdk-for-nodejs#209]
Implementing a skill, and with no user intent on both .listen() and .listen( reprompt ), Alexa errors out by saying "There was a problem with the requested skill's response."

`
'use strict';
 
const Alexa = require('alexa-sdk');
const APP_ID = undefined;
 
const handlers = { 
    'LaunchRequest': function () {
        const launchMsg = "How can I help you?";
        const reprompt = "You can say, give me the weather.";
        this.response.speak( launchMsg )
            .listen( reprompt ); // errors out here on .listen if no input this.emit(':responseReady'); },
    'WeatherIntent': function () {
        this.response.speak( 'It is 100 degrees Kelvin' );
        this.emit(':responseReady'); 
    }
}
 
exports.handler = function (event, context, callback) {
    const alexa = Alexa.handler(event, context, callback);
    alexa.APP_ID = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
`

**Comment by Liamdelee** [comment]
hi there,
did you try it with: 
`this.emit(':ask', launchMsg, repromt);`
Just to see if the problem lays with the .listen or if it is something else.

**Comment by Amazon-tianrenz** [comment]
Hi @craig-o-curtis 

When user doesn't provide any input after reprompt times out, skill will receive a ``SessionEndedRequest`` with the reason "EXCEEDED_MAX_REPROMPTS". 

Your skill should be able to gracefully handle ``SessionEndedRequest`` in case of unexpected error happens. See [here](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#sessionendedrequest) for more possible reasons causing ``SessionEndedRequest`` sent to skill

In this case, you can choose to either handle this in ``SessionEndedRequest`` handler function or define an `Unhandled``` function in handler to catch all unexpected errors. 

Please let me know if above solution solves the problem. Feel free to close the issue if it does .

Regards

**Comment by craig-o-curtis** [comment]
@Liamdelee 
Tried that.
Still have same error.

**Comment by craig-o-curtis** [comment]
@Amazon-tianrenz 
So I tried adding just another handler:

`'SessionEndedRequest' : function() {
        this.emit(':tell', 'test end message');
  },`

But that ended with Alexa saying: "No sweat" instead of my 'test end message'.
Second test ended with Alexa LED turning green and playing a chime.

Attempting to see if this is a native API prefixed with AMAZON, I tried:

`  'AMAZON.SessionEndedRequest' : function() {
        this.emit(':tell', 'test end message);
    }`

This resulted in the original error "There was a problem with the requested skill's response".

Finally, I tried the 'Unhandled' handler:

`'Unhandled': function() {
        this.emit(':tell', 'test end message');
}`

This more gracefully ends, but doesn't read my 'test end message'. It also ends with the LED going green and chiming.

Question
-- Is my implementation of the SessionEndedRequest correct?
-- Can the Unhanded handler take any :emit commands?

Thanks!

**Comment by Amazon-tianrenz** [comment]
Hi @craig-o-curtis, 

As pointed out in this [document](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#sessionendedrequest), 
>Your skill cannot return a response to SessionEndedRequest.

A more common logic found in ``SessionEndedRequest`` function is to log the request and reason text. 

I've tried replicate the error and can confirm that skill will receive a ``SessionEndedRequest`` when user doesn't respond to reprompt. 

SDK logic provides that if a ``SessionEndedRequest`` handler is not provided, it will try to fall back to ``Unhandled``, which is I believe is consistent with your last attempt. 

``Unhandled`` can definitely emit a response just like a normal handler function. However, when responding to certain type of request that doesn't expect response from your skill service, try to emit a response with speech might cause an error. 

Regards
