### ISSUE TITLE
state of handler function context(this) is always null.

### ISSUE THREAD

**Issue by watanabeshuji** [alexa/alexa-skills-kit-sdk-for-nodejs#210]
In handler function, object `this` is 'handlerContext' (alexa.js L239 -257).

handlerContext has `state` property (L243).
But `this.state` is always null in handler function.

this.state is string BEFORE emit event for handler.
When `EmitEvent` function is called,  `this.state` is update.
But handlerContext.state is NOT update.
We must use `this.handler.state`, but NOT use `this.state` in handler function.

handlerContext.state should be deprecated, or update handlerContext.state before call handler.

**Comment by Amazon-tianrenz** [comment]
Hi @watanabeshuji 

Thanks for bring this into our attention. 
I've labeled this as a bug and created task internally to track this issue. At the meanwhile, please continue using ``this.handler.state`` instead of ``this.state``.

Regards,

**Comment by Amazon-tianrenz** [comment]
Hi @watanabeshuji, 
This issue has been resolved in the [1.0.19 release](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/releases/tag/1.0.19). 
Please feel free to reopen this issue if problem persists. 
Regards

**Comment by watanabeshuji** [comment]
thanks!
