### ISSUE TITLE
Handling reprompt scenario-Help wanted

### ISSUE THREAD

**Issue by roshancsc** [alexa/alexa-skills-kit-sdk-for-nodejs#212]
Hi,
I have a scenario where customer ask Alexa what's my travel plan which is map to "TravelIntent". This intent fetches customer travel details from REST API and after retrieving if customer is having more than 1 travel plan I want to present a dialog / reprompt with details that  "I can see that there are more than 1 plan. Say 1 for weekend trip , say 2 for blah blah... etc. " .Now if customer respond 1 Alexa skills should tells the complete travel detail of trip 1. Now my question is how to handle customer response after reprompt.
Do I have to create separate intent and how it fits in provided that I have multiple intent in the skill which can possibly pose similar scenario to reprompt or ask  customer input after Rest API call.

Thanks!!!

**Comment by Amazon-tianrenz** [comment]
Hi @roshancsc 
Customer's response to the reprompt will comes in as another intent request. You can define another intent (for example: TripSelectionIntent) in the interaction model and assign a AMAZON.Number Slot or a custom slot in the utterance to record potential input from customer. And then, in TripSelectionIntent, fetch the result and execute corresponding logic. 
Regards

**Comment by roshancsc** [comment]
Thanks @Amazon-tianrenz  for the response I am wondering in a scenario where I have multiple intents  in a skill and we have to re-prompt customer in some of the intent then what's the best way to handle it because one TripSelectionIntent cannot handle all the re-prompt,

**Comment by Amazon-tianrenz** [comment]
Hi @roshancsc,

If the reprompt might receives similar response from user, for example: User can say "1" to ``TravelInfoIntent`` and ``OtherInforIntent``, one good way to separate those is to use [State Management](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#making-skill-state-management-simpler)
You can use ``State`` to identify which scenario user is responding to and provide corresponding logic. 

Regards,

**Comment by roshancsc** [comment]
Yes that's the approach I was thinking Thanks @Amazon-tianrenz .
