### ISSUE TITLE
Alexa account linking debug ....

### ISSUE THREAD

**Issue by akshar001** [alexa/alexa-skills-kit-sdk-for-nodejs#213]
Hello,
I am trying to connect alexa user to my system using oauth 2.0
but somewhere it gets error. As i have tried in other systems my oauth server works properly..
would any one tell me where to debug the error because at my oauth server i found access token is assigned so i can not find where is the problem

**Comment by Amazon-tianrenz** [comment]
Hi @akshar001 

Are there any error logged in the cloudwatch? Those could help. 
Also, please make sure you filled everything correctly in account linking section of the developer portal. 
Regards

**Comment by akshar001** [comment]
Hello @Amazon-tianrenz  I appreciate your for help...yes i haved try cloud watch below i am pasting it..
`(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Method request body before transformations: grant_type=authorization_code&code=7b0ea6dafc9eed0f017ca9070d01b03323b71f08&redirect_uri=https%3A%2F%2Flayla.amazon.com%2Fapi%2Fskill%2Flink%2FM3BVP74N95SP1F&client_id=alexa&client_secret=alexa
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Endpoint request URI: https://lendinglistsjd.in/alexa/login/token.php
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Endpoint request headers: {x-amzn-apigateway-api-id=zcki9wxua5, CloudFront-Viewer-Country=IE, CloudFront-Forwarded-Proto=https, CloudFront-Is-Tablet-Viewer=false, User-Agent=Apache-HttpClient/4.5.x (Java/1.8.0_152), CloudFront-Is-Mobile-Viewer=false, X-Forwarded-Proto=https, CloudFront-Is-SmartTV-Viewer=false, Host=lendinglistsjd.in, Accept-Encoding=, X-Forwarded-Port=443, X-Amzn-Trace-Id=Root=1-5a029a59-03bf5c7124ebac923bbb84e2, Via=1.1 d94f0d72f08b19c6213ba63f63f3e070.cloudfront.net (CloudFront), X-Amz-Cf-Id=uOu5_q87TXXzhkzhz6tKaImcwqDlsahEXQHu4M_CzQ3GxDAHK3JciA==, X-Forwarded-For=54.240.197.10, 216.137.56.53, CloudFront-Is-Desktop-Viewer=true, Content-Type=application/x-www-form-urlencoded}
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Endpoint request body after transformations: grant_type=authorization_code&code=7b0ea6dafc9eed0f017ca9070d01b03323b71f08&redirect_uri=https%3A%2F%2Flayla.amazon.com%2Fapi%2Fskill%2Flink%2FM3BVP74N95SP1F&client_id=alexa&client_secret=alexa
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Sending request to https://lendinglistsjd.in/alexa/login/token.php
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Received response. Integration latency: 1307 ms
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Endpoint response body before transformations:
{
    "access_token": "79a3b369f9bac112eb288565fa314284e5ffd317",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "profile:user_id",
    "refresh_token": "21f1d2ec78ef64d984b531c70ce5d7af36ae2d29"
}
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Endpoint response headers: {Keep-Alive=timeout=5, max=500, Transfer-Encoding=chunked, Server=Apache, Cache-Control=no-store, Connection=Keep-Alive, Pragma=no-cache, Date=Wed, 08 Nov 2017 05:46:47 GMT, Content-Type=application/json;charset=UTF-8}
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Method response body after transformations:
{
    "access_token": "79a3b369f9bac112eb288565fa314284e5ffd317",
    "expires_in": 3600,
    "token_type": "Bearer",
    "scope": "profile:user_id",
    "refresh_token": "21f1d2ec78ef64d984b531c70ce5d7af36ae2d29"
}
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Method response headers: {Keep-Alive=timeout=5, max=500, Server=Apache, Cache-Control=no-store, Connection=Keep-Alive, Pragma=no-cache, Date=Wed, 08 Nov 2017 05:46:47 GMT, Content-Type=application/json;charset=UTF-8}
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Successfully completed execution
(40a4545f-c448-11e7-b7bf-71c7b76b99d9) Method completed with status: 200`

please help me where to find the error now..

**Comment by akshar001** [comment]
And @Amazon-tianrenz  also i have tried credential with body and with http basic authentication actually access_token has been granted to alexa but it doesn't seems to accept it.. i believe this is the small error of mine but if you can help it will save my time a lot..

**Comment by Amazon-tianrenz** [comment]
Hi @akshar001 
Account linking feature is not managed by our team. I can try and assigned this issue to the service team guys. 
Meanwhile, here are two great documentations ([link](https://developer.amazon.com/docs/custom-skills/link-an-alexa-user-with-a-user-in-your-system.html), [link](https://developer.amazon.com/blogs/post/tx3cx1etrzz2npc/alexa-account-linking-5-steps-to-seamlessly-link-your-alexa-skill-with-login-wit)) on how to set up account linking for your Alexa skill. Hope they can help!
Regards

**Comment by akshar001** [comment]
Hello @Amazon-tianrenz  i can understand this is not issue if you can suggest me where to go i will close this issue and move on to them it would be a very great help then

**Comment by Amazon-tianrenz** [comment]
Hi @akshar001 
I would suggest [Alexa Developer forum ](https://forums.developer.amazon.com/spaces/165/index.html) as a great place to post this question. It's actively monitored by Amazon engineers and lots of developers are posting there, too!

**Comment by akshar001** [comment]
@Amazon-tianrenz  thanks for your support i wish this thing would come into your area..you are very helpful thanks for that i won't bother you anymore..

**Comment by Amazon-tianrenz** [comment]
Hope you have a wonderful experience with our Node.js SDK!
Please feel free to open issue if you have any questions in the future!
