### ISSUE TITLE
Global state store with a global key in the DynamoDB

### ISSUE THREAD

**Issue by vidanov** [alexa/alexa-skills-kit-sdk-for-nodejs#215]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#persisting-skill-attributes-through-dynamodb

It seems you support only local attributes saving in the database.
But what if I want to put global attributes for the skill in the DynamoDB table?
like "state": {"highscore":{"Ant Lion":"100"}}

Do you plan to add this too? It is the very useful feature.

**Comment by Amazon-tianrenz** [comment]
Hi @vidanov 
Thanks for your input! I've created tasks on internal backlog to track this feature. 
Meanwhile, AWS SDK provides a great [dynamoDB API client ](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB.html)that might be useful in your case. 
Regards

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).

**Comment by vidanov** [comment]
Thank you a lot! The greatest update 👍
