### ISSUE TITLE
Passing slot values within intents in same skill

### ISSUE THREAD

**Issue by sailesharya** [alexa/alexa-skills-kit-sdk-for-nodejs#217]
Hello I have a requirement where i need to keep the slots values same when intent is changing. Any way?

Example:
Intent1: PaymentDetails
Intent2: ApprovePayment
Intent3: InvoiceDetails

Alexa, what is status of payment of supplier ABC
--> Payment of 200$ is pending
1. Approve it
2. Details of the invoice etc

so in both the cases it should take the slot values of the previous intent.

**Comment by Amazon-tianrenz** [comment]
Hi @sailesharya, 

For persisting information through sessions, you could use the stateManagement feature our SDK provides. See [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#persisting-skill-attributes-through-dynamodb) for example. 

The slot value is defined in the skill interaction model. So for different intent, the slot value is passed by the customer, not the skill. 

Regards
