### ISSUE TITLE
The data of elicitSlot already obtained disappear

### ISSUE THREAD

**Issue by yoonji-kim** [alexa/alexa-skills-kit-sdk-for-nodejs#221]
After getting the data for the elicitSlot, other slots' data do not exist which is already get from the user.
So, Alexa keeps asking for the answer of elicitSlots endless.
How can I keep the other slots' data which was already filled by the user?
Here is my code below.

'getDataIntent': function () {
        const typeSlot = this.event.request.intent.slots.type;
        const idSlot = this.event.request.intent.slots.id;
        
        if(!idSlot.value) {
            var slotToElicit = 'id';
            var speechOutput = "Please say the pin number.";
            var repromptSpeech = speechOutput;
            this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech);
        } else if(!typeSlot.value){
            var slotToElicit = 'type';
            var speechOutput = "Please say the pin type. Analog? Digital?";
            var repromptSpeech = speechOutput;
            this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech);
        } else {
            var id = idSlot.value;
            id = id.substring(4, id.length);
            handleIntent(this, typeSlot.value, pinId);
        }
}

**Comment by TianTXie** [comment]
Hi，@yoonji-kim:
When you updated the slot, you should update the intent also. The correct format is:
this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech, updatedIntent);
Could you try the code below:
```
if(!idSlot.value) {
        var slotToElicit = 'id';
        var speechOutput = "Please say the pin number.";
        var repromptSpeech = speechOutput;
        var updateIntent = this.event.request.intent;
        this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech, updateIntent);
    } else if(!typeSlot.value){
        var slotToElicit = 'type';
        var speechOutput = "Please say the pin type. Analog? Digital?";
        var repromptSpeech = speechOutput;
        var updateIntent = this.event.request.intent;
        this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech, updateIntent);
    } else {
        var id = idSlot.value;
        id = id.substring(4, id.length);
        handleIntent(this, typeSlot.value, pinId);
    }
```
