### ISSUE TITLE
Echo Show

### ISSUE THREAD

**Issue by jawetzel** [alexa/alexa-skills-kit-sdk-for-nodejs#224]
using the code example in the documentation results in the lambda function timing out. my lambda function currently working using ':tellWithCard'.

Code:

`const Alexa = require('alexa-sdk');
// utility methods for creating Image and TextField objects
const makePlainText = Alexa.utils.TextUtils.makePlainText;
const makeImage = Alexa.utils.ImageUtils.makeImage;

"market_update": function () {
     const builder = new Alexa.templateBuilders.BodyTemplate1Builder();
     var template = builder.setTitle("My BodyTemplate1")
        .setBackgroundImage(makeImage("https://imgur.com/gallery/6l4C5', 500, 250, '500x250", "this is an image"))
        .setTextContent(makePlainText("potatoes"))
        .build();

this.response.speak('Rendering a template!')
          .renderTemplate(template);
          this.emit(':responseReady');
 },`

I have also tried this function using the one makeimage paramater with the same output:
makeImage('https://imgur.com/gallery/6l4C5')

error message:
{
  "errorMessage": "2017-11-22T18:15:59.187Z 2db3f9ae-cfb1-11e7-9b33-8db5e6dda322 Task timed out after 3.00 seconds"
}

Log output:
START RequestId: 2db3f9ae-cfb1-11e7-9b33-8db5e6dda322 Version: $LATEST
END RequestId: 2db3f9ae-cfb1-11e7-9b33-8db5e6dda322
REPORT RequestId: 2db3f9ae-cfb1-11e7-9b33-8db5e6dda322	Duration: 3003.15 ms	Billed Duration: 3000 ms 	Memory Size: 128 MB	Max Memory Used: 83 MB	
2017-11-22T18:15:59.187Z 2db3f9ae-cfb1-11e7-9b33-8db5e6dda322 Task timed out after 3.00 seconds

**Comment by TianTXie** [comment]
Hi, @jawetzel 
The link of your image resource is invalid. The image should be an image format like .jpeg, .png.
If you can not find this kind of image, you could download an image and save it in the S3. Remember when you upload the image to S3,  in the set permissions, you need to select 'Grant public read access' to access the image.

**Comment by radmoose** [comment]
@jawetzel The link you used is the imgur URL to the web page that displays
the image.  The image URL is https://i.imgur.com/4qJvAi2.jpg
