### ISSUE TITLE
```:tellWithPermissionCard``` returning SpeechletResponse as null

### ISSUE THREAD

**Issue by arctouch-pedrocosta** [alexa/alexa-skills-kit-sdk-for-nodejs#227]
If I use the ```this.emit(':tellWithPermissionCard', "Message", ['read::alexa:household:list', 'write::alexa:household:list']);``` code within my custom skill the alexa skill fails with the error "Null SpeechletResponse" I'm not sure what I'm doing wrong since I'm assuming I'm following the correct format. Can someone help me?

**Comment by TianTXie** [comment]
Hi, @arctouch-pedrocosta,
I can not find any problem here, could you post a code snippet, so that I can know more context?

**Comment by arctouch-pedrocosta** [comment]
@TianTXie a simple code snippet would be the following

```
"use strict";
const Alexa = require("alexa-sdk");
const https = require("https");

exports.handler = (event, context) => {
  let alexa = Alexa.handler(event, context);
  alexa.appId = "<YOUR_ID>";
  alexa.registerHandlers(genericHandlers);
  alexa.execute();
};

// Generic Handlers

const genericHandlers = {
  "LaunchRequest": function() {
    this.emit(':tellWithPermissionCard', "Launch Request", ['read::alexa:household:list', 'write::alexa:household:list']);
  },
  "Unhandled": function() {
    this.emit(':tellWithPermissionCard', "Unhandled", ['read::alexa:household:list', 'write::alexa:household:list']);
  }
};

```

I'm using a Lambda Function with Node.js 4.3

**Comment by TianTXie** [comment]
@arctouch-pedrocosta ,
In the alexa developer console, when you configure the skill, did you add Lists Read and Lists Write in Permissions?

**Comment by arctouch-pedrocosta** [comment]
@TianTXie I did, see screenshot
![screen shot 2017-11-30 at 12 55 05 pm](https://user-images.githubusercontent.com/10923005/33454447-c4515bf2-d5cd-11e7-8671-6eba1a2a3c98.png)

**Comment by TianTXie** [comment]
@arctouch-pedrocosta,
I can not replicate the error. This is the code I used to test:
```
'LaunchRequest': function () {
        this.emit(':tellWithPermissionCard', "Launch Request", ['read::alexa:household:list', 'write::alexa:household:list']);
    },
```
I got the result below in the [alexa console](https://alexa.amazon.com):
<img width="852" alt="screen shot 2017-11-30 at 1 44 08 pm" src="https://user-images.githubusercontent.com/4759738/33456545-92056be6-d5d4-11e7-9180-e3f87517a2c0.png">

**Comment by arctouch-pedrocosta** [comment]
@TianTXie Could it be something related to the way the skill is setup in AWS and Dev Console? I did add the permissions as mentioned above but my skill is not live yet. do you see any possible problems that could cause such thing?

**Comment by TianTXie** [comment]
@arctouch-pedrocosta , 
I think as long as you can see the logs in the cloudWatch when you send the launch request, your skill is live and connect to the lambda correctly. Can you try just send a normal response like: this.emit(':tellWithCard',....) in the launch request to see if it works or not?

**Comment by arctouch-pedrocosta** [comment]
@TianTXie that works without problems, I would like to add that this snippet I sent in the first response was added inside a lambda function that already existed and has a full working alexa skill (not yet published), right now the only thing remaining is adding this permission card.

**Comment by TianTXie** [comment]
@arctouch-pedrocosta,
Could you check which alexa-sdk version do you use now? The latest one is 1.0.21.

**Comment by arctouch-pedrocosta** [comment]
hm that's it @TianTXie ! I didn't know I had to update the sdk used, how do I do that? is there a easy way? I didn't find it within the lambda function, right now I'm using 1.0.6

**Comment by TianTXie** [comment]
@arctouch-pedrocosta ,
In the node_modules directory, there is a folder called alexa-sdk, you can check the SDK version in package.json file. You can run `npm update` to get the newest version.

**Comment by arctouch-pedrocosta** [comment]
@TianTXie 
I'm developing the Alexa Skill through the AWS Portal writing code using the inline feature, therefore I didn't want to upload a zip file, I would prefer if it's possible to update it within the AWS portal it self, doing a little bit of research on Google I couldn't find a answer regarding the way to do it. can you provide guidance in this?

**Comment by Amazon-tianrenz** [comment]
hi @arctouch-pedrocosta, 
"tellWithPermissionCard" is not available at version 1.0.6. Please consider upgrade to the latest version of SDK. 

If you are developing using the inline editor on Lambda console, the SDK might have been outdated. We noticed the problem and are actively contacting the team responsible to fix the issue. But for now, please consider using offline editors and upload your code files in a zip folder. 

[Here](https://github.com/alexa) are plenty of great sample skills that shows how to use our latest sdk combined with ASK-CLI tools, like [this one](https://github.com/alexa/skill-sample-nodejs-fact). Hope those can help! 

Regards

**Comment by arctouch-pedrocosta** [comment]
hello @Amazon-tianrenz thanks for the reply, it would be ideal to have it fixed in the inline editor but I'm able to use the upload zip tactic for now.

thank you, this can be closed.

**Comment by Amazon-tianrenz** [comment]
@arctouch-pedrocosta, glad i could help!

**Comment by talkingnews** [comment]
@arctouch-pedrocosta - it's a pain, for sure, and the new lambda interface doesn't help.
So I never go near it now - once you get familiar with ask-cli your life will dramatically improve!

Do this once:
```
ask clone (then choose your skill)
once cloned, cd to (skill)/lambda/custom
npm install
npm update
ask deploy -t lambda
```

Now you are running the latest sdk! And when you've edited your node code a bit, just do:
`ask deploy -t lambda`
takes about 5 seconds each time, no messing with zip files and uploading them.

Take an hour to get used to the ask-cli and you will save yourself tens of hours in the future :)

**Comment by arctouch-pedrocosta** [comment]
@talkingnews interesting! I did give it a try but somehow I cannot link the `aws_profile`, I called the `ask init` multiple times and I'm redirected to the amazon login page to login it's always successful and the console says `Profile [default] initialized successfully.`, but, the `aws_profile` is always null, therefore I cannot download the Lambda Function code

**Comment by talkingnews** [comment]
Hi @arctouch-pedrocosta - this probably isn't the right thread to continue with the ask-cli linking problems, so come on over to http://www.alexaslack.com/ or https://forums.developer.amazon.com/spaces/23/index.html and ask there. 

Just one thing to try, though - just ensure you are definitely logging in with the same account, in the correct region, and also try this:
`ask init --no-browser`
> --no-browserOptional. This provides an alternative method to initialize ASK CLI without opening the browser in the same developing environment. Instead, you can copy the url displayed in the console and open the link with a web browser anywhere. This will direct you to the login page of Amazon. Sign in and copy the Authcode back to the terminal, then you have initialized ASK CLI successfully.

**Comment by arctouch-pedrocosta** [comment]
thanks @talkingnews the problem was that I didn't have the full access to AWS, now that I have it's working! thank you!!
