### ISSUE TITLE
How to Identify Which Device has requested a Custom Skill

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/alexa-skills-kit-sdk-for-nodejs#231]
Hi Experts,

I am writing a custom Alexa Skill and I need Alexa-Skill API in Lambda to know who has invoked custom skill. 

For example:-
I have created one ProductID:- SampleDevice in Amazon Developers account.
Now, I have registered 3 different Devices with Serial Numbers, 0001,0002,003. I have created one custom Skill named **"MyCustomSkill"**. So now each of these devices can invoke my custom skill.

So I need some Alexa-Skill API in Lambda to identify which device has invoked MyCustomSkill.

Regards
Sandy

**Comment by TianTXie** [comment]
Hi, @sandeepajesh ,
In the request your skill received, there is a 'deviceId' (context-> System-> device -> deviceId) that can recognize which device has invoked the skill. See [this](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-body-syntax) for more information.

**Comment by sushantbisht** [comment]
The DeviceId is not the same as the Device Serial no and hence knowing the deviceId will not help. Any Suggestion on mapping the device serial no to the deviceId received in the alexa skill?

**Comment by seino-tsuyoshi** [comment]
Why don't you create 'MappingIntent'?

for example, 

```
slot: serialno - AMAZON.FOUR_DIGIT_NUMBER
Sample Utterance: connect my echo to {serialno}
```
Using dynamoDB, you can put the mapping data - serial no and device id in the Lambda function.

**Comment by sushantbisht** [comment]
It is good idea where we can ask Customer to put the Serial No through let's say mappingIntent. However given that serial No is known ahead of time, I am wondering whether there is a way of getting that mapping done without asking the DSN from the customer.

**Comment by jbfitb** [comment]
Is there a way of knowing the device type in a skill? Like knowing that the request came from a Bose headphones vs an Echo show?
