### ISSUE TITLE
Just start learning coding again, but still don't  Understand some of the code.

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#233]
onIntent: function (intentRequest, session, response) {
      var intent = intentRequest.intent,
        intentName = intentRequest.intent.name,
        intentHandler = this.intentHandlers[intentName];
    if (intentHandler) {

        console.log('dispatch intent = ' + intentName);       //the 'dispatch intent ='

        intentHandler.call(this, intent, session, response);//and the call 
    } else {
        throw 'Unsupported intent = ' + intentName;
    }
},

> 

AlexaSkill.prototype.intentHandlers = {};

AlexaSkill.prototype.execute = function (event, context) {
    try {
        console.log("session applicationId: " + event.session.application.applicationId);

        // Validate that this request originated from authorized source.
        if (this._appId && event.session.application.applicationId !== this._appId) {
            console.log("The applicationIds don't match : " + event.session.application.applicationId + " and "
                + this._appId); // also it is the same code every time?
            throw "Invalid applicationId";
        }

        if (!event.session.attributes) {
            event.session.attributes = {};
        }

        if (event.session.new) {
            this.eventHandlers.onSessionStarted(event.request, event.session);
        }

        // Route the request to the proper handler which may have been overriden.
        var requestHandler = this.requestHandlers[event.request.type];
        requestHandler.call(this, event, context, new Response(context, event.session));
    } catch (e) {
        console.log("Unexpected exception " + e);
        context.fail(e);
    }

> };

**Comment by allthepies** [comment]
Is there a question ?

**Comment by Amazon-tianrenz** [comment]
Hi @25kcdiez, 
Is there a specific part that you need help with?

**Comment by 25kcdiez** [comment]
Tianrenz thanks for the reply  man and sorry for the late reply..

so I solve it by my self and thank's  for the support tianrenz.

Just one more thing  what thus  this code do?

` this._context()` "_context".

**Comment by Amazon-tianrenz** [comment]
@25kcdiez 
it passes the context parameter from Lambda function to your handler
