### ISSUE TITLE
audioPlayerPlay does not allow chaining play directives

### ISSUE THREAD

**Issue by scottbouma** [alexa/alexa-skills-kit-sdk-for-nodejs#24]
I'd like to queue up multiple audio streams, as per the directives array discussed in the API docs here:  
https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills

The natural way seems to be to make multiple calls to audioPlayerPlay.  Unfortunately that method just overwrites the directive array every time instead of pushing new items.  It would be nice if that method would support multiple calls.

**Comment by KrishFuriaAmazon** [comment]
Making multiple calls is currently not supposed by the API. But you can look in this [sample](https://github.com/alexa/skill-sample-nodejs-audio-player/blob/mainline/js/audioEventHandlers.js#L41) how "**_PlaybackNearlyFinished_**" is implemented to solve your purpose.

For more information checkout "**_Handling AudioPlayer Requests_**" section of the [API Docs](https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills).
