### ISSUE TITLE
Getting started with alexa notifcations

### ISSUE THREAD

**Issue by malikasinger1** [alexa/alexa-skills-kit-sdk-for-nodejs#246]
Hey,
We want to develope a alexa skill to deploy on alexa devices that will send notifications three times a day , and we are using express server and deploying it on heroku, my questions are.
1) Does alexa-sdk( https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) support alexa notifications?
2) How can we use alexa-sdk( https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs ) with our node server.

**Comment by TianTXie** [comment]
@malikasinger1, Notification service is available in AVS, the documentation is [here](https://developer.amazon.com/docs/alexa-voice-service/notifications-overview.html). But it is not supported by alexa-sdk for now.

**Comment by malikasinger1** [comment]
you men if I'm making alexa skill for alexa device i can not use the notification feature?

**Comment by TianTXie** [comment]
@malikasinger1 , Yep. Not for now. I will update the SDK if supported in future. Stay tuned.

**Comment by kyle-ssg** [comment]
Any update on this ?

**Comment by SubrahmanyamSistha** [comment]
any update on alexa notifications?

**Comment by dgreene1** [comment]
I’d settle for some simple clear documentation because at the moment I can’t even find an API spec for the calls I assume I have to make to set notifications. That link provided above by @TianTXe has a sequence diagram but there are no technical information on how to implement those calls.

**Comment by mInzamamMalik** [comment]
any update?

**Comment by tamerbak** [comment]
Any update on this feature ?
