### ISSUE TITLE
Building a similar SDK for Lex

### ISSUE THREAD

**Issue by hotessy** [alexa/alexa-skills-kit-sdk-for-nodejs#248]
Hi,
I am building voice assistant which will be deployed in an Android app. After a lot of research (and some implementation), I found out [Lex](http://docs.aws.amazon.com/lex/latest/dg/what-is.html) is a better option than Alexa Skill Kit for this purpose. I'm pretty sure this use case is very common.

Is there a similar NodeJS SDK for Lex ? If not, would anyone like to collaborate to build one ?

@amazon_team if is post is inappropriate here, please direct me to some place where I could get some real help (I've already posted it on the [Alexa forum](https://forums.developer.amazon.com/questions/101987/nodejs-sdk-for-lex.html))

**Comment by TianTXie** [comment]
@hotessy,
That is really a good suggestion, I will create an internal issue to discuss it.
Thanks for your inputting.

**Comment by hotessy** [comment]
Great @TianTXie
