### ISSUE TITLE
Minor Correction in README for ListTemplate

### ISSUE THREAD

**Issue by terrenjpeterson** [alexa/alexa-skills-kit-sdk-for-nodejs#251]
In the instructions for rendering a list template, it's using an undeclared variable "template".

    this.response.speak('Rendering a list template!')
    			.renderTemplate(template);
    this.emit(':responseReady');

I'm using the SDK now, and it's an easy fix - the second line should read 

.renderTemplate(listTemplate);

**Comment by TianTXie** [comment]
Fixed. Thanks!
