### ISSUE TITLE
Action Links?

### ISSUE THREAD

**Issue by prichey** [alexa/alexa-skills-kit-sdk-for-nodejs#259]
There's reference to 'action links' in the Display Interface Reference (here: https://developer.amazon.com/docs/custom-skills/display-interface-reference.html#bodytemplate2-for-image-views-and-limited-centered-text) but I don't see anything in the SDK (either the documentation or code) that suggests that it supports it. Am I wrong? Are there any plans to implement this functionality with the SDK?

Thanks!

**Comment by TianTXie** [comment]
Hi, @prichey,
If you want to include the action link in the display interface, specify your text content type to 'RichText', then you can use the supported markup and supported XML characters to change the appearance of the text. [This](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html#supported-markup) is the Supported Markup for Text in Display Templates.
```javascript
const Alexa = require('alexa-sdk');
const bodyTemplateBuilder = new Alexa.templateBuilders.BodyTemplate1Builder();
const template = bodyTemplateBuilder
                         .setTextContent(Alexa.utils.TextUtils.makeRichText('<action value = "WelcomeIntent">Welcome Screen</action><br/><br/>'))
                         .setTitle('Including actions in rich text elements')
                         .build();
 
     this.response.speak('Welcome!')
                 .renderTemplate(template)
                 .setShouldEndSession(null);
     this.emit(':responseReady');
```

**Comment by prichey** [comment]
Thanks @TianTXie. That's helpful but I'm not sure that's the 'action links' shows in the documentation.

I'm trying to implement something as shown in these screens (https://m.media-amazon.com/images/G/01/mobile-apps/dex/ask-customskills/bt-3._TTH_.png), the blue links above the title text, rather than bolded links in the body content.

Any ideas?

**Comment by TianTXie** [comment]
Hi, @prichey,
Yes the blue links are action links. Just follow the sample code snippet to make your text clickable.
If you want to make bold, then use \<b\>your text\<\b\> following XML syntax.

**Comment by prichey** [comment]
Right, I know that the blue links are action links, but your solution includes them in the body content (below the title). If you look at the examples shown [here](https://m.media-amazon.com/images/G/01/mobile-apps/dex/ask-customskills/bt-3._TTH_.png), there are action links shown above the title, which I do not believe is possible using the method you suggested of adding them in the text content.

Is there any way with the SDK to include links above the title as shown? Thanks for your help!

**Comment by TianTXie** [comment]
In the sample picture, the title is 'Mild Gouda' at top right which can not be made as rich text.
All content at the right side include 'Food pairings', 'Wine pairings' and bold 'Mild Gouda' are included in textContent that you can make rich follow XML syntax.

**Comment by prichey** [comment]
Alright, thanks for your help @TianTXie!
