### ISSUE TITLE
How do I get city (or any other string) as Input in Alexa?

### ISSUE THREAD

**Issue by hayderma** [alexa/alexa-skills-kit-sdk-for-nodejs#260]
I am having truoble getting input from user voice, I tried using "ask", but I am not sure how to actually access the object, my intent schema looks like this:
```
{
  "intents": [
    {
      "intent": "HelloIntent"
    },
    {
      "intent": "AgeIntent"
    },
     {
      "intent": "CityDataIntent"
    },
    {
      "intent": "TimeIntent"
    },
    {
      "intent": "AMAZON.HelpIntent"
    },
    {
      "slots": [
        {
          "name": "city",
          "type": "AMAZON.US_CITY"
        }
      ],
      "intent": "Ask"
    }
  ]
}
```
My Sample Utterances:
`Ask city name`
In my index.js , the intent function looks like this:

```
'Ask' : function() {
        //emit response directly
       this.emit(':ask', "Which US city do you want information for?");
        var inp = this.event.request.intent.slots["object.city"].value;
        console.log(inp);
    }
```
Amazon Log 
```
TypeError: Cannot read property 'value' of undefined
at Object.Ask (/var/task/index.js:55:65)
at emitNone (events.js:86:13)
at AlexaRequestEmitter.emit (events.js:185:7)
at AlexaRequestEmitter.EmitEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:211:10)
at AlexaRequestEmitter.ValidateRequest (/var/task/node_modules/alexa-sdk/lib/alexa.js:176:23)
at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:121:25)
at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:95:31)
at exports.handler (/var/task/index.js:76:11)
```

I get the "Which US city do you want information for?" on the Alexa, and it waits for input but once I say something, it calls another intent function, can someone please give me direction to how to get input?  
Thanks

**Comment by TianTXie** [comment]
Hi, @hayderma,
I think you can use this.event.request.intent.slots.city.value to get the input value from user.

**Comment by hayderma** [comment]
@TianTXie , thanks for reply, i have tried that first, it didn't work either, iam getting "undefined" when i print (typeof inp) or (inp) 
```
var inp = this.event.request.intent.slots.city.value; 
console.log(typeof inp);
```
Starting from` intent` the IDE underline it as `Unresolved Variable` , same thing with` slots` and `value`.

**Comment by TianTXie** [comment]
@hayderma , Could you try that before this.emit(':ask'). Because this will immediately stops processing of any further background tasks. I don't know if the data in this request is still available after you emit the response.

**Comment by hayderma** [comment]
@TianTXie , just did, same problem: undefined.

**Comment by TianTXie** [comment]
@hayderma , actually, I am a little bit confusing, in the 'Ask' intent, you said this.emit(':ask', "Which US city do you want information for?"),  that is asking user to provide the city name, and at that time your slot is not filled, that is why it is undefined. You can print out the request JSON string in the console to see if the slot is filled or not.

**Comment by hayderma** [comment]
@TianTXie , I just did, this is what i have when i print the request:

```
{ type: 'IntentRequest',
requestId: 'amzn1.echo-api.request.ce493e60-471c-4ba9-bb2b-b0a2f4055a15',
timestamp: '2018-01-05T22:54:57Z',
locale: 'en-US',
intent: 
{ name: 'Ask',
confirmationStatus: 'NONE',
slots: { city: [Object] } } }
```

**Comment by TianTXie** [comment]
@hayderma If the sample utterance is 'Ask {city name}' which means that the user tells Alexa that he/she wants to ask information about this city. So the Alexa already knows which city the user is interested in so the slot value is filled in and you don't need to ask user "Which US city do you want information for?" again. If the sample utterance is 'Ask city name', then you ask user "Which US city do you want information for?" and user will answer you this question by {city name}, you need to define another intent to receive this message and the slot should be defined and filled there.

**Comment by pranavshenoy** [comment]
@TianTXie  I have a doubt regarding getting slot values related to this .
suppose the slot value is empty when passing the JSON to the corresponding intent and how can we ask for the slot value?

in the above example, 
    this.emit(':ask', "Which US city do you want information for?");

after this line, where will the value given by the user gets stored  so that we can access it?
like for dialog model(according to my understanding),

            const slotToElicit = 'Source';
            const speechOutput = 'Where would you like to fly from?';
            const repromptSpeech = speechOutput;
            this.emit(':elicitSlot', slotToElicit, speechOutput, repromptSpeech);
(source: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master)
this code asks for the city to fly from and the response gets stored in Source(slotToElicit variable).

I would like to know similar way for this.emit(':ask',....) also


Thanks in advance!!

**Comment by TianTXie** [comment]
@pranavshenoy 
  Your schema posted initially is a standard request model. The standard request is one turn dialog. That means in the ‘Ask’ handler, once you emit the question by calling this.emit(':ask', "Which US city do you want information for?"), the dialog is over. It’ll never execute the code below. 
  What you can do is to define another intent called AnswerIntent for example, define a slot in that intent and  the sample utterance of this intent should be something like {city name}, I want to ask {city name} when you build the model. When user answer by an utterance that includes city name, the AnswerIntent will be shot and the slot in that intent will be filled in. You can read the slot value in that intent handler and implement your own logic using that value. There is a sample skill called [quiz game](https://github.com/alexa/skill-sample-nodejs-quiz-game) that is similar to your user case you can refer.
  Dialog model which you mentioned above is totally different. It is multi-turn. It’ll keep asking you questions until all slots are filled in one intent. You can take a look at this [sample](https://github.com/alexa/skill-sample-nodejs-decision-tree) to see how it works.
