### ISSUE TITLE
How thus the OnIntent work?

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#262]
` onIntent: function (intentRequest, session, response) {
        var intent = intentRequest.intent,
            intentName = intentRequest.intent.name,
            intentHandler = this.intentHandlers[intentName];
        if (intentHandler) {
            console.log('dispatch intent = ' + intentName);
            intentHandler.call(this, intent, session, response);
        } else {
            throw 'Unsupported intent = ' + intentName;
        }
    },`
just confuse. Is it when  In Session then you said again"Alexa" tells invocation, then the Intent?(also maybe when just like the story telling skills, 3 routes (three different intent))?

Or is it just the  basic Structure on building alexa skill's? 

OnSession
Onlaunch
OnIntent
OnEndSession

also tried deleting it and Try to see if the code work's  it doesn't  if some one can shed some light on it that would be awesome.

LOve the Attention and Time on reading this basic question!!
Much love and Be blessed.

KC-Diez

**Comment by TianTXie** [comment]
Hi, @25kcdiez, OnSession, OnLaunch, OnIntent, OnEndSession are correspond to SessionStart request, LaunchRequest,  IntentRequest, ShouldEndSession respectively which are standard request types. If you want the skill to response to customer's certain type of requests, then you should implement them in the skill. For example, if customer says "Alexa, launch 'your skill name'", it will send the launchRequest to the skill, then the skill will trigger OnLaunch function and execute the content inside it. If the customer says "Alexa, tells your skill to do something", it will send the intentRequest to the skill, then the OnIntent function will be triggered. If you don't implement them, then the skill can not route the customer request to the corresponding function. The skill will fail to response.

**Comment by 25kcdiez** [comment]
Exactly what I'm thinking thanks TianTXie....
