### ISSUE TITLE
custom skill not invoked with specific connecting words

### ISSUE THREAD

**Issue by dhananjayj29** [alexa/alexa-skills-kit-sdk-for-nodejs#264]
Hi 
I have custom skill written for the commands:
1. Mute
2. Set Volume
3. Play 
4. Pause
5. Next

As custom skill trigger style is as below
Set volume to 50 in <invocation name for custom skill>

But somehow it matches with internal commands for all the above commands.
If I try using the below commands
Ask <invocation name for custom skill> Set volume to 50 
then it works.. I don't understand what is the difference between above two quries.
Above is as per the guidelines. Also is there any way to disable internal commands for all the above types.

**Comment by JennJin** [comment]
Invoking a Custom Skill with Intent requires a launch phrase to indicate the request is going to a custom skill.
[Understanding How Users Invoke Custom Skills](https://developer.amazon.com/docs/custom-skills/understanding-how-users-invoke-custom-skills.html)

Based on the utterances you shared, maybe the Smart Home API might be a better fit for your use case. [Understanding the Different Types of Skills](https://developer.amazon.com/docs/ask-overviews/understanding-the-different-types-of-skills.html)

The [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) would be the best source for general troubleshooting help. If you're still having issues, please post there.

**Comment by TianTXie** [comment]
I'm closing this issue for now. Please feel free to reopen it if you encounter further issues.
