### ISSUE TITLE
why is my shouldEndSession = true   in test simulator?

### ISSUE THREAD

**Issue by jliukai** [alexa/alexa-skills-kit-sdk-for-nodejs#265]
in test simulator, the json response {shouldEndSession = true}
i want to keep the skill going. it looks like the launch request intent works, and responded appropriately.

```
'use strict';
const Alexa = require('alexa-sdk');
const APP_ID = 'amzn1.ask.skill.e2bxxxxxxxxxxxxxx819';  
const languageStrings = {};

const handlers = {
    'LaunchRequest': function () {
        this.response.speak('Launch Request response from lambda');
        this.emit(':responseReady');
    },
    'GetNewFactIntent': function () {
        this.response.speak('sample fact poo');
        this.emit(':responseReady');
    },
    'AMAZON.HelpIntent': function () {
        const speechOutput = 'moo help message';
        const reprompt = 'moo reprompt';
        this.emit(':ask', speechOutput, reprompt);
    },
    'AMAZON.CancelIntent': function () {
        this.emit(':tell', 'cancel moo');
    },
    'AMAZON.StopIntent': function () {
        this.emit(':tell', 'stop moo');
    },
};

exports.handler = function (event, context) {
    const alexa = Alexa.handler(event, context);
    alexa.APP_ID = APP_ID;
    // To enable string internationalization (i18n) features, set a resources object.
    alexa.resources = languageStrings;
    alexa.registerHandlers(handlers);
    alexa.execute();
};
```

**Comment by TianTXie** [comment]
@jliukai, what kind of device are you using? There are three cases that the shouldEndSession to be true in echo:
1. The user says “exit”.
2.The user does not respond or says something that does not match an intent defined in your voice interface while the device is listening for the user’s response.
3. An error occurs.
Check the log in cloudWatch to see what case is happened. If you are not sure, you can paste your log here. For more information, check this [link](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#sessionendedrequest).

**Comment by thecoleorton** [comment]
@jliukai are you calling this.response.listen() as well? Per the docs it seems if you don't, `shouldEndSession` will be set to `true`.

**Comment by TianTXie** [comment]
Closing this issue for now. Please feel free to reopen it if you encounter further issues.
