### ISSUE TITLE
Change the Aexa accent to US

### ISSUE THREAD

**Issue by dhananjayj29** [alexa/alexa-skills-kit-sdk-for-nodejs#267]
Hi ,

I have embedded system powered by Alexa framework. But problem is accent of Alexa speaking is Indian.I want to change it to US accent.
Please point me towards the settings.
Also in my companion app installed on Android device doesn't show language option.

**Comment by TianTXie** [comment]
Hi, @dhananjayj29 , it is not SDK problem but I found a [link](http://bestwirelessroutersnow.com/change-alexa-voice/) that might be helpful.

**Comment by dhananjayj29** [comment]
I went through the link earlier , but my alexa app doesn't show the language settings option.
