### ISSUE TITLE
AWS SDK not passing correct credentials to test harness

### ISSUE THREAD

**Issue by baq** [alexa/alexa-skills-kit-sdk-for-nodejs#27]
I've followed the instructions supplied in the awesome [tutorial](https://developer.amazon.com/public/community/post/Tx24Z2QZP5RRTG1/New-Alexa-Technical-Tutorial-Debugging-AWS-Lambda-Code-Locally) provided by Nathan Grice.  

I set up all users/roles/permissions/credentials correctly AFAICT but I end up with the following error:

`get error: {
    "message": "The security token included in the request is invalid.",
    "code": "UnrecognizedClientException",
    "time": "2016-10-19T19:26:12.380Z",
    "requestId": "8123U3IOJAJQH3PDLEOUS484HRVV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 0
}
context.fail
Error fetching user state: UnrecognizedClientException: The security token included in the request is invalid.
`

When I print out the security credentials, I noticed that they do no match the credentials I set up in my ~/.aws/credentials file for the debug user that I created.  They're something else entirely.

When I hard-code my security credentials inside my test/main.js function like so

`AWS.config.update({
            accessKeyId: "...XXX...",//data.Credentials.AccessKeyId,
            secretAccessKey: "...xxx...",//data.Credentials.SecretAccessKey,
            sessionToken: data.Credentials.sessionToken
        });`

I'm able to access my data in my dynamoDB.

So something's up with the credentials not getting passed around correctly, or I just messed up or misunderstood something.  I'm happy to close this out if it's my bad, but I need to know what I'm doing incorrectly.

I've also pasted the test/main.js file I'm using for greater context.
[main.js.txt](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/files/540009/main.js.txt)

**Comment by bclement-amazon** [comment]
The credentials won't match the security credentials you put in the .aws/credentials file as you are calling [AWS AssumeRole](http://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) which will generate a set of credentials that are valid for ~1 hr by default.

First I'd start with verifying that the credentials you set up for the role being assumed are correct. See [this link](http://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_control-access_assumerole.html) for that documentation.

I'm afraid it took us a bit longer to get back to you than I would have liked. i'm going to close this issue as I don't think it pertains to the SDK, feel free to reach out if my thoughts above don't work for you.
