### ISSUE TITLE
Alexa Payment

### ISSUE THREAD

**Issue by kamalnathponnusamy** [alexa/alexa-skills-kit-sdk-for-nodejs#270]
Hi,
    I am developing a sample payment skill in Alexa using java. I need to make a payment either using the debit or credit card details which is already linked to the amazon account.Is that possible in Alexa .If yes anybody please help me to know.. how to check whether debit or credit card has been linked already or else to add card details in amazon. 

Regards,
Kamal

**Comment by TianTXie** [comment]
Hi，Kamal, Alexa doesn't support amazon pay for now, but Alexa has [account linking service](https://developer.amazon.com/docs/custom-skills/link-an-alexa-user-with-a-user-in-your-system.html), If you have all payment information in the system/application you'd like to pay, Then you could link your skill to this system/application's account and any purchase you make will go through that system/application.

**Comment by kamalnathponnusamy** [comment]
Hi TianTXie,
                 Thanks for your reply it is more helpful for me to proceed.

**Comment by kamalnathponnusamy** [comment]
Hi TianTXie,
                 Thanks for your reply ,just now I have gone through the account linking service in Amazon very useful one but in my case its not suitable.Why I am saying means my application wont get the account details anywhere from the user in web application side.
                Is there any alternate to proceed please help me :( .

**Comment by tianrenz** [comment]
Hi, 

This is a Alexa feature request. It would be more helpful if you post the requests [here](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote). 

Regards
