### ISSUE TITLE
aws-sdk

### ISSUE THREAD

**Issue by smhgit** [alexa/alexa-skills-kit-sdk-for-nodejs#272]
Seems that aws-sdk package is used only for DynamoDB. The issue is that this package is very large which increase upload time of lambda. Is there a way to remove this package if DynamoDB Is not used within the skill?

**Comment by TianTXie** [comment]
Thanks for suggestions. I'll create an internal task to track this issue.

**Comment by bheather** [comment]
Plus 1

Bruce

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).
