### ISSUE TITLE
Entity resolution resolves to utterance from different state and intent

### ISSUE THREAD

**Issue by dbenader** [alexa/alexa-skills-kit-sdk-for-nodejs#273]
I'm creating a multiple choice skill where a user can answer a question by saying either the letter ('a', 'b', 'c') or the answer ('apple'). When a user returns to the skill, he/she can say 'continue' to resume playing.

The problem:
Ever since creating ContinueIntent, anytime a user answer 'b', or 'c' in STATE 2, ContinueIntent is called

Example:

STATE 1 ContinueIntent Utterances:
"resume",
"continue",
"I want to continue",
"I want to resume",
"I want to continue where I left off",
"continue where I left off"

STATE 2 AnswerIntent Utterances: **ContinueIntent is not in STATE 2
"{Answer}",
"let's go with {Answer}",
"I think the answer is {Answer}",
"I think it's {Answer}",
"how about {Answer}",
"is it {Answer}",
"i think {Answer}",
"the {Answer}",
"I want to go with {Answer}",
"I would think it's {Answer}",
"I want to say {Answer}",
"It's {Answer}",
"the answer {Answer}",
"{Answer} is the answer",
"the answer must be {Answer}",
....
....
....
(There are about 50 more utterances for this intent)

The only thing I can think of is that it is somehow resolving 'c' to 'continue' from ContinueIntent

**Comment by TianTXie** [comment]
@dbenader, I don't think it is because Alexa resolves 'c' to 'continue'. You can check alexa.amazon.com to see the actual utterance that Alexa heard. It could be also helpful if you paste some of the lambda log here for example the request string you received.

**Comment by dbenader** [comment]
I was able to solve this issue by deleting almost all of the utterances for AnswerIntent. In fact, a rep from Amazon told me that you'll see the highest accuracy by creating a second intent, AnswerOnlyIntent, that has a single utterance: "{Answer}".
