### ISSUE TITLE
Need to check value of behavior to prevent error with expectedPreviousToken

### ISSUE THREAD

**Issue by natherz** [alexa/alexa-skills-kit-sdk-for-nodejs#274]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/ded2e5c7713c11813056c2fc502f027a50ef4e63/lib/responseBuilder.js#L190

**Comment by natherz** [comment]
As noted in the comment to the method, expectedPreviousToken is only allowed when the behavior is ENQUEUE. The code should check this value and adjust the object accordingly.

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).
