### ISSUE TITLE
Feature request: Allow saving some attributes but not all to DynamoDB

### ISSUE THREAD

**Issue by jacobweber** [alexa/alexa-skills-kit-sdk-for-nodejs#278]
If you use the DynamoDB feature of alexa-sdk, I understand that it will persist the state and all attributes to the database. Maybe I'm understanding this wrong, but it seems like this isn't desirable behavior most of the time. I might want to set some attributes, or set a state, and have them only persist for the length of the session (e.g. they shouldn't be stored in the DB). But I might want selected attributes to be stored in the DB.

And I might not want the state to be stored, if I'm just using it for when the skill asks a question, puts itself in an "answer" state, and then waits for the answer. In this case the state only needs to persist for the length of the session.

**Comment by TianTXie** [comment]
Thanks for your input. We are currently in the process of redesigning the Alexa SDK. We will keep this in mind and try to solve this problem in the new design. Stay tuned!

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).
