### ISSUE TITLE
Add Mobile Analytics to ASK

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-skills-kit-sdk-for-nodejs#28]
I have started integration of Mobile Analytics into the ASK and the basic cases are working.
The repo is at:  https://github.com/rmtuckerphx/alexa-skills-kit-sdk-for-nodejs

The code to create custom events inside an intent handler function is not working. Here is a sample of what I am trying to do:

```
    'GetNewFactIntent': function () {
        this.recordMobileAnalyticsEvent('foo', 'sessionId');
```

Feedback on the changes or help figuring out this issue is appreciated.

**Comment by bclement-amazon** [comment]
closing #28 tracking in #51
