### ISSUE TITLE
PlaybackController interface documentation error - won't work as documented!

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-skills-kit-sdk-for-nodejs#281]
Right now,  https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#playback-controller-interface says:
```
const handlers = {
    'PlaybackController.NextCommandIssued' : function() {
        //Your skill can respond to NextCommandIssued with any AudioPlayer directive.
    },
```

But that doesn't work, so after much banging of head against brick walls, I found it was being split by https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/eventParser.js so I have created a pull request at #280

**Comment by TianTXie** [comment]
Thanks, the latest commit solved this issue.
