### ISSUE TITLE
Issue with AMAZON.TIME built-in slot

### ISSUE THREAD

**Issue by chasebish** [alexa/alexa-skills-kit-sdk-for-nodejs#282]
I am using AMAZON.TIME to get time input from the user.  I have created my own intent called "TimeIntent" and the only utterance that should activate it is my slot {time} with the slot type AMAZON.TIME.  However, whenever I give input that should fall into "Unhandled" it goes into TimeIntent instead.  This is causing me an issue when I actually try to use TimeIntent because when I'm giving it bad input it instead sends the request to TimeIntent, giving me an error.

JSON for TimeIntent
```javascript
{
        "name": "TimeIntent",
        "samples": [
          "{time}"
        ],
        "slots": [
          {
            "name": "time",
            "type": "AMAZON.TIME"
          }
```

If I give my skill input "ABC 123" this is the request it sends

```javascript
"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.XXXXX",
		"timestamp": "2018-01-25T20:11:45Z",
		"locale": "en-US",
		"intent": {
			"name": "TimeIntent",
			"confirmationStatus": "NONE",
			"slots": {
				"time": {
					"name": "time",
					"confirmationStatus": "NONE"
				}
			}
		}
	}
```

The input "ABC 123" should not be sent to TimeIntent, it should definitely be sent to Unhandled

**Comment by chasebish** [comment]
So I've continued to mess with it and it seems like this issue occurs anytime there is an intent utterance of just a slot.  Is there any way around this issue?

**Comment by TianTXie** [comment]
@chasebish,
I have the same situation, to avoid mess up, you can always check the value of the slot, if it is undefined, then you can forward this event to unhandled handler function or something else.

**Comment by chasebish** [comment]
@TianTXie,

Having to check the value of the slot is redundant since it should already be checking if there is a match with the interaction model.

However, I believe I found a solution for the issue.  When an intent is called based on a slot when it should not be called, the status code will return "ER_SUCCESS_NO_MATCH" since the slot value does not match one within the interaction model.

The way to get the access code: (using slot name "time")

```javascript
let statusCode = this.event.request.intent.slots.time.resolutions.resolutionsPerAuthority[0].status.code
```

If statusCode === "ER_SUCCESS_MATCH" that means the slot value is valid and matches one from the interaction model.  If statusCode === "ER_SUCCESS_NO_MATCH" that means the slot value does not match one from the interaction model.

In my opinion, this should not be necessary.  If the slot is returning "no match", it should never call the specified intent because it's not a valid request if the slot does not match one of the values.

**Comment by talkingnews** [comment]
+1
