### ISSUE TITLE
How to have handlers in seperate files

### ISSUE THREAD

**Issue by 3uPh0riC** [alexa/alexa-skills-kit-sdk-for-nodejs#283]
Can someone maybe assist a noob here. The docs mention that the handlers can be in separate files and imported later. Can someone please show me the correct Nodey way of doing this. Im actually more of a Java dev, so im not sure what the correct syntax for this is... Callbacks or no callbacks, how to define the imports and exports its all a bit bewildering to me.

Defining all my handlers under a 

```
const handlers = {
    "LaunchRequest": function() {
         this.emit('tell:':'Whazzzzuuuup')
     },
     "ÖtherIntent": function(){
         this.emit(); //Lots of stuff in this function I want to have it in its own file
      }
}
```
Makes the file really big. How to I split them out

Thanks!

**Comment by TianTXie** [comment]
@3uPh0riC ,
You can do 
```javascript
const handler1 = {
"LaunchRequest": function() {
         this.emit('tell:':'Whazzzzuuuup')
     },
     "ÖtherIntent": function(){
         this.emit(); //Lots of stuff in this function I want to have it in its own file
      }
}
```
in one file, and 
```javascript
const handler2 = {
   "ÖtherIntent": function() {
         this.emit('tell:':'Whazzzzuuuup')
     },
     "ÖtherIntent": function(){
         this.emit(); //Lots of stuff in this function I want to have it in its own file
      }
}
```
in other file, and expose the handlers in the form of an array so that the Alexa.registerHandlers can be receive them.
```javascript
const handlers = [handler1, handler2 .....]
```
In the index.js file, do
```javascript
alexa.registerHandlers(handlers);
```

**Comment by 3uPh0riC** [comment]
Yeah that doesnt work. Or im sure it would, if I understood how to import/export those constants. I tried various things and theres always an error along the lines of Árgument 1 is not an object

**Comment by chasebish** [comment]
@3uPh0riC,

You have to make sure you are properly importing the handlers.  Let's assume everything is inside a directory called "src" with another directory called "handlers" inside.

Assume I have two handlers in the directory "handlers"

The following file is called "newSession.js" which would have the path /src/handlers/newSession.js
```javascript

const newSession = {
    "LaunchRequest": function() {
             this.response.speak("Welcome to my app");
             this.emit(":responseReady");
     }
    // Insert whatever intents you would like in this handler
}

module.exports = newSession;
```

Assume this file is called "handler2.js" so it would have the path /src/handlers/handler2.js
```javascript
const handler2 = {
    "AMAZON.HelpIntent": function() {
             this.response.speak("Do XYZ to get to point A");
             this.emit(":responseReady");
     }
    // Insert whatever intents you would like in this handler
}
module.exports = handler2;
```

Now, to properly import your handlers, you need to go to your index.js file and require them and add them to your active handlers.

```javascript
const Alexa = require("alexa-sdk");

// handlers
const newSession = require("./handlers/newSession");
const handler2 = require("./handlers/handler2");

exports.handler = function (event, context, callback) {
    let alexa = Alexa.handler(event, context);
    alexa.registerHandlers(
        newSession,
        handler2
    );
    alexa.execute();
};
```

If you are still confused on how to import modules in node with require, I recommend reading the docs here: [https://nodejs.org/api/modules.html](https://nodejs.org/api/modules.html)

Hopefully this cleared things up for you.  Good luck!

**Comment by ajayarjun-bka** [comment]
If I am having a separate folder I have to place a copy of node_modules in that directory as well. How do I make it point to the node_modules in the root directory

**Comment by chasebish** [comment]
@ajayarjun-bka - no, node_modules only needs to be in their once

**Comment by ajayarjun-bka** [comment]
Ya got it. I made a mistake in the directory structure. Thanks

**Comment by lucakl** [comment]
How is this working in v2 ?
