### ISSUE TITLE
Can I ask a Question what is the difference between BuildSpeechRespone and BuildSpeecRespone without card?

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#284]
function buildSpeechletResponseWithoutCard(output, repromptText, shouldEndSession) {
    return {
        outputSpeech: {
            type: "PlainText",
            text: output
        },
        reprompt: {
            outputSpeech: {
                type: "PlainText",
                text: repromptText
            }
        },
        shouldEndSession: shouldEndSession
    };
}

 and  the 

function buildSpeechletResponse(title, output, repromptText, shouldEndSession) {
    return {
        outputSpeech: {
            type: "PlainText",
            text: output
        },
        card: {
            type: "Simple",
            title: title,
            content: output
        },
        reprompt: {
            outputSpeech: {
                type: "PlainText",
                text: repromptText
            }
        },
        shouldEndSession: shouldEndSession
    };
}

is it the way how alexa is structure? or there some meaning to it to involve both of them 

because this always how Alexa  will response 

"version": "1.0",
  "response": {
    "outputSpeech": {
      "text": "I will ask you 5 questions, try to get as many right as you can. Just say the number of the answer. Let's begin. Question 1. What Makes Santa's Reindeer Fly? 1. Amanita muscaria. 2. Fusion. 3. Elves. 4. Magical Reindeer Dust. ",
      "type": "PlainText"
    },
    "card": {
      "content": "I will ask you 5 questions, try to get as many right as you can. Just say the number of the answer. Let's begin. Question 1. What Makes Santa's Reindeer Fly? 1. Amanita muscaria. 2. Fusion. 3. Elves. 4. Magical Reindeer Dust. ",
      "title": "Trivia"
    },
    "reprom....

**Comment by TianTXie** [comment]
Hi, @25kcdiez , the card will be shown on the [alexa console](https://alexa.amazon.com).
