### ISSUE TITLE
TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by mipicdev** [alexa/alexa-skills-kit-sdk-for-nodejs#286]
Hello,
I'm writing a new skill that accesses DynamoDB. Everything works fine, all data is stored and retrieved. However CloudWatch tells me constantly, that there's an error. It appears about every minute in the log and also after invoking the skill. The listed RequestId doesn't correspond to any of the RequestIds during the invocation of the skill.

So far I tried the following:

Lambda function
- Raised the timeout to 10 seconds
- Increased memory to 512 MB
- Created a new role with AmazonDynamoDBFullAccess and AWSLambdaDynamoDBExecutionRole

index.js
- this.emit(':saveState', true); before calling emit(':tell', speech);
- Switched from Response to ResponseBuilder

Here's an extract from CloudWatch:

```
START RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Version: $LATEST
2018-01-28T11:09:03.327Z 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:112:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:100:31)
    at exports.handler (/var/task/index.js:98:11)
END RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe
REPORT RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe	Duration: 456.10 ms	Billed Duration: 500 ms Memory Size: 128 MB	Max Memory Used: 37 MB	
RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Process exited before completing request

START RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Version: $LATEST
2018-01-28T11:09:59.208Z 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:112:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:100:31)
    at exports.handler (/var/task/index.js:98:11)
END RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe
REPORT RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe	Duration: 376.52 ms	Billed Duration: 400 ms Memory Size: 128 MB	Max Memory Used: 37 MB	
RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Process exited before completing request

START RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Version: $LATEST
2018-01-28T11:10:56.387Z 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:112:38)
    at AlexaRequestEmitter.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:100:31)
    at exports.handler (/var/task/index.js:98:11)
END RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe
REPORT RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe	Duration: 361.77 ms	Billed Duration: 400 ms Memory Size: 128 MB	Max Memory Used: 37 MB	
RequestId: 3d2e2f4f-5ac7-4e0d-8b0f-39266e6822fe Process exited before completing request
```

**Comment by talkingnews** [comment]
Just make sure that you really are using the latest aws and alexa sdk, by going to the lambda dir and typing `npm install;npm update`, and the zip or push the lambda code as you normally would.

Also, check that your index.js file, and anywhere else that you use that lambda code, has this up top:

```
var ALEXA = require('alexa-sdk');
var AWS = require('aws-sdk');
AWS.config.update({
region: "eu-west-1" // or whatever region your lambda and dynamo is
});
```

Let us know if this helps!

**Comment by mipicdev** [comment]
Thank you for the quick response.

I executed both commands, but the latest versions were already there and I also updated my index.js with the AWS part. The TypeError still exists.

**Comment by TianTXie** [comment]
@mipicdev,
The locale is retrieved from the request from Alexa device, the code refers [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/alexa.js#L112). Your local shows undefined means your locale can not be recognized by Alexa. Could you check what language are you using in your Alexa device setting? Alexa support several languages currently, for more information about developing the skill in multi-language, click [here](https://developer.amazon.com/docs/custom-skills/develop-skills-in-multiple-languages.html).

**Comment by mipicdev** [comment]
Alexa-app (iOS)
- Device Location : Germany
- Device time zone : Central European Standard Time (Paris)
- Language : German

And some more informations
- Skill language : German
- Lambda : eu-west-1
- DynamoDB : eu-west-1

**Comment by mipicdev** [comment]
Today I solved the problem. This is now my Inline Policy:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": [
                "dynamodb:PutItem",
                "dynamodb:DeleteItem",
                "dynamodb:GetShardIterator",
                "dynamodb:GetItem",
                "dynamodb:UpdateItem",
                "dynamodb:DescribeStream",
                "dynamodb:ListStreams",
                "dynamodb:GetRecords"
            ],
            "Resource": "*"
        }
    ]
}
```

Additionally I reinstalled the Alexa app, but I don't think it matters.

**Comment by manhdan** [comment]
I have same problem, I try this Inline Policy but theTypeError still exists.
