### ISSUE TITLE
Query related to Custom Skill & Triggers from Lambda

### ISSUE THREAD

**Issue by sandeepajesh** [alexa/alexa-skills-kit-sdk-for-nodejs#293]
Hi Team,

We are working on a Alexa based prototype device and  writing Custom skills for it. 

I have two queries:-

1)  I have a lambda function for a Custom skill and I want to send a trigger from Lambda to Alexa Device.   E.g:- I have Mqtt Subscriber running in Lambda , whenever it receives a particular message I want to Send a Welcome message to my device which should get played on Alexa Device through Avs-device-SDK.

2)  I have written a custom skill and  to invoke this skill , always I have to Say "Alexa, ask myskill to Turn on Light", "Alexa, ask myskill to Turn Off Light".  
Is there any way I can say like this "Alexa,Turn off Light".  How we can do this?

Regards
Sandeep S

**Comment by mikemaas-amazon** [comment]
Hi Sandeep,

1. I don't know the specifics of the AVS-Device-SDK but using MQTT to communicate to devices from a Lambda function is entirely possible. For example, using AWS IoT as an MQTT broker. One thing to keep in mind is that the Lambda will need special permissions if you are using AWS IoT. If you are using your own, you will just need to make sure you have the correct network access.

2. Yes, there is. For commands without your custom invocation, you will need to look to the Smart Home API. This means creating a Smart Home skill and not a custom skill. In particular, have a look at https://developer.amazon.com/docs/smarthome/build-smart-home-skills-for-lights.html to get started.

**Comment by sandeepajesh** [comment]
Thanks for the response mikemaas-amazon.

I am still not very clear on first point. AVS-device-SDK is Amazon's Client which is running on devices. It takes voice commands from user and send it to AVS Server. Then AVS Server processes it and sends response back to Alexa engine running on device, which plays audio response.  For my Custom skills response is coming from my Lambda function instead of some other server.
Now let's say I have MQTT subscriber which is running in Lambda function.So now  I have to send a message to my device which gets played by Alexa client running on device. In my case I haven't invoked any voice command from My device, instead I need to invoke it from Lambda function.

**Comment by mikemaas-amazon** [comment]
If this is a question specific to AVS, please consider opening the issue in the AVS repo: https://github.com/alexa/avs-device-sdk. Additionally, long-running code like an MQTT subscriber in a Lambda function seems incorrect. Lambda is both stateless and a function-level virtualization. You should also have a look at https://aws.amazon.com/lambda/faqs/ for more information.
