### ISSUE TITLE
What is Alexaskill.call and why do we use it?

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#294]
Just one more question guy's  I know that It's  the back link  and I shouldn't  care about it  but.....
But I figure out I would love to do this Coding For the rest  of my life (My Love) and using my creativity with it, so I'm kinda learning coding while pursue what I love,

So my QUESTION is why do we use AlexaSkill.call() and why do we use it, and there some skill's  that I don't need alexaskill.call(this, APP_ID) Just getting a perspective on what's going on here, It would be so much awesome if there is a Forum or a link where I can read this.

Example: 

The Fact skill(is the alexa skill.call(this, APP_ID) in Fact skill //optional? 
There's  no alexaskill.call(this,APP_ID) on Reindeer Game's Just  rerouting the request on the app_ID
in the third skill(all in A Cloud Gurus I know that there is some % that they created  that way) is MineCraftHelper, has AlexaSkill.call(...etc) I know that I'm kinda Harashing you guy's right now and I'm sorry,  and this Is my last Question.

Much love and Be Blessed ☀

KC. Diez,

**Comment by benedekh** [comment]
Hi @25kcdiez ,

Could you send me examples where you encountered the `skill.call(this, APP_ID)` code?

Thank you.
