### ISSUE TITLE
How to get meeting information?

### ISSUE THREAD

**Issue by divyam8** [alexa/alexa-skills-kit-sdk-for-nodejs#296]
Let's say I have linked Alexa with my Google account. When I ask Alexa, When is my next meeting scheduled?
Alexa replies,You have a meeting scheduled at 2 pm with XYZ (for example a meeting is scheduled at 2 pm)
How can I programmatically get the calendar data as it is internally linked with Alexa.
Are there any functions available for it?
Thanks.

>

**Comment by TianTXie** [comment]
@divyam8   Yes, you can create a skill and call the google calendar api to get the data. There is a sample skill called [skill-sample-nodejs-calendar-reader](https://github.com/alexa/skill-sample-nodejs-calendar-reader) which is similar to your user case that you can refer.
