### ISSUE TITLE
There was a problem with the requested skill's response

### ISSUE THREAD

**Issue by katrsn** [alexa/alexa-skills-kit-sdk-for-nodejs#297]
I tried to run the sample skill (Reddit Reader) given by John Wheeler in his 3 part video. But, I am getting the following message both on the simulator and the Echo device.
"There was a problem with the requested skill's response"
Please let me know how to fix this issue.
ngrok is working fine with another skill.

**Comment by chasebish** [comment]
"There was a problem with the requested skill's response" means that your lambda function is crashing.  You should check your logs and it should clarify what your issue is.

**Comment by minlare** [comment]
To get detailed error logs for this type of error do the following: 

In the Alexa skill page, click on test, type an utterance, and you'll see your request, and possibly response (if your code successfully generates one). Copy the request, go to your lambda code and configure a new test event, paste the request in there and hit save and test.

The result should show you what went wrong or at least what line of code to look at/near.
