### ISSUE TITLE
Using Alarm functionality in a Skill

### ISSUE THREAD

**Issue by lostvicking** [alexa/alexa-skills-kit-sdk-for-nodejs#300]
I'd like set an alarm as part of an Alexa Skill but I've seen that last year this was not yet possible:  #197 , is that still the case?

**Comment by lostvicking** [comment]
Hi, still waiting on a response on this please?

**Comment by andrewmholloway** [comment]
Hey @lostvicking , I don't know exactly what you're trying to do but Alexa skill comes with an alerts interface that you can play with. Here's the link: https://developer.amazon.com/docs/alexa-voice-service/alerts.html

**Comment by allthepies** [comment]
You can't do it.  The doc linked to by Andrew above is for AVS i.e. if you're a product builder and looking to integrate Alexa into your product.
For custom Alexa skills there is currently no way to create/manage native Alexa timers/alarms.  The closest thing you have is the Notifications API but that's still in developer preview and not publicly available.

**Comment by TariqP** [comment]
Yeah, I also almost got tricked into thinking it was possible by the AVS documentation. In any case, @internal devs please make this possible!

**Comment by tianrenz** [comment]
Hi all, 

The feature mentioned above is not yet supported by Alexa Skills Kit service. I would recommend to check out the Notification service [here](https://developer.amazon.com/blogs/alexa/post/833b9af4-26e6-47d2-a13d-bdbd9a257512/expanded-developer-preview-of-notifications-for-alexa-skills).
