### ISSUE TITLE
Building phone call function in Alexa Skill

### ISSUE THREAD

**Issue by sangmshin** [alexa/alexa-skills-kit-sdk-for-nodejs#301]
I am trying to build Alexa skill that has functionality to call someone within the skill. If I were to store someone's name and his/her phone number and user asks Alexa to call this person, is there an API for this type of situation?

**Comment by haseebr** [comment]
I'm not sure if the user can talk to people over a call on Alexa. However, you can try and call the user using the Twilio API and Twilio connects the user to the destination number.
