### ISSUE TITLE
Chaining Handlers

### ISSUE THREAD

**Issue by 3uPh0riC** [alexa/alexa-skills-kit-sdk-for-nodejs#302]
Im not sure im chaining my handlers correctly, or im misunderstanding something. So I call a handler as per normal, and from that handler based a certain condition I want to go directly into another handler:

this.emit('SetupIntent');

now in setup intent i want to elicit some slots. This just plain fails saying there was a problem with the requested skills response. No proper error that I can see.

If I print out the request entering the SetupIntent its the same request as what I got for the original intent, so im thinking it has something to do with that. The intent mentioned in the request isnt actually the SetupIntent so how is it going to complete that slot. If i call SetupIntent directly it works fine.

Any guidance? 

Thanks

**Comment by TianTXie** [comment]
Hi, @3uPh0riC, I think the way you chain the handlers is correct.  The chaining handlers will all use the initial requestIntent. You can not overwrite any value of intent between them. So you can not finish the multi-turn dialog conversation across handlers.

**Comment by kyle-wrenn** [comment]
I'd also like to chain intents, except I'm trying to handle state. I have two sets of intents: one without an associated state and one with. Assuming I have entered an intent with a state and then want to back out to a "stateless" state, can I remove the state attribute before invoking the other intent?

**Comment by TianTXie** [comment]
@kyle-wrenn, yes, in your state handler, calling this.handler.state = '' will let you go back to no mode handlers.
