### ISSUE TITLE
what is SYNONYMS in the alexa?

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#303]
the Dialogue I  after  is....

Alexa  Open Talia.....

Talia= welcome...... HI....
(User) 
what are my rejections 
ok here are your rejections.....
1
2
3
what do you want to here ......
(User) 
how  about  ......

so right now I don't see anyway  I can target what's inside the Rejection
I Kinda need help...

basically this is the whole code
` 

- module.exports = [{
-    "Positivity":[ //make it like a ssml kevin
-              "etc......."
-              ".......etcc.........",
-              ]
-              },
-              {
-         
-     /**"RandomAckOfKindnessIntent"**/ //after I figure out what to put here that would help people SEE how my perspective on how I see the world
-       "Rejection": {
-           "rejection 1": "Ask for to work in Pizza hut  and gut turn down. Maybe.",
-           "rejection 2": "Ask to do a marketing campaing for a Massage  Therapist, They said NO wooh!",
-           "rejection 3": "You Call jeff and got Rejected quote and quote, I'm already doing my own Facebook marketing why should I need you? coma,  what you learn kevin is not all people Kevin need you and you shouldn't like what Jesus said, Help the people that want's to be Help, you don't need help everyone just help one people at a time One random ack of Kindness."

    }
}
];
       
       ` Can I actually make that in alexa?

**Comment by chasebish** [comment]
Just letting you know, this is impossible to understand.  You should probably reformat your question.
