### ISSUE TITLE
Filtering/escaping characters? 

### ISSUE THREAD

**Issue by dealancer** [alexa/alexa-skills-kit-sdk-for-nodejs#306]
Ho to correctly filter/escape characters for Alexa? I am having some problems with an equal sign:

```
Fatal error occurred when processing SSML content. This usually happens when the SSML is not well formed. Error: Unexpected character '=' (code 61); expected a semi-colon after the reference for entity 'referrerSource'
```

**Comment by benedekh** [comment]
Hi @dealancer ,

Have you tried using a [library](https://github.com/mandnyc/ssml-builder) for building a SSML response, instead of building them by hand? So that you could avoid chracter escaping problems. Otherwise, just see the [escaping rules](https://stackoverflow.com/questions/1091945/what-characters-do-i-need-to-escape-in-xml-documents) in XML documents.

**Comment by TianTXie** [comment]
Since there is no response here, I'm closing this issue for now. Please feel free to reopen it if you encounter further issues.

**Comment by dealancer** [comment]
@benedekh, @TianTXie, sorry for late reply.

I have not used SSML library for building a response. I am building it by hand and sometimes I want Alexa to read text that I do not control (e.g. RSS feeds).

I think either Alexa SDK should take care of escaping characters, or it should be clearly stated in the documentation that all responses should be escaped.

**Comment by gavinr** [comment]
I am getting this error too - would be nice if escaping automatically were an option. `ssml-builder` library does not appear to be maintained.

(PS - related/duplicate of #25 and https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/472#issuecomment-459779174 ?)

**Comment by nikhilym** [comment]
Hey @gavinr , @dealancer ,  #522 added support for auto-escaping XML characters feature in the SDK. Does this align with the use-case you were trying? If not, please feel free to open a new issue on the repo so that we can investigate into it further.

**Comment by gavinr** [comment]
@nikhilym Thank you for pointing me to that PR. It looks like that does solve my problem! Note that in [v2.5.1](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/CHANGELOG.md#251-2019-03-08) the behavior of that PR [was removed from being default](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/31ce953), so as a developer we have to call that [utility method](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/ASK-SDK-Utilities.html#ssmlutils) ourselves:

```
return handlerInput.responseBuilder
      .speak(Alexa.escapeXmlCharacters(speakOutput))
      .getResponse();
```
