### ISSUE TITLE
The possibilities of interpolation in translations are missing in the readme

### ISSUE THREAD

**Issue by sjaakieb** [alexa/alexa-skills-kit-sdk-for-nodejs#309]
The SDK provides possibilities for interpolation in the translations. Since the SDK uses i18next an improvement might be to mention this in the readme and add this link : https://www.i18next.com/interpolation.html

**Comment by tianrenz** [comment]
Hi @sjaakieb ,

Thanks for your support in ASK SDK. The documentation has been updated in this [commit](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/d171175f39e52e46b7b31be0c5dfe681c4558688).

Regards
