### ISSUE TITLE
Q: Streams By Timezone (Getting Custom Slots from Utterances)

### ISSUE THREAD

**Issue by mcalvo** [alexa/alexa-skills-kit-sdk-for-nodejs#31]
Instead of audioData being a list of podcast files, I'm creating a list of streams. Each one is identified by a key tied to their timezone.

Since there doesn't appear to be a way to ask the device for the timezone, I've been prompting the user to provide the timezone. Once I get the value, I plan to check against the list of timezones I have streams for. If it's valid, I'll store it as an attribute in the session and store it in the db. Otherwise, reprompt the user. 

For context:

**Custom Slot**
`LIST_OF_TZ: Hawaii-Aleutian | Alaska | Pacific | Mountain | Central | Eastern | Atlantic`

**Utterance**
`GetTZ {Timezone}`
`GetTZ Set my timezone to {Timezone}`

**State Handler**

```
 getTZIntentHandlers : Alexa.CreateStateHandler(constants.states.GET_TZ, {
 'LaunchRequest' : function () {
            // Session ended mid-tz setup.
           //  Initialize other attributes
           [...]
           // TZ Check
            if (!this.attributes['tz_info']) {
                var message = 'No timezone detected.  What timezone you are in?';
                this.response.speak(message).listen(message);
                this.emit(':responseReady');
            } else {
                var message = 'Timezone detected. On with the show!';
                this.response.speak(message);
                controller.play.call(this);
            }
        },
'GetTZ' : function () {
           // #TODO: Validation for invalid Custom Slot Type Values.
           this.attributes['tz_info'] = this.request.intent.slots.Timezone.value;   // The problem line.
           var message = 'You have a timezone. On with the show!';
           this.handler.state = constants.states.START_MODE;
           this.response.speak(message);
           controller.play.call(this);
        },
[...]
}
```

On to the main problem: I'm having trouble getting the slot value from the request.  Is `this` referring to the session? It'd explain why I can't get the value through `this.request.intent.slots.Timezone.value`. If that's the case, who would I do it? And after that, how would I go about validating it against my custom slot type?

Sidebar: Is there another way to do this? It'd be great if there was something in the SDK for node.js like Alexa.locale.tz_info.

**Comment by deegles** [comment]
Try `this.event.request.intent.slots`

alexa-sdk dynamically binds context to `this`, it contains the event, context and helper functions. You can see what properties are available [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/alexa.js#L225).

**Comment by mcalvo** [comment]
Thanks! 

As a sidebar, I've settled on taking user zipcode to determine timezone. Seems like less of a hassle than determining specific language for the slot values.
