### ISSUE TITLE
Execution error, "intentHandlers.register is not a function".

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#310]
Having trouble understanding  my intentHandlers.register is not a function

here is my Service Request:
```json
{
  "session": {
    "new": true,
    "sessionId": "SessionId.074c134f-6058-4e29-ae70-20cf742c4fd7",
    "application": {
      "applicationId": "amzn1.ask.skill.70bc4d12-38b9-4ab6-bfaf-cfbaa757a6b9"
    },
    "attributes": {},
    "user": {
      "userId": "amzn1.ask.account.AE5YI4IQQL5UBI3QEXNNZRAAY2W3NVFQHXVN32OEOTTVYXQZ5Z7JR4OPQC2EFCYAECP3KREJESZNV2HNCZCVKCLTNRNNXIOOBRP64DG4ALNVSP4SPP5UT7ZHDU252EBUTLNBHBAOXYHTTWQPI62QDMEJUC2ONWODQ7QR25R4YWHC5VFAHJOSRU7ZJ3YZKSLPV23BTFVGQSW52UY"
    }
  },
  "request": {
    "type": "IntentRequest",
    "requestId": "EdwRequestId.361b6ccf-158b-4071-b54f-812e2be3c6eb",
    "intent": {
      "name": "POSITIVITYIntent",
      "slots": {
        "item": {
          "name": "item",
          "value": "positive"
        }
      }
    },
    "locale": "en-US",
    "timestamp": "2018-03-04T22:27:52Z"
  },
  "context": {
    "AudioPlayer": {
      "playerActivity": "IDLE"
    },
    "System": {
      "application": {
        "applicationId": "amzn1.ask.skill.70bc4d12-38b9-4ab6-bfaf-cfbaa757a6b9"
      },
      "user": {
        "userId": "amzn1.ask.account.AE5YI4IQQL5UBI3QEXNNZRAAY2W3NVFQHXVN32OEOTTVYXQZ5Z7JR4OPQC2EFCYAECP3KREJESZNV2HNCZCVKCLTNRNNXIOOBRP64DG4ALNVSP4SPP5UT7ZHDU252EBUTLNBHBAOXYHTTWQPI62QDMEJUC2ONWODQ7QR25R4YWHC5VFAHJOSRU7ZJ3YZKSLPV23BTFVGQSW52UY"
      },
      "device": {
        "supportedInterfaces": {}
      }
    }
  },
  "version": "1.0"
}
```

my Execution Result:

Response:
```json
{
  "errorMessage": "intentHandlers.register is not a function",
  "errorType": "TypeError",
  "stackTrace": [
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:4:18)",
    "Module._compile (module.js:570:32)"
  ]
}
```

Request ID:
"7ed9e9ea-1ffc-11e8-9710-3977e57b34d5"

Function Logs:
START RequestId: 7ed9e9ea-1ffc-11e8-9710-3977e57b34d5 Version: $LATEST
module initialization error: TypeError
    at Object.<anonymous> (/var/task/positivity.js:19:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/var/task/index.js:4:18)
    at Module._compile (module.js:570:32)
END RequestId: 7ed9e9ea-1ffc-11e8-9710-3977e57b34d5
REPORT RequestId: 7ed9e9ea-1ffc-11e8-9710-3977e57b34d5	Duration: 307.46 ms	Billed Duration: 400 ms 	Memory Size: 128 MB	Max Memory Used: 20 MB	
module initialization error
TypeError

**Comment by benedekh** [comment]
Hi @25kcdiez ,

I would really improve the readability of your question, if you put the code snippets (json objects) between ``` and ``` marks (it gives [syntax highligting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) in github).

Could you share the `index.js`, or whichever file with us, where you register your handlers to the Alexa SDK?

**Comment by TianTXie** [comment]
I'm closing this issue for now. Please feel free to reopen it if you encounter further issues.
