### ISSUE TITLE
[please forward] ask-cli problem

### ISSUE THREAD

**Issue by ricardocasares** [alexa/alexa-skills-kit-sdk-for-nodejs#311]
Sorry I did not find a better place to open ask this question since Amazon developer forums kinda suck (sorry), but:

I was trying to use `ask-cli` to generate and deploy a new skill but I was unable to move forward from the `ask init` command.

Chose my profile, the browser opened, I logged in successfully but then nothing happened.

Digging deep on `ask-cli` I found a piece of code expecting a callback to be executed by `simple-oauth2`:

```js
OAuth.authorizationCode.getToken(tokenConfig, (err, result) => {
  if (err) {
    profileHelper.deleteProfile(profile);
    console.error('Access token failed. ' + err);
  } else {
    let token = OAuth.accessToken.create(result).token;
    oauthWrapper.writeToken(token, profile);
    console.log('Tokens fetched and recorded in ask-cli config.');
    callback();
  }
});
```

Callback was never called, so looked up this is method and found it is now [async](https://github.com/lelylan/simple-oauth2/commit/6f4c2d68fe4fd8c5fb121dd60536afec110b3ea5#diff-a05b43a9d77af37516cd8ac9f0739dd3L39).

Even though pinned version of `simple-oauth2` is constrained to `^1.0.2`  inside `ask-cli` and GH history shows this method indeed uses a callback for `1.5.1`, when you install `simple-oauth2@1.5.1` you get the code using `async`.

Please check https://github.com/lelylan/simple-oauth2/issues/177

**Comment by ricardocasares** [comment]
BTW, I was able to continue working by rewriting my local `ask-cli` to use `.then()` & `.catch()` blocks, then I was able to login and generate needed files with tokens. Please open source `ask-cli` code too!

**Comment by RonWang** [comment]
Hey Ricardo! Thank you so much for bringing this out! Yes, you are totally correct, and we have already publish a new revision for ask-cli addressing this issue. Please check our latest version!

**Comment by ricardocasares** [comment]
Working now! Thanks
