### ISSUE TITLE
getFullAddress only returns postal code and country, address keys are null

### ISSUE THREAD

**Issue by gDev95** [alexa/alexa-skills-kit-sdk-for-nodejs#313]
Can someone explain to me rather this is a bug or something is wrongly configured please

Log:
```
    2018-03-06T16:45:22.452Z    c24b7465-215d-11e8-aefd-bfbf7ac6d9a8    
    { 
    addressLine1: null,
    addressLine2: null,
    addressLine3: null,
    districtOrCounty: null,
    stateOrRegion: null,
    city: null,
    countryCode: 'US',
    postalCode: '63101' 
    }
```
My code: 
```
    const token = event.context.System.apiAccessToken
    const apiEndpoint = event.context.System.apiEndpoint
    const deviceId = event.context.System.device.deviceId
    console.log(
      `Token: ${token} \n 
       Api Endpoint: ${apiEndpoint}
       Device ID: ${deviceId}`)
    const deviceAddressService = new Alexa.services.DeviceAddressService()
    const fullAddress = deviceAddressService.getFullAddress(deviceId,apiEndpoint,token).then(data => {
      resolve(data)
    })
    .catch(err => {
      reject(err.message)
      })
    })
```

[Picture of Permission given in the Developer Portal:](https://i.stack.imgur.com/O6Y98.png)

I get a valid consent Token, apiEndpoint and deviceId**

**Token:** eyJ0eXAiOiJKV1QiLCJhXXX

**Api Endpoint:** https://api.amazonalexa.com
**Device ID:** amzn1.ask.device.AETPMACRXXX

**Comment by gDev95** [comment]
@Richard0528 I wish I would remember and I want to apologized that I did not post the solution at time. It was not a code issue, the code that you see is the working, you can check my repo if you want.

**Comment by TianTXie** [comment]
@Richard0528, I think that's because you didn't set the address for your device. You can go to Alexa console and set the address there.

**Comment by Richard0528** [comment]
@TianTXie which one are you talking about? 
alexa.amazon.com?
console.aws.amazon.com?
developer.amazon.com?
I think it gathers address information from the Amazon account right?

**Comment by Richard0528** [comment]
@gDev95 I tried it. I think it's still not working. XD
![1](https://user-images.githubusercontent.com/25624883/39161899-bc56eb08-4727-11e8-98f6-05d26ba59427.jpg)

**Comment by Richard0528** [comment]
![2](https://user-images.githubusercontent.com/25624883/39162260-8fe9aa68-4729-11e8-9b51-9b330e1ab47b.png)
Here is my code. I followed exactly this blog said. 
https://developer.amazon.com/blogs/alexa/post/0c975fc7-17dd-4f5c-8343-a37024b66c99/alexa-skill-recipe-using-the-device-address-api-to-request-information

**Comment by TianTXie** [comment]
@Richard0528 , In alexa.amazon.com, can you log in and check if you set the device address or not?

**Comment by gDev95** [comment]
@Richard0528 yes, I remember now I had to set the location. I did this in my alexa app that was connected to my alexa device under settings!
