### ISSUE TITLE
renderTemplate does not consistently fire after response.playVideo during live device testing

### ISSUE THREAD

**Issue by appeality** [alexa/alexa-skills-kit-sdk-for-nodejs#316]
I am developing/testing a skill on a live device (Echo Show), and I noticed renderTemplate does not consistently show the template after playing a video via the videoApp interface with this.response.playVideo. Sometimes it renders the template, and sometimes it simply ends the session.

The behavior is intermittent, as the template does render sporadically. I checked the CW logs and can see the render template directive sent in the response each time.

Has anyone else experienced this? Any ideas what might be causing it? I would like to have confidence this will not occur when the skill is live. 

Cloudwatch Log of Response
`
2018-03-07T23:02:51.350Z	a8d2b6b7-225b-11e8-96db-e55a377c4c31	RESPONSE :::: [ { type: 'VideoApp.Launch',
videoItem: 
{ source: 'https://[REDACTED]',
metadata: [Object] } },
{ type: 'Display.RenderTemplate',
template: 
{ type: 'ListTemplate1',
token: 'lstDoSomething',
title: 'What do you want to do?',
listItems: [Object] } } ]
`

**Comment by TianTXie** [comment]
@appeality Do you still have this problem? I tested on my device to send a response that has both display template directive and play video directive. The video always plays first, after it finishes, the template is rendered.
