### ISSUE TITLE
How to stop user session with Alexa-sdk?

### ISSUE THREAD

**Issue by faiza-nawaz-confiz** [alexa/alexa-skills-kit-sdk-for-nodejs#32]
Hi, i'm using alexa-sdk. My skill is very simple, but i'm not sure how to stop user session so that he can't use my skill without restarting it.
I use "**shouldEndSession**" for this purpose, when not using SDK. but i'm unable to find this in functionality provided by SDK (I'm sure it's been provided. Please guide).

**Comment by deegles** [comment]
Hi,

If you use `this.emit(':tell', ...)` the current session will end.

**Comment by faiza-nawaz-confiz** [comment]
@deegles, means, if i use this.emit(':tell',...), the session will end. and if i use this.emit(':responsebody'), it will not? 
Please guide in a little more detail.. Will be really helpful. thanks

**Comment by gabrielkaputa** [comment]
Hi, here you can see what ends the session and what does not: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/response.js. this should answer your question

**Comment by bclement-amazon** [comment]
Closing as @gabrielkaputa answered with reference doc.

Feel free to re-open if you have any further questions

**Comment by pranavshenoy** [comment]
Hi
I am using this.emit(':tell', 'hello alexa'), but this is not ending the session, it executes the following  statements too. due to this i am getting timeout error in lambda function

**Comment by DKorosec** [comment]
Same here, the :tell emit is not ending the session and alexa is waiting for the async get request to complete (executed after the :tell) which creates an annoying 3-4 seconds delay in response. Is there any workaround?

**Comment by DKorosec** [comment]
@pranavshenoy thanks, it resolved the issue I was having 👍. 
If your following statements are synchronous, they will be executed because they are inside the same event. If you make then asynchronous (for example wrap them around setTimeout) they will be put inside an event loop and won't be executed in the current event which executes the :tell command.
