### ISSUE TITLE
Sending Speech Output to Response that Includes audioPlayer.Stop()

### ISSUE THREAD

**Issue by Caoimhin89** [alexa/alexa-skills-kit-sdk-for-nodejs#321]
Is it possible to add speech output to a response that includes audioPlayer.Stop()?

I'm attempting to do this in the following example:

  
```
    'AMAZON.StopIntent': function () {
        const goodbyeMsg = 'Thanks for listening. See you next time.';

        // Set speech output
        this.response.speak(goodbyeMsg);

        // Set audio directive
        this.response.audioPlayer.Stop();

        // Build response and send to Alexa
        this.emit(':responseReady');
    }
```

However, this does not work as intended. The audio stops playing, but Alexa does not deliver the speech output.

**Comment by xtiantia** [comment]
Shouldn't it be this.response.speak(goodbyeMsg).audioPlayerStop()? It should work. When responding to a LaunchRequest or IntentRequest, your response can include both AudioPlayer directives and standard response properties such as outputSpeech, card, and reprompt.
