### ISSUE TITLE
"locale" information missing in Alexa HouseholdList event request / How to get multi language support in event handler?

### ISSUE THREAD

**Issue by exe222** [alexa/alexa-skills-kit-sdk-for-nodejs#322]
I have successfully integrated the Alexa.HousholdListEvents in my node.js AWS lambda based skill. Now I am trying to use language translation as for usual Intents / Requests.

Unfortunately in the HousholdListEvent the "request" does not contain locale information and instead of a translated string I am getting just the identifier repeated when using t(). See example below. I cannot get the locale information from the received event and would have to fall back to english which is blocking me from starting skill the certification process.

If you need further information - feel free to ask. I am more than happy to provide more details if needed.

Any advice? Help is appreciated!

Why do I have no locale information as part of the event?

Why is t() not working as expected (just like for normal intents)?

How could I translate in the event handler based on the origin locale?

My event request:

    "request": {
        "type": "AlexaHouseholdListEvent.ItemsCreated",
        "requestId": "4a3d1715-e9b3-4980-a6eb-e4047ac40907",
        "timestamp": "2018-03-12T11:20:13Z",
        "eventCreationTime": "2018-03-12T11:20:13Z",
        "eventPublishingTime": "2018-03-12T11:20:13Z",
        "body": {
            "listId":        "YW16bjEuYWNjb3VudC5BRVlQT1hTQ0MyNlRQUU5RUzZITExKN0xNUUlBLVNIT1BQSU5HX0lURU0=    ",
            "listItemIds": [
                "fbcd3b22-7954-4c9a-826a-8a7322ffe57c"
            ]
        }
    },

My translation usage:

    this.t('MY_STRING_IDENTIFIER')

My result (in the ItemsCreated event handler):

    MY_STRING_IDENTIFIER

Expected result (as for other requests):

    "This is my translated text"

**Comment by xtiantia** [comment]
Yes, I've checked that in household list request there is no locale information, but the SDK retrieves the  locale from the request, so the solution here might be accessing the localization client this.i18n, and manually set the locale information.

**Comment by exe222** [comment]
Thanks, will give it a try. But still wondering:
How to get the appropriate target locale information? This depends on whom triggered the event (which is the linked alexa user). Since it is an out of session request I cannot go that way.

**Comment by exe222** [comment]
Sorry for the late response. Could you give some guidance how I can access / how to use i18n directly from an event handler? I would likt to pull the locale information from i18n as you mentioned and use this information in my event handler.

**Comment by exe222** [comment]
I could not test, yet since in the middle of ASK SDK migration to v2. 
The translation seems different in v2, though.

**Comment by tianrenz** [comment]
Hi @exe222, 

Thank you for support for ASK SDK. I'm closing this issue now since it's no longer relevant to v2 SDK. Please feel free to open a new issue if you encounter the same issue when migrating skills to v2. 

Regards
