### ISSUE TITLE
Multiple Requests Within Dialogue Turn-Based Simulator

### ISSUE THREAD

**Issue by aspencerpsu** [alexa/alexa-skills-kit-sdk-for-nodejs#323]
Sorry, this project is pretty secure, but I hope I can provide just a snippet of code and provide you the context leading to my problem and why I'm writing this issue.

I have a skill where the user can call upon a name to invoke a handler for looking up telecom information for a particular user in an external database. If the user exists within the records and shares a symlink to another entity, then I would persist important values extrapolated from the external database to the DynamoDB and forward the intent to a separate handler to make a phone call through a server hook by making a request.

```
     callSubject": function (){
         const intentObj = this.event.request.intent,
                   telecom = JSON.parse(this.attributes['telecom']);
         this.emit(":tellWithCard","We are in the process of calling the intended receipient.",imageObj);
          var data = {},
                 contact = `[${JSON.stringify(
                                                {
                                                  fname: intentObj.slots.person.value.split(" ")[0],
                                                  cell: {value: telecom.find(e=>e.use==="mobile")?
                                                          telecom.find(e=>e.use==="mobile").value:"no recording"},
                                                          home: {value: telecom.find(e=>e.use==="home")?
                                                          telecom.find(e=>e.use==="home").value:"no recording"},
                                                          email: {value: telecom.find(e=>e.use==="email")?
                                                          telecom.find(e=>e.use==="email").value:"no recording"}
                                                 }

                           )}]`,
                           callback = this.attributes['deskNo'],
                           agent = this.attributes['agent'],
                           subject = typeof intentObj.slots.subject.value!=="undefined"?
                                           intentObj.slots.patient.value:
                                           this.attributes['subject']?
                                           this.attributes['subject']:
                                           "A Subject",
        message = `${agent} is calling you, we are forwarding you to the adminstration`;
        data['contacts'] = contact;
        data['callback'] = callback;
        data['duration'] = "One Time";
        data['urgency'] = "call";
        data['subject'] = subject;
        data['agent'] = agent;
        data['message'] = message;
       /* this function keeps calling the subject 4 or 5 times when the call is a success, no idea why or how to stop this behavior */
        request.postAsync({url: this.attributes['route']+"/api/red-sub/callOnly",
                                       form: data})
        .then((body)=>{
           console.log("CALL SUCCESSFUL");
           console.log(body);
       }).catch(err=>console.error(err));
       return;
     },
```

This final destination or last intent stop runs through a succession of calls when the original intention of this request handler is to make a call only **once**.  I'm looking for some advice on why there are multiple call requests happening in this handler function. The timeout on the lambda function is 50 seconds and the call flow operation occurs in no more than 40 seconds.

**Comment by aspencerpsu** [comment]
Can anyone provide some clarity on this?If this question is too vague or verbose, I'd be more than willing to provide some evidence via a video screenshot showing what's happening.

**Comment by tianrenz** [comment]
Hi @aspencerpsu , 

Sorry for the late reply. If this issue is still active, could you provide more information on how the handler is invoked?

If you are logging the request and response, could you provide some cloudwatch logs as well. Those might help investigating the issue. 

Regards

**Comment by aspencerpsu** [comment]
Hey thanks for the response, but it's resolved now. Thanks. Now that I can use async/await in multi turn dialogue sequences, it resolved the spamming issue when using the npm request module. If I have issues again, I'll open a new ticket.

Akeem
