### ISSUE TITLE
Feature Request: Allow an Intent to hold the conversation

### ISSUE THREAD

**Issue by vedantshetty** [alexa/alexa-skills-kit-sdk-for-nodejs#327]
Currently, an intent is activated through a user utterance and once activated we cannot take any further input from the user for that particular intent.

**Comment by benedekh** [comment]
Hi @vedantshetty ,

You might would like to have a look at the Dialog Interface [here](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html) and [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#dialog-interface), which might be capable of doing it.

**Comment by vedantshetty** [comment]
Thanks a lot. That does help
