### ISSUE TITLE
Can I ask a question how do you exactly add a Username in SSML?

### ISSUE THREAD

**Issue by 25kcdiez** [alexa/alexa-skills-kit-sdk-for-nodejs#329]
for example:....
   
    ` "<speak> got it</speak>"  + username+ "<speak> right ? ....</speak>";`

in Service response or voice simulator it returns error
  <speak>got it</speak>Kevin<speak>....</speak> 
it doesn't read Kevin because it's plain text....
so How do we exactly add  or can we do this in this current version on ALEXA?

**Comment by seino-tsuyoshi** [comment]
` "<speak> got it "  + username+ " right ? ....</speak>";`


How is this?

**Comment by 25kcdiez** [comment]
thanks bro, like >_< of course, also I think I double issue it here. 
thanks again much love and Be blessed.

Kevin,
