### ISSUE TITLE
How to user this library with express?

### ISSUE THREAD

**Issue by oprog** [alexa/alexa-skills-kit-sdk-for-nodejs#33]
Hi guys,

any example on how to use this with express and not with AWS lambda?

Thanks!

**Comment by deegles** [comment]
We don't have example code, but you can build your skill as if for Lambda and then use a mock context object within your Express handlers to invoke the skill code.

https://github.com/SamVerschueren/aws-lambda-mock-context

**Comment by oprog** [comment]
Thanks @deegles I'll try that. I'm new with AWS Lambda, actually I have it worked in there, but debugging is not easy so I'd like to have something on my server.

**Comment by oprog** [comment]
I managed to have it working in an https express server.
I put what I did in this [gist](https://gist.github.com/oprog/f7761f9c8034c0ee276b01233dd9a6b7)

**Comment by AnnaKra** [comment]
Hi oprog, this is great what you wrote :) Have you managed to go through Alexa certification? Could you write me please how file /alexa/index.js should look like? I would be very greatful to you :)

**Comment by oprog** [comment]
Hi @AnnaKra, I started the certification process but then I had to give up. Too much issues with signed requests and tests from Alexa team and I needed to go live ASAP. It took too much time to submit request for certification, have feedback, fix and repeat several times. So I switched to lambda function approach to get rid of all that. Time to market won on my tech desires :)

**Comment by AnnaKra** [comment]
sad because as your own server there is much more possibilities. Could you help me please showing how should file /alexa/index.js looks like?
