### ISSUE TITLE
How to do reuse intents for one-shot and dialog 

### ISSUE THREAD

**Issue by McGern** [alexa/alexa-skills-kit-sdk-for-nodejs#331]
Hi,

This question was asked a while ago, but immediately closed by the author. In the old SDK, there were examples that showed how to use one-shots e.g. "Alexa ask MYSKILL for the XYZINTENT", and dialog e.g. "Alexa open MYSKILL", "get XYZINTENT", where the intent code was the same.

The basic use case is that if I am in dialog mode, i.e. I have opened the skill without an intent, you will get the "Hi welcome to SKILL. What do you want to do?", and after each completed intent, the skill will then default to "Would you like to do anything else?". In the one-shot you won't get the welcome message and the skill will close after the intent is completed.

Here's what I have working now.
- Open the skill with the one shot intent
- get kicked out after the intent has completed

- Open the skill and get the welcome message
- Trigger the intent and get kicked out after completion

I can think of hacky ways to complete this possibly, but I was looking for an injection of good sense - I keep coming back to hacky if's for every intent, or having to write my own intent parser to switch the ask/tell or speak/listen responses.

Sort of pseudocode below, but hopefully you get the gist. This then becomes more complicated when adding cards etc.

Tried to split apart the this.response.speak and this.reponse.listen (or multiple this.response.speak), but it seems that they must be chained to work.

```
    'LaunchRequest': function () {
        this.attributes['isDialog'] = true;
        this.emit(':ask','Hi, what do you want?','What do you want?');
    },
    'MyIntent':function () {
        var speech = "This is my response. ";
        if( this.attributes.isDialog ) {
            this.emit(':ask', speech + '. Anything else?','Anything else?')
        } else {
            this.emit(':tell', speech)
        }
    }
```

Any help appreciated, just want to know the correct pattern for this behaviour.

Thanks,
Jarrod

**Comment by McGern** [comment]
Thanks for the reply @TianTXie 

I'm still trying to get to grips with using the state pattern, some of my previous attempts haven't worked so well (have another question/issue going for this repo, but no answers). 

If you used the state pattern, does that mean you would need to do a new CreateStateHandler for every intent, or at the least double up on each method (perhaps extracting the "work" portion of the intent to another module?)

This is what I ended up doing

```
    'LaunchRequest': function () {
        this.attributes['isDialog'] = true;
        this.emit(':ask','Hi, what do you want?','What do you want?');
    },
    'MyIntent':function () {
        // do logic that produces the answer, does dialogs etc
        var speech = "this is my speech output";

        this.emit('AnythingElseIntent', speech );
    },
    'AnythingElseIntent': function(speech) {
        var anythingElseSpeech = "Is there anything else I can help with?";
        var askTell = this.attributes.isDialog ? ':ask' : ':tell';
        var speech = this.attributes.isDialog ? speech + ". <break time='500ms' /> " + anythingElseSpeech : speech;
        this.emit(askTell,speech,anythingElseSpeech);
    },
```

Every intent then passes their speech through to the "AnythingElseIntent". Seems to work. It could be extended to push card content etc.

**Comment by tianrenz** [comment]
Hi @McGern , 

We just launched the V2 generation of SDK. We encourage you to migrate to v2 for expanding your skills. You can check out the [migration guide ](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/ASK-SDK-Migration-Guide)here. Or start new with our[ getting started guide](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki). 

Regards
