### ISSUE TITLE
Passing between intents in state handler e.g. HelpIntent back to Prior intent

### ISSUE THREAD

**Issue by McGern** [alexa/alexa-skills-kit-sdk-for-nodejs#332]
Hi,

I have been to trying to work out state handlers as they seem to suit my situation (maybe), where I have a bunch of entry intents which then pass out to the relevant state handler. I am using state because some intents will have contextual help about that intent (I think that's the purpose of the state handler?), but I am struggling with the pattern of handing back to the main intent i.e. where to re-ask the question or how to feed into the original intent. 

I am using dialog slot filling for the main intent in the handler, and am trying to emit to this handler (tried emitWithState as well), but it doesn't seem to pick up the fact that I have jumped from help.

I guess the basic question in summary is "how do you re-prompt after asking for help about an intent with a dialog slot filling?". The highlowgame example looks like it has something similar, but my scenario is a bit  different in that the answer to the question won't trigger the intent again.

Thanks.

**Comment by TianTXie** [comment]
This question is exactly same with what was discussed in one previous [issue](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/250). You could check more information there.

**Comment by McGern** [comment]
Thanks again @TianTXie for helping.

That discussion exactly answers my question by there being no answers :-)

Guess I can close this one?
