### ISSUE TITLE
response builder function chaining not working

### ISSUE THREAD

**Issue by nandor-poka** [alexa/alexa-skills-kit-sdk-for-nodejs#333]
Hello!

I have the following code in one of my intents and when the intent is activated, Alexa only speaks the WELCOME_MSG. 
```javascript
this.response.speak(WELCOME_MSG).listen(ASK_TO_START);
this.emit(':responseReady');
```
When not chained, but written as separate commands like this:
```javascript
this.response.speak(WELCOME_MSG);
this.response.listen(ASK_TO_START);
this.emit(':responseReady');
```
then Alexa does not play the WELCOME_MSG.

Am I doing something wrong?

**Comment by TianTXie** [comment]
@nandor-poka , there is no difference between those two. Did you check the logs in the cloudWatch?

**Comment by nandor-poka** [comment]
Hello,

Yes I did, but could not find any meaningful info regarding this issue. I definitely didn't see any errors. I'll take a thorough look again though, just to make sure nothing slipped my attention.

**Comment by tianrenz** [comment]
Hi @nandor-poka , 

I was trying to replicate the error but couldn't. Could you check again if the problem still exists?

Regards

**Comment by nandor-poka** [comment]
Hi @tianrenz.

The issue still persists. However I'm going to use v2 API from now and see if there's a similar issue or not. Therefore I'm pretty sure that this is not relevant anymore.

**Comment by tianrenz** [comment]
Thanks. I’ll close the issue then. Please feel free to open a new issue if you encounter the same problem with v2
