### ISSUE TITLE
Forcefully Saving session in dynamoDB without user saying stop or any exception

### ISSUE THREAD

**Issue by PrithiviRajG** [alexa/alexa-skills-kit-sdk-for-nodejs#335]
We are using Alexa skill kit to persist data in session and saving data to dynamoDB on session end. Sometimes Session is not persisting to dynamoDB when there is sudden power loss to echo Dot or internet failure in echoDot. So we want to save session to dynamoDB on certain actions or save session after every n minutes. is it possible?

**Comment by jitendraavinash** [comment]
You have to save the attributes after every important operation in your code.

**Comment by PrithiviRajG** [comment]
can we add saveState after responseReady? Like the below code.

```
this.emit(':responseReady');
this.emit(':saveState', true);
```

**Comment by jitendraavinash** [comment]
yes, you can do that.

**Comment by TianTXie** [comment]
@PrithiviRajG , you don't need to call this.emit(':responseReady'); just call this.emit(':saveState', true);

**Comment by PrithiviRajG** [comment]
@TianTXie I am having speak and listen events also in the same block. can I use `this.emit(':saveState', true);` instead of `this.emit(':responseReady');`

**Comment by tianrenz** [comment]
Hi @PrithiviRajG, 

For v1 SDK, `this.emit(':ResponseReady')` will automatically call saveState when session ended. You can use `alexa.saveBeforeResponse = true` to force saving data on everything dialog turn. 

Meanwhile, we would recommend checking the v2 SDK for Node.js which provides better support for attributes management. You can check out the documentation [here](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/). 

Regards

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if problem persists.
