### ISSUE TITLE
To get audio progress callback

### ISSUE THREAD

**Issue by keerthy-cf** [alexa/alexa-skills-kit-sdk-for-nodejs#336]
Hi,
I want to know the progress of audio played on device. Per docs its possible using progressReportDelayInMilliseconds
https://developer.amazon.com/docs/alexa-voice-service/audioplayer.html#play

But I could not figure out from docs how that is possible using the  play interface mentioned here
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/Readme.md#interfaces

Can you please help ?

**Comment by TianTXie** [comment]
@keerthy-cf , I think that is for AVS,  the Alexa skill kit doesn't support yet.

**Comment by keerthy-cf** [comment]
Then how do we get to know the progress using skill kit SDK? For my usecase
I want to know track how much of the content user has progressed .

**Comment by Amazon-tianrenz** [comment]
Hi, @keerthy-cf,

For custom skill in Alexa Skills Kit, it's currently not supported. The closest thing you can get is `AudioPlayer.PlaybackNearlyFinished`. See this [link](AudioPlayer.PlaybackNearlyFinished) for more information.
