### ISSUE TITLE
home skill is at higher priority than custom skill?

### ISSUE THREAD

**Issue by nqd** [alexa/alexa-skills-kit-sdk-for-nodejs#34]
Hello,

We are testing a custom skill, on which have command like "tell abc to turn on device xyz". Reply to me is always the smart home skill, not my custom skill. Though testing on Service Simulator is ok.

Just want to confirm that home skill is always at higher priority than custom skill. Is there any way to overwrite the priority?

Thanks.

**Comment by bclement-amazon** [comment]
Essentially, Alexa is trying to resolve a conflict between the the smart home skill, and your skill's command "turn on device xyz". There is currently no way to overwrite the priority but i'd try the following:

You might be able to get better accuracy by launching the skill first and then saying the command as a separate interaction, but that will require two commands out of the user. 

You may also be able to provide more training data via sample utterances to increase the recognition accuracy.
