### ISSUE TITLE
notifications?

### ISSUE THREAD

**Issue by carterw** [alexa/alexa-skills-kit-sdk-for-nodejs#340]
Is there anything in the API for generating notifications? That would be a critical feature for my use case.

**Comment by stagingreview** [comment]
@carterw could you provide more information about your use case so that we can see if we could help here.

**Comment by TianTXie** [comment]
@carterw could you provide more information about your use case so that we can see if we could help here.

**Comment by carterw** [comment]
I make IoT devices that sense and report events that are of interest to my customers. I have various conventional ways to notify them in real time (SMS messages for example), but I think Alexa notifications would be a really valuable feature.

**Comment by Amazon-tianrenz** [comment]
Hi @carterw, 

Notification feature of Alexa skill has not been made public yet. You can check out this [link](https://developer.amazon.com/blogs/alexa/post/833b9af4-26e6-47d2-a13d-bdbd9a257512/expanded-developer-preview-of-notifications-for-alexa-skills) for information on how to opt in developer preview.
