### ISSUE TITLE
Number Input

### ISSUE THREAD

**Issue by chasebish** [alexa/alexa-skills-kit-sdk-for-nodejs#342]
One thing I have noticed when testing on the simulator online is a discrepancy between numbers as a word and numbers as an actual digit.

I am using the `AMAZON.NUMBER` built in slot and when I type in "1" instead of "one", I am directed to the wrong intent.

I have two questions regarding this:
1. Is this intentional that "1" != "one" when handling input?
2. When a user is speaking with an actual alexa device, if their response is "one", does it register as "1" or "one"?  If what the user says registers as "one" then this would only be a bug within the simulator.

**Comment by TianTXie** [comment]
@chasebish I would suggest Alexa Developer forum (https://forums.developer.amazon.com/spaces/165/index.html)as a great place to post this question. It's actively monitored by Amazon engineers and lots of developers are posting there, too!
