### ISSUE TITLE
support multiple successive calls to this.response.speak(...)

### ISSUE THREAD

**Issue by jonnedeprez** [alexa/alexa-skills-kit-sdk-for-nodejs#344]
I noticed in my Skills that speech sent to Alexa is often constructed in several steps of a longer algorithm. It would therefore be nice to be able to call the speak() method several times in a row, each time adding snippets to a queue.

    this.response.speak('I will count to five: ');
    
    for(int i = 1; i <= 5; i++) {
      this.response.speak(`${i} `);
    }

    this.emit(':responseReady'); // Alexa: 'I will count to five: one, two, three, four, five'

**Comment by TianTXie** [comment]
You can build a outputSpeech string recursively first and then call this.response.speak(outputSpeech) afterwards.

**Comment by jonnedeprez** [comment]
Thanks, but that's quite obvious ;-)

**Comment by TianTXie** [comment]
Thanks for your suggestion, I will bring this up with the team!

**Comment by jprateekvmware** [comment]
We looking at something , where we have filed a request. The process takes too much time.
We can emit response to the user "You ticket is getting filed, will confirm short while" and once the ticket is created we emit response . Your ticket number is .....

**Comment by ZuBB** [comment]
Hello everyone! Sorry for bumping of quite old thread/issue

@TianTXie I am just wondering if you have any news on subject. It would be really nice to have an ability to so something like next

```js
  if (_.isArray(speakObj.phrases)) {
    responseBuilder = _.reduce(
      speakObj.phrases,
      phraseObj => responseBuilder.speak(translate(phraseObj.phrase, phraseObj.phraseParams)),
      responseBuilder
    );
  }
```
