### ISSUE TITLE
listItemBuilder without an Image

### ISSUE THREAD

**Issue by robbalmbra1** [alexa/alexa-skills-kit-sdk-for-nodejs#345]
Is it possible to remove the image from the listItemBuilder output in the ListTemplate1 template? , it is shown in the Alexa documentation: 
https://developer.amazon.com/docs/custom-skills/display-interface-reference.html

**Comment by TianTXie** [comment]
Yes, only token is required, all other parameters are optional, just passing in them as undefined should work.

**Comment by robbalmbra1** [comment]
Yes, however there is a gaping space, it doesn't remove the space that the picture occupies.

**Comment by Amazon-tianrenz** [comment]
Hi @robbalmbra1 , 

Yes, Echo show support multiple preset templates that have fixed layout. See [here](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html).  If you don't need to display image on the page, maybe consider switching to a different template.

**Comment by robbalmbra** [comment]
If you read the documentation on Amazon’s website it says an image is optional in ListTemplate1. Furthermore the output on echo show simulator clearly shows html tags showing that the template is fluid.
