### ISSUE TITLE
ErrorHandler from HelloWorld v2 is not defined

### ISSUE THREAD

**Issue by warhost** [alexa/alexa-skills-kit-sdk-for-nodejs#350]
The ErrorHandler mentioned here https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Developing-Your-First-Skill

is nowhere defined in the example.

**Comment by itachiRedhair** [comment]
For now, you can do with this
`const ErrorHandler = {
  canHandle() {
    return true;
  },
  handle(handlerInput, error) {
    console.log(`Error handled: ${error.message}`);

    return handlerInput.responseBuilder
      .speak('Sorry, I can\'t understand the command. Please say again.')
      .reprompt('Sorry, I can\'t understand the command. Please say again.')
      .getResponse();
  },
};`
