### ISSUE TITLE
RequestHandlerChain not found!

### ISSUE THREAD

**Issue by karri-sek** [alexa/alexa-skills-kit-sdk-for-nodejs#352]
Error handled: RequestHandlerChain not found! 
## Expected Behavior
 whenever I invoke the handler(v2 sdk) with test.js file , I see this error on the console.
Error handled:  RequestHandlerChain not found! 
## Current Behavior
I should not see this error on console

## Possible Solution
 Not sure

## Steps to Reproduce (for bugs)
create any new skill with alexa cli and write a small test file contains the request to invoke any intent on the handler suppose say 'Launch request'.
type node test.js ..
immediately you see an error message.

## Context
I am trying to invoke an intent from the test file running from command line....
## Your Environment
"dependencies": {
    "ask-sdk-core": "^2.0.0",
    "ask-sdk-model": "^1.0.0"
  }

mac OS
## Node.js and NPM Info
node : v9.11.1
npm : 5.6.0

**Comment by Amazon-tianrenz** [comment]
Hi @karri-sek, 

Could you copy a code snippet of your handlers and the test event you send that causes the `RequestHandlerChain not found` error?

Normally this error is being thrown when no handler is found that can handle the request. (aka, no handler's `canHandle` returns true.)

Regards

**Comment by mehtanilay10** [comment]
I have also faced the same issue, I have debugged canHandle() of my handler and got that misspell in Intent name so it returns false. Means none of the handlers return true so it does not get any handler for that request.
After changing the intent name it works. May this will help you.

**Comment by hyzhak** [comment]
Got the same error:

```javascript
AskSdk.DefaultRequestDispatcher Error: RequestHandlerChain not found!
    at Object.createAskSdkError (./node_modules/ask-sdk-core/lib/util/AskSdkUtils.js:22:17)
    at DefaultRequestDispatcher.<anonymous> (./node_modules/ask-sdk-core/lib/dispatcher/DefaultRequestDispatcher.js:116:49)
    at step (./node_modules/ask-sdk-core/lib/dispatcher/DefaultRequestDispatcher.js:44:23)
    at Object.next (./node_modules/ask-sdk-core/lib/dispatcher/DefaultRequestDispatcher.js:25:53)
    at fulfilled (./node_modules/ask-sdk-core/lib/dispatcher/DefaultRequestDispatcher.js:16:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) name: 'AskSdk.DefaultRequestDispatcher Error'
```

I've got it on `AudioPlayer.PlaybackStarted`, `AudioPlayer.PlaybackNearlyFinished` intents. Which work fine on v1.

**Comment by TianTXie** [comment]
@hyzhak Could you copy your canHandle() function for AudioPlayer intents here? It should be something like this which keeps the 'AudioPlayer' prefix:
```
const request = handlerInput.requestEnvelope.request;
return request.type === 'AudioPlayer.PlaybackStarted'
```

**Comment by tianrenz** [comment]
Hi all, 

We've changed the error message to a more meaning message in the latest release. The error is thrown when skill could not find handler that can handle the request. (no handler's canHandle returns true). Please check if your intended canHandle logic for the request returns true if the error is thrown. Usually it's due to a typo in the name of request or forget to register it in the skill builder. 

Please feel free to reopen the issue if problem persists. 

Regards
