### ISSUE TITLE
"Cannot read property trim of undefined" when using elicitation directive

### ISSUE THREAD

**Issue by sem4phor** [alexa/alexa-skills-kit-sdk-for-nodejs#357]
When using the elicitation directive i get an error message.
The skill is pretty basic you should be able to reproduce it easily by using the elicitation directive.

The message is definitly not from the SDK side of code because i dont use an external library or a trim function.

## Expected Behavior

I get a more meaningful message and the session is not ended after elicitation.

## Current Behavior

I ask the user for a slot value with elicitation the user inputs a value. The elicitation in fact works. But in the console logs i get "Session ended with reason: USER_INITIATED" and later on "Cannot read property 'trim' of undefined".

`Session ended with reason: USER_INITIATED`
`Error handled: Cannot read property 'trim' of undefined`

## Possible Solution
The trim issue is propably related to request input validation.

## Steps to Reproduce (for bugs)
```
handle(handlerInput) {
   const slots = handlerInput.requestEnvelope.request.intent.slots
   let foo = slots.foo && slots.foo.value ? parseInt(slots.foo.resolutions.resolutionsPerAuthority[0].values[0].value.id) : undefined
    let speechText = undefined

    if (!foo) {
      speechText = `What isnt bar`
    } else {
      console.log(foo) // <- works!
    }

    return handlerInput.responseBuilder
      .speak(speechText)
      .addElicitSlotDirective('foo')
      .getResponse();
  }
```

## Context

Process a user response after elicitation. And send another response.

## Your Environment

* ask-sdk-core: 2.0.0
* ask-sdk-model: 1.0.0
* Operating System and version: macOS high sierra

## Node.js and NPM Info
* Node.js version used for development: 8.10
* NPM version used for development: 5.6.0

**Comment by TianTXie** [comment]
@sem4phor, that means speechText is undefined. You can put return statement inside if block.

**Comment by tianrenz** [comment]
Hi @sem4phor,

This issue has been fixed in the latest release. Please feel free to reopen the issue if the problem persists.

**Comment by sem4phor** [comment]
The trim error still occurs on ask-sdk-core 2.0.3 and ask-sdk-model 1.2.0
@tianrenz
