### ISSUE TITLE
Put ask-sdk-model on Github too

### ISSUE THREAD

**Issue by hoegertn** [alexa/alexa-skills-kit-sdk-for-nodejs#358]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
It would be great if the `ask-sdk-model` dependency was available on Github too. So users could create PRs with missing features to the model like metadata for audio player directives for example.

**Comment by tianrenz** [comment]
Hi @hoegertn,

We are discussing the possible options for making ask-sdkmodel package public internally right now. Because the model package is being generated, we can't really merge any PR on that.

**Comment by hoegertn** [comment]
Ok, can you then please add the metadata for audio player directives in your generator? Still, it would be great to have it on Github to see the code of the used model.

**Comment by nikhilym** [comment]
Hey @hoegertn , audio player metadata has been added to the models.
