### ISSUE TITLE
Typo in wiki

### ISSUE THREAD

**Issue by kev2480** [alexa/alexa-skills-kit-sdk-for-nodejs#360]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Skill-Builders

`DynamoDbPersistentAdapter` should be `DynamoDbPersistenceAdapter` right?

**Comment by tianrenz** [comment]
Hi @kev2480,

Good catch! The wiki has been updated.
Thanks for your support!
