### ISSUE TITLE
Localization in V2:  What's the suggested way to handle localized language strings?

### ISSUE THREAD

**Issue by hueezer** [alexa/alexa-skills-kit-sdk-for-nodejs#365]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Documentation on how to handle localization on V2.  I've searched the issues and source code, but couldn't find anything.

**Comment by tianrenz** [comment]
Hi @hueezer, 

There's no suggested way currently. The v2 SDK has a modular design that encourages developers to extend from the platform. We do offer a couple samples that utilizes the i18n library. I would suggest go check those out: [Trivia](https://github.com/alexa/skill-sample-nodejs-trivia), [How To](https://github.com/alexa/skill-sample-nodejs-howto)

**Comment by tianrenz** [comment]
Closing the issue for now. Please feel free to reopen if problem persists
