### ISSUE TITLE
Having trouble getting the adapter working

### ISSUE THREAD

**Issue by gshenar** [alexa/alexa-skills-kit-sdk-for-nodejs#367]
Besides changing to use this import line, do I have to do anything else to get the adapter to work with a v1 project?

let Alexa = require('ask-sdk-v1adapter');

I just get this basic error with no information about where to look next:

Unable to import module 'index': Error at Object.<anonymous> (/var/task/index.js:2:13) at Module._compile

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
Take v1 project that works. install alexa sdk and adapter and change import line to 
let Alexa = require('ask-sdk-v1adapter');
Now it doesnt work anymore and gets a useless error.

## Context

I can't migrate my skill to use SDK v2 which I need to ISPs.

## Your Environment

* ASK SDK for Node.js used: 2.0.0
* Operating System and version: Windows 10

## Node.js and NPM Info
* Node.js version used for development: 8.1.3
* NPM version used for development: 5.0.3

**Comment by tianrenz** [comment]
Hi @gshenar,

Could you provide your package.json here? `ask-sdk-v1adapter` requires a peer dependency of `ask-sdk`. Also, when you upload your code package to lambda, make sure you compress all the code files instead of the folder. 

Regards

**Comment by tianrenz** [comment]
Communicated with the customer offline. Close issue now. Please feel free to reopen if you have any problems.

**Comment by kawboyer** [comment]
Experiencing the issue described above. I do have the peer dependency of `ask-sdk` installed.

**Comment by tianrenz** [comment]
@kawboyer , could you attach your error message and your index.handler snippet here please?

**Comment by kawboyer** [comment]
__error log__
Unable to import module 'index': Error
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/index.js:2:13)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)

__index.js__
```
'use strict';
// const Alexa = require('alexa-sdk');
const Alexa = require('ask-sdk-v1adapter');

const Handlers = require("./Handlers.js");

exports.handler = function(event, context, callback) {
    const alexa = Alexa.handler(event, context, callback);
    alexa.appId = process.env.APP_ID;
    alexa.registerHandlers(Handlers);
    alexa.execute();
};
```

**Comment by tianrenz** [comment]
Hi @kawboyer , 

Could you confirm that when uploading to lambda, you are zipping all the files together instead of zipping the folder directly? The ``index.js`` file needs to be available at the top most layer

Regards

**Comment by kawboyer** [comment]
@tianrenz I'm deploying to the ASK CLI not manually.

**Comment by tianrenz** [comment]
Hi @kawboyer , 

The error you are seeing here usually indicates some problem with your node dependency. Could you try delete the package-lock.json and the node_modules folder and reinstall all the dependencies?

Regards

**Comment by nikhilym** [comment]
Considering the deployment process is different from the actual logged issue, it would be better to move this conversation to a new issue and track from there. Since this issue is already closed, there is a chance that the community might not be looking into or pitching in their ideas of the fix.

@kawboyer , can you please create a new issue with the steps of reproduction and the error stack trace, so that we can investigate this better?

**Comment by gshenar** [comment]
FYI, if you get the 'unable to import module index' error, try going you
your lambda console and sending a test event. Many times you'll get a
better error message.

**Comment by kawboyer** [comment]
@tianrenz Thanks. I tried to reinstall all dependencies but got the same error message.
@gshenar Thanks for the suggestion. The error is definitely related to the v1adapter package.
```
{
  "errorMessage": "Cannot find module 'ask-sdk-v1adapter'",
  "errorType": "Error",
  "stackTrace": [
    "Module._compile (module.js:652:30)",
    "Object.Module._extensions..js (module.js:663:10)",
    "Module.load (module.js:565:32)",
    "tryModuleLoad (module.js:505:12)",
    "Function.Module._load (module.js:497:3)"
  ]
}
```

**Comment by tianrenz** [comment]
@kawboyer, looks like the `ask-sdk-v1adapter` was not installed. Could you run the following command (``npm ls --depth=0``) in your project directory and check if `ask-sdk-v1adapter` is listed?

Could you also attach a copy of your package.json file here please?

Regards, 
Tianren

**Comment by kawboyer** [comment]
Thanks @tianrenz. The command shows that `ask-sdk-v1adapter` is installed. 

**package.json:**
```
 {
  "name": "lambda",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "alexa-sdk": "^1.0.15",
    "ask-sdk": "^2.3.0",
    "ask-sdk-s3-persistence-adapter": "^2.3.0",
    "ask-sdk-v1adapter": "^2.3.0",
    "dateformat": "^3.0.2",
    "promise": "^8.0.1",
    "superagent": "^3.8.1"
  }
}
```

**Comment by tianrenz** [comment]
@kawboyer , could you verify that the ``node_modules`` folder are under the same directory as your ``index.js`` file and inside that ``node_modules`` folder there's a ``ask-sdk-v1adapter`` folder? The error is definitely caused by ``ask-sdk-v1adapter`` not installed correctly. 

Regards

**Comment by kawboyer** [comment]
Thanks @tianrenz! You were right. I had the node_module folder in the wrong directory.

**Comment by balayogesh007** [comment]
Hi,
Im used <h4>alexa-sdk </h4> Im getting the error like  undefined  "locale". So i go throught the documentation they suggest to use with adapter then i changed require to <h4>ask-sdk-v1adapter</h4> But still im getting the same error. help me to solve this. @tianrenz 
![image](https://user-images.githubusercontent.com/91451601/216296662-d12b0ec0-f632-4cf6-a202-425a3bc9aa09.png)
