### ISSUE TITLE
Errors in SDK Type Definitions (with TypeScript 2.8.3)

### ISSUE THREAD

**Issue by toedter** [alexa/alexa-skills-kit-sdk-for-nodejs#370]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

In the package.json I have the following dependencies:
```
  "dependencies": {
    "ask-sdk": "^2.0.1",
    "typescript": "^2.8.3"
  },
  "devDependencies": {
    "@types/node": "^9.6.7"
  }
```
I would expect no errors in the type definitions of ASK.

## Current Behavior

When running the TypeScript compiler (tsc, v2.8.3) the following errors occur:
```
node_modules/ask-sdk-model/index.d.ts(100,86): error TS2304: Cannot find name 'Map'.
node_modules/ask-sdk-model/index.d.ts(100,120): error TS2304: Cannot find name 'Map'.
node_modules/ask-sdk-model/index.d.ts(103,37): error TS2304: Cannot find name 'Map'.
node_modules/aws-sdk/lib/config.d.ts(39,37): error TS2693: 'Promise' only refers to a type, but is being used as a value here.
```

## Possible Solution

I did not find a solution yet.

## Steps to Reproduce (for bugs)

Create a file index.ts with the following content and compile it:
```
import * as Alexa from 'ask-sdk';
```

## Context

I am trying to port the "hello, world" skill written in JavaScript to TypeScript.

## Your Environment

* ASK SDK for Node.js used: 2.0.1
* Operating System and version: Windows 10, version 1709

## Node.js and NPM Info
* Node.js version used for development: v8.11.1
* NPM version used for development: 5.6.0

**Comment by tianrenz** [comment]
Hi,

Could you please try add —lib es2017, dom in your typescript config ?

**Comment by toedter** [comment]
Thank you, @tianrenz 
When adding     "lib": ["es2017", "dom"] in the compilerOptions, everything compiles without error.

Here is my tsconfig.json that works:

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": ["es2017", "dom"]
  },
  "include": [
    "src"
  ],
  "exclude": [
    "node_modules",
    "**/*.spec.ts"
  ]
}
```
