### ISSUE TITLE
Syntax Error in Wiki Documentation for ImageHelper and TextHelpers

### ISSUE THREAD

**Issue by acucciniello** [alexa/alexa-skills-kit-sdk-for-nodejs#374]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

[Here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Response-Building#image-and-text-helpers) `withPrimaryTexT()` should be written as `withPrimaryText()` for each of the  3 Helpers (ImageHelper, PlainTextContentHelper, RichTextContentHelper).

**Comment by tianrenz** [comment]
Thanks @acucciniello. Good catch there. The wiki has been updated. Thanks for your support in ASK SDK
