### ISSUE TITLE
Example of proper usage of addDelegateDirective

### ISSUE THREAD

**Issue by warhost** [alexa/alexa-skills-kit-sdk-for-nodejs#376]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am unsure of how to ask the user for a missing parameter in an intent using the prompts defined in the skill builder.
Let's say we have the following intent and utterance:

Intent: 'WelcomeIntent'
Utterance: My name is {name} and I am {age} years old
Where {name} is of type AMAZON.US_FIRST_NAME and {age} of type AMAZON.NUMBER.
I made both "required" to fulfill the intent and defined prompts for them.

And the code:

```
const WelcomeIntentHandler = {
	canHandle(handlerInput) {
		return handlerInput.requestEnvelope.request.type === 'IntentRequest'
			&& handlerInput.requestEnvelope.request.intent.name === 'WelcomeIntent';
	},
	handle(handlerInput) {
		const { intent } = handlerInput.requestEnvelope.request;

		const name = intent.slots.name.value;
		const age = intent.slots.age.value;

		if (!name || !age) {
			// Name or Age missing
			return handlerInput.responseBuilder
				.addDelegateDirective()
				.getResponse();
		} else {
			let speechText = `Welcome ${name}! You are ${age} years old.`;
			return handlerInput.responseBuilder
				.speak(speechText)
				.reprompt(speechText)
				.getResponse();
		}
	},
};
```

## Expected Behavior

I would expect that if I input "My name is Peter" without providing the age, it would ask one of the defined prompts automatically, like this:

-> Open `skillname`
-> 'Welcome! What is your name and age?`
-> My name is Peter
-> 'What is your age?' (This is defined in the skill builder as prompt)

## Current Behavior

When I provide just the name, the skill reponds with the `LaunchRequest` handlers response, like this:
-> Open `skillname`
-> 'Welcome! What is your name and age?`
-> My name is Peter
-> 'Welcome! What is your name and age?'
-> Then I input either 'Peter' or 'Twenty'
-> Nothing, there is literally no response whatsoever

## Your Environment

* ask-sdk-core for Node.js used: 2.0.2
* Operating System and version: MacOS 12.6

## Node.js and NPM Info
* Node.js version used for development: 8.10
* NPM version used for development: 5.6

**Comment by warhost** [comment]
I found the problem.

Apparently I have to add **just** `{name}` and `{age}` as utterances for the `WelcomeIntent` for this to work. Weird, since I did exactly that for the respective slots.

**Comment by FootGround** [comment]
thank you for this.

**Comment by bestimmaa** [comment]
Same problem here :/ is this also the solution if ask for 2 dates in my intent?
