### ISSUE TITLE
Alexa.CreateStateHandler & potential of being able to specify a list of intent handlers in a Request

### ISSUE THREAD

**Issue by dly9014** [alexa/alexa-skills-kit-sdk-for-nodejs#38]
From the readme: 'Alexa-sdk will route incoming intents to the correct function handler based on state.' 

Just a thought, and it isn't specific to the alexa-sdk, but rather the way Requests are made with ASK - It seems like it could be more powerful if you could pass a list of intents in the Request that you wanted to be considered for when the user utterance is mapped to an intent. You could then prevent the wrong intent from firing (when a custom slot is misinterpreted for example) or handle a situation where you want the same utterance to invoke one of many intent handlers depending on the context.

Example:

Below OtherOptionsA and OtherOptionsB intent handlers are created to each only be applicable to the WELCOME state and the LODGE state, respectively. Both intents are set up to be invoked with the same sample utterance of 'other'. 

If the skill is not in state=WELCOME, OtherOptionsAIntent will not work. So there is only one intent handler at a time that is active and can be invoked with the utterance 'other'. But as it stands now, when the skill is in state=LODGE and a user says 'other', the intent request comes in for OtherOptionsAIntent, which by definition is not available since it was defined specific to state=WELCOME. Since OtherOptionsAIntent isn't available, the Unhandled intent handler under state=LODGE is invoked, producing a response of res.lodgeUnhandled(), not res.OtherOptionsB().

In this example it is easy enough to just have a single intent handler that fires with utterance 'other', and then route to the appropriate response within that handler, but just wondering about the potential of being able to specify a list of handlers in a Request.

```
module.exports.welcome = Alexa.CreateStateHandler(APP_STATES.WELCOME, mixinHandlers(coreHandlers, {
  NewSession () {
      res.ask.call(this, res.welcomeGuest())
  },
  OtherOptionsAIntent () {
    this.handler.state = APP_STATES.OTHEROPTIONS
    res.ask.call(this, res.otherOptionsA())
  },
  Unhandled () {
    res.ask.call(this, res.welcomeUnhandled(), res.welcomeUnhandled())
  }
}))

module.exports.lodge = Alexa.CreateStateHandler(APP_STATES.LODGE, mixinHandlers(coreHandlers, {
  NewSession () {
      res.ask.call(this, res.lodge())
  },
  OtherOptionsBIntent () {
    res.ask.call(this, res.OtherOptionsB())
  },
  Unhandled () {
    res.ask.call(this, res.lodgeUnhandled(), res.lodgeUnhandled())
  }
}))
```

**Comment by bclement-amazon** [comment]
Hey @dly9014 ,

This is a great suggestion - passing a list of 'hints' to the ASK service that you'd like to be considered. 
As a skill developer, I'd love a feature like this -- and i've passed this feedback along to the team responsible for this engine.

I'm closing this issue for now.
