### ISSUE TITLE
Could not save item to table: Missing region in config

### ISSUE THREAD

**Issue by danjohnson95** [alexa/alexa-skills-kit-sdk-for-nodejs#384]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I'm using Webpack to compile my lambda, but I'm having trouble using the persistent adapter to store data in DynamoDB.

My deployment process involves compiling Typescript to commonJS, and then uploading the output to an S3 bucket with an incremented version number. I then point the lambda to grab the latest version from the S3 bucket. The outputted file is one single file which includes required dependencies.

## Expected Behavior

A table should be created if it doesn't already exist, and data should be stored after `.savePersistentAttributes()` is resolved.

## Current Behavior

I'm receiving an error related to a missing region in the config file:

> Could not save item (...) to table (exampleTableName): Missing region in config

Here's my entry file, where I'm specifying the table name:

```javascript
import * as Alexa from 'ask-sdk'

exports.handler = Alexa.SkillBuilders
    .standard()
    .addRequestHandlers(
        // omitted for brevity
    )
    .withTableName('exampleTableName')
    .withAutoCreateTable(true)
    .lambda()
```

and a part of my code which is responsible for storing the attributes

```javascript
this.attributesManager.setPersistentAttributes({
    exampleData: 'foo'
})

this.attributesManager.savePersistentAttributes()
```

Full code for my project is available here:
https://github.com/danjohnson95/ring-of-fire-alexa

## Possible Solution

I tried importing the `aws-sdk` library, and specifying the region with the following code in my entry file:

```javascript
import * as aws from 'aws-sdk'

aws.config.update({
    region: 'eu-west-1'
})
```

This gave me a new error message - 

> Could not save item (...) to table (exampleTableName): Missing credentials in config

But from reading example material, I can't see anywhere where region and credentials are being passed into the lambda code. 

I'm assuming they're maybe being set somewhere when deploying using the `ask cli`? If so, where can I set these settings without the `ask cli` deployment method?

## Your Environment

* ASK SDK for Node.js used: 2.0.4
* ASK DynamoDB Persistence Adapter: 2.0.4
* Webpack: 4.8.1
* Operating System and version: macOS 10.13.4

## Node.js and NPM Info
* Node.js version used for development: 8.10.0
* NPM version used for development: 5.6.0

**Comment by dustincoates** [comment]
@danjohnson95 you can pass in a custom DynamoDB client with the region specified:

```javascript
exports.handler = Alexa.SkillBuilders.standard()
  .addRequestHandlers(
    LaunchRequestHandler,
    Unhandled
  )
  .withSkillId(skillId)
  .withTableName("exampleTableName")
  .withAutoCreateTable(true)
  .withDynamoDbClient(
    new AWS.DynamoDB({ apiVersion: "latest", region: "us-east-1" })
  )
  .lambda();
```

**Comment by danjohnson95** [comment]
**Update**

I've been playing around with my webpack config file. I've just added in the following line:

```json
target: 'node
```

which is giving me a different error message! :tada:

I'm now getting:

> Could not save item (...) to table (exampleTableName): Requested resource not found

The table doesn't exist yet, but I was hoping `.withAutoCreateTable(true)` would take care of that

**Comment by danjohnson95** [comment]
Thanks @tianrenz.

For anyone interested, here's my `webpack.config.ts` file.

```typescript
import * as path from 'path'

module.exports = {
    mode: process.env.mode,
    entry: './index.ts',
    output: {
        path: path.resolve(__dirname, 'dist'),
        filename: 'handler.js',
        library: 'handler',
        libraryTarget: 'commonjs2'
    },
    target: 'node',
    resolve: {
        extensions: ['.ts', '.js']
    },
    module: {
        rules: [
            { test: /\.ts$/, use: 'ts-loader' }
        ]
    }
}
```
