### ISSUE TITLE
Manually redirecting in code flow in v2

### ISSUE THREAD

**Issue by alekslyse** [alexa/alexa-skills-kit-sdk-for-nodejs#385]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Since the change from v1 to v2 it seems to me it changed from an emit to a pure class with promises. Im just trying to wrap my head around this, but I cant find anything in the doc.

-> Alexa request towards a intent -> a function intercept to check if the user can use the intent / if everything is ready -> if yes, go on - > if no, manually trigger another intent / dialog instead of asking the user to ask for this and that.

Is this possible in v2? (in other words how to stop and redirect the flow in an interceptor)

**Comment by TianTXie** [comment]
@alekslyse, 
 In v1, the SDK uses event emitter to dispatch the request to corresponding handle function. Inside the handle function, you can also use event emitter to call other handle functions.
In v2, it’s a one-shot process. Each request handler has a canHandle and handle function. When the skill receives a request, it’ll call canHandle functions of all request handlers registered in skill and dispatches to the request handler whose canHandle returns true. Inside the handle function you can not forward the request to other request handler. You can register a request handler that can handle multiple intents to avoid forwarding request.

**Comment by alekslyse** [comment]
@TianTXie  But why is the "addRequestInterceptors" (process function) resolved after the canHandle function in the intents? If I add a request interceptor, add something to handlerInput, then should it not be the logical thinking that canHandle run after the interceptor, not before?

Say for example if I just want to change intent->name to something else or add a persistant attribute in the interceptor, before the intents, thats not possible cause of order of execution?

**Comment by tianrenz** [comment]
Hi @alekslyse ,

Yes. We are aware of the broken behavior of interceptors. We've already issued a #389. Once that's reviewed and approved, we will issue a new release. 

Regards

**Comment by tianrenz** [comment]
@alekslyse Great! The update has been release to NPM. You can update now and pull the latest code. 

Regards
