### ISSUE TITLE
Run Code on Session Start

### ISSUE THREAD

**Issue by seanfisher** [alexa/alexa-skills-kit-sdk-for-nodejs#39]
Is there a way to run code when a session has started? I understand there's a `NewSession` handler, but it seems mutually exclusive with any other handler and intercepts any intent requests.

For example, let's say somebody launches my skill with `Alexa, tell {MyApp} {SomeIntent}`. This is both a new session and an intent request. I'd like to execute code to initialize an analytics SDK only when a session is started regardless of whether or not it is an intent request (e.g. in the case of a `LaunchRequest` as well), and then continue on processing the intent request or the `LaunchRequest` like normal.

**Comment by deegles** [comment]
You can initialize before you call `alexa.execute()` in your Lambda event handler.

For example:
```javascript
var Alexa = require('alexa-sdk');
exports.handler = function(event, context) {
    var alexa = Alexa.handler(event, context);
    initialize(() => {
        alexa.execute();    
    });
}

function initialize(callback) {
    // initialize your SDK here
    callback();
}
```

Lambda is stateless, so two requests from a single user's session may go to different containers. You shouldn't rely on checking if the session is new if you're going to depend on the SDK on subsequent requests. You can cache your SDK after initializing to conserve resources.

**Comment by seanfisher** [comment]
Yes, sorry, I should be more clear. I'm not concerned about running when the *Lambda* session is new, but only when a request comes in from Alexa with the `session.new` variable set to `true`. Running the code as you've shown here will run the `initialize` function on every new Lambda request, which is not what I'm looking for.

**Comment by deegles** [comment]
In that case, you can easily check the `new` session attribute in the incoming request.

```javascript
var Alexa = require('alexa-sdk');
exports.handler = function(event, context) {
    var alexa = Alexa.handler(event, context);
    initialize(event, () => {
        alexa.execute();    
    });
}

function initialize(event, callback) {
    if(event.session['new']){
        // initialize your SDK here
    }
    callback();
}
```

You can see the JSON interface reference [here](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference).

**Comment by seanfisher** [comment]
OK, that looks like it will work, thanks. What's the relationship between the special `NewSession` handler and doing something like this?

**Comment by deegles** [comment]
`NewSession` can be defined to have different behavior depending on the current state, or can be skipped altogether. The above would run on all requests.

**Comment by deegles** [comment]
Just out of curiosity, what analytics SDK are you using?

**Comment by seanfisher** [comment]
OK, so I ended up checking the `session.new` as your second example demonstrates. I'm using VoiceLabs.co for the analytics.
