### ISSUE TITLE
Provide example / feature to show what permissions a user has enabled for a skill

### ISSUE THREAD

**Issue by kev2480** [alexa/alexa-skills-kit-sdk-for-nodejs#390]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ X ] Feature request
[ X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Trying to figure out how to pick out what permissions a user has enabled inside the skill. I.e. if they have enabled device address access but not the lists write access. Is there a way to individually pick out what has and hasn't been enabled inside the skill code? Want to do this so I can then send a `withAskForPermissionsConsentCard` to ask the user to enable the missing permission. 

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by jonnedeprez** [comment]
I would also find this very useful. There currently seems to be no other way than to try out the happy path, assuming that permissions were granted, and catching the error when it doesn't work. Such code is not elegant and even slows down the dialogue because of the additional request.

**Comment by sungolivia** [comment]
Hey there, sorry to keep you all waiting, I will bring this back to the team for discussion and let you know of any update!

**Comment by tianrenz** [comment]
Hi, 

Currently, there's no option to retrieve the permission status without pinging the service API. This would be a service side implementation not related to the SDK. We would recommend to post this on the [Alexa User Voice Forum](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote) to gain more feedback from the community. 

Regards
