### ISSUE TITLE
Alexa Skills Kit: How to call custom intent from another intent in ASK sdk V2

### ISSUE THREAD

**Issue by cbothra** [alexa/alexa-skills-kit-sdk-for-nodejs#391]
Hi I have been using and developing skills on Alexa since quite few months. Recently I updated to the ask sdk version 2. I find everything cool and stuck nowhere.

I couldn't find a way to emit an intent now. Like earlier we were able to call Intent from another Intent in following manner:

`this.emitWithState(<intent name here>);`

Anybody know how to achieve this in ask sdk V2?

Any help would be highly appreciated.

**Comment by allthepies** [comment]
It's a completely different approach to how intents are handled.  You need to rethink the structure of your code, or use the v1Adapter to allow your "old world" code to work.

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/ASK-SDK-Migration-Guide

**Comment by tianrenz** [comment]
Hi @cbothra , 

In v1, since we attach everything in the function context(though `this`), we introduce the `emitWithState` to help you invoke another handler with necessary function context. 

In v2, we attach all necessary input through the `HandlerInput` parameter. so a more 'traditional' functional programming way would be more suited. You can simply just import the target handle function (if it's in a different module) or just invoke the it directly and pass in the `handlerinput`. For example

```javascript
const fooHandler = {
    canHandle(input) {
        ....your logic
    },
    handle(input) {
        // invoke another handler
        return barHandler.handle(input);
    }
}
```

**Comment by brendanclement** [comment]
This comment may also help -- https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/408#issuecomment-397028721

**Comment by tianrenz** [comment]
HI @fluxquantum , 

The event request received by your skill can only be triggered by user utterances.

For the sample usage you described, the setup would be something like

'GetDateIntent' -> Handler returns a response that ask for date input -> user answer with date -> 
'MyDateIntent' -> Handler reads the date information and proceed with skill logic. 

Regards

**Comment by fluxquantum** [comment]
Thanks for explaining tianrenz. So then the approach you described to cbothra only makes sense if you know what follow up handler/ intent you want to subsequently trigger ahead of time?

**Comment by cbothra** [comment]
Hi @fluxquantum ,

As tianrenz said, it will definitely make sense only if you know what follow up handler / intent you want to subsequently trigger ahead of time. 

Besides that you can come to know what follow up handler / intent ahead of time based on user's utterance. Now lets say you have two very similar intents which can get triggered based on users utterance you can use **state** **management** .
