### ISSUE TITLE
Setting Up The ASK SDK

### ISSUE THREAD

**Issue by StarfighterJ** [alexa/alexa-skills-kit-sdk-for-nodejs#394]
I was really lost on this until I found out you needed a package.json first before this would work:
using npm init and npm install. for new beginners like me I think you should add this in your steps.

**Comment by nikhilym** [comment]
Hey @StarfighterJ , thanks for letting us know. Do you mind contributing to the docs by sending out a PR with the expected steps?

**Comment by robm26** [comment]
Hi @StarfighterJ 
I was having similar issues.  While it is recommended to run "npm init" to setup a package.json for your project, it is not required.  If the command "npm install ask-sdk" is not saving the module to your node_modules folder, check all the parent folders and see if any of them defines a package.json or node_modules.  NPM will try and add to those first.

**Comment by tianrenz** [comment]
Hi @StarfighterJ , 

I've added the relevant link to the github wiki. Thanks for letting us know!

Regards
