### ISSUE TITLE
No handler event fired when the cancel button is pressed in the android app

### ISSUE THREAD

**Issue by e-compton** [alexa/alexa-skills-kit-sdk-for-nodejs#396]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
AMAZON.SessionEndedRequest is fired when the cancel button is pressed in the android app.

## Current Behavior
I cannot seem to find an event that is fired when the user presses the cancel button in the android app when halfway interacting with my skill.

It would make sense for the AMAZON.SessionEndedRequest to be fired here.

## Steps to Reproduce (for bugs)
Open up android app
Start custom skill that emits `:ask`
When alexa begins listening for response press the X button.
(no event is emitted on this click)

## Context
We need this feature so that we can cleanup session information stored in `this.attributes` ready for the next invocation of the skill. 

## Your Environment
Alexa-sdk 1.0.25

## Node.js and NPM Info
Node,js 8.9.4
NPM 6.0.1

**Comment by tianrenz** [comment]
Hi @e-compton 

This seems to be a non-SDK related issues. We would recommend to post on [Alexa user voice forum](https://forums.developer.amazon.com/spaces/165/index.html). 

Regards
