### ISSUE TITLE
Outdated Documentation

### ISSUE THREAD

**Issue by westlakem** [alexa/alexa-skills-kit-sdk-for-nodejs#397]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Documentation should follow the V2 specs

## Current Behavior
Most of the documentation is still V1, and useless

## Possible Solution

Update the docs

**Comment by nikhilym** [comment]
Hey @westlakem , Can you point out which document is still V1 and leading to problems?

**Comment by westlakem** [comment]
basically anything that still has `emit`

**Comment by tianrenz** [comment]
Hi @westlakem , 

Could you attach the link where you see the outdated documentation? The [readme](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/README.md) and [wiki](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki) for v2 SDK has been updated. 

Regards

**Comment by westlakem** [comment]
I don't have a time to do an exhaustive search, but looked at my history from the day I posted that, and could easily point out 2 places that AWS was responsible for.  There's a lot if information on 3rd party websites that Amazon doesn't control, but the blueprints, docs, and blogs Amazon does.

The blog announcement for alexa-skills-kit:
https://developer.amazon.com/blogs/post/Tx213D2XQIYH864/announcing-the-alexa-skills-kit-for-node-js

Almost all (if not all) the node blueprints that are recommended.  These skills are listed in multiple places, but one of the sites is:
https://developer.amazon.com/docs/custom-skills/host-a-custom-skill-as-an-aws-lambda-function.html
