### ISSUE TITLE
ValidationError loading data from DynamoDB

### ISSUE THREAD

**Issue by febbraro** [alexa/alexa-skills-kit-sdk-for-nodejs#4]
On my first request the dynamodb table is created successfully, but one each subsequent request to my service i get an error with the following message:

> Error fetching user state: ValidationException: The provided key element does not match the schema

Here is the CloudWatch Log.

```
{
    "message": "The provided key element does not match the schema",
    "code": "ValidationException",
    "time": "2016-07-25T20:52:59.605Z",
    "requestId": "AR03L7713TK9HP5QEVK6GFO8U7VV4KQNSO5AEMVJF66Q9ASUAAJG",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 0
}
```

This is simply when testing the Start New Session event via Lambda.

**Comment by febbraro** [comment]
Turns out that userId is null.

```
{
    "Key": {
        "userId": null
    },
    "TableName": "XXXXXXX",
    "ConsistentRead": true
}
```

digging further

**Comment by deegles** [comment]
Are you using the Lambda test events? The default templates use 'null'. Try using any other string value.

**Comment by febbraro** [comment]
Yep, that was it. Sorry to think out loud here. Configured the userId in the test template and it works.  Hopefully someone can find this issue, I will also submit a PR to update the docs with this information.
