### ISSUE TITLE
Getting a "Process exited before completing request" when querying a mysql database

### ISSUE THREAD

**Issue by MatthiasPetersen** [alexa/alexa-skills-kit-sdk-for-nodejs#400]
Hi,
I'm doing a small mysql database query. When it's okay, Alexa should say "Success".  I'm sure that the database access is correct, but the lamdba function is always writing a "Process exited before completing request" in the log.

Here's my code (using the current version of the sdk):

let speechOutput = "Emtpy Answer";
"use strict";
const Alexa = require('alexa-sdk');
var mysql = require('mysql');
var config = require('./config.json');
var conn  = mysql.createConnection({
    host     : config.dbhost,
    user     : config.dbuser,
    password : config.dbpassword,
    database : config.dbname
  });
var result;
const handlers = {
	'GetDealIntent': function () {

        console.log("1");
        conn.connect(function(err) {
            if (err) throw err;
            con.query("select 1", function (err, result, fields) {
              if (err) throw err;
              console.log("2.1");
              speechOutput = "Success";
              this.response.speak(speechOutput);
              console.log("2.2");
            });
          });

          console.log("3");
          this.emit(":responseReady");
          console.log("4");
          }
    };

exports.handler = (event, context) => {
    const alexa = Alexa.handler(event, context);
    alexa.appId = APP_ID;
    alexa.registerHandlers(handlers);
    alexa.execute();
};

Can you help me, please?
Thanks
Matthias

**Comment by tianrenz** [comment]
Hi @MatthiasPetersen , 

When using any of the `this.emit()` or `this.response` inside the callback function, could you verify that the context of the function has been setup correctly? `this` in a handler would carry all of the sdk features. But when switching function context, those attached properties might be lost and ended up returning no response. 

Besides, have you checked that the connection time to database is lower than the timeout settings of the lambda function?

Regards

**Comment by MatthiasPetersen** [comment]
Hi tianrenz,
thanks for your answer. I've already found a solution: Connecting the database in a synchronous call and just querying the database in a callback function. This works finde.

Regards
Matthias
