### ISSUE TITLE
Wrapping .lambda() call

### ISSUE THREAD

**Issue by dannolan** [alexa/alexa-skills-kit-sdk-for-nodejs#402]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I've migrated an Alexa Skill I've built to the v2 Typescript SDK and I'm absolutely loving it. I'm using the serverless framework currently and exporting the skill using the .lambda() call on the skillbuilder. I was wondering is there any way I can wrap the skill's lambda handler in another function? The rationale for that is I'd like to use a warmup handler on my lambda endpoint so the skill is really responsive but in doing this I get the following issue

<code>
{
    "errorMessage": "Cannot read property 'System' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "Skill.<anonymous> (/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:97:1)",
        "step (/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:44:1)",
        "Object.next (/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:25:45)",
        "/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:19:1",
        "__awaiter (/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:15:1)",
        "Skill.invoke (/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/Skill.js:78:1)",
        "/var/task/webpack:/node_modules/ask-sdk-core/dist/skill/factory/BaseSkillFactory.js:171:1",
        "invoke (/var/runtime/node_modules/awslambda/index.js:285:5)",
        "InvokeManager.start (/var/runtime/node_modules/awslambda/index.js:151:9)"
    ]
}
</code>

I'd love to be able to intercept the request and bail out early if possible. Food for thought!

## Your Environment

* ASK SDK for Node.js used: 2.0.4

## Node.js and NPM Info
* Node.js version used for development: Node 6.10
* NPM version used for development: (Yarn 1.70

**Comment by tianrenz** [comment]
Hi @dannolan , 

`skill.lambda()` function returns another function that that takes in a `RequestEnvelope` that has a shape as shown on this [page](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-body-syntax).  
Please make sure that the warmup function is invoking the function with the correct parameters.

Regards

**Comment by dannolan** [comment]
@tianrenz  thank you
