### ISSUE TITLE
ask-sdk-v1adapter suggest removing 'Unhandled': function() from code.

### ISSUE THREAD

**Issue by HugoCatch** [alexa/alexa-skills-kit-sdk-for-nodejs#404]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

ask-sdk-v1adapter 
suggest if a user has an 'Unhandled': function() in original code to remove this, otherwise the Unhandled function always gets called instead of the new code. 
At least that was the issue I had.

**Comment by tianrenz** [comment]
Hi @HugoCatch , 

Thanks for your help! I've updated the wiki doc to include the changes. 

Regards

**Comment by fluxquantum** [comment]
Hello, if we can't use an unhandled function from ask-sdk-v1, what's the alternative for v2?

**Comment by tianrenz** [comment]
Hi @fluxquantum ,

Please see this [handler](https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/lambda/custom/index.js#L144) which does the exact same thing as the `Unhandled` in v1.  Please note that you need to register this handler at last (see [here](https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/lambda/custom/index.js#L267)) to avoid it intercepting any other handlers. 

Regards
