### ISSUE TITLE
progressive response is not progressive

### ISSUE THREAD

**Issue by alrouen** [alexa/alexa-skills-kit-sdk-for-nodejs#406]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report 
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When sending a progressive response (https://developer.amazon.com/docs/custom-skills/send-the-user-a-progressive-response.html) is a lambda function (nodejs 8.x + ask-sdk-core 2.0.5), I'm expecting Alexa to send a response (i.e. : ok please wait...) before executing an async/long running action (i.e.: sleep, calling another ) and finally giving a final response.

## Current Behavior
The progressive response is not sent before executing the next promise running task but:
- after the execution of all promises
- but the order of speech actions remain good

So if your handler behavior is the following:
- await progressive response : "please wait"
- await sleep 5s
- return final response "remote service answer is xxxx"

You expect to ear:
- "please wait"
- 5s of nothing
- "remote service answer is xxxx"

You will ear:
- 5s of nothing
- "please wait"
- "remote service answer is xxxx"

## Steps to Reproduce (for bugs)

This bug can be reproduced by using the sample code from the Alexa cookbook.

- sample code available here : https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-progressive-response
- Using the alexa console (https://developer.amazon.com/alexa/console/ask) to setup the skill
- create the lambda function with source code from: https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-progressive-response/lambda/custom
- configure the skill to use the lambda
- Invoke the skill with the alexa console in test mode

## Context
Building an Alexa skill that have to deal with async task. Big impact on user experience if not fixed.

## Your Environment
* ASK SDK for Node.js used: 2.0.5 or ASK SDK Core / mode for Node.js used: 2.0.5 / 1.3.0
* AWS Lambda for Node.js 8.10

## Node.js and NPM Info
* Node.js version used for development: 8.10

**Comment by alrouen** [comment]
I got a response from the Alexa support team explaining me that this is the expected behavior when testing the skill using the alexa console.

But I also get the same behavior from the device.

**Comment by sgmbh** [comment]
I have the same problem... After the spoken command the echo spot is silent for 3-4 seconds an then speaks the "please wait" & "finished successfully" just after each other. It's like one response.

**Comment by lucas-rudd** [comment]
Is there any update on this? We've run into this issue when testing our new Skill and it is a serious roadblock for us. In theory the progressive response API sounds like a game-changer; but, we've experienced the same issue reported above in both the simulator and on an echo dot.

**Comment by tianrenz** [comment]
Hi all, 

Sorry kept you all waiting. I tested this with a sample hello world skill and have no issue with the response order. Below are the code sample i used. 

```javascript
const HelloWorldIntentHandler = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'IntentRequest'
      && handlerInput.requestEnvelope.request.intent.name === 'HelloWorldIntent';
  },
  async handle(handlerInput) {
    const speechText = 'Hello World!';

    await callDirectiveService(handlerInput);

    return new Promise((resolve, reject) => {
      setTimeout(() => {
        const response = handlerInput.responseBuilder
                        .speak(speechText)
                        .withSimpleCard('Hello World', speechText)
                        .getResponse();
        resolve(response)
      }, 3000);
    })
  },
};

function callDirectiveService(handlerInput) {
  // Call Alexa Directive Service.
  const requestEnvelope = handlerInput.requestEnvelope;
  const directiveServiceClient = handlerInput.serviceClientFactory.getDirectiveServiceClient();

  const requestId = requestEnvelope.request.requestId;
  const endpoint = requestEnvelope.context.System.apiEndpoint;
  const token = requestEnvelope.context.System.apiAccessToken;

  // build the progressive response directive
  const directive = {
    header: {
      requestId,
    },
    directive: {
      type: 'VoicePlayer.Speak',
      speech: `this is a test speech`,
    },
  };

  // send directive
  return directiveServiceClient.enqueue(directive, endpoint, token);
}
```
Please make sure you are testing this on an physical alexa device. The test console on developer portal doesn't support progressive response at the moment. 

Regards

**Comment by artemkovalyov** [comment]
@tianrenz, your solution worked for me. Thank you very much for testing as it's lacking from the docs, how to use this part of SDK. By the way, in web testing tool it was fine as well.

**Comment by nikhilym** [comment]
Thanks for confirming @artemkovalyov !!

@alrouen , @sgmbh , @lucas-rudd did you guys try it out with @tianrenz's code-snippet? Please update the issue with your findings!!

**Comment by sgmbh** [comment]
My skill is based on ASK SDK v1. Is it possible that the progressive response only works with the v2 request handler interface? Or have I made a mistake in my code? 
I tested this with the online tool from amazon and with my real echo spot. Everything works, only the progressive response is to late. The behaviour is exactly like alrouen said: 

- some seconds of nothing
- "please wait"
- "my ping message"

Thanks for your help!

    'MyIntent': function () {
        .....
        callDirectiveService(this.event)
        .....
        apiRequestService.send(this.event.session.user.accessToken, '/api/devices/Ping')
            .then((success) => {
                const speechOutput = PING_MESSAGE;
                this.response.cardRenderer(SKILL_NAME, PING_MESSAGE);
                this.response.speak(speechOutput);
                this.emit(':responseReady');
            })
            .catch((err) => {
                const speechOutput = ERROR_MESSAGE;
                const reprompt = HELP_REPROMPT;
                this.response.cardRenderer(SKILL_NAME, ERROR_MESSAGE);
                this.response.speak(speechOutput).listen(reprompt);
                this.emit(':responseReady');
            });
    },

.....

    function callDirectiveService(event) {
	// Call Alexa Directive Service.
	const ds = new Alexa.services.DirectiveService();
	const requestId = event.request.requestId;
	const directive = new Alexa.directives.VoicePlayerSpeakDirective(requestId, WAIT_MESSAGE);
	const endpoint = event.context.System.apiEndpoint;
	const token = event.context.System.apiAccessToken;
	return ds.enqueue(directive, endpoint, token);
    };

**Comment by tianrenz** [comment]
Hi @sgmbh ,

``callDirectiveService(event)`` returns a ``Promise``. So you need to put your following code in the ``then((data) => {})`` to ensure the correct execution order. 

Regards

**Comment by tianrenz** [comment]
Hi all, 

Closing this issue. Please reference the solution posted above.

Regards

**Comment by sgmbh** [comment]
Hi @tianrenz,
I should have thought of that myself. Thanks a lot! It works now.
Regards

**Comment by artemkovalyov** [comment]
@tianrenz, @nikhilym, could it be SDK related that invoking VoicePlayerSpeakDirective Alexa returns an exception despite playing the message?

`2018-09-05T15:22:10.570Z	751c4730-b11f-11e8-9e90-1b49e9134a79	(node:1) UnhandledPromiseRejectionWarning: ServiceError: The skill is not allowed to send directives at the moment.
    at DirectiveServiceClient.<anonymous> (/var/task/node_modules/ask-sdk-model/index.js:148:35)
    at step (/var/task/node_modules/ask-sdk-model/index.js:42:23)
    at Object.next (/var/task/node_modules/ask-sdk-model/index.js:23:53)
    at fulfilled (/var/task/node_modules/ask-sdk-model/index.js:14:58)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)`

I can't combine `Promises` because of this exception.

Here is my DirectiveService:
import * as Alexa from 'ask-sdk'
` 
const callDirectiveService = (handlerInput, message) => {
  // Call Alexa Directive Service.
  const requestEnvelope = handlerInput.requestEnvelope
  const directiveServiceClient = handlerInput.serviceClientFactory.getDirectiveServiceClient()
 
  const endpoint = requestEnvelope.context.System.apiEndpoint
  const token = requestEnvelope.context.System.apiAccessToken
  const requestId = requestEnvelope.request.requestId
  const directive = new Alexa.directives.VoicePlayerSpeakDirective(
    requestId,
    message
  )
  
  // build the progressive response directive
  // const directive = {
  //   header: {
  //     requestId,
  //   },
  //   directive: {
  //     type: 'VoicePlayer.Speak',
  //     speech: message
  //   }
  // }
 
  // send directive
  return directiveServiceClient.enqueue(directive, endpoint, token)
}
export default callDirectiveService
`
Here is how I invoke it now. Alexa plays the message but returns an exception which makes it impossible to use this for the actual purpose it was created.
`
try {
      await callDirectiveService(
        handlerInput,
        `Got you! I need a bit of time to load the most recent 7 days of your stats.`
      )
    } catch (error) {
      console.error(error)
    }
`

Have anyone had this problem and knows how to solve it?

**Comment by tianrenz** [comment]
Hi @artemkovalyov ,

We are aware of the indeterministic behavior. In our testing, the scenario described would happen randomly.  Unfortunately, there's no clear reason as for what triggers it. We believe it could be a service issue, not SDK related. We would recommend to report this on [Alexa developer forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html).

Regards

**Comment by jimenaCabrejas** [comment]
Hi,

Do you know if this solution should work on the Amazon Alexa Android App? I tried @tianrenz example skill but I got the problem described above. It waits for 3 seconds then says this is a test speech and hello world just after each other.

Thanks and regards

**Comment by Junot-Jean** [comment]
hi? i'm having the same issue, i've been trying to solve it with @tianrenz code but nothing changes.
