### ISSUE TITLE
Long Compilation on AWS Lambda

### ISSUE THREAD

**Issue by cnpants** [alexa/alexa-skills-kit-sdk-for-nodejs#416]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Context
Im trying to compile it now on AWS Lambda, it takes very long to 'Save' it.

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by tianrenz** [comment]
Hi @cnpants , 

How big is the zipped pacakge size? The saving time would become longer as the size of the package grows. I would recommend to upload your code package to S3 and use s3 as the source for lambda. 

Regards

**Comment by cnpants** [comment]
It is about 5MB. Yup its really long and gets timeout. However, I shortened it by not installing not required packages.
