### ISSUE TITLE
Can't get slot id from intent

### ISSUE THREAD

**Issue by annedroiid** [alexa/alexa-skills-kit-sdk-for-nodejs#418]
I'm having issues getting the slot id from my intent. For the life of me I cannot figure out how to access it, and I cannot find any documentation on accessing it either.

Here is the request that is getting passed to my skill

```
"request": {
  "type": "IntentRequest",
  "requestId": "amzn1.echo-api.request.5222c9ac-3b6e-461c-8909-15f20a782f97",
  "timestamp": "2018-06-24T10:27:49Z",
  "locale": "en-GB",
  "intent": {
    "name": "RecipeIntent",
    "confirmationStatus": "NONE",
    "slots": {
      "RecipeName": {
        "name": "RecipeName",
        "value": "strawberry macaron",
        "resolutions": {
          "resolutionsPerAuthority": [
            {
              "authority": "amzn1.er-authority.echo-sdk.amzn1.ask.skill.531c3e51-40e3-4ea1-b7a6-ed915039e2d7.RecipeName",
              "status": {
                "code": "ER_SUCCESS_MATCH"
              },
              "values": [
                {
                  "value": {
                    "name": "strawberry macaron",
                    "id": "StrawberryMacarons"
                  }
                }
              ]
            }
          ]
        },
        "confirmationStatus": "NONE"
      }
    }
  }
}
```

I have tried all of the below and none of them work.

```
this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority.values.value.id
this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority[].values.value.id;
this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority[0].values.value.id;
this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority[1].values.value.id;

```

I can get the value fine using `this.event.request.intent.slots.RecipeName.value;`, but since when it gets synonyms it returns the synonym and not the main value itself I want to use the ID as it will be consistent across all synonyms.  I'm normally a Scala developer not a Javascript one so I'm not sure if I'm just messing up the JS syntax or what is happening (which is why I tried a bunch of different syntaxes that I didn't really expect to work) but I just cannot figure this out. 

I'm running my code on AWS Lambda with Node.js 6.10.

**Comment by tianrenz** [comment]
Hi @annedroiid , 

The `request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority.values` is an array. So you can access the slot id with the following code:

```
this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority[0].values[0].value.id;
``` 

Regards

**Comment by warhost** [comment]
@annedroiid Got a fair point here, because 

`this.event.request.intent.slots.RecipeName.resolutions.resolutionsPerAuthority[0].values[0].value.id;`

doesn't cut it. For example, I am getting this as request:

```
"gender": {
	"name": "gender",
	"value": "frau",
	"resolutions": {
		"resolutionsPerAuthority": [
			{
				"authority": "...",
				"status": {
					"code": "ER_SUCCESS_NO_MATCH"
				}
			},
			{
				"authority": "...",
				"status": {
					"code": "ER_SUCCESS_MATCH"
				},
				"values": [
					{
						"value": {
							"name": "female",
							"id": "female"
						}
					}
				]
			}
		]
	},
	"confirmationStatus": "NONE"
},
```
So here the `id` is in `resolutionsPerAuthority[1]`.

**Comment by tianrenz** [comment]
Hi @warhost ,

I think the issue @annedroiid posted here is about retrieving slot id from a fixed response type. When you are dealing with entity resolution, you should try to scan through the resolutionsPerAuthority and identify the one with success match. See this example [here](https://github.com/alexa/skill-sample-nodejs-decision-tree/blob/master/lambda/custom/index.js#L58). 

Regards

**Comment by warhost** [comment]
@tianrenz Thanks, still this is weird, since as of this morning I am not getting the empty `ER_SUCCESS_NO_MATCH` in `resolutionsPerAuthority[0]` anymore, only the `ER_SUCCESS_MATCH`, for which my usual function for retrieving the slot values works again. I don't know what was going on there, but if I am not mistaking, `ER_SUCCESS_NO_MATCH` should not be in `resolutionsPerAuthority[0]` if there is a clear match right?

Btw, my function for getting the slotvalues taken from one of the examples:

```
function getSlotValues(filledSlots) {
	const slotValues = {};

	Object.keys(filledSlots).forEach((item) => {
		const { name } = filledSlots[item];

		if (filledSlots[item]
			&& filledSlots[item].resolutions
			&& filledSlots[item].resolutions.resolutionsPerAuthority[0]
			&& filledSlots[item].resolutions.resolutionsPerAuthority[0].status
			&& filledSlots[item].resolutions.resolutionsPerAuthority[0].status.code) {
			switch (filledSlots[item].resolutions.resolutionsPerAuthority[0].status.code) {
				case 'ER_SUCCESS_MATCH':
					slotValues[name] = {
						synonym: filledSlots[item].value,
						resolved: filledSlots[item].resolutions.resolutionsPerAuthority[0].values[0].value.name,
						id: filledSlots[item].resolutions.resolutionsPerAuthority[0].values[0].value.id,
					};
					break;
				case 'ER_SUCCESS_NO_MATCH':
					slotValues[name] = {
						synonym: filledSlots[item].value,
						resolved: filledSlots[item].value,
					};
					break;
				default:
					break;
			}
		} else {
			slotValues[name] = {
				synonym: filledSlots[item].value,
				resolved: filledSlots[item].value,
			};
		}
	}, this);
	return slotValues;
}
```

**Comment by tianrenz** [comment]
Hi @warhost , 

I would recommend checking out this [link](https://developer.amazon.com/blogs/alexa/post/cfbd2f5e-c72f-4b03-8040-8628bbca204c/alexa-skill-teardown-understanding-entity-resolution-with-pet-match). 

Furthermore, we are balancing the workload of issues and PR on the SDK repository. For non SDK related issues (bugs, things not working, etc), please post on [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/index.html). 

Regards
