### ISSUE TITLE
lambda handler for heroku

### ISSUE THREAD

**Issue by cnpants** [alexa/alexa-skills-kit-sdk-for-nodejs#419]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Request
Is there a way I can host this on my Heroku app as an endpoint and not the AWS Lambda?

**Comment by tianrenz** [comment]
Hi @cnpants , 

This is a non-SDK related issue. We would recommend to post in Alexa Developer Forum (see [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/426)) to get more input from the community. 

Regards
