### ISSUE TITLE
How to call a different intent with a slot value?

### ISSUE THREAD

**Issue by mrtj** [alexa/alexa-skills-kit-sdk-for-nodejs#42]
I understand that I can call a different intent handler using `this.emit('OtherIntent');` inside the original handler. If the other intent handler expects a slot value, how can I call it with a specific value? I would expect something like `this.emit('OtherIntentWithSlots', { 'slotName' : 'slotValue' });`. Is this possible?

**Comment by deegles** [comment]
When you call a different intent handler, the slots and slot values for the original intent handler will remain the same. You can pass new parameters inside the emit (as you are doing above) but they will not overwrite the original slot values. 

Keep in mind that `this.emit` might not use the correct state, use `this.emitWithState` to call handlers in the current state defined in `this.handler.state`

e.g

```javascript
'Intent' : function() {
    this.emit('OtherIntent', 'someValue');
},
'OtherIntent': function(value) {
    console.log(value) // prints 'someValue'
}
```

**Comment by mrtj** [comment]
Thank you, it adds some overhead in the code (I should check both for slot values and eventual function parameters), but I think I can leave with it. I also did not know about emitWithState. By the way, do you have a complete reference documentation somewhere?

**Comment by bclement-amazon** [comment]
Closing
tracking API documention in issue #66
