### ISSUE TITLE
[please forward] ask-cli shows `ExperimentalWarning: The fs.promises API is experimental`

### ISSUE THREAD

**Issue by hideokamoto** [alexa/alexa-skills-kit-sdk-for-nodejs#422]
Hi.
I can't find any good place to report about `ask-cli` issues.
Could you forward the ticket to `ask-cli` team ?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

All command should not show any warning.

```
$ ask util

  Usage: ask-util 

  $ ask util [command]

  Util functions to manage the life cycle of Alexa Skills.

  Options:

    -h, --help                     output usage information

  Commands:

    generate-lwa-tokens [options]  generates LWA tokens from 3p clientId and clientCredentials
```

## Current Behavior
`ask-cli` shows `ExperimentalWarning` at first line.

```
$ ask util
(node:35788) ExperimentalWarning: The fs.promises API is experimental

  Usage: ask-util 

  $ ask util [command]

  Util functions to manage the life cycle of Alexa Skills.

  Options:

    -h, --help                     output usage information

  Commands:

    generate-lwa-tokens [options]  generates LWA tokens from 3p clientId and clientCredentials
```

## Possible Solution

I think we should update `fs-extra` package to `6.0.1` or later.
https://github.com/jprichardson/node-fs-extra/pull/578#issuecomment-388533580

I've fixed issue by following actions.

```
$ cd /usr/local/lib/node_modules/ask-cli
$ npm i -S fs-extra@6.0.1
$ ask util

  Usage: ask-util 

  $ ask util [command]

  Util functions to manage the life cycle of Alexa Skills.

  Options:

    -h, --help                     output usage information

  Commands:

    generate-lwa-tokens [options]  generates LWA tokens from 3p clientId and clientCredentials
```

## Steps to Reproduce (for bugs)

```
$ npm i -g ask-cli
$ ask util
(node:35788) ExperimentalWarning: The fs.promises API is experimental

  Usage: ask-util 

  $ ask util [command]

  Util functions to manage the life cycle of Alexa Skills.

  Options:

    -h, --help                     output usage information

  Commands:

    generate-lwa-tokens [options]  generates LWA tokens from 3p clientId and clientCredentials
```

## Context

I wanna to run some CI tests, but for now, assertion does not work well.
Because the warning shows at first line.

### test code
```
const assert = require('power-assert')
const { spawn } = require('child_process')

describe('test by ask-cli', () => {
  it('exit code should be zero', (done) => {
    var cli = spawn('ask', [
      'api', 'get-model', '-s', 'amzn1.ask.skill.d7d6176c-ab76-4e4c-b5ee-81366c4cd223'
    ])

    cli.stdout.on('data', function (data) {
      assert.deepEqual(data.toString(), {})
      done()
    })
    cli.stderr.on('data', function (err) {
      assert.deepEqual(err.toString(), {})
      done()
    })

    cli.stdin.write('testing')
  })
})
```

### test result
```
  1) test by ask-cli
       exit code should be zero:
     Uncaught AssertionError [ERR_ASSERTION]: '(node:35815) ExperimentalWarning: The fs.promises API is experimental\n' deepEqual {}
```
## Your Environment
```
$ ask -v
1.4.0
```

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

```
$ node -v
v10.1.0

$ npm -v
5.6.0
```

Kindly regards.

**Comment by sungolivia** [comment]
Hey there, I would suggest posting [here](https://forums.developer.amazon.com/spaces/281/alexa-skill-management-api-smapi_2.html) as it's better place for CLI team to get back to you!

**Comment by hideokamoto** [comment]
Thanks !

I've post the same question to there.
https://forums.developer.amazon.com/questions/175589/ask-cli-shows-experimentalwarning-the-fspromises-a.html
