### ISSUE TITLE
Regarding Alexa access_token after successful Account Linking

### ISSUE THREAD

**Issue by umershabbir16** [alexa/alexa-skills-kit-sdk-for-nodejs#428]
I am able to successfully link the Alexa skill with 3rd path Auth server. I am also able to get the access token in session.user.accessToken object. I am also able to pull the user profile by passing this access token in my nodejs code as under:
       let options = {
          method: 'GET',
          url: Constants.FRIDGETIZE_USER_PROFILE_URL,
          headers:{
            authorization: 'Bearer ' + session.attributes.accessToken
          }
        };
    
        request(options, function(error, response, body) {
        .....
        .....
        });

But I noticed that this access token is only 32 characters long whereas the real access token should be way longer than 32 characters. The problem is when I use this shorter access token and make the backend API services calls which expect a valid access token they reject my requests from Alexa against this short access token. Could you please guide me how to retrieve the valid access_token since this short access token is working only to pull the user profile but not to invoke the backend rest api calls. I get unauthorized response.

Thanks,

**Comment by umershabbir16** [comment]
![image](https://user-images.githubusercontent.com/36803042/42656548-3912e2c2-85e5-11e8-971d-e8647becd311.png)

**Comment by nikhilym** [comment]
Hi @umershabbir16 , can you please update your issue following the [issue template](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/ISSUE_TEMPLATE.md), so that we will have more context on the SDK version, NPM version etc.

**Comment by umershabbir16** [comment]
Hi,
I am using NodeJS 6.10.3 and NPM 3.10.10
This issue is not related to any version. It's the way the access_token is coming back from Alexa which is not getting recognized/validated by the Auth server since the token which alexa is sending me is only 32 characters long whereas the auth server is expecting longer access_token. Also as I mentioned above, I am successfully able to retrieve the user profile from the same access token coming from alexa but when I call the REST backend services against the same access token, the auth server does not validate that token and send me unauthorized exception. Here's my Alexa Account linking settings as under:

![image](https://user-images.githubusercontent.com/36803042/42672161-e70cf77a-8629-11e8-929a-260bb49d7a30.png)

**Comment by tianrenz** [comment]
Hi @umershabbir16 ,

This is an issue that's not relevant to the SDK. We would recommend to post general question about Alexa Skills Kit on the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/23/index.html).
 
At the meantime, here are some [resources](https://developer.amazon.com/docs/account-linking/configure-authorization-code-grant.html) that might help. 

Regards
