### ISSUE TITLE
Session expiry issue on Echo Dot

### ISSUE THREAD

**Issue by nutanlade** [alexa/alexa-skills-kit-sdk-for-nodejs#430]
I have followed same steps in basic alexa nodejs integration. It is working while testing in amazon alexa skill test console. But when I have enabled skill on Amazon Echo Dot it is opening skill and asking for question it is throwing below error. Some one please help me in resolving this issue.

`2018-07-18T04:06:53.198Z 00d0968e-8a40-11e8-8a84-7fe6b2d92d36 Session ended with reason:
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.a1fed625-0cec-4341-ace7-9bb3a3c975cf",
        "application": {
            "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
        },
        "user": {
            "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
            },
            "user": {
                "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AE2FSKJFNVARSG5OE2NFXK2ZS4KEXFSOIDUSTDLVYRCSEMOVLCJ5RB77BYY4RJLZT2X33Q5ASHBRTPRRDC5AR3JJMQZIDY2LXOTHSPFGKBFFLM3EJ2XEMQHUOUHSBXZR2J4UZPCR3EQOAB5457U2B7YZPEUQ",
                "supportedInterfaces": {}
            },
            "apiEndpoint": "https://api.eu.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjM5Njc1NTA4LWMyYTEtNGYwYi1hODk5LTZlODFjMjliM2I2NiIsImV4cCI6MTUzMTg5MDQxMiwiaWF0IjoxNTMxODg2ODEyLCJuYmYiOjE1MzE4ODY4MTIsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUUyRlNLSkZOVkFSU0c1T0UyTkZYSzJaUzRLRVhGU09JRFVTVERMVllSQ1NFTU9WTENKNVJCNzdCWVk0UkpMWlQyWDMzUTVBU0hCUlRQUlJEQzVBUjNKSk1RWklEWTJMWE9USFNQRkdLQkZGTE0zRUoyWEVNUUhVT1VIU0JYWlIySjRVWlBDUjNFUU9BQjU0NTdVMkI3WVpQRVVRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUU3RlJMNVk1NVhISkVQSzJUT1NOTVBINko0WDRPSkVUVkFSR0lDVjRRRlVGSlpBMzdJMjJPSTRXS0pSVzVPT1VEMzZJS0JCTEJNTU1SUTdLTTZaSkdWNkZUNks0RFpCTk03NjM0QjVLU09JV1lENzRDS0JURjRaUkxXWk9RTTNWQkFMUlpFS1JNRlc3UlBZVk1LSklQWVRBQ1ZaNUVESVJENEVDR1FPSjdTUlVJWVVLQ0pUQUQ2R1lOSTdHRDUyWUlLNkU2UVdBU0pKM1NRIn19.X3UVOqdg_30UFdNHfajTsQu4L37Q4KdvX2WjjlKoZJHU-IgsKea9lvpf-admyZcPbmpkyeGeaQRQe-Q1yxDN_t0mrhXGq2vO6nfrZIG6x6R_NbPP8chLgY281UnbtXWlwgyzaKqa7Gu--PqhdCe29uTt3l6aTUlunTD-aehYWen9xMRnTaQ76AwSDDfgWXQUSHmWO6XFTaJEUJw4aLbgApb7pn6Yc5Id5uD4zSB0sLq5EbW3xgxhKtTCXHykOpBCFhZpQ9dn3Hw3sgwz7MOC4lphqX_1utiY_Ndg3qe_6WFN0BnJ2FZ7DD5r0_DaDh0MEg_pRWiMDOuZE-9aVrrluw"
        }
    },
    "request": {
        "type": "SessionEndedRequest",
        "requestId": "amzn1.echo-api.request.407b3f84-27a0-4a80-82a9-76ad2acd5281",
        "timestamp": "2018-07-18T04:06:52Z",
        "locale": "en-IN",
        "reason": "ERROR",
        "error": {
            "type": "INTERNAL_SERVICE_ERROR",
            "message": "Internal Server Error"
        }
    }
}`

**Comment by nutanlade** [comment]
Hey @nikhilym , I followed below link for development and testing on Amazon echo.

https://github.com/alexa/skill-sample-nodejs-hello-world

**Comment by nutanlade** [comment]
Hi @tianrenz , 

I have tried many times after giving some gaps. It opens the skill and read out the welcome message. Once I ask a question immediately got this issue.

Thanks,
Nutan

**Comment by nikhilym** [comment]
Can you provide your code snippet? After the welcome message, what question are you asking?

**Comment by nutanlade** [comment]
@nikhilym 

Below is Launch Request and Receipe Handler. The question I asked is **"How to use snow golem"**.

`const LaunchRequestHandler = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
  },
  handle(handlerInput) {
    const requestAttributes = handlerInput.attributesManager.getRequestAttributes();
    const sessionAttributes = handlerInput.attributesManager.getSessionAttributes();

    const item = requestAttributes.t(getRandomItem(Object.keys(recipes.RECIPE_EN_US)));

    const speakOutput = requestAttributes.t('WELCOME_MESSAGE', requestAttributes.t('SKILL_NAME'), item);
    const repromptOutput = requestAttributes.t('WELCOME_REPROMPT');

    handlerInput.attributesManager.setSessionAttributes(sessionAttributes);

    return handlerInput.responseBuilder
      .speak(speakOutput)
      .reprompt(repromptOutput)
      .getResponse();   },}; 

```
RecipeHandler  = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'IntentRequest'
            && handlerInput.requestEnvelope.request.intent.name === 'RecipeIntent';
  },
  handle(handlerInput) {
    console.log('Loading RecipeHandler');
    const requestAttributes = handlerInput.attributesManager.getRequestAttributes();
    const sessionAttributes = handlerInput.attributesManager.getSessionAttributes();
    const itemSlot = handlerInput.requestEnvelope.request.intent.slots.Item;
    let itemName;
    if (itemSlot && itemSlot.value) {
      itemName = itemSlot.value.toLowerCase();
    }
    const cardTitle = requestAttributes.t('DISPLAY_CARD_TITLE', requestAttributes.t('SKILL_NAME'), itemName);
    const myRecipes = requestAttributes.t('RECIPES');
    const recipe = myRecipes[itemName];
    console.log('Loading function');
    console.log('itemName =', itemName);
    let speakOutput = "";
    if (recipe) {
      sessionAttributes.speakOutput = recipe;
      //sessionAttributes.repromptSpeech = requestAttributes.t('RECIPE_REPEAT_MESSAGE');
      handlerInput.attributesManager.setSessionAttributes(sessionAttributes);
      return handlerInput.responseBuilder
        .speak(sessionAttributes.speakOutput) // .reprompt(sessionAttributes.repromptSpeech)
        .withSimpleCard(cardTitle, recipe)
        .getResponse();
    }
    else{
      speakOutput = requestAttributes.t('RECIPE_NOT_FOUND_MESSAGE');
      const repromptSpeech = requestAttributes.t('RECIPE_NOT_FOUND_REPROMPT');
      if (itemName) {
        speakOutput += requestAttributes.t('RECIPE_NOT_FOUND_WITH_ITEM_NAME', itemName);
      } else {
        speakOutput += requestAttributes.t('RECIPE_NOT_FOUND_WITHOUT_ITEM_NAME');
      }
      speakOutput += repromptSpeech;
      sessionAttributes.speakOutput = speakOutput; //saving speakOutput to attributes, so we can use it to repeat
      sessionAttributes.repromptSpeech = repromptSpeech;
      handlerInput.attributesManager.setSessionAttributes(sessionAttributes);
      return handlerInput.responseBuilder
        .speak(sessionAttributes.speakOutput)
        .reprompt(sessionAttributes.repromptSpeech)
        .getResponse();
    }
  }
}; 
`

**Comment by tianrenz** [comment]
Hi @nutanlade , 

Could you check in CloudWatch logs if the skill is throwing any other errors?

Regards

**Comment by nutanlade** [comment]
Hi @tianrenz ,

Cloud watch logs are below. Exception session exception nothing else is thrown.
```

START RequestId: 7d8b7d97-8d00-11e8-94eb-2f2df855d16e Version: $LATEST
END RequestId: 7d8b7d97-8d00-11e8-94eb-2f2df855d16e
REPORT RequestId: 7d8b7d97-8d00-11e8-94eb-2f2df855d16e Duration: 402.98 ms Billed Duration: 500 ms Memory Size: 128 MB Max Memory Used: 62 MB
START RequestId: 89d3dddb-8d00-11e8-81f5-cbb68c13c788 Version: $LATEST
2018-07-21T16:10:08.722Z 89d3dddb-8d00-11e8-81f5-cbb68c13c788 Inside SessionEndedRequestHandler
2018-07-21T16:10:08.742Z 89d3dddb-8d00-11e8-81f5-cbb68c13c788 Session ended with reason:
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.f41509bd-e8d6-47a5-b9fe-bc1c9b5ddc39",
        "application": {
            "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
        },
        "user": {
            "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
            },
            "user": {
                "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AE2FSKJFNVARSG5OE2NFXK2ZS4KEXFSOIDUSTDLVYRCSEMOVLCJ5RB77BYY4RJLZT2X33Q5ASHBRTPRRDC5AR3JJMQZIDY2LXOTHSPFGKBFFLM3EJ2XEMQHUOUHSBXZR2J4UZPCR3EQOAB5457U2B7YZPEUQ",
                "supportedInterfaces": {}
            },
            "apiEndpoint": "https://api.eu.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjM5Njc1NTA4LWMyYTEtNGYwYi1hODk5LTZlODFjMjliM2I2NiIsImV4cCI6MTUzMjE5MzAwOCwiaWF0IjoxNTMyMTg5NDA4LCJuYmYiOjE1MzIxODk0MDgsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUUyRlNLSkZOVkFSU0c1T0UyTkZYSzJaUzRLRVhGU09JRFVTVERMVllSQ1NFTU9WTENKNVJCNzdCWVk0UkpMWlQyWDMzUTVBU0hCUlRQUlJEQzVBUjNKSk1RWklEWTJMWE9USFNQRkdLQkZGTE0zRUoyWEVNUUhVT1VIU0JYWlIySjRVWlBDUjNFUU9BQjU0NTdVMkI3WVpQRVVRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUU3RlJMNVk1NVhISkVQSzJUT1NOTVBINko0WDRPSkVUVkFSR0lDVjRRRlVGSlpBMzdJMjJPSTRXS0pSVzVPT1VEMzZJS0JCTEJNTU1SUTdLTTZaSkdWNkZUNks0RFpCTk03NjM0QjVLU09JV1lENzRDS0JURjRaUkxXWk9RTTNWQkFMUlpFS1JNRlc3UlBZVk1LSklQWVRBQ1ZaNUVESVJENEVDR1FPSjdTUlVJWVVLQ0pUQUQ2R1lOSTdHRDUyWUlLNkU2UVdBU0pKM1NRIn19.eDOJbSyeh8gZ8fZfHX9mbsvilOuoJ_QN9psEtjh3LOtnSywZMscqacV-3n8RWrA9bQJ5ROgGe3j4w52-pa_QHKR9NNnIUQpjndxlrfltRFKNQhHWS52tcufptIz1t5jgFUFbbcpHTGC67_pffXuA-LCsdvbxqgNvGwTIVhU8xm4CRQbfCzqheHMxrxrk6pF5mM4ld1nlgxhoosNJcJK4oHwO1R34Ua6vof5sbbgtwIPkbmugK0TNyxqfARwL-CBUqxn5BbW2-k5X8UwE6yEf3QCzpyxyVkqBAKDD4IZil3Zbski-IKDrvTLcSNLbAlIvvL0diLs-Zqhit7Xxthtanw"
        }
    },
    "request": {
        "type": "SessionEndedRequest",
        "requestId": "amzn1.echo-api.request.54bafdf3-4e34-4f8e-a4dc-3b93cfaa90cf",
        "timestamp": "2018-07-21T16:10:08Z",
        "locale": "en-IN",
        "reason": "USER_INITIATED"
    }
}

END RequestId: 89d3dddb-8d00-11e8-81f5-cbb68c13c788
REPORT RequestId: 89d3dddb-8d00-11e8-81f5-cbb68c13c788 Duration: 91.47 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 62 MB
START RequestId: 89f39ba7-8d00-11e8-a66f-65d5718ae60f Version: $LATEST
END RequestId: 89f39ba7-8d00-11e8-a66f-65d5718ae60f
REPORT RequestId: 89f39ba7-8d00-11e8-a66f-65d5718ae60f Duration: 1.29 ms Billed Duration: 100 ms Memory Size: 128 MB Max Memory Used: 62 MB
START RequestId: 932b87c5-8d00-11e8-b8df-d1674aa1d5f2 Version: $LATEST
2018-07-21T16:10:24.543Z 932b87c5-8d00-11e8-b8df-d1674aa1d5f2 Inside SessionEndedRequestHandler
2018-07-21T16:10:24.562Z 932b87c5-8d00-11e8-b8df-d1674aa1d5f2 Session ended with reason:
{
    "version": "1.0",
    "session": {
        "new": false,
        "sessionId": "amzn1.echo-api.session.71ce3210-bf4d-4985-8ad8-73b0a9b5dc25",
        "application": {
            "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
        },
        "user": {
            "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
        }
    },
    "context": {
        "System": {
            "application": {
                "applicationId": "amzn1.ask.skill.39675508-c2a1-4f0b-a899-6e81c29b3b66"
            },
            "user": {
                "userId": "amzn1.ask.account.AE7FRL5Y55XHJEPK2TOSNMPH6J4X4OJETVARGICV4QFUFJZA37I22OI4WKJRW5OOUD36IKBBLBMMMRQ7KM6ZJGV6FT6K4DZBNM7634B5KSOIWYD74CKBTF4ZRLWZOQM3VBALRZEKRMFW7RPYVMKJIPYTACVZ5EDIRD4ECGQOJ7SRUIYUKCJTAD6GYNI7GD52YIK6E6QWASJJ3SQ"
            },
            "device": {
                "deviceId": "amzn1.ask.device.AE2FSKJFNVARSG5OE2NFXK2ZS4KEXFSOIDUSTDLVYRCSEMOVLCJ5RB77BYY4RJLZT2X33Q5ASHBRTPRRDC5AR3JJMQZIDY2LXOTHSPFGKBFFLM3EJ2XEMQHUOUHSBXZR2J4UZPCR3EQOAB5457U2B7YZPEUQ",
                "supportedInterfaces": {}
            },
            "apiEndpoint": "https://api.eu.amazonalexa.com",
            "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjM5Njc1NTA4LWMyYTEtNGYwYi1hODk5LTZlODFjMjliM2I2NiIsImV4cCI6MTUzMjE5MzAyNCwiaWF0IjoxNTMyMTg5NDI0LCJuYmYiOjE1MzIxODk0MjQsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUUyRlNLSkZOVkFSU0c1T0UyTkZYSzJaUzRLRVhGU09JRFVTVERMVllSQ1NFTU9WTENKNVJCNzdCWVk0UkpMWlQyWDMzUTVBU0hCUlRQUlJEQzVBUjNKSk1RWklEWTJMWE9USFNQRkdLQkZGTE0zRUoyWEVNUUhVT1VIU0JYWlIySjRVWlBDUjNFUU9BQjU0NTdVMkI3WVpQRVVRIiwidXNlcklkIjoiYW16bjEuYXNrLmFjY291bnQuQUU3RlJMNVk1NVhISkVQSzJUT1NOTVBINko0WDRPSkVUVkFSR0lDVjRRRlVGSlpBMzdJMjJPSTRXS0pSVzVPT1VEMzZJS0JCTEJNTU1SUTdLTTZaSkdWNkZUNks0RFpCTk03NjM0QjVLU09JV1lENzRDS0JURjRaUkxXWk9RTTNWQkFMUlpFS1JNRlc3UlBZVk1LSklQWVRBQ1ZaNUVESVJENEVDR1FPSjdTUlVJWVVLQ0pUQUQ2R1lOSTdHRDUyWUlLNkU2UVdBU0pKM1NRIn19.j1JklqjEgfnvaC8SOKGnfyYpIyMUlv5nbVlCztyeXESxefQsLIF6Vx5bfWjVHY3EHEwKXZ6qozWBpR5C3GFaXqSPsgkswSDZr6X7kH9O99yiskOlYASMP7c-Oqc6iwMpUipiaQo8Lr3s2-a4BMj7ZEejDpghiEGfnoj0BIRucKbDpqVt_1ivs1Yb_BcTGAh7FsWeh3OBkuMGJ3KV21VaN5MPfC8gk8qNmJP-yGy6I72zovFTGSYnyh5NkK7kWMJCJB0IXSroOg8S3DwMwa4_lbbrRQSOM_ITczgsqY2GqFsdVIMwcvDNqmoa7-kwPBXxVdoYFyUNhXDvZ-1mWhDRfQ"
        }
    },
    "request": {
        "type": "SessionEndedRequest",
        "requestId": "amzn1.echo-api.request.e866646e-2f92-40c0-b498-6e70b614b110",
        "timestamp": "2018-07-21T16:10:24Z",
        "locale": "en-IN",
        "reason": "ERROR",
        "error": {
            "type": "INTERNAL_SERVICE_ERROR",
            "message": "Internal Server Error"
        }
    }
}

END RequestId: 932b87c5-8d00-11e8-b8df-d1674aa1d5f2
REPORT RequestId: 932b87c5-8d00-11e8-b8df-d1674aa1d5f2 Duration: 220.42 ms Billed Duration: 300 ms Memory Size: 128 MB Max Memory Used: 64 
```MB

**Comment by tianrenz** [comment]
Hi @nutanlade , 

I noticed that you have this log statement (`console.log('Loading RecipeHandler')`) inside your `RecipeHandler`. However, the statement was not printed in the cloudwatch log. Could you verify that the handler is getting invoked and the request envelope is has the right intent name?

Regards

**Comment by tianrenz** [comment]
Hi @nutanlade , 

That what I suspected. The reason that the `RecipeHandler` was not invoked could be that you have a different intent name configured in the interaction model, therefore the skill could not locate your handler. Could you verify that the event has the correct intent name of RecipeIntent and the handler has been registered through the skill builder?

Regards

**Comment by nutanlade** [comment]
Hi All,

Thanks for your help. Issue is resolved after changing Language settings to English IN

Regards
