### ISSUE TITLE
Does ASK SDK do  Request Validation ?

### ISSUE THREAD

**Issue by samothx** [alexa/alexa-skills-kit-sdk-for-nodejs#432]
Hi, 
I am currently submitting a skill and while going through the requirements I came across the following: 

> The service must verify that incoming requests were sent by the Alexa service. You can do this by validating the request signature as discussed in the "Verifying that the Request was Sent by Alexa" section of Hosting a Custom Skill as a Web Service.

The article pointed out states that the java api (SpeechServlet) does this for you but there is no mention of the ASK SDK for nodejs. Is this something the SDK does or do I have to implement it myself ? 

Cheers Thomas

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

**Comment by tianrenz** [comment]
Hi @samothx , 

To get more context on the issue, are you hosting you skill on lambda or as a web service?

Regards,

**Comment by tianrenz** [comment]
Merging this with #434 . Please move future discussions there.
