### ISSUE TITLE
Provide code sample for verifcations (certificate url, signature url etc)

### ISSUE THREAD

**Issue by giorgio79** [alexa/alexa-skills-kit-sdk-for-nodejs#434]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Alexa Node JS SDK should provide boiler plate code for checking Amazon Alexa calls.

## Current Behavior

Only skillbuilder examples are provided

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
Provide boiler plate  / copy paste code
## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
Try to submit app

![image](https://user-images.githubusercontent.com/283347/43073715-dc459992-8e7a-11e8-8b45-2d27dde2bbf7.png)

## Context

Have to code that every other app dev will have to code
## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:
centos 7
## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by giorgio79** [comment]
PS just found some attempts to provide one https://github.com/alexa-js/alexa-verifier-middleware

**Comment by tianrenz** [comment]
Hi @giorgio79 , 

Thanks for the information. We are working on SDK support for web based skill. Stay tuned!

Regards

**Comment by fildanrcs** [comment]
Hi @giorgio79 ,

Thanks for asking it, I would really appreciate this feature too.
Meanwhile I've tried alexa-verifier, but on Windows seems to not work. Have you tried only on Linux?

Regards

**Comment by soltrinox** [comment]
That makes three. I would like this feature as well. I am getting a CERTIFICATION rejection in the Alexa Functional Test section. Help on the NodeJS  side would be greatly appreciated.

Please provide a code snippet to add to my NodeJS Express code to properly reject the NON-ALEXA request only documentation is for Java ASK SDK missing for nodejs.

**Comment by soltrinox** [comment]
> PS just found some attempts to provide one https://github.com/alexa-js/alexa-verifier-middleware
> and another one https://github.com/mreinstein/alexa-verifier

I tried both and i am still getting rejection on Alexa Dev Console.

**Comment by stefanopog** [comment]
Hello, was anybody able to find an interim solution that works ? Thanks so much

**Comment by ShenChen93** [comment]
New package ask-sdk-express-adapter is available on NPM now, which make it easy to host skill as webservice. Therefore, close the issue and please feel free to reopen if you have any problems.

**Comment by JonathanDn** [comment]
@ShenChen-Amazon There's not a single example in the documentation in github or in NPM to how to properly use this. I would much appreciate one to successfully verify my web service with amazon through a middleware...

**Comment by ShenChen93** [comment]
Hi @JonathanDn 

There's doc link under [Usage and Getting Started tab](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/ask-sdk-express-adapter#usage-and-getting-started), and will direct to [Alexa developer portal](https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-nodejs/host-web-service.html).  Sorry the link seems not obvious enough :(    Please feel free to follow up if you have other concerns. 

Thanks,
Shen

**Comment by JonathanDn** [comment]
After a few hours of searching, reading, and triyng various things according to the API documentation I was able to find this video of this kind fellow who helped me get up and running and close a cycle with a test skill that will be triggered + send a hello world response.
https://www.youtube.com/watch?v=wH6mkxuf9tE

Thanks though.
