### ISSUE TITLE
Delete Persistent Attributes including account ID

### ISSUE THREAD

**Issue by warhost** [alexa/alexa-skills-kit-sdk-for-nodejs#436]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
I am struggling to find how I can delete persistent Attributes **including** the key, which is the amazon account ID by default.

## Current Behavior
I am doing it the following way:

```
attributesManager.setPersistentAttributes();
await attributesManager.savePersistentAttributes();
```
But then, the ID remains as Key, there are just no entries for it. I want to delete everything for a given user.

**Comment by tianrenz** [comment]
Hi @warhost , 

AWS DynamoDb supports operation to delete items from table. That function currently is not exposed through `AttributesManager`. You can use the `aws-sdk` directly to achieve what you want (see this [link](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/DynamoDB/DocumentClient.html#delete-property)).

We'll mark this as a feature request and review the need in future. If there's enough request, we will schedule task to add support. In the meanwhile, we recommend to post your ideas in [Alexa User Voice forum](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322783) as we regularly review idea on there. 

Regards

**Comment by ghost** [comment]
The right answer is if a user disables your skill, the framework should delete the persistent info record from the DynamoDB stream for the alexa skill automagically.  Why leave dead data in my persistence store?  The user has decided to disable the skill.  It even gives you a warning that it will remove information but it's not deleting it from my dynamo db stream.

**Comment by ghost** [comment]
@FTC23Admin That should be how it's handled, especially since the user gets a new account ID from amazon upon reactivation, so all previous data is dead. However I don't think it is technically feasible for Amazon to go into your DB and delete stuff, since there is no guarantee everyone structures the data the same way.
