### ISSUE TITLE
Provide sample for CanFulfilIntentRequest

### ISSUE THREAD

**Issue by giorgio79** [alexa/alexa-skills-kit-sdk-for-nodejs#437]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Easy copy and paste example for CanFulfilIntentRequest, https://developer.amazon.com/docs/custom-skills/request-types-reference.html#CanFulfillIntentRequest

## Current Behavior

no example

## Possible Solution
Provide one. The one I found is a bit vague without code comments at https://github.com/PaulCutsinger/Sample-For-Can-Fulfill-Intent-Request
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by giorgio79** [comment]
Any news please? "Service" seems to be taking a long time

**Comment by tianrenz** [comment]
Hi @giorgio79 , 

I've forwarded your request to the service team. Sorry kept you waiting. I'll follow up with them to check on the status. Meanwhile, I would recommend to checkout our public documentation on [understanding name free invocations](https://developer.amazon.com/docs/custom-skills/understand-name-free-interaction-for-custom-skills.html) and [implementation CanfullfillIntentRequest](https://developer.amazon.com/docs/custom-skills/implement-canfulfillintentrequest-for-name-free-interaction.html). 

Regards

**Comment by giorgio79** [comment]
Thanks! Have you tried following the "Understanding name free invocation" docs? I checked those docs before and it would take weeks of trial and error. (Even you as an insider is asking for help from the service team) Take a look at the Google Docs API for proper API docs (those I could use for implementating a client) :)

**Comment by MattDormond** [comment]
Are there any updates on this?  I have looked at the example mentioned under Expected Behavior, but I haven't had any luck.  A simple code example for new features would be helpful.
