### ISSUE TITLE
Echo Show closes template/dialog direct if using withShouldEndSession(true)

### ISSUE THREAD

**Issue by Bubelbub** [alexa/alexa-skills-kit-sdk-for-nodejs#444]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have a small dialog and at the end the Echo Show shows only one second the template and then I'm back on the main page.
But why?

Normally the user can click on some list items within the template so that a new intent will be called - when I understand it correct.

So why it closes the session direct?
How to "hold it" open?

## Expected Behavior
The dialog is still open but Alexa is not waiting for answering the question.

## Current Behavior
The Echo Show hides the dialog/template direct after finishing the sentence.

    const responseBuilder = handlerInput.responseBuilder;
    responseBuilder
        .addRenderTemplateDirective({
            'type': 'ListTemplate2',
            'title': 'Echo Show closes template/dialog direct if using withShouldEndSession(true)',
            'listItems': [
                {
                    textContent: new Alexa.RichTextContentHelper()
                        .withPrimaryText('Example')
                        .withSecondaryText('on Github')
                        .withTertiaryText('- visible one Minute')
                        .getTextContent()
                }
            ]
        })
        .addHintDirective('A small hint which is visible one second :-D');
    
    return responseBuilder
        .speak('Something which isnt needed because I want to show only')
        .reprompt('Something which isnt needed because I want to show only')
        .withShouldEndSession(false) // if I put it to true it will close everything directly but if its false it waits for an answer
        .getResponse();

**Comment by nikhilym** [comment]
As per the [documentation](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#response-object), alexa ends the session once it is done speaking, when ``shouldEndSession`` is set as ``true``. If you want the users to interact back, then the session has to be left open and ``shouldEndSession`` as ``false``. This is the default behavior. @Bubelbub , does that clarify the issue you are facing?

**Comment by Bubelbub** [comment]
No because Alexa should only Show the rendered template and not waiting for feedback.
Im using speak and the directive.
But if she finishes the Dialog is away 😑

**Comment by nikhilym** [comment]
Currently,``shouldEndSession`` is the only available attribute that controls how Alexa understands about your skill session. If there is a feature request related to keeping the directive shown, then this would be a service side implementation not related to the SDK. We would recommend to post this on the [Alexa User Voice Forum](https://alexa.uservoice.com/forums/906892-alexa-skills-kit-ask) to gain more feedback from the community.
