### ISSUE TITLE
Context switching during dialog with ASK SDK V2

### ISSUE THREAD

**Issue by SimpleConjugate** [alexa/alexa-skills-kit-sdk-for-nodejs#446]
In V2 of `ask-sdk`, what is an efficient method for switching back and forth between between intents without restarting when returning to an intent. It would useful to maintain some attributes created or slots filled in between invoking another intent and returning to an intent.

`Intent 1 start` -> `Intent 1  middle` -> `Intent 2` ->`Intent 1 middle` -> ...

If possible, it would be useful if  `Intent 2` could switch to other intents(preserving attributes or slots as necessary) before the user is brought back to their original place in `Intent 1`. 

There is a tutorial for v1 on maintaining context when switching between intents:
[How to Enable Alexa to Switch Context Mid-Conversation with Dialog Management](https://developer.amazon.com/blogs/alexa/post/d8579cd6-9109-42b2-ada6-df017fc1dee5/how-to-handle-different-intent-requests-with-dialog-management)

The quick review of it is that for each session attribute, a new one is created with different name that includes the intent name.  When switch back to intents, the temporary attributes are restored to the current request. 

A direct adaptation of the V1 method is to store the same temporary variables in `HandlerInput` in V2. **Does V2 provide more efficient ways of accomplishing this?**

### REVIEW: Change Intent through IntentHandler in V2
Based on documentation and useful comments (  [#408](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/408#issuecomment-397028721) and   [#391](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/391#issuecomment-391082767) ), it is simple to switch intents by calling the child handlers `.handle(HandlerInput)` function inside the parent handler. 

 I'll use {`parentHandler`,`fooHandler`,`barHandler`} as my set of dummy handlers. I wish to conditionally invoke "child handlers"  (`fooHandler`,`barHandler`) from a "parent handler" (`parentHandler`). 

```javascript
const feeHandler = {
    canHandle(HandlerInput) {
        //your logic
    },
    handle(HandlerInput) {
        // prior logic
        if (fooCondition){
            return FooHandler.handle(HandlerInput);
        }
        else if(barCondition) {
            return BarHandler.handle(HandlerInput);
        }
        else {
            // alt logic
        }
        // resume default feeHandler logic
}
```
#### Saving session attributes
>When we are in any state other than COMPLETED, we save the data into the session attributes and we name the session attribute after the intent name while appending temp_ to the beginning. Saving the state information based on the intent name will allow us to build a skill that has multiple intents that delegate slot collection that can context switch and not lose any previously collected slots.
```javascript
if (this.event.request.dialogState !== "COMPLETED") {
   this.attributes['temp_' + this.event.request.intent.name] = this.event.request.intent;
} else {
   delete this.attributes['temp_' + this.event.request.intent.name];
}
```
#### Restoring Dialog Management Context
>To determine if we need to rehydrate, we check to see if the session attributes contain an attribute named `'temp_' + this.event.request.intent.name`. If we were returning to the **PetMatchIntent,** the session attributes would contain, **temp_PetMatchIntent.** Next we loop through the set of slots that we saved in the session attributes, and for each one that has a value, restore it into the request. Doing so enables the skill to continue on through dialog management where it left off before the user invoked the **ExplainSizeIntent**
```javascript
if (this.event.request.dialogState !== "COMPLETED") {
    
    // new code
    if (this.attributes['temp_' + this.event.request.intent.name]) {
    
        let tempSlots = this.attributes['temp_' + this.event.request.intent.name].slots;
        Object.keys(tempSlots).forEach(currentSlot => {
            if (tempSlots[currentSlot].value) {
                this.event.request.intent.slots[currentSlot] = tempSlots[currentSlot]
            }
        }, this);
        
    } else {
        this.attributes['temp_' + this.event.request.intent.name] = this.event.request.intent;
    }
    // end new code
    
} else {
  delete this.attributes['temp_' + this.event.request.intent.name];
}
```

**Comment by nikhilym** [comment]
Hi @SimpleConjugate , at this moment, as you have already mentioned under **"REVIEW: Change Intent through IntentHandler in V2"**, the developer can add preprocessing information in handler input's request attributes and use it to conditionally check and switch intents. 

However, if there is a common information that needs to be processed, before intent handling kicks in, we suggest you to use request interceptors to store that information, and use the `canHandle` to check for the condition instead. This makes the handler logic much cleaner and avoids intent switching. Does that help?

**Comment by Bubelbub** [comment]
But sorry @nikhilym, I want to implement Amazon Pay now.
And then I have this workflow.

`Order Intent` -> `Connections.Response` -> How get back? `Order Intent`

In order intent I'm returning a `Connections.SendRequest` directive.
Then my response / next intent is `Connections.Response`.
And how to get back to my `Order Intent`?

Yes I'm able to use something like `OrderIntent.handle(handlerInput)` BUT when I'm at the Cart I can't use `addConfirmIntentDirective` because it thinks its a `Connections.Response`.
