### ISSUE TITLE
Custom SkillBuilder withPersistenceAdapter Example

### ISSUE THREAD

**Issue by rgstephens** [alexa/alexa-skills-kit-sdk-for-nodejs#447]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It would be useful to have an example persistence adapter function.

The Custom Skill Builder provides a **withPersistenceAdapter** option but I can't find any examples of a persistence adapter. Previous issues (#351, #359 & #393) hit on this issue but none reference example code for a withPersistenceAdapter function.

In particular, I'd like to see an example that stores profile data to a private DynamoDB table and stores some public data to a separate table that is accessible to all users of a skill.

**Comment by rgstephens** [comment]
@nikhilym Thanks for the reference to the DynamoDbPersistenceAdapter as an example. I was thinking that using the Custom Skill builder and withPersistenceAdapter, I could create a adapter that had calls like **getPublicAttributes** & **getPrivateAttributes** that would store data to completely separate tables with different access policies.

Is this a workable approach?

**Comment by nikhilym** [comment]
The only requirement for such an adapter would be to have an interface similar to the one mentioned [here](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Skill-Attributes.html#persistenceadapter). Also, the [attribute manager object](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Skill-Attributes.html#attributesmanager) under `HandlerInput` only has a `getPersistentAttributes` method, which doesn't take in any table name parameter as input. 

So, the logic to figure out the scope of the attributes and load them accordingly is left to the skill developers. For the use case you mentioned, maybe you can use the provided attributes manager for one of the calls, and use a custom adapter tagged to `HandlerInput` for the other.

**Comment by rcassis** [comment]
I would love to see this in the documentation too.  My skill needs to write to several tables and subscribe to insertions in a table (which I found examples for) and read from several other tables.  It's a lot more than just "session" or "user preference" data.

**Comment by nikhilym** [comment]
@rcassis , We are revisiting the documentation and making some necessary changes as part of PR #443 . Please track the PR and add your comments in case you see anything missing or want more information, or wait for the PR to be merged (soon) and let us know.

@rgstephens hopefully my comment clarifies your question. Please close the issue or update it accordingly.
