### ISSUE TITLE
Adding a Standard Card during Enqueue

### ISSUE THREAD

**Issue by XTron3453** [alexa/alexa-skills-kit-sdk-for-nodejs#448]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I have a skill that invokes the PlayAudioDirective for a setlist and will enqueue the next story when it reaches the end of the current story. For some reason, an error is thrown when I try to add a card to the responsebuilder (This is being done during the NearlyFinished Event). When I invoke the NextIntent manually, it will allow me to add a card. Is there a reason I cannot add a card to my responseBuilder?

## Current Behavior

Here is the Error I receive, it comes in as a SystemException
`[ERROR] SystemException: {
  "requestEnvelope": {
    "version": "1.0",
    "context": {
      "AudioPlayer": {
        "offsetInMilliseconds": 0,
        "token": "0",
        "playerActivity": "PLAYING"
      },
      "System": {
        "application": {
          "applicationId": "amzn1.ask.skill.5a283a2c-5b1f-4831-802b-0284d7f8f042"
        },
        "user": {
          "userId": "amzn1.ask.account.AEHB44PDTNANGENSFTNHZSII77JJ77CSUIXSOU43MWHH25WP75QYTLNO5UFW6ADH77XWVZGPS2T23N3W2JLODU5SH2FI3XCDOPV2NRZSQRQHPQMZSNYUP5Q2MN6WEMKY6HMMXJAYUKMCHOQVWU4QVFCPPID7AFZXCRYIO6I6U6452JUJJET2BCFOYKSNXNSRXDRRZ5DDAZ6GQLI"
        },
        "device": {
          "deviceId": "amzn1.ask.device.AGF4OPFZFSMNPO4KJC36SMUCFALGJ47WMV62UXUCS7DRDVHXLMPADOPF6HKR3QZIRMUDS5NS3DYRC3TAX5NB5KZOXMSS7ETN3TM5BSVKQ75QXVVTXQDAQA77THPCG36GYZOPYJR3IJQTT2UNFTZLQTMZRNU7TJXBORW2NDV64QMXR5G37AASC",
          "supportedInterfaces": {
            "AudioPlayer": {}
          }
        },
        "apiEndpoint": "https://api.amazonalexa.com",
        "apiAccessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjEifQ.eyJhdWQiOiJodHRwczovL2FwaS5hbWF6b25hbGV4YS5jb20iLCJpc3MiOiJBbGV4YVNraWxsS2l0Iiwic3ViIjoiYW16bjEuYXNrLnNraWxsLjVhMjgzYTJjLTViMWYtNDgzMS04MDJiLTAyODRkN2Y4ZjA0MiIsImV4cCI6MTUzNDI2OTM2MywiaWF0IjoxNTM0MjY1NzYzLCJuYmYiOjE1MzQyNjU3NjMsInByaXZhdGVDbGFpbXMiOnsiY29uc2VudFRva2VuIjpudWxsLCJkZXZpY2VJZCI6ImFtem4xLmFzay5kZXZpY2UuQUdGNE9QRlpGU01OUE80S0pDMzZTTVVDRkFMR0o0N1dNVjYyVVhVQ1M3RFJEVkhYTE1QQURPUEY2SEtSM1FaSVJNVURTNU5TM0RZUkMzVEFYNU5CNUtaT1hNU1M3RVROM1RNNUJTVktRNzVRWFZWVFhRREFRQTc3VEhQQ0czNkdZWk9QWUpSM0lKUVRUMlVORlRaTFFUTVpSTlU3VEpYQk9SVzJORFY2NFFNWFI1RzM3QUFTQyIsInVzZXJJZCI6ImFtem4xLmFzay5hY2NvdW50LkFFSEI0NFBEVE5BTkdFTlNGVE5IWlNJSTc3Sko3N0NTVUlYU09VNDNNV0hIMjVXUDc1UVlUTE5PNVVGVzZBREg3N1hXVlpHUFMyVDIzTjNXMkpMT0RVNVNIMkZJM1hDRE9QVjJOUlpTUVJRSFBRTVpTTllVUDVRMk1ONldFTUtZNkhNTVhKQVlVS01DSE9RVldVNFFWRkNQUElEN0FGWlhDUllJTzZJNlU2NDUySlVKSkVUMkJDRk9ZS1NOWE5TUlhEUlJaNUREQVo2R1FMSSJ9fQ.ItqYTfoRp425OJBakl0Pzroy1SKSg0PSqHHzMmB_HgUSF4MAGPktpuzvPPl1HIzwHdmMn0msT3C3IXaySVHeeKxs2B4m182yjpnUbbKq7BFuUhvPju0uFHiDlWuIMDLT6pRbbktNr0DTphab4xLwLbASfd2oux0nprr1lRQr_w-fX6O60Rxd1Ha7uh81WtlcKQuUoB8ks1ruQ4T5GLBEjW540nGKWHa0bFfI13McaqsVTVdrbPwEGUXFnINcgFqQlGCUe8CvHAESwOI5reeiPPS5WGMRAadRa4kdm8qrqOr1sEmTCmmhYXRb5ONQDyzLZpH4vafRQk8g8ItKNfhlpw"
      }
    },
    "request": {
      "type": "System.ExceptionEncountered",
      "requestId": "amzn1.echo-api.request.498b1001-98ab-4c89-9a58-be087f7df9e3",
      "timestamp": "2018-08-14T16:56:03Z",
      "locale": "en-US",
      "error": {
        "type": "INVALID_RESPONSE",
        "message": "The following directives are not supported: Response may not contain a card"
      },
      "cause": {
        "requestId": "amzn1.echo-api.request.72a26be9-3ef9-46b8-9de0-1e3c3416b873"
      }
    }
  },
  "attributesManager": {},
  "responseBuilder": {}
}`

## Your Environment

* ASK SDK for Node.js used: 2.0.7
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development: 8.10.0
* NPM version used for development: 6.2.0

**Comment by tianrenz** [comment]
Hi @XTron3453 , 

Based on this [documentation](https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#valid-response-types-3),  your responses to `AudioPlayer.PlaybackNearlyFinished` event can not contain a card. 

Regards

**Comment by XTron3453** [comment]
If this is the case, is any way to add the card to the next story?

**Comment by tianrenz** [comment]
Hi @XTron3453 

For ``AudioPlayer`` event, you can not add any card, speech, reprompt. For normal intent request, you can respond the usual way. Please see this [documentation](https://developer.amazon.com/docs/custom-skills/audioplayer-interface-reference.html#playbackstarted) for more information. 

Regards
