### ISSUE TITLE
Is Alexa Wikipedia Skill Code OpenSourced ?

### ISSUE THREAD

**Issue by ujjwalagrawal17** [alexa/alexa-skills-kit-sdk-for-nodejs#449]
I am a Contributor from Wikimedia Commons app team. I would like to know Is Alexa Wikipedia Skill Code OpenSourced? I would like to contribute to it . If yes please share the link. If not I think it should be open Sourced as it is the Aim of Wikimedia Foundation to provide free educational content to the world and all of it's code is open sourced.

**Comment by ujjwalagrawal17** [comment]
Link to the skill https://www.amazon.com/Amazon-Wikipedia/dp/B0722X4JGT

**Comment by ujjwalagrawal17** [comment]
@asisin1

**Comment by tianrenz** [comment]
Hi @ujjwalagrawal17 , 

Thanks for your interest in Alexa skills kit. However, this is an issue that's not relevant to the SDK. We would recommend to post on [Alexa User Voice Forum](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote) to gain more feedback from the community. 

Regards

**Comment by ujjwalagrawal17** [comment]
@tianrenz Thanks for the quick response. As told by you I will post the issue in Forum.

**Comment by ujjwalagrawal17** [comment]
Umm , the forum looks closed for posting @tianrenz can you share some other link ?

**Comment by tianrenz** [comment]
@ujjwalagrawal17 hi this [link](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote) works for me

**Comment by ujjwalagrawal17** [comment]
![screenshot_20180817-020113](https://user-images.githubusercontent.com/19607555/44289774-5719c900-a293-11e8-860c-0b8f606a98fc.png)

The moderators seems quite inactive. I haven't recieved any reply from last 2 days.

**Comment by ujjwalagrawal17** [comment]
@tianrenz can you tell me how should I proceed ?

**Comment by tianrenz** [comment]
All post in the forum are being moderated to control total throughput. Your post should be able to come public in the future!

Regards
