### ISSUE TITLE
Provide an example for reading from a DynamoDB table before the response is returned

### ISSUE THREAD

**Issue by lucky090** [alexa/alexa-skills-kit-sdk-for-nodejs#452]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Please provide an example of how to read from a DynamoDB table, which holds book-items (with id of the book, title, author and releasedate). Nothing about the user, just a simple table filled with simple items. 

## Current Behavior

GetItem/Scan are executed after the return of the function, which makes it difficult, to read from a table.
In alexa-sdk, i could emit the response inside the success-part of the reading-function. Thats somehow not possible anymore - or i didn find the right way.

## Possible Solution

I tried it with promises, callbacks and interceptors, but it wasn't really helpfull. I have no idea, how i can get it to work..

## Your Environment

* ASK SDK for Node.js used: 2.0.7
* Operating System and version: Windows 10

## Node.js and NPM Info
* Node.js version used for development: 
* NPM version used for development: 5.6.0

**Comment by lucky090** [comment]
Hi @tianrenz,
thanks for your answer. As mentioned in the "Current Behavior"-part of my issue, i have a table without a clientId or an userId. Sorry i didn wrote it correctly/specific. I will do it now:

I am already using the PersistentAdapter for retrieving and storing my sessionAttributes. That works like charme - but: i need to read/write from/to a simple dynamodb-table, which holds book-items (as already mentioned). There are no alexa-relevant columns in that table, because it doesn't need it. I use the table also for a web app and i want alexa to get a item from this table and read it to the user.

But i saw that async/await were used inside the skill you mentioned. I will give it a try and hopefully it works with it. If not, it would be great if there would be a example of how to get items, scan or save items into the dynamodb-tables while using the ask-sdk v2.

**Comment by nikhilym** [comment]
@lucky090 Please update the issue once you give it a try.

**Comment by sujitcl** [comment]
@Tianrez
Your solution works beautifully. I was stuck with the same issue of synchronising the handler response to wait for the rest API to return.

The async - await approach is easy to understand and implement 

Thanks to you and @lucky090 for raising the issue too

**Comment by nikhilym** [comment]
@lucky090, hope your problem got resolved. Please reopen the bug if you still have an issue.

**Comment by McGern** [comment]
I'm having the same issue. I wish to use data stored in dynamodb but don't know the "correct" way to reference a second table. I have used the Persistence adapter to store user details which automatically uses the Echo User Id as the table key, but don't have the know-how to either (a) use my own id to reference some other info in the same table or (b) use a second table with similar ease of use as the persistence adapter.

I have seen other lambda examples (non-alexa sdk) which attach to tables, but if there is already a library in use by the Alexa SDJK, I would rather use that that install a second package.

This issue (not the title) exactly describes my problem, so not sure whether to re-open this one or start a new one.

@lucky090 did you manage to get your problem sorted?
