### ISSUE TITLE
Alexa not returning SessionEndedRequest when user speaks nothing on echo show

### ISSUE THREAD

**Issue by rahul04gupta** [alexa/alexa-skills-kit-sdk-for-nodejs#454]
I have found this on the hub... https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/223 but my issue is when I submit my skill for certifcation, it failed because it is saying that session kept open for the skill. Because on echo show, when user doesn't say anything, it is supposed to return sessionEndedRequest so that I can handle that. But it is not returning anything and my session kept open. How to resolve this?

**Comment by tianrenz** [comment]
Hi @rahul04gupta , 

To help facilitate reviewing the issues, please update your issue using our issue template. 

Regards

**Comment by nikhilym** [comment]
Hey @rahul04gupta , since there was no update, we are closing this issue. Please open a new issue following the template, if you are facing any problem with the SDK.
