### ISSUE TITLE
Provide docs how to unit test skill, intent.

### ISSUE THREAD

**Issue by seban** [alexa/alexa-skills-kit-sdk-for-nodejs#456]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Is there any way to unit test properly skill/intent written with Alexa Skills SDK for node.js? 

I implemented some simple request handler:

```
const LaunchRequestHandler = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
  },

  handle(handlerInput) {
    const speechText = 'Welcome to the Alexa Skills Kit, you can say hello!';

    return handlerInput.responseBuilder
      .speak(speechText)
      .reprompt(speechText)
      .withSimpleCard('Hello World', speechText)
      .getResponse();
  },
};
```

I started to test (using mochajs) to be something like
```
describe('LaunchRequestHandler', () => {
  describe('#canHandle', () => {
    context("when request type is equal 'LaunchRequest'", () => {
      it('returns true', () => {
        const handlerInput = {
          requestEnvelope: {
            request: { type: 'LaunchRequest' },
          },
        };
        const result = LaunchRequestHandler.canHandle(handlerInput);

        assert.equal(result, true);
      });
    });

    context("when request type is not equal 'LaunchRequest'", () => {
      it('returns false', () => {
        const handlerInput = {
          requestEnvelope: {
            request: { type: 'NotLaunchRequest' },
          },
        };
        const result = LaunchRequestHandler.canHandle(handlerInput);

        assert.equal(result, false);
      });
    });
  });

  describe('#handle', () => {});
});
```

But to be honest only way how to properly unit test `handle` function? I can just pass some spies, but I think it would be better to check returned object than assuming some code will be called.

**Comment by tianrenz** [comment]
Hi @seban , 

The `handle` function returns a ``Response`` or a ``Promise<Response>`` type. You can just check for the properties such as ``outputSpeech`` in the `Response` to see if they match the expected output. You can even check out the unit tests we have for the SDK. I believe they would provide a good reference. Sample can be found [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/tst/skill/Skill.spec.ts).

Regards

**Comment by seban** [comment]
Superb! Will check this one, thank you.
