### ISSUE TITLE
While i am trying to play mp4 video file using alexa echo dot, it is throwing some error like "Target device doesnot supported the specified directive". What may be the reason.

### ISSUE THREAD

**Issue by sravanvadla** [alexa/alexa-skills-kit-sdk-for-nodejs#459]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by nikhilym** [comment]
Hey @sravanvadla , can you fill in the issue template and provide more information on your skill and the development environment?

**Comment by tianrenz** [comment]
Hi @sravanvadla ,

Echo dot doesn't support display interface or video app interface. Please see this [link](https://developer.amazon.com/blogs/alexa/post/12826e9e-e06a-4ab4-a583-8e074709a9f3/how-to-build-alexa-skills-for-echo-show) for more information. 

Regards

**Comment by tianrenz** [comment]
Closing issue due to empty template. Please feel free to open a new issue with template information filled in.

Regards
