### ISSUE TITLE
VideoApp repromt issue in Alexa device

### ISSUE THREAD

**Issue by koushikSen** [alexa/alexa-skills-kit-sdk-for-nodejs#461]
This is my code 
`   function playVideo(videoSrc, videoTitle, reprompt, pSessionAttributes) {
    var response = {
        "version": "1.0",
        "sessionAttributes": pSessionAttributes,
        "response": {
            "outputSpeech": null,
            "card": null,
            "directives": [{
                "type": "VideoApp.Launch",
                "videoItem": {
                    "source": videoSrc,
                    "metadata": {
                        "title": videoTitle,
                        "subtitle": ""
                    }
                }
            }],
            "reprompt": null
        }
    } this.context.succeed(response);
}
 `
this works fine. but Alexa responds an unhandled exception if I use any string as a "reprompt" value. does Alexa not support this?

**Comment by nikhilym** [comment]
Hey @koushikSen , please fill in the [Issue Template](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md) and provide us with more information for investigating the issue. 

Also by looking at the request, it seems to be unrelated to SDK. We suggest you to check in [Alexa Developer Forums](https://forums.developer.amazon.com/spaces/165/index.html) for more information.

**Comment by koushikSen** [comment]
@nikhilym  yes you are right, this is not SDK issue. I have posted an issue in Alexa forum.

**Comment by nikhilym** [comment]
Hey @koushikSen , thanks for the update. Here is the [issue link](https://forums.developer.amazon.com/questions/183110/alexa-skill-videoapp-reprompt-not-working.html) on forum posts for any users stumbling upon this in future. Closing the issue.
