### ISSUE TITLE
The ask-sdk-dynamodb-persistence-adapter has aws-sdk listed as a dependency.

### ISSUE THREAD

**Issue by AustinMathuw** [alexa/alexa-skills-kit-sdk-for-nodejs#462]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When the ask-sdk is installed, it installs the ask-sdk-dynamodb-persistence-adapter, which is fine, but ask-sdk-dynamodb-persistence-adapter has the aws-sdk listed as a dependency, which then adds the aws-sdk to any skill using the ask-sdk. This is redundant when using Lambda, as Lambda has the aws-sdk preinstalled, which means that having the aws-sdk in your deployment package is adding almost 5.2 MB of fluff to the zipped skill, thus not allowing for the skill to be editable in Lambda.

## Expected Behavior

I expect the ASK SDK to not create redundant node modules and for my small skills to be editable in Lambda.

## Current Behavior

When the ask-sdk is installed, it installs the ask-sdk-dynamodb-persistence-adapter, which is fine, but ask-sdk-dynamodb-persistence-adapter has the aws-sdk listed as a dependency, which then adds the aws-sdk to any skill using the ask-sdk. This is redundant when using Lambda, as Lambda has the aws-sdk preinstalled, which means that having the aws-sdk in your deployment package is adding almost 5.2 MB of fluff to the zipped skill, thus not allowing for the skill to be editable in Lambda.

## Possible Solution

Because Lambda has the aws-sdk node module pre-installed, why should the ask-sdk-dynamodb-persistence-adapter have aws-sdk as a dependency? When removed, my skills become almost 5.2 MB (when zipped) smaller, which allows me to edit in Lambda.

In short, the aws-sdk should be removed as a dependency of ask-sdk-dynamodb-persistence-adapter.

## Steps to Reproduce (for bugs)

Install the ask-sdk (has ask-sdk-dynamodb-persistence-adapter as a dependency) in any skill, then upload to Lambda. You will notice that the deployment package includes the aws-sdk, which is redundant, because Lambda already has the aws-sdk installed.

## Context

Most of my skills are small and I would like to be able to edit them in Lambda. Without this issue, I do not have to worry about removing the dependency every time I update my skill and I really don't like having to manually zip up my package and upload via .ZIP. Also, since the CLI instals the node modules, then uploads, it still does not help me or any of us who would like to edit in Lambda.

## Your Environment

* ASK SDK for Node.js used: 2.0.7
* Operating System and version: Mac OS High Sierra (10.13.4)
* IDE: Visual Studio Code

## Node.js and NPM Info
* Node.js version used for development: 8.9.2
* NPM version used for development: 6.1.0

**Comment by tianrenz** [comment]
Hi @AustinMathuw , 

We understand your concerns about package size. However, our SDK is intended to be used across platforms. The ``aws-sdk`` dependency is required for ``ask-sdk-dynamodb-persistence-adapter`` for deployment in any other environment (i.e. web server).

Regards

**Comment by AustinMathuw** [comment]
I understand, but is there an ability to have those who want to dev for another environment add the aws sdk themselves? I'm asking, because I feel like it is easier to to add the aws-sdk than to remove it (on the skill developers end). Plus, lambda is a service Amazon provides and, by adding the redundant modules, the development experience diminishes for Lambda users.

Basically, with the addition of the redundant files, a very useful feature of Lambda is unavailable...

**Comment by tianrenz** [comment]
Hi @AustinMathuw , 

The dependency listed in the package.json is described as required run time dependency. NPM will attempt to install all packages under that section automatically. 

Regards

**Comment by AustinMathuw** [comment]
I understand that, but I think that you should be able to disable that though, even if its a command for the cli... For example, if the cli knows that the developer is deploying to a lambda endpoint, why take away lambda functionality by adding redundant packages. There does not need to be a fix now, but I think that, in the future, taking away features from recommended hosts should not be allowed. I'm losing a lot of time deploying because of this issue. Many developers may not be aware of how big the aws-sdk is and how not including it would give (most of) them the ability to edit there skill directly in Lambda.

**Comment by tianrenz** [comment]
@AustinMathuw , a skill project dependency of ``aws-sdk`` might differ from what lambda offers. Removing aws-sdk package during cli deployment might cause unexpected behavior of skill in deployment. Plus, ``aws-sdk`` dependency is also required for local testing, CI and unit testing. 

Regards

**Comment by AustinMathuw** [comment]
Alright
