### ISSUE TITLE
Where can I checkout a source for documentation to contribute?

### ISSUE THREAD

**Issue by artemkovalyov** [alexa/alexa-skills-kit-sdk-for-nodejs#463]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Many things are missing from docs, why not crowdsource it?
For example, it's currently stated that you should encode XML related chars that indirectly implies `speak` method won't accept SSML
![image](https://user-images.githubusercontent.com/10460752/45232821-141aa680-b2d1-11e8-96b9-1fcfc96adb31.png)
But it apparently handles it very well. That's just one discovery among many other docs shortcomings.

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by tianrenz** [comment]
Hi @artemkovalyov , 

Thank you for your support in ASK SDK for Node.js. Sources of our docs are located under the [docs](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/docs) folder in our github repository. You are more than welcomed to submit pull request.

Regards

**Comment by artemkovalyov** [comment]
Got it. Thanks. I'll be happy to make updates as I progress with it.
