### ISSUE TITLE
V2 Api lacks support of progressive response feature ?

### ISSUE THREAD

**Issue by fboerncke** [alexa/alexa-skills-kit-sdk-for-nodejs#466]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When migrating my skills from V1 to V2 it seems that there is no support for the "progressive response" feature in V2. At least I do not find any working example in the documentation. This is currently blocking one migration project for one of my customers.

## Expected Behavior
V2 api should support progressive response feature as V1 skills already do. Alternative: If this is possible already please add a working sample skill to the documentation.

## Possible Solution
Add support for progressive response in V2 or provide some working example code.

**Comment by nikhilym** [comment]
Hey @fboerncke , the v2 SDK already supports Progressive Response. 

#406 provides a sample code on how to use Progressive Response through V2 SDK. You can also find sample code in the cookbook examples [here](https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-progressive-response). Is this what you are looking for?

**Comment by fboerncke** [comment]
Thank you so much, this solved my problem. 
Obviously I must have searched at the wrong places.
This ticket can therefore be closed.
