### ISSUE TITLE
Intent attribute missing from request

### ISSUE THREAD

**Issue by greenygh0st** [alexa/alexa-skills-kit-sdk-for-nodejs#470]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
That the intent would be available on the request so the slot values can be retrieved. As seen here 😄 
![image](https://user-images.githubusercontent.com/1551020/45923585-f859f780-beaf-11e8-852f-15dcf7813693.png)
https://developer.amazon.com/blogs/alexa/post/f167aa0f-8abe-4602-b985-65118b3032ca/code-deep-dive-slots-and-session-attributes-in-the-ask-sdk-for-node-js

## Current Behavior
Intent is missing from request object.

![image](https://user-images.githubusercontent.com/1551020/45923557-37d41400-beaf-11e8-914b-05f0b3442c80.png)

## Context
The goal is retrieve the values from the pair of slots and return them to the API to complete the request.

"typescript": "^2.9.0"
"ask-sdk": "^2.0.9"

node: 8.11.3

So any ideas why this is missing?

**Comment by nikhilym** [comment]
Hey @greenygh0st , just to get more context of the problem, did you try invoking the intent through the test console? Does the invocation request from the test console, when you fire that intent, have the corresponding slots present?

**Comment by greenygh0st** [comment]
Sorry for the delayed response. This question had fallen by the wayside and I apologize for that. This issue is outside of the invocation. Within Typescript the "intent" attribute is missing and typescript is erroring on that.

**Comment by greenygh0st** [comment]
It is reachable within canHandle but does not exist when searching within the context of handle.

**Comment by tianrenz** [comment]
Hi @greenygh0st, 

``intent`` is available under ``IntentRequest`` type. You need to case the request envelope to ``IntentRequest`` to let the compiler know of the type info. i.e. ``(handlerInput.requestEnvelope as IntentRequest).request.intent``

**Comment by greenygh0st** [comment]
That did it! 

Though I do have a slight correction:

`(handlerInput.requestEnvelope.request as IntentRequest).intent.slots.<slot-name>`

You can cast the request not the requestEnvelope 😄 

Thanks for the help!
