### ISSUE TITLE
The Response Builder should escape speech for SSML

### ISSUE THREAD

**Issue by ghost** [alexa/alexa-skills-kit-sdk-for-nodejs#472]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When returning speech, e.g. the following way:
```
return handlerInput.responseBuilder
    .speak('This & That')
    .getResponse();
```
it leads to an `invalid SSML Output` error, because `&` isn't valid in SSML. I think instead of using something like `ssml-builder` library, this library should acutally take care of making sure the speech provided gets escaped before it is emitted. This also will directly lead to fewer crashes for skills using this library (especially skills with 'unpredictable' output like when API calls are involved).

## Expected Behavior

This library should escape provided speech according to SSML specs.

## Current Behavior
No escaping is done, it needs to be done manually. Skills trying to emit invalid SSML crash.

## Possible Solution
Implement something like `ssml-builder` does.

## Steps to Reproduce (for bugs)
See above.

## Context
When dealing with skills which return unpretictable speech resulting from API calls, where you simpy don't know if the text is "ssml safe", this leads to frustration, because you have to yet include another library as a middleware and pass every speech through that.

**Comment by tianrenz** [comment]
Hi @warhost ,

Thanks for the suggestion. I'll bring this back to the team and arrange tasks. 

Regards

**Comment by reflexdemon** [comment]
I had written a utility for this issue and it works without failing. We had to let the teams know we cannot have such non XML friendly characters in the responses.

```JS
//stringutil.js
module.exports = {
    speakSafeText: function(input) {
        if (input) {
            return input.toString().replace(/[^a-zA-Z0-9 ]/g, '');
        }
        return input;
    }
}
```
Usage:
```JS
const sutil = require('path/to/stringutil');

...
return handlerInput.responseBuilder
    .speak(sutil.speakSafeText('This & That'))
    .getResponse();
```

I agree this is annoying to do this manually. You may use this as a `quick help`.
