### ISSUE TITLE
transferring data from the context and event object to alexa outputSpeech

### ISSUE THREAD

**Issue by pawelgagorowski** [alexa/alexa-skills-kit-sdk-for-nodejs#476]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I am struggling to find how I can provide alexa with context data. I wonder if this is possible and why my code is wrong. Thank you!

<pre><code>
const Alexa = require('alexa-sdk')

exports.handler = function(event, context, callback) {
var nameFunction = context.getRemainingTimeInMillis();

return {
    data : nameFunction;
   }
 }
 var handlers = {
  "LaunchRequest": function () {
    const text = `The approximate remaining execution time is ${exports.handler.data}`;

    this.response.speak(text);
    this.emit(':responseReady');
  }
}

exports.handler = function(event, context, callback){
  var alexa = Alexa.handler(event, context);
    alexa.registerHandlers(handlers);
    alexa.execute();
}
</code></pre>

**Comment by pawelgagorowski** [comment]
ok sorry for bothering, the answer is very simple :)
 <pre><code>
var handlers = {
  "LaunchRequest": function () {
    const text = `The approximate remaining execution time is ${this.context.getRemainingTimeInMillis()}`;

    this.response.speak(text);
    this.emit(':responseReady');
  }
}
</pre></code>



it is simple, but at the same time I still do not understand it, because if we omit the word new then Alexa is not a constructor. Maybe this is more of a js question, but I would be grateful for the answer. Thanks in advance!
<pre><code>
const A = {};

A.myFunction = function (a,b) {
this.a = a;
this.b = b;
}

const alexa = A.myFunction("data-a", "data-b");

console.log(alexa.a) //undefined
</pre></code>

**Comment by tianrenz** [comment]
HI @pawelgagorowski , 

I would recommend this [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new) which provides a great explanation of the use of `new` keyword. 

Regards

**Comment by tianrenz** [comment]
BTW @pawelgagorowski , have you checked out our v2 SDK yet? It has 100% feature coverage as v1 sdk and more! 

Regards

**Comment by pawelgagorowski** [comment]
I haven't but I will, thanks @tianrenz I am appreciate

Regards

**Comment by nikhilym** [comment]
Closing this issue. @pawelgagorowski , please reopen or create a new issue if you have any questions regarding the SDK.
