### ISSUE TITLE
When will be alexa-skills-kit-sdk-for-nodejs 2.x_public-beta live?

### ISSUE THREAD

**Issue by harikrishnanp** [alexa/alexa-skills-kit-sdk-for-nodejs#478]
When will be https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.x_public-beta live?
Could you please give me an ETA?

**Comment by tianrenz** [comment]
Hi @harikrishnanp , 

Unfortunately, we are not supposed to discuss timelines here. I would recommend to stay tuned to any future update! Features in the public-beta branch will be merged to 2.0.x when it's going GA. 

Regards,

**Comment by ghost** [comment]
Er, I thought it WAS at 2.x? What am I missing?
```
npm install ask-sdk
+ ask-sdk@2.1.0
```

Is there another beta waiting to go live? I'm not moving from 1.x to 2.x until I'm *sure* that there's no big surprises. I'd rather make all the changes in one move from 1 to 2!

**Comment by tianrenz** [comment]
Hi @digitaltoast ,

The ``CanFulfillIntentRequest`` is the only feature in the beta sdk right now. It will not bring breaking changes when move to GA. You can safely migrate to v2 SDK today. :D We are working on bring the beta SDK up to date. At current point, I would suggest stick with the GA SDK. 

Regards
