### ISSUE TITLE
Primary key in dynamoDB

### ISSUE THREAD

**Issue by sohanmaheshwar** [alexa/alexa-skills-kit-sdk-for-nodejs#479]
Hello

Sohan from the Alexa IN team. Is there a way to use a custom primary key for dynamoDB? Currently the ask-sdk uses userId as the default but was wondering if we could use deviceID as a primary key. 

Tried Googling and looking at the docs but couldn't find a definitive answer. 
Thanks in advance!

**Comment by SleepyDeveloper** [comment]
Sohan I just wrote a blog post in Japanese about this. You can override the default values with the PersistenceAdapter. 

Here’s the RTD entry for it. You have to use the custom SkillBuilder. 
https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Managing-Attributes.html?highlight=DynamoDbPersistenceAdapter

**Comment by nikhilym** [comment]
Hey @sohanmaheshwar , as @SleepyDeveloper pointed out, the ``partitionKeyGenerator`` function in the DynamoDb Persistence adapter [configuration](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Managing-Attributes.html?#config-options) is used by the SDK to populate the primary key value in the DynamoDb tables. It is defaulted to ``userId``, but you can override this with any value you need. Does this help?

**Comment by sohanmaheshwar** [comment]
Oh that's great and exactly what I was looking for. Thanks @SleepyDeveloper and @nikhilym 

Closing the issue.
