### ISSUE TITLE
Links in documentation point to nonexistent .html files and not to extant .rst files

### ISSUE THREAD

**Issue by dmichelin** [alexa/alexa-skills-kit-sdk-for-nodejs#480]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Links in documentation point to .html files and not .rst files

## Expected Behavior

Links in documentation should point to current .rst files
## Current Behavior

Currently links in the docs 404
## Possible Solution

Simply change the url endings from .html to .rst
## Steps to Reproduce (for bugs)

Navigate to https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/docs/en/index.rst
Click any link except for the feedback link

**Comment by tianrenz** [comment]
Hi, @dmichelin , 

The .rst files are used to host document on readthedocs.org. They will be compiled to html files. You can view them [here](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/). 

Regards, 
Tianren

**Comment by dmichelin** [comment]
I see, it should still be in the readme. Googling the link turns up very few responses.

**Comment by tianrenz** [comment]
Hi @dmichelin , 

You can find the links to the documentation under the "Technical Documentation" section. We currently have both English and Japanese version available. 

Regards

**Comment by tianrenz** [comment]
Closing the issue now. Please feel free to reopen the issue. 

Regards
