### ISSUE TITLE
There should be a supportsDisplay() function

### ISSUE THREAD

**Issue by chickdan** [alexa/alexa-skills-kit-sdk-for-nodejs#481]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The tutorial for using display directives states the following function should be added and used to detect whether or not a device has a display: 

```javascript
function supportsDisplay(handlerInput) {
    var hasDisplay =
	handlerInput.requestEnvelope.context &&
	handlerInput.requestEnvelope.context.System &&
        handlerInput.requestEnvelope.context.System.device &&
	handlerInput.requestEnvelope.context.System.device.supportedInterfaces &&
	handlerInput.requestEnvelope.context.System.device.supportedInterfaces.Display
    return hasDisplay;
}
```

My suggestion is to provide this function as part of the SDK as it's boilerplate and will most likely be used, I suspect, the same way by everyone (if I am wrong in this, please correct me).

## Expected Behavior

I would like to be able to call `Alexa.supportsDisplay()` or something along those lines and receive a boolean value for whether or not the device has a display.

## Current Behavior

Current behavior is that this function has to be copied and pasted into each skill targeting displays.

## Possible Solution

If the SDK has any access to the `handlerInput`, `requestEnvelope`, `context`, or `System` then it should be a pretty similar solution to the above function.

## Context

It's not a huge burden to copy and paste but it would certainly make developers' code less cluttered with boilerplate.

**Comment by benhawley7** [comment]
As a backup, it would be good if the response builder could check if the current device supports display, and if it doesn't, then remove any display directive we've added, so it doesn't break non-display Echo devices.

**Comment by chickdan** [comment]
@benhawley7 the purpose of this function _is_ to check if the current device supports display. With the returned boolean, skill builders could then properly handle how to build their response (ie., with or without the display directive).

**Comment by sem4phor** [comment]
I recommend you to write your own utility file for common functions like this. Then you could upload it to npm for example (see https://docs.npmjs.com/creating-and-publishing-private-packages) and import it in your project. Such helper ,ethods are out of the ask scope IMO
