### ISSUE TITLE
deviceID Generation algorithm

### ISSUE THREAD

**Issue by MaYinjian** [alexa/alexa-skills-kit-sdk-for-nodejs#482]
We used UUID to find that it was repeated，how alexa create a new deviceID ？  sha256(mac+imei +androidID+ uuid） ?

**Comment by nikhilym** [comment]
Hey @MaYinjian , the SDK doesn't have control on how this data is generated or populated. Please look into [Alexa Developer Forums](https://forums.developer.amazon.com/spaces/165/index.html) for more info

**Comment by MaYinjian** [comment]
Did you mean that you let developers to provide a deviceID to alexa sdk, and the sdk never create the deviceID itself?

**Comment by MaYinjian** [comment]
@nikhilym

**Comment by nikhilym** [comment]
No, I mean the SDK doesn't populate it by itself, we just use the value that the Alexa Service provides. How the service creates the deviceID is not in the scope of the SDK itself.

**Comment by MaYinjian** [comment]
I have different kinds of devices, sucn as tv,phone, watch and so no。When you request the service to get a new deviceID,did you provides any params? such as mac / imei / androidID or something?   
What's more，do you have any suggestion to store the device id ? store it in the share preferences enough?

**Comment by MaYinjian** [comment]
@nikhilym
