### ISSUE TITLE
ask-cli  when using a saml identity provider

### ISSUE THREAD

**Issue by brettswift** [alexa/alexa-skills-kit-sdk-for-nodejs#483]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Current Behavior

I tried `ask init` to see if I could get to the developer console via the CLI. But I see this: 

```
ask init 
? Please type in your new profile name:
 askcli
-------------------- Initialize CLI --------------------
Error: Invalid AWS credential file. Incomplete key/value pair
    at lines.forEach (/usr/local/lib/node_modules/ask-cli/node_modules/aws-profile-handler/lib/ini.js:35:27)
    at Array.forEach (<anonymous>)
    at Function.decodeIniData (/usr/local/lib/node_modules/ask-cli/node_modules/aws-profile-handler/lib/ini.js:13:15)
    at Function.listProfiles (/usr/local/lib/node_modules/ask-cli/node_modules/aws-profile-handler/index.js:64:33)
    at Object.resolve (/usr/local/lib/node_modules/ask-cli/lib/init/aws-resolver.js:20:73)
    at directInitProcess (/usr/local/lib/node_modules/ask-cli/lib/init/init.js:71:17)
    at inquirer.prompt.then (/usr/local/lib/node_modules/ask-cli/lib/init/init.js:148:9)
```
## Context

I have experience using the `ask-cli` for personal use.  I was looking into developing a skill to enable at work.  (private skill).

We use our corporate AD as a SAML identity provider.  I have no way to create a skill for our company unless presumably I use the root account - which we don't want to do.

My question - how do I work with Alexa Skills in our existing accounts?  Maybe I missed a guide somewhere that explains  using a federated login ? 

## Your Environment

* ASK SDK for Node.js used: ask-cli version 1.4.6
* Operating System and version: OSX 17.3.0

## Node.js and NPM Info
* Node.js version used for development:  v10.11.0
* NPM version used for development: 6.4.1

**Comment by nikhilym** [comment]
Hey @brettswift , we would recommend to post this on the [Alexa developer forum](https://forums.developer.amazon.com/spaces/23/index.html) to get more feedback from the community. 

I've forwarded your question to the service team for reply and will update the thread once we get an answer.

**Comment by brettswift** [comment]
I found an existing issue on the forum that was close enough to this one.  However, it is 3 years old and no replies since. 

https://forums.developer.amazon.com/questions/9643/enterprise-level-provisioning-features.html?childToView=189904#answer-189904

Feel free to close this if the developer forum is the place for this.  However, if documentation exists or is to be created, I wonder if this repo would be where most would look for it.

**Comment by RonWang** [comment]
Hey @brettswift 

If looking at your error log, it points to this line https://github.com/novking/aws-profile-handler/blob/master/lib/ini.js#L35. Can you double check your aws credential file and see if that's formatted correctly?

Thanks,
Ron

**Comment by brettswift** [comment]
Oops. R fingered the close button. 

My credentials file is fine. I use my saml generated tokens every day.  

How would that be the problem?  I authenticate with AD using those tokens.  Your ask-init doesn't create keys using our saml identity provider.  

More importantly I can't log in with our identity provider on the console even. 

That's the real question here. 

Are you familiar with the AD authenticated login?

**Comment by brettswift** [comment]
> If looking at your error log, it points to this line https://github.com/novking/aws-profile-handler/blob/master/lib/ini.js#L35. Can you double check your aws credential file and see if that's formatted correctly?

As mentioned, the credentials file is fine, and I have tested it with the aws-cli.

**Comment by RonWang** [comment]
Hi @brettswift 
Could you provide us more details on your issue. CLI manages both Alexa and AWS credentials but relying on defferent authentication domains. Alexa's developer portal uses Login with Amazon and for AWS part I assume your AD usage is based on AWS Cognito for your Federated identity? When I saw your stack trace I thought you meant for the AWS part. But then when I read your post, it seems you are trying to login Alexa's developer portal with non-root account. So could you please tell us which part of authorization you are failing to go through?

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if the issue persists.
