### ISSUE TITLE
Customer profile API along with device location API 

### ISSUE THREAD

**Issue by sukritchakravarty** [alexa/alexa-skills-kit-sdk-for-nodejs#485]
I created two different intents one to get the customer profile data and second to get the device location data.
When I run these two separately in your templates they work fine but when I try to use both of these API's in single lambda function, it gives me an error.
I am not sure how to resolve this.

Here is my code for the intent that fails:

const PERMISSIONS = ['read::alexa:device:all:address'];
const FULL_NAME_PERMISSION = "alexa::profile:name:read";
const EMAIL_PERMISSION = "alexa::profileemailread";
const MOBILE_PERMISSION = "alexa::profile:mobile_number:read";

const LaunchRequestHandler = {
canHandle(handlerInput) {
return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
},
async handle(handlerInput) {
const speechText = Hello, welcome to ${APP_NAME}.;
const repromptText = 'You can say find ABCD';

const { requestEnvelope, serviceClientFactory, responseBuilder } = handlerInput;

const consentToken = requestEnvelope.context.System.user.permissions
  && requestEnvelope.context.System.user.permissions.consentToken;
if (!consentToken) {
  return responseBuilder
    .speak(messages.NOTIFY_MISSING_PERMISSIONS)
    .withAskForPermissionsConsentCard(PERMISSIONS)
    .getResponse();
}
try {
  const { deviceId } = requestEnvelope.context.System.device;
  const deviceAddressServiceClient = serviceClientFactory.getDeviceAddressServiceClient();
  const address = await deviceAddressServiceClient.getFullAddress(deviceId);
  const url_part = `${address.addressLine1} ${address.stateOrRegion} ${address.postalCode}`;
  let response;
  if (address.addressLine1 === null && address.stateOrRegion === null && address.postalCode === null) {
    response = responseBuilder
    .speak(messages.NO_ADDRESS)
    .withSimpleCard(APP_NAME, messages.NO_ADDRESS)
    .getResponse();
  } else {
      await getRemoteData('URL')
      .then((response) => {
        var data = JSON.parse(response);
        ipstat_lat = parseFloat(data.results[0].geometry.location.lat);
        ipstat_lon = parseFloat(data.results[0].geometry.location.lng);
      });
    
    response = responseBuilder
    .speak(speechText)
    .reprompt(repromptText)
    .withSimpleCard(APP_NAME, speechText)
    .getResponse();
  }
  return response;
} catch (error) {
  if (error.name !== 'ServiceError') {
    const response = responseBuilder
    .speak(messages.ERROR)
    .withSimpleCard(APP_NAME, messages.ERROR)
    .getResponse();
    return response;
  }
  throw error;
}
},
};

This works fine as I am using this to get the device data, but when I introduce the lines into this to get the customer profile data it fails:

const upsServiceClient = serviceClientFactory.getUpsServiceClient();
const profileName = await upsServiceClient.getProfileName();

Can you please help me in this?

**Comment by tianrenz** [comment]
Hi @sukritchakravarty , 

Could you please update your issue with our issue template? It helps us a lot to process the information more efficiently. 

Could you also provide log of the error being thrown? What's the error message and status code?

Regards

**Comment by sukritchakravarty** [comment]
## I'm submitting a...

<pre><code>
[x] Other issue - Calling Device address API and Customer Profile API in launch intent
</code></pre>



## Expected Behavior
I am not sure if this is a bug or am I missing something, but I want to know if its possible to call both the API's in a single intent?

## Current Behavior
I am trying to call the device address api and customer profile api in my launch intent and everytime I add the line of code const upsServiceClient = serviceClientFactory.getUpsServiceClient(); and const deviceAddressServiceClient = serviceClientFactory.getDeviceAddressServiceClient(); in the same intent it doesnt give me any output. Unfortunately since I am new to this I dont know where to check what error it is throwing or what error code it is.

## Possible Solution
Do we have a github directory I can see how both are called in a single intent, if there is that would be of great help 

## Steps to Reproduce (for bugs)
 `const PERMISSIONS = ['read::alexa:device:all:address'];
const FULL_NAME_PERMISSION = "alexa::profile:name:read";
const EMAIL_PERMISSION = "alexa::profileemailread";
const MOBILE_PERMISSION = "alexa::profile:mobile_number:read";

const LaunchRequestHandler = {
canHandle(handlerInput) {
return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
},
async handle(handlerInput) {
const speechText = Hello, welcome to ${APP_NAME}.;
const repromptText = 'You can say find ABCD';

const { requestEnvelope, serviceClientFactory, responseBuilder } = handlerInput;

const consentToken = requestEnvelope.context.System.user.permissions
&& requestEnvelope.context.System.user.permissions.consentToken;
if (!consentToken) {
return responseBuilder
.speak(messages.NOTIFY_MISSING_PERMISSIONS)
.withAskForPermissionsConsentCard(PERMISSIONS)
.getResponse();
}
try {
const { deviceId } = requestEnvelope.context.System.device;
const deviceAddressServiceClient = serviceClientFactory.getDeviceAddressServiceClient();
const address = await deviceAddressServiceClient.getFullAddress(deviceId);
const url_part = ${address.addressLine1} ${address.stateOrRegion} ${address.postalCode};
let response;
if (address.addressLine1 === null && address.stateOrRegion === null && address.postalCode === null) {
response = responseBuilder
.speak(messages.NO_ADDRESS)
.withSimpleCard(APP_NAME, messages.NO_ADDRESS)
.getResponse();
} else {
await getRemoteData('URL')
.then((response) => {
var data = JSON.parse(response);
ipstat_lat = parseFloat(data.results[0].geometry.location.lat);
ipstat_lon = parseFloat(data.results[0].geometry.location.lng);
});

response = responseBuilder
.speak(speechText)
.reprompt(repromptText)
.withSimpleCard(APP_NAME, speechText)
.getResponse();
}
return response;
} catch (error) {
if (error.name !== 'ServiceError') {
const response = responseBuilder
.speak(messages.ERROR)
.withSimpleCard(APP_NAME, messages.ERROR)
.getResponse();
return response;
}
throw error;
}
},
};`

`const upsServiceClient = serviceClientFactory.getUpsServiceClient();
const profileName = await upsServiceClient.getProfileName();`

## Context
 I am trying to provide my users a personalized experience thats why I want my skill to take their name, also I am using geocoding from the device address

## Your Environment

* ASK SDK for Node.js used: 2.0
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development: 8.10
* NPM version used for development: latest version

**Comment by tianrenz** [comment]
Hi @sukritchakravarty , 

If you are hosting your skill on AWS Lambda, you can find your log in the CloudWatch log streams. In your lambda function console, go to monitor -> view logs in cloudwatch. Please paste the error logs here if there are any. 

Besides checking the logs, could you please verify the following information: 

1. when you are building the skill instance, did you pass in an `ApiClient`? (No need to do this, if you are using `SkillBuilders.standard`)
2. which version of the `ask-sdk-model` package are you using? (You can find it in the node_modules/ask-sdk-model/package.json)

Regards

**Comment by sukritchakravarty** [comment]
@tianrenz : I did check the logs of CloudWatch but there were no errors.
For APIClient I have included the below code:
![image](https://user-images.githubusercontent.com/38478983/48382470-21b82800-e696-11e8-8bf5-da8669a29b43.png)

ask-sdk-model@1.3.0

Thank you so much for your help.

**Comment by tianrenz** [comment]
Hi @sukritchakravarty , 

Could you try and update your `ask-sdk-model` package to the latest version? the `upsServiceClient` is not present in earlier version SDK. 

Regards,

**Comment by sukritchakravarty** [comment]
@tianrenz : Thank you so much.
It worked like magic :)

**Comment by GitRaghu2019** [comment]
How to update ask-sdk-model? I have similar code to fetch email address but after  below statement const upsServiceClient = serviceClientFactory.getUpsServiceClient(); there are no logs.
cloud watch logs are not giving any hint.

**Comment by nephisto1954** [comment]
Don't know if that may help but looking at the email permission, shouldn't it be `alexa::profile:email:read` instead of `alexa::profileemailread` ?
