### ISSUE TITLE
How to add APL directive in v1 skills?

### ISSUE THREAD

**Issue by CoreyCole** [alexa/alexa-skills-kit-sdk-for-nodejs#486]
This is the only documentation I've found for nodejs APL implementations: https://developer.amazon.com/docs/alexa-presentation-language/apl-support-for-the-nodejs-2-0-sdk-in-your-skill.html

But that is nodejs v2 format. Is it possible to use display templates in v1 skills? What is the name of the function?

**Comment by CoreyCole** [comment]
Found what I was missing: https://developer.amazon.com/docs/alexa-presentation-language/apl-support-for-your-skill.html#add-apl-support-to-your-skill-without-nodejs-20-sdk-support

**Comment by CoreyCole** [comment]
I'm actually still not sure how to add a raw directive like I found in the second link, reopening

**Comment by CoreyCole** [comment]
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/1.x/lib/services/directiveService.js#L28

Are we supposed to use the DirectiveService? where url is the `Alexa.Presentation.APL.RenderDocument`? 😕

**Comment by CoreyCole** [comment]
Using the `_addDirective()` function worked for me:
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/1.x/lib/responseBuilder.js#L337

To help others trying to do this:
```typescript
intentHandler.response._addDirective({
    'type': 'Alexa.Presentation.APL.RenderDocument',
    'token': `prompt-${uuid()}`,
    'document': getPromptDocument(),
    'datasources': getPromptDataSources(prompt)
});
```

**Comment by tianrenz** [comment]
Hi @CoreyCole , 

V1 SDK has been deprecated and doesn't have official support for APL. We do highly recommend to check out our v2 SDK since it will get the latest feature update. :)

In v1 SDK, you can use `this.response_addDirective()` to inject any directive into your response. 

Regards
