### ISSUE TITLE
Question for APL

### ISSUE THREAD

**Issue by waigel** [alexa/alexa-skills-kit-sdk-for-nodejs#491]
Hey,

i submittet a skill to the store. But is was rejected. With this problem: 

```
Issues observed on device with display (Echo Spot):
 
Code references are displayed in the rich GUI cards for your skill. Please remove any code references to make the content user friendly.
```
So i don't understand this problem? If the request include a display size, i resposne with a APL Information... Thats the response...

```json
"directives": [
				{
					"type": "Alexa.Presentation.APL.RenderDocument",
					"document": {
						"type": "APL",
						"version": "1.0",
						"theme": "dark",
						"import": [],
						"resources": [],
						"styles": {},
						"layouts": {},
						"mainTemplate": {
							"items": [
								{
									"type": "Image",
									"source": "https://s3-eu-west-1.amazonaws.com/skill-gluecksrad/energy.png",
									"width": "480px",
									"height": "480px",
									"align": "center",
									"scale": "best-fill"
								}
							]
						}
					},
					"datasources": {}
				}
			]
```

Anybody a solution? In the developer console the output on all devices are ok. So I'can solve the problem with this information at the moment... 

Edit:
Card from Alexa App:
![image](https://user-images.githubusercontent.com/25115243/49109667-993ba900-f28b-11e8-98ae-17f10e0baa3e.png)

**Comment by tianrenz** [comment]
Hi @VerHext , 

The problem seems to be related to the skill card display. You can find it in the home page of Alexa app. Could you update the issue with our issue template and attach a screenshot of the card that skill sent?

Regards

**Comment by waigel** [comment]
Thats the response from lambda: https://pastebin.com/kr7KKzns

**Comment by nikhilym** [comment]
The paste contains the card content different from the card content mentioned in the issue. Can you please provide the response paste of your skill code that is leading to this problem? 

However, the directive seem to work as expected and the response provided in the earlier comment seems to be fine.

**Comment by nikhilym** [comment]
Hey @VerHext , did you get around the problem? Please update the issue if you are still having the problem

**Comment by nikhilym** [comment]
Hey @VerHext , please update the issue in case you fixed anything from the code side. This would help the community in fixing the problem in case someone faces it in future. Thanks!!
