### ISSUE TITLE
ask init Command freezes halfway.

### ISSUE THREAD

**Issue by kuroshi07** [alexa/alexa-skills-kit-sdk-for-nodejs#492]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

In the following situations, I can choose with the arrow keys.

```
> ask init
? Please type in your new profile name:
 default
-------------------- Initialize CLI --------------------
? There is no AWS credentials file found in .aws directory, do you want to set up the credentials right now? (for lambd
a function deployment) (Use arrow keys)
> Yes. Set up the AWS credentials.
  No. Use the AWS environment variables.
  No. Skip AWS credentials association step.
  Abort the initialization process.
```

## Current Behavior

I can not move the arrow keys from there.
I can not `Ctrl + c` it.
I can not `Enter` it.

```
> ask init
? Please type in your new profile name:
 default
-------------------- Initialize CLI --------------------
? There is no AWS credentials file found in .aws directory, do you want to set up the credentials right now? (for lambd
a function deployment) (Use arrow keys)
> Yes. Set up the AWS credentials.
  No. Use the AWS environment variables.
  No. Skip AWS credentials association step.
  Abort the initialization process.
```

## Steps to Reproduce (for bugs)

1. Open command prompt.
1. `> ask init`
2. Press the enter key.

## Context

I want to complete the initialization by executing the command.

## Your Environment

* Operating System and version: Window 10 Home

## Node.js and NPM Info
* Node.js version used for development: 8.1.0
* NPM version used for development: 5.0.3

## NPM Packages Info
* `ask-cli`  version used for development: 1.5.1
* `windows-build-tools` version used for development: 5.0.0(vs2015)

## Other Info
* Python version used for development: 2.7.15
* pip version used for development: 9.0.3

**Comment by nikhilym** [comment]
Hey @kuroshi07 , thanks for the issue. The concerned service team has been informed about this. We will update the issue once we get any information from the team.

**Comment by RonWang** [comment]
Hey @kuroshi07 I replicate your environments by changing the version node version to v8.1.0, I got the same result as you from windows machine. Please use late v8 node runtime (like v8.12.0) for now to unblock yourself, and we will keep posting the result of investigation here.

**Comment by RonWang** [comment]
Hey @kuroshi07 so the root cause is from node v8.1.0 this version. This CLI error is generated from inquirer https://github.com/SBoudrias/Inquirer.js/issues/547 where it links to the node issue at https://github.com/nodejs/node/issues/13557. Please use a later version of node (>v8.1.4) to unblock.

**Comment by nikhilym** [comment]
@RonWang thanks for the update. Hey @kuroshi07 , please update the issue once you test the command after updating your node version

**Comment by kuroshi07** [comment]
@nikhilym @RonWang 
After updating the version of Node to v8.1.4, trying the `ask init` command again succeeded. Thanks for the advice.
