### ISSUE TITLE
CredentialsError: Missing credentials in config - no info in the docs about `.ask/config`

### ISSUE THREAD

**Issue by jmeyers91** [alexa/alexa-skills-kit-sdk-for-nodejs#496]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I'm trying to deploy a skill to another organization using an IAM user provided by the organization, but after setting the credentials in `~/.aws/credentials`, I get this error when I try to run `ask deploy`:

```
[Error]: Get Lambda ARN ask-custom-talk_stem-default failure for custom/default.
CredentialsError: Missing credentials in config
```

## Expected Behavior
The ask CLI should use the credentials in `~/.aws/credentials` like every other AWS service. Or there should at least be some documentation about the `.ask/config` file (I assumed it would be under ["Configuring and Testing Your Skill"](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Developing-Your-First-Skill.html#configuring-and-testing-your-skill), but that contains almost no information about configuring the skill).

## Current Behavior
The ask CLI doesn't load my credentials from `~/.aws/credentials`. The "configuring your skill" documentation doesn't include enough documentation for configuring your skill.

## Possible Solution
Use `~/.aws/credentials` for AWS credentials or include instructions for configuring your skill in the "configuring your skill" section of the docs.

## Context
This is completely blocking us from deploying a skill to our client's AWS account.

## Your Environment
ASK CLI version 1.5.1
Mac OSX v10.14.2

## Node.js and NPM Info
* Node.js version used for development: v9.11.2
* NPM version used for development: v5.6.0

**Comment by RonWang** [comment]
Hey @jmeyers91 

Could you check the profile you use for deploy command does exist in your ~/.aws/credentials file? The credential file will contains your profile name surronded by [ ].

ask-cli does use the aws credentials file for aws credential, and the message "CredentialsError: Missing credentials in config" is actually from aws-sdk's. Let me know if this helps you out!

Thanks,
Ron

**Comment by jmeyers91** [comment]
The profile does exist in `~/.aws/credentials`. I was able to fix the issue by re-running `ask init` and selecting the profile.
