### ISSUE TITLE
Sdk issue

### ISSUE THREAD

**Issue by fuzzykarthik** [alexa/alexa-skills-kit-sdk-for-nodejs#497]
I tried upgrading Alexa version. But it throws error. Can I please help.me.with that. Please refer issue number 2439

**Comment by fuzzykarthik** [comment]
Dear team,
I was using alexa sdk and aws sdk for my lambda function. I tried to upgrate that to version 2. But it is throwing error , not able to rollback my changes as well.
Can you please help me on this
i downloaded from the below link
https://developer.amazon.com/blogs/alexa/post/decb3931-2c81-497d-85e4-8fbb5ffb1114/now-available-version-2-of-the-ask-software-development-kit-for-node-js
but existing modules also throwing error

[ts]
Could not find a declaration file for module 'alexa-sdk'. 'd:/Node Projects/SampleInitial/alexa-mortgage/node_modules/alexa-sdk/index.js' implicitly has an 'any' type.
Try npm install @types/alexa-sdk if it exists or add a new declaration (.d.ts) file containing declare module 'alexa-sdk'; [7016]
module "d:/Node Projects/SampleInitial/alexa-mortgage/node_modules/alexa-sdk/index"

I created separate function to test the lambda layer.But throws the belwo error`

Response:
{
  "errorMessage": "Cannot read property 'update' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)"
  ]
}

**Comment by tianrenz** [comment]
Hi @fuzzykarthik , 

Could you update the issue to use our issue template? Also, could you attach the code snippet of the part throwing the error?

Regards

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen.
