### ISSUE TITLE
ask init doesn't create the expected .ask folder

### ISSUE THREAD

**Issue by unlucio** [alexa/alexa-skills-kit-sdk-for-nodejs#502]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Preamble: this lib's doc is so confusing after 2 days dealing with it I'm not even sure where my head is now. It's undoubtedly extensive but at the same time extremely ripetitive and dispersive. For instance I haven't even been able to find a simple page listing all the objects/namespaces/methods available in the packages :(

## Expected Behavior
`ask init` seems supposed to create a `.ask` directory in the current project root dir, but instead it's creating it under my `home` folder (`~/`).
I say seems because, again, I haven't been able to find a clear piece of doc regarding `init`.

## Current Behavior
After running `init` when I launch `ask deploy` I'm getting the following error:
`[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project that contains the project config in the hidden .ask folder.`
running `find ~/ -name ".ask"` shows only the one created in my home folder.

## Possible Solution
Be less confusing?

## Steps to Reproduce (for bugs)
- create a new project
- run `ask init`
- Setting up ask profile selecting an AWS profile
- grant permissions on the webpage
- verify there's no `.ask` directory in the current folder:
```sh
➜  testSkill git:(master) ✗ ls -lah
total 8
drwxr-xr-x  5 lucio  staff   160B  8 Jan 11:55 .
drwxr-xr-x  3 lucio  staff    96B  8 Jan 14:38 ..
drwxr-xr-x  3 lucio  staff    96B  8 Jan 12:05 lambda
drwxr-xr-x  3 lucio  staff    96B  8 Jan 12:23 models
-rw-r--r--  1 lucio  staff   1.2K  8 Jan 12:06 skill.json
```
- run `ask deploy`
- receive the error message: `[Error]: Failed to deploy. Please ensure current working directory is the root of your skill project that contains the project config in the hidden .ask folder.`
- throw a fit 'cose after 2 days of going around this with no results it start to be frustrating.
- verify there's a `.ask` directory in your home folder:
```sh
➜  testSkill git:(master) ✗ ls ~/.ask
cli_config
```
- wonder why it's there and bang your head on the wall until your nervs calm down.

## Context

It's frustrating me as I'm simply trying to deploy an helloworld!

🤷‍♂️ it's an hello world

## Your Environment

* ASK SDK for Node.js used: 1.5.2
* Operating System and version: MacOS 10.14.2

## Node.js and NPM Info
* Node.js version used for development: v11.4.0
* NPM version used for development: 6.4.1

**Comment by RonWang** [comment]
Hi Luciano, 

The "init" command is used for authorization: https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html#init-command for Alexa skill development. Since it's a user profile, we store the cli_config in the $HOME path. 
What you are looking for is actually the "ask new" command which set the starting template for you along with a project config, which is used to track the property and state of your skill project.

Usually users do "ask init" to authorize, "ask new" to start the project ("ask clone" to start on existing skill), "ask deploy" to deploy the project.

Let me know what you think is the best experiences~
Ron

**Comment by RonWang** [comment]
And can you describe more of your usage for "I haven't even been able to find a simple page listing all the objects/namespaces/methods", what do you mean by that?

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if the problem persists.
