### ISSUE TITLE
please forward] ask-cli installation problem on Mac

### ISSUE THREAD

**Issue by pankaz** [alexa/alexa-skills-kit-sdk-for-nodejs#503]
I was trying to use ask-cli on my Macbook. When I run "sudo npm install -g ask-cli", I get the following error:

`npm ERR! path /usr/local/lib/node_modules/ask-cli/node_modules/mkdirp/bin/cmd.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/ask-cli/node_modules/mkdirp/bin/cmd.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
`
Any help on this front would be really appreciated.

**Comment by reflexdemon** [comment]
did you try `npm install -g ask-cli` without `sudo`?

**Comment by RonWang** [comment]
Hey @pankaz 
First please make sure you don't have ask-cli installed before you run the "sudo npm install -g ask-cli".
Then my question is how do you install the npm? It seems the mkdirp dependency is not found, could you try install that first and then run the installation of ask-cli?
Let me know the result! Thanks~
Ron

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if problem reappear. 

Regards
