### ISSUE TITLE
.addAudioPlayerPlayDirective is not responding after cancel the intent and want to play song again

### ISSUE THREAD

**Issue by Srinivasb0** [alexa/alexa-skills-kit-sdk-for-nodejs#506]
Hello,

I am creating an audio stream by using this template. 
https://github.com/skilltemplates/audio-stream-starter-alexa

Where in here I was able to play the .mp3 file first time in Alexa companion app with the invocation of  Alexa ask Brownie Master to Play. In the process of testing, I was able to stop the music with the Utterance of Cancel or Stop. But the song is not re-playing with the utterance of Play, Resume or Invocation of Alexa ask Brownie Master to Play.

The temporary fix I found here is I have to disable and re-enable the skill to work as like normal with the invocation. Hence this is not a permanent fix, how I can solve this

Here is the skill code

    const STREAMS = [
      {
    "token": "stream-12",
    "url": 'https://s3.amazonaws.com/myprojrct/Merupula+Merisina+-+SenSongsMp3.Co.mp3',
    "metadata" : {
      "title": "Stream One",
      "subtitle": "A subtitle for stream one",
      "art": {
        "sources": [
          {
            "contentDescription": "example image",
            "url": "https://s3.amazonaws.com/cdn.dabblelab.com/img/audiostream-starter-512x512.png",
            "widthPixels": 512,
            "heightPixels": 512
          }
        ]
      },
      "backgroundImage": {
        "sources": [
          {
            "contentDescription": "example image",
            "url": "https://s3.amazonaws.com/cdn.dabblelab.com/img/wayfarer-on-beach-1200x800.png",
            "widthPixels": 1200,
            "heightPixels": 800
          }
        ]
      }
    }
     }
    ];

    const PlayStreamIntentHandler = {
     canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'IntentRequest' &&
      (
        handlerInput.requestEnvelope.request.intent.name === 'PlayStreamIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.ResumeIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.LoopOnIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.NextIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.PreviousIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.RepeatIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.ShuffleOnIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.StartOverIntent'
        
        );
     },
  
      handle(handlerInput) {
       let stream = STREAMS[0];

       handlerInput.responseBuilder
       .speak(`starting ${stream.metadata.title}`)
       .addAudioPlayerPlayDirective('REPLACE_ALL', stream.url, stream.token, 0, null, stream.metadata);
      
       return handlerInput.responseBuilder
      .withShouldEndSession(true)
      .getResponse();
    
      },
    };

    const CancelAndStopIntentHandler = {
      canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'IntentRequest' &&
        (handlerInput.requestEnvelope.request.intent.name === 'AMAZON.StopIntent' ||
        handlerInput.requestEnvelope.request.intent.name === 'AMAZON.CancelIntent'
          );
    
      },
      handle(handlerInput) {
        return handlerInput.responseBuilder
          .speak("Good Bye")
          .addAudioPlayerClearQueueDirective('CLEAR_ALL')
          .addAudioPlayerStopDirective()
          .withShouldEndSession(true)
          .getResponse();
        },
      };

**Comment by tianrenz** [comment]
Hi @Srinivasb0 , 

To help further investigate the issue, could you please provide some cloudwatch log if you have them?

Also, could you please update the issue to use our issue template and provide more detailed description on the part 
>"But the song is not re-playing with the utterance of Play, Resume or Invocation of Alexa ask Brownie Master to Play."

Was there any error message that Alexa says or is it simply non-responsive?

Regards

**Comment by Srinivasb0** [comment]
@tianrenz Thank you for your response.

Here is the log from Cloud watch
    module initialization error: ReferenceError at Object.<anonymous> (/var/task/index.js:404:5) at 
    Module._compile (module.js:652:30) at Object.Module._extensions..js (module.js:663:10) at 
    Module.load (module.js:565:32) at tryModuleLoad (module.js:505:12) at Function.Module._load 
    (module.js:497:3) at Module.require (module.js:596:17) at require (internal/module.js:11:18)

Once I tried to replay the audio after closing the session with replay intent handler, Alexa can able to deliver .speak response, but it's not handling .addAudioPlayerPlayDirective

Here is how the conversation happening
// Play the audio
Alexa ask brownie master to play -------- (PlayStreamIntentHandler responsive)
Starting Stream-1 --------  (.speak(`starting ${stream.metadata.title}` response)
Playing Audio ----------   ( .addAudioPlayerPlayDirective('REPLACE_ALL', stream.url, stream.token, 0, 
                                             null, stream.metadata     response);
// Cancel or stop the audio
Cancel ------- (CancelAndStopIntentHandler  responsive)
Alexa stops the audio

//Replay the Audio 
Alexa ask brownie master to play -------- (PlayStreamIntentHandler responsive)
Starting Stream-1 --------  (.speak(`starting ${stream.metadata.title}` response)
There after alexa is non-responsive

**Comment by tianrenz** [comment]
Hi @Srinivasb0 , 

thanks for providing the info. Could you try using the TEST on Lambda function console to test it? It usually gives a more meaningful error message. 

Regards,

**Comment by Srinivasb0** [comment]
Hi @tianrenz 

This is the error from lambda console, Cannot read property 'type' of undefined and it looks like different error

Response:
{
  "errorMessage": "Cannot read property 'type' of undefined",
  "errorType": "TypeError",
  "stackTrace": [
    "Object.canHandle (/var/task/index.js:61:49)",
    "GenericRequestMapper.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:69:61)",
    "step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:44:23)",
    "Object.next (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:25:53)",
    "/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:19:71",
    "new Promise (<anonymous>)",
    "__awaiter (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:15:12)",
    "GenericRequestMapper.getRequestHandlerChain (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:58:16)",
    "GenericRequestDispatcher.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:133:60)",
    "step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:44:23)"
  ]
}

Request ID:
"0509fe96-64f2-468f-97cc-0a6023d37a70"

Function Logs:
START RequestId: 0509fe96-64f2-468f-97cc-0a6023d37a70 Version: $LATEST
2019-02-01T21:17:11.091Z	0509fe96-64f2-468f-97cc-0a6023d37a70	{"errorMessage":"Cannot read property 'type' of undefined","errorType":"TypeError","stackTrace":["Object.canHandle (/var/task/index.js:61:49)","GenericRequestMapper.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:69:61)","step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:44:23)","Object.next (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:25:53)","/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:19:71","new Promise (<anonymous>)","__awaiter (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:15:12)","GenericRequestMapper.getRequestHandlerChain (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/request/mapper/GenericRequestMapper.js:58:16)","GenericRequestDispatcher.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:133:60)","step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:44:23)"]}
END RequestId: 0509fe96-64f2-468f-97cc-0a6023d37a70
REPORT RequestId: 0509fe96-64f2-468f-97cc-0a6023d37a70	Duration: 264.48 ms	Billed Duration: 300 ms 	Memory Size: 128 MB	Max Memory Used: 62 MB

**Comment by tianrenz** [comment]
Hi @Srinivasb0 , 

It seems on this location `index.js:61:49` you are accessing an undefined object. Would you mind attach that part of code here for debugging purposes?

Regards

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if the issue persists. 

Regards
