### ISSUE TITLE
Peer dependency "ask-sdk-model" version must be updated in ask-sdk-core 

### ISSUE THREAD

**Issue by markuskappel** [alexa/alexa-skills-kit-sdk-for-nodejs#508]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

The version of the peerDependency ask-sdk-model in ask-sdk-core's package.json must be updated to ^1.9.0.

The version of ask-sdk-model in the [ask-sdk-core's package.json](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/package.json#L30) is set to `^1.0.0`.

When upgrading the the ask-sdk from an earlier version (e.g. 2.0.4) to 2.3.0 the version its dependency ask-sdk-core gets also upgraded to 2.3.0. Version 2.3.0 of ask-sdk-core depends on ask-sdk-model ^1.0.0. Hence, ask-sdk-model might not get updated, but it should:

Version 2.3.0 of ask-sdk-core introduced the [`canFulfillIntent`](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/f38c3d02afa5ef00cbd7d4d367bcd45b61f9bd47) and imports `canfulfill` from ask-sdk-model. `canfulfill` was added to [ask-sdk-model in version 1.9.0](https://github.com/alexa/alexa-apis-for-nodejs/commit/7413165a1e8cf6e33029ca00b8dd2bf539eefe40#diff-c1bea112418a506d12c87b03a26bacea).

## Expected Behavior

When updating the ask-sdk to version 2.3.0 the transitive dependency of ask-sdk-model should be updated to 1.9.0.

## Current Behavior

When upgrading the ask-sdk to version 2.3.0 the ask-sdk-model should be upgraded to version 1.9.0.

## Possible Solution

Set the version of the peerDependency ask-sdk-model in ask-sdk-core's [package.json](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/package.json#L30) to 1.9.0.

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by tianrenz** [comment]
Hi @markuskappel , 

Thanks for your input about this. In v2.3.0, we added support for adding `canfullfilIntent` to the `responseBuilder`. Such change requires the the ask-sdk-model > 1.9.0. However, since we are only using the type definition for development work, such dependency requirement would be added as the `dev-dependency`. I'll add this task to our work backlog. 

However, when it comes to upgrading the peer dependency, we need to be more careful as an upgrade of the version dependency will be counted as a breaking change (since developers using version prior to this will be required to upgrade their ask-sdk-model manually as well). 

Regards

**Comment by markuskappel** [comment]
Hi @tianrenz ,

not sure if I fully understand. ask-sdk v2.3.0 requires ask-sdk-core  v2.3.0 and ask-sdk-model: ^1.0.0 as a normal dependencies. That is why ask-sdk-model (v1.2.0 in my case) is in my node_modules. The presence satisfies the *peer* dependency of ask-sdk-core to ask-sdk-model: ^1.0.0 even thought I don't specified that dependency.

My project is written in TypeScript  and `tsc` fails because `canfulfill` is imported in `responseBuilder` but is not exported by ask-sdk-model. This is a problem. Now I have to manually upgrade ask-sdk-model. I need to introduce a direct dependency to ask-sdk-model: ^1.9.0 to fix it. 

About the second part of your response: Which developer might use the ask-sdk-model prior to 1.9.0 while depending on ask-sdk 2.3.0?
I understand that updating the peer dependency to ^1.9.0 would result in a broken package.json for that developer. But that developer is likely using TypeScript and would already be in the situation that I am in right now: compilation fails due to the missing export of  `canfulfill`.

I missed the dependency from ask-sdk v2.3.0 to ask-sdk-model: ^1.0.0 when I created this issue. But now I believe that ask-sdk v2.3.0 should have the updated dependency to ask-sdk-model 1.9.0.

Regards

**Comment by tianrenz** [comment]
Hi @markuskappel , 

Thanks for your input in this. I'll record this info and include a fix in future releases. 

Regards
