### ISSUE TITLE
Alexa doesn't recognize utterances and intents in alexa sdk v2

### ISSUE THREAD

**Issue by falent** [alexa/alexa-skills-kit-sdk-for-nodejs#509]
I was working a long time with alexa sdk v1 and everything works. I change to sdk v2 and it looks strange :( I refactored my code and I can talk with alexa

``
    U: ask mySkill
    A: Hi, what is your name
    U: my name is monica
    A: nice to see you monica
    U: what is my gender?
    A: Your name is Monica and gender female
``
and it works as expected. But... When my user say somethong like that:
``
    U: ask mySkill
    A: Hi, what is your name
    U: I am going to Africa
``
Alexa takes me to apiIntent but I havent defined that utterance!

My Interaction model:
``
    {
        "interactionModel": {
            "languageModel": {
                "invocationName": "mySkill",
                "intents": [
                    {
                        "name": "AMAZON.CancelIntent",
                        "samples": []
                    },
                    {
                        "name": "AMAZON.HelpIntent",
                        "samples": []
                    },
                    {
                        "name": "AMAZON.StopIntent",
                        "samples": []
                    },
                    {
                        "name": "AMAZON.NavigateHomeIntent",
                        "samples": []
                    },
                    {
                        "name": "ApiIntent",
                        "slots": [],
                        "samples": [
                            "What is my gender"
                        ]
                    },
                    {
                        "name": "NameIntent",
                        "slots": [
                            {
                                "name": "name",
                                "type": "AMAZON.US_FIRST_NAME"
                            }
                        ],
                        "samples": [
                            "My name is {name}"
                        ]
                    }
                ],
                "types": []
            }
        }
    }
``
I based my code at https://github.com/alexa/skill-sample-nodejs-hello-world/blob/master/lambda/custom/index.js

I also check in the alexa simulator in the developer portal. The demo skill (skill-sample-nodejs-hello-world) reacts the same. It is expecting "Hello Word" as utternace in InteractionModel but whatever I type alexa forward me to helloWorld intent. Why?

If sdk v2 works in that way it makes no sense to use it :(

Does anybody has idea what I am doing wrong?

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
If user say something which is not defined in utterances Alexa shouldnt try to trigger any intent and return unhandled!

## Current Behavior
I can say anything what makes no sese and Alexa takes me to random intent!

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by tianrenz** [comment]
Hi @falent , 

ASK SDK doesn't have the ability to influence how Alexa resolves user utterances to your skill intent. It receives intent as it is and route it to your defined handler. 

Could you verify that your skill is actually receiving the `ApiIntent` when there's a strange utterance being said? If you have cloudwatch logs, please attach them here. Normally, when user says some unrecognized intent, Alexa will send your skill an "Amazon.FallbackIntent". Did you define an handler to handle that case?

Regards

**Comment by falent** [comment]
Hi @tianrenz,

everything works. Sorry for my silly question. I needed to add FallbackIntent. 

Thank you for your help :)

Best Regards,
