### ISSUE TITLE
Add SessionStart and SessionEnd Callbacks for Tracking Analytics

### ISSUE THREAD

**Issue by rmtuckerphx** [alexa/alexa-skills-kit-sdk-for-nodejs#51]
This issue talks about integrating Mobile Analytics into the ASK:
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/28

I think a better solution would now be SessionStart and SessionEnd callbacks that could be used with any analytics: Amazon Mobile, Google, VoiceLabs, etc.

At a minimum, these callbacks would pass the sessionId.

This would allow any analytics to be used with Alexa skills.

**Comment by stagingreview** [comment]
@smhgit For standard requests, that depends on the shouldEndSession value in your response. If it is true, the sessionEnd request will be called immediately. If it is false and there is no reprompt it will send the sessionEndedRequest after it's timeout. For more information, check [this](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-body-parameters) link.

**Comment by TianTXie** [comment]
@smhgit For standard requests, that depends on the shouldEndSession value in your response. If it is true, the sessionEndedRequest will be send immediately. If it is false and there is no reprompt the sessionEndedRequest will be send after timeout. For more information, check [this](https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html#request-body-parameters) link.

**Comment by Amazon-tianrenz** [comment]
Closing the issue for now. Please open an new issue with our issue template if the question persists.
