### ISSUE TITLE
ask-sdk issue when creating Reminders

### ISSUE THREAD

**Issue by lekanoni20** [alexa/alexa-skills-kit-sdk-for-nodejs#511]
handlerInput.serviceClientFactory.getReminderManagementServiceClient is not a function

**Comment by tianrenz** [comment]
Hi @lekanoni20 , 

Could you update your issue with the template?

We need information such as the version of ask-sdk-model you are using to identify the issue. 

Regards, 
Tianren Zhang

**Comment by tianrenz** [comment]
Closing the issue due to inactivity and insufficient information for investigation. Please feel free to open a new issue using our template if the problem persists. 

Regards
