### ISSUE TITLE
Types for Slot are incorrect

### ISSUE THREAD

**Issue by dgreene1** [alexa/alexa-skills-kit-sdk-for-nodejs#512]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[X ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

The d.ts files would have correct types for the slot values that reflect how they look with the raw JSON. For instance, an event can have slots with two different shapes (as shown below). In some cases there is a `value` property, and in other cases the `value` property is undefined. The types say that `value` will always be a string.
```
"intent": {
			"name": "OrgSelection",
			"confirmationStatus": "NONE",
			"slots": {
				"ideaWords": {
					"name": "ideaWords",
					"confirmationStatus": "NONE"
				},
				"suggestion": {
					"name": "suggestion",
					"value": "world peace",
					"confirmationStatus": "NONE",
					"source": "USER"
				}
			}
		},
```

## Current Behavior

If you type `slots.ideaWords.value.toLowerCase()` you would get a runtime error because there is no `toLowerCase` on `undefined`. 

## Possible Solution

If I were to represent these types in TypeScript I would do the following:
```
interface ISlotBase {
    'name': string;
    'value'?: string;
    'confirmationStatus': SlotConfirmationStatus;
    'resolutions'?: slu.entityresolution.Resolutions;
}
export interface ISlotUnFilled {
    'confirmationStatus': "None"
}
export interface ISlotFilled extends ISlotBase {
    'value': string;
    'confirmationStatus': SlotConfirmationStatus;
}
export type Slot = ISlotUnFilled | ISlotFilled 
```
Now, I understand that these types are part of the swagger types that are autogenerated. So the solution might have to be enacted in anther repo. But then this repo and the ask-sdk-models repo would need to get their versions bumped for the types to be upgraded. So this seems like a good place to post the issue.

## Steps to Reproduce (for bugs)

Create an intent with a not required slot. Utter something that does not fill the slot. Observe that the JSON does not have a `.value` on the slot you've made even though the types say that if a slot exists it will always have a string for `.value`. This can also be seen in the JSON above.

## Context

Junior developers on my team will be unable to identify quickly that they have runtime bugs. Now we have to more stringently review the code. So if the types can be upgraded, that would help us deliver more value to our customers faster.

## Your Environment

* ASK SDK for Node.js used: 2.1
* Operating System and version: Windows 10 locally, Lambda with Node 8+ at runtime

## Node.js and NPM Info
* Node.js version used for development: Node 8.9.3
* NPM version used for development: 5.5.1

**Comment by tianrenz** [comment]
Hi @dgreene1 , 

Thanks for your input. I will bring this back to our team and discuss the fix. 

Regards

**Comment by tianrenz** [comment]
HI @dgreene1 , 

In the latest ``ask-sdk-model`` [release](https://github.com/alexa/alexa-apis-for-nodejs/blob/master/ask-sdk-model/index.ts#L510), we've updated the ``value`` field to be optional. This should fix the incorrect typing definition as you mentioned above. 

Closing the issue for now. Please feel free to reopen if the issue persists. 

Regards

**Comment by dgreene1** [comment]
@tianrenz does that mean that this library will get a version bump and a yarn upgrade to include the model changes?

**Comment by tianrenz** [comment]
Hi @dgreene1 , 

The changes are already released in the latest version v1.12.0

Regards

**Comment by dgreene1** [comment]
Thank you! I guess I should have installed GreenKeeper by now or something. You’re the best @tianrenz :)

**Comment by tianrenz** [comment]
@dgreene1 Thanks for your support in ASK SDK. Please let us know if you have any more questions.
