### ISSUE TITLE
How to use .withAutoCreateTable(true) in ask-sdk2.0 such as to avoid creation of a dynamo db table every time i run the lambda function

### ISSUE THREAD

**Issue by aishjain** [alexa/alexa-skills-kit-sdk-for-nodejs#514]
Basically I am using .withAutoCreateTable(true) in ask-sdk2.0 to create a dynamo db table in order to store the session attributes but every time i run the lambda function a db is created again and since the name remains the same it overrides the last one resulting in loss of data.Any solution would be helpful.Thank you!
PS-the question might seem a bit too naive but I ma new to it sorry for it

**Comment by tianrenz** [comment]
Hi @aishjain , 

I tried with a test skill and was not able to replicate the issue. The table was only created the first time and any subsequent call will not recreate the table. 

To facilitate the investigation, would you mind update the issue using our issue template and provide all the information on there?

Regards

**Comment by tianrenz** [comment]
closing the issue due to inactivity. Please feel free to reopen if problem persists.
