### ISSUE TITLE
ask-cli clone fails with AccessDeniedException

### ISSUE THREAD

**Issue by tholu** [alexa/alexa-skills-kit-sdk-for-nodejs#517]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When trying to clone an existing Alexa Skill, it fails with:

```
[Error]: Get Lambda function error.
AccessDeniedException: User: <user> is not authorized to perform: lambda:GetFunction on resource: <resource>
```

I have setup the IAM policy according to: https://developer.amazon.com/de/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html (in detail: https://developer.amazon.com/de/docs/smapi/manage-credentials-with-ask-cli.html#create-aws-credentials).

The JSON representation of the policy is:
```
{
    "Version": "2012-10-17",
    "Statement": {
        "Effect": "Allow",
        "Action": [
            "iam:CreateRole",
            "iam:GetRole",
            "iam:AttachRolePolicy",
            "iam:PassRole",
            "lambda:AddPermission",
            "lambda:CreateFunction",
            "lambda:GetFunction",
            "lambda:UpdateFunctionCode",
            "lambda:ListFunctions",
            "logs:FilterLogEvents",
            "logs:getLogEvents",
            "logs:describeLogStreams"
        ],
        "Resource": "*"
    }
}
```

`ask init` works fine. `ask clone` also lists my skill properly, and it starts cloning it. It fails with the error above, despite explicitly being allowed without resource restriction. The policy is assigned to a group, and the user is in the group.

## Expected Behavior

It should properly clone the Alexa skill without error.

## Current Behavior

Output of `ask clone`:
```
? List of all your skills. <Skill>
-------------------- Clone Skill Project --------------------
[Warn]: Project with same name existed. Project will be overwritten.

Project directory for Skill created at
    ./Skill

Skill schema for Symptoma created at
    ./Skill/skill.json

Skill model for de-DE created at
    ./Skill/models/de-DE.json
Skill model for en-US created at
    ./Skill/models/en-US.json

[Error]: Get Lambda function error.
AccessDeniedException: User: <user> is not authorized to perform: lambda:GetFunction on resource: <resource>
```

## Possible Solution

Is there a necessary permission missing in the initial policy setup?

## Steps to Reproduce (for bugs)

Follow Quickstart guide after setting up an Alexa skill: https://developer.amazon.com/de/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html

Try to run `ask init` and after successful initialization, try to clone your Skill with `ask clone`. 

## Context

Trying to develop my Alexa skill locally.

## Your Environment

* ASK CLI 1.6.2
* Operating System and version: MacOS 10.14.3

## Node.js and NPM Info
* Node.js version used for development: v11.10.0
* NPM version used for development: 6.7.0

**Comment by tholu** [comment]
The problem seems to be less likely an "Access denied" kind of error, but more like an "Lambda function not found" error, as `ask lambda download` shows nothing to choose from.

When I look at my AWS Lambda console, there are no Lambda functions at all (despite deploying the skill and getting some Lambda function ID in the "Endpoint" menu on the Alexa Developer Console).

**Comment by RonWang** [comment]
Hey @tholu 

According to your description (since you can get the Lambda function ARN), are you first creating the Alexa hosted skill through website and trying to move your development to local using ask-cli?

If so, because the Lambda function for the hosted skill is actually owned by Alexa, you could not download it using your aws account. This is why you got the "Access denied" error. 

For now to unblock your cli's deploy command, you can copy the Lambda source code down to your project, modify the api endpoint in skill.json by pointing the "sourceDir" and "uri" correctly to create your own Lambda for the skill deployment (instructions at https://developer.amazon.com/de/docs/smapi/ask-cli-intro.html#deploy-skill)

Thanks,
Ron

**Comment by tholu** [comment]
@RonWang Thanks, this makes sense - it works for me this way now, `ask deploy` was successful. Would be good to add this to the documentation somewhere.
