### ISSUE TITLE
How to develop during certification?

### ISSUE THREAD

**Issue by mkliu** [alexa/alexa-skills-kit-sdk-for-nodejs#519]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

My skill is in certification phase, during this time I can't deploy changes. The process takes many days, what's the best practice for development during this phase?

**Comment by RonWang** [comment]
Hey @mkliu 

[ask-cli](https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html) has a solution towards this issue by using the profile for your skill project. 

You can create a new profile, say you name it "dev", initiated with a different Alexa (Amazon) account and a different AWS account/user than the one you are using for your current skill (This will promise you won't influence your original skill especially its Lambda function). Then you can simply run "ask deploy --profile dev", and CLI will create your skill in a totally different environment decided by "dev" profile. With this method, you are treating your "default" profile as a live stage. You can keep deploying using "dev" profile while waiting for certification, and "ask deploy" your work when using the "dev" profile, once you are allowed to update live Lambda and skill.

Please look at this [page](https://developer.amazon.com/docs/smapi/manage-credentials-with-ask-cli.html#amazon-credentials) to have a straightforward understanding of CLI profile if you want to know more about it.

Hope it helps,
Ron

**Comment by mkliu** [comment]
Thanks for the reply @RonWang , this looks like a workable temp solution. thanks!
