### ISSUE TITLE
Where to get slot values in intent function handler?

### ISSUE THREAD

**Issue by shaunwarman** [alexa/alexa-skills-kit-sdk-for-nodejs#52]
I'm having a hard time with the best approach to pull out slot values in the intent function handlers.

So for example:
utterance:
```
getFactAbout get fact about {name}
...
```

intent:
```
{
...
"intent": "getFactAbout",
"slots": [{
  "name": "name",
  "type": "string"
}]
...
```

handler:
```
getFactAbout: function () {
  const name = this.event.request.intent.slots.name.value;

  this.emit(":tell", name + " is ....");
}
```

Is this the correct approach? `this.event.request.intent.slots.name.value` has the value of the name passed in via an utterance like `"Get fact about shaun"`. Where the value above would be `shaun` taken from the utterance and available in the handler?

Also, what other values are available on `this` object? (e.g. `this.attributes` and `this.events`)

**Comment by bclement-amazon** [comment]
Will track this via #26 . Looking into the PR now
