### ISSUE TITLE
Catalog associated with custom skill? 

### ISSUE THREAD

**Issue by mkliu** [alexa/alexa-skills-kit-sdk-for-nodejs#520]
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Ask-cli allowed me to associate a catalog with my custom skill. But looks catalog isn't supported on custom skill? If so the cli should probably blocks this scenario to avoid confusion?

**Comment by RonWang** [comment]
Hi @mkliu 

Thanks for your post. Yes that's correct, catalog is not supported in custom skill, but you can still associate catalog with music skills. So far this is what this API is mostly used for. We will implement the validation in skill association to check if the skill is one of allowed skill types in SMAPI service, to avoid confusion.

Thanks,
Ron
