### ISSUE TITLE
Testing & Debugging experience

### ISSUE THREAD

**Issue by davinci26** [alexa/alexa-skills-kit-sdk-for-nodejs#527]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x] Other... Please describe:
</code></pre>

## Testing & Debug experience

I am not sure what are the debugging + code quality expectations for Alexa skills. There are various issues here. 

1. There is no official test framework for alexa skills. On top of that, even the examples [highlowgame](https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/lambda/custom/index.js) do not have tests.
2. ASK cli deploy & simulate is a way for debugging a skill but there are some issues with that. For start it takes a lot of time to deploy a skill (~15sec) and more importantly  if you have a bug the error message is `"An unexpected error occurred."`

There are solutions offered in the web #70 #134 but is the expectation for the developer to go through the repo issues to test his skill?

I would love to hear your thoughts on this.

**Comment by jmeyers91** [comment]
I'm also interested in this. One solution I've considered for testing is to manually pass custom payloads through the lambda handler. For example:

tests/handler.test.js

```js
const handler = require('../lambda/custom');

describe('Lambda handler', () => {
  test('Should launch successfully', async () => {
    const event = { /* custom event goes here */ };
    const context = { /* custom context goes here */ };
    const response = await new Promise((resolve, reject) => {
        handler(event, context, (error, response) => {
          if(error) reject(error)
          else resolve(response);
        })
    });
    // check if response matches expected response
  });
});
```

I haven't tried this yet. Unfortunately alexa events and responses are deeply nested and complicated, so most of the work here would probably be spent reverse-engineering the SDK to figure out how to structure the test event.

I've also spent far too much time trying to debug "An unexpected error occurred.". I've even gone as far as wrapping everything I can in async `try/catch` blocks, but somehow I still end up with unhandled errors that produce no meaningful response and aren't logged in cloudwatch. This is what my handler's index.js looks like:

```js
const Alexa = require('ask-sdk-core');

try {
  const handlers = require('./handlers');

  const wrappedHandlers = handlers.map(handler => ({
    ...handler,
    async handle(handlerInput) {
      try {
        console.log(`Running handler ${handler.name}`, JSON.stringify(handlerInput, null, 2));
        const response = await handler.handle(handlerInput);
        console.log(`Successfully ran handler ${handler.name}`, JSON.stringify(response, null, 2));
        return response;
      } catch(error) {
        console.log(`Failed to run handler ${handler.name}`, error.stack);
        throw error;
      }
    },
  }));

  exports.handler = Alexa.SkillBuilders
    .custom()
    .addRequestHandlers(...wrappedHandlers)
    .addErrorHandlers(require('./handlers/error'))
    .lambda();
} catch(error) {
  console.log('Fatal initialization error', error);
  exports.handler = Alexa.SkillBuilders
    .custom()
    .addRequestHandlers({
      canHandle() { return true; },
      handle(handlerInput) {
        return handlerInput.responseBuilder
          .speak(`Initialization error`, error.stack);
      },
    })
    .lambda();
}
```

As you can see, everything except the ask-sdk import is wrapped in `try/catch` blocks, but somehow errors are still slipping through.

**Comment by anadaz** [comment]
This is what I do for testing lambda locally:

- Install this npm package https://www.npmjs.com/package/lambda-local
`npm install -g lambda-local`

- Capture all requests json from developer portal (launch, all intents, stop or cancel), save each in a separate file
-  run this command in terminal or create npm script 
`lambda-local -l ./lambda/custom/index.js -h handler -e ./lambda/custom/debug/launch.e.json`

- I get the response json in terminal
- run the test command for each request json you captured

Also, you don't have to deploy the whole skill every time, you can deploy lambda only:
`ask deploy -t lambda`

I hope this helps

**Comment by davinci26** [comment]
I ended up using the [bespoken virtual-alexa framework](https://github.com/bespoken/virtual-alexa) for testing purposes.

Still I would love to see what is the Alexa-team recommendation on the subject. Basically I would love to see what the team that developed SDK considers best practices in terms of skill development. :)

**Comment by ShenChen93** [comment]
Hi guys,

Thanks for your patient. We have already noticed that the current testing experience is not user friendly, and we will improve it for sure. Thanks for posting this issue :) Closed this issue for now
