### ISSUE TITLE
Docs: SsmlUtils not documented

### ISSUE THREAD

**Issue by jacobweber** [alexa/alexa-skills-kit-sdk-for-nodejs#530]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
N/A

## Current Behavior
The [docs](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Building-Response.html#available-methods) refer to SsmlUtils, but don't provide an example or API to describe how to use it.

## Possible Solution
N/A

## Steps to Reproduce (for bugs)
NA/

## Context
N/A

## Your Environment
N/A

## Node.js and NPM Info
N/A

**Comment by tianrenz** [comment]
Hi @jacobweber , 

Thanks for the tips. I will add a task to our backlog!

Regards

**Comment by tianrenz** [comment]
Hi @jacobweber , 

We've added documentation for all ASK SDK utilities in the latest [commit](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/884a904979bc23db217b4f06acd946ecec006a01)! Closing this issue for now. Please feel free to reopen if problem persists!

Regards
