### ISSUE TITLE
Certificate check fails when requests originate from the Alexa Developer Console

### ISSUE THREAD

**Issue by juliaqiuxy** [alexa/alexa-skills-kit-sdk-for-nodejs#533]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

Certificate check should pass when valid regardless of where requests originate from i.e. Alexa Developer Console or a physical device. 

## Current Behavior

Signature validation fails when requests originate from the Alexa Developer Console.

## Possible Solution

n/a
## Steps to Reproduce (for bugs)

[My Alexa skill](https://github.com/juliaqiuxy/slopeninja-backend/blob/master/src/api.js#L174-L180) is open source so feel free to fork it if you want to be able to reproduce the issue.

## Context

I'm hosting my skill as a custom web service and having difficulty getting sig verification to work when using the Alexa Developer Console. Note that it seems to be working fine when requests are dispatched via a physical device.

I'm using [alexa-verifier](https://github.com/mreinstein/alexa-verifier) to handle sig verification.

When validation is turned off, the functional tests fail as follows which is expected:

<img width="758" alt="Screen Shot 2019-03-26 at 4 31 04 PM" src="https://user-images.githubusercontent.com/10065050/55041092-b0479900-4fe8-11e9-8429-25d03c70c42a.png">

I'm able to get the functional tests to pass when I have validation turned on:

```js
koaAlexa({
  skill,
  validate: true,
})(ctx);
```

<img width="778" alt="Screen Shot 2019-03-26 at 4 37 19 PM" src="https://user-images.githubusercontent.com/10065050/55041100-bb9ac480-4fe8-11e9-880c-445ff4bce252.png">

However, when validation is turned on, Alexa Developer Console fails with "There was a problem with the requested skill's response". The odd thing is that the app launches successfully. But any other request after fails with the same message. 

<img width="289" alt="Screen Shot 2019-03-26 at 4 38 19 PM" src="https://user-images.githubusercontent.com/10065050/55041105-c3f2ff80-4fe8-11e9-981e-865989b1e532.png">

My skill is failing certification because of this issue. Here's an excerpt from the email I received from the Alexa Skills Team:

> Issues observed on devices with display (Echo Show, Echo Spot)
>
> 1. When invoking the skill with one or more of the intent(s) or sample utterances, the skill’s response is irrelevant to the request or contains an error. 
>
> Issue: [GetSnowConditionsIntent] Intent
>
> Steps To Reproduce:
>
> User: "Alexa, open slope ninja"
>
> Skill: "Welcome to Slope Ninja! Here’s your snow update: It’s currently 14 degrees Fahrenheit in Lake Tahoe, Everyone’s abuzz with reports of snow. 5 resorts reports of pow! If you’re planning to hit the mountains, currently, on CA-89, chains, all-wheel-drive or snow tires are required, on I-80, CA-267, and CA-88, chains or all-wheel-drive with snow tires are required, CA-89 is partially closed. For resort specific conditions, you can say "tell me snow conditions at Squaw Valley" or your favorite resort, or, you can say cancel... What can I help you with?"
>
> User: "how about homewood"
>
> Skill: "There was a problem with the requested skill's response" 
>
> Please see our Submission Checklist for guidance on intent responses.
>
>Additional, please refer to our documentation regarding the implementation of Built-in Intents.

Evidently, they are also using the Alexa Developer Console to run their tests.

Possibly related to #434

## Your Environment

* ASK SDK for Node.js used: ^2.224.1
* Operating System and version: macOS High Sierra

## Node.js and NPM Info
* Node.js version used for development: v9.11.1
* NPM version used for development: 5.6.0

**Comment by tianrenz** [comment]
Hi @juliaqiuxy , 

Since you are using alexa-verifier  to handle request validation, it's likely that the problem comes from their part. Would you mind to open an issue on their github repo while we are investigating this issue?

Currently we have an open issue #434  tracking the feature request for validating request URL, signature, etc. 

Regards

**Comment by juliaqiuxy** [comment]
@tianrenz Thanks. Created an issue, mreinstein/alexa-verifier/issues/64, on alexa-verifier as well.

**Comment by ShenChen93** [comment]
New package ask-sdk-express-adapter is available on NPM now, which make it easy to host skill as webservice. Therefore, close the issue. Please feel free to reopen if there's any problems.
