### ISSUE TITLE
Response builder returns null when called separate file?

### ISSUE THREAD

**Issue by dillonharlessNHRMC** [alexa/alexa-skills-kit-sdk-for-nodejs#537]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

## Expected Behavior
I would expect the responseBuilder to speak back to Alexa no matter where it is called, as long as it's
surrounding function has access to the handlerInput. 

## Current Behavior
It always returns null, even after using Promises
to ensure the data is there.

## Steps to Reproduce (for bugs)
I don't believe this is a bug... I'm pretty confident I'm just misunderstanding something.

## Context
I'm rewriting a skill that was written before I got to my company. They wrote it in v1 and I'm rewriting it in v2. They used a helper called speechHelper that reaches out to s3, and uses the the return data
to do ' this.emit(:ask, data...) '.
I would like to retain this modularity, so I added a parameter to the helper file's function so it could accept the handlerInput. Then I called it from the intentHandler like they did before. I don't get any errors, and my console.log statements which are on the lines right above the responseBuilder print the
data. But it always returns null. Something I'm missing or forgetting about the responseBuilder maybe?

Thanks for any help!

## Your Environment

* ASK SDK for Node.js used: v2
* Operating System and version: Windows 10

## Node.js and NPM Info
* Node.js version used for development: 8.12.0
* NPM version used for development: 6.4.1

**Comment by hideokamoto** [comment]
Hi.
Could you share your code in the ticket?

The responseBuilder will not return any object without calling `getResponse()` method.

## Show the response JSON
```javascript
const response = handlerInput.responseBuilder
      .speak(speakOutput)
      .reprompt(repromptOutput)
      .getResponse()
console.log(response)
```

## Not show the response JSON
```javascript
const response = handlerInput.responseBuilder
      .speak(speakOutput)
      .reprompt(repromptOutput)
console.log(response)
```

**Comment by dillonharlessNHRMC** [comment]
This was a typo on my part, we can close it. I missed a return statement.
