### ISSUE TITLE
AWS CodeCommit not compatible to Alexa ASK CLI

### ISSUE THREAD

**Issue by StefanV85** [alexa/alexa-skills-kit-sdk-for-nodejs#550]
Hello 
The AWS CodeCommit Repositorys doesn't have an URL which ends with ".GIT"
e.g. 
`https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/XXXX-Alexa-Template`

Unfortunately in the ASK CLI is a Check that a Valid GIT URL must end with .GIT
Its in ask-cli\lib\utils\url-utils.js    Method: isUrlWithGitExtension 

If i modify this check, the ASK CLI works very fine with CodeCommit Repositorys.
e.g.
ask new --url https://git-codecommit.eu-west-1.amazonaws.com/v1/repos/XXXX-Alexa-Template

Would be very fine if someone could fix this issue.

Kind Regards
Stefan

**Comment by RonWang** [comment]
Hi Stefan,

Thanks for posting your usage over this command, I think it's a valid use case. We will investigate how to accept a broader range of URL inputs as well as keeping it secure.

Thanks,
Ron

**Comment by nikhilym** [comment]
Since this issue is related to ASK-CLI, it's better to track it on the CLI repo. @RonWang can you transfer this to the corresponding repo?

**Comment by StefanV85** [comment]
is there anything new about this? i updated the ask cli and have again the same problem. but my hack doesn't work anymore. if i change again the url-utils.js the error doesn't apear, but the ask cli is not asking about git credentials... it hangs... and doesn't create my skill.

**Comment by RonWang** [comment]
@StefanV85 Close this issue and please head over to https://github.com/alexa/ask-cli/issues/269 for further discussion.

**Comment by kakhaUrigashvili** [comment]
@RonWang opened a PR https://github.com/alexa/ask-cli/pull/273
