### ISSUE TITLE
TypeError: Cannot read property 'locale' of undefined

### ISSUE THREAD

**Issue by naraenmd** [alexa/alexa-skills-kit-sdk-for-nodejs#552]
Hi guys, can anyone help me with this issue  

2019-05-21T09:47:51.281Z7b9825eb-7e05-4494-8980-6e6661cf13ef 
[index.js.zip](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/files/3202169/index.js.zip)
TypeError: Cannot read property 'locale' of undefined
at Adapter.execute (/var/task/node_modules/ask-sdk-v1adapter/dist/adapter.js:126:42)
at handler (/var/task/index.js:404:7)

**Comment by hideokamoto** [comment]
Will you check the skill request?
eg). `console.log(event)`

**Comment by naraenmd** [comment]
yes @hideokamoto . Why am I facing this issue?any ideas please

**Comment by hideokamoto** [comment]
I'm no longer using alexa-sdk and v1-adapter.
But i think we need to check the request parameters.

Will you add `console.log()` like this?
You can check the entire request log in your CloudWatch Logs console.

```javascript
exports.handler = function (event, context, callback) {
 console.log(event)
  const alexa = Alexa.handler(event, context);
  alexa.registerHandlers(handlers);
  alexa.execute();
};
```

**Comment by ShenChen93** [comment]
@naraen1117 

Sorry for responding late. Have you tried to log the event just like hideokamoto mentioned. It would be great if you can paste the event logs here, so we can use that to narrow down the problem.

Thanks,
Shen

**Comment by ShenChen93** [comment]
Close for now, please feel free to reopen
