### ISSUE TITLE
Add example for updating dynamic entities outside of launch intent

### ISSUE THREAD

**Issue by jakerye** [alexa/alexa-skills-kit-sdk-for-nodejs#553]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I want to update dynamic entities from a non-launch intent.

## Expected Behavior

What I really want is:
  1. (User) "Alexa, ask Board Game Bot to teach me Catan"
  2. (Alexa) "Catan is played by..."

Where the game type (e.g. Catan) can use entity resolution and be resolved against a list that is loaded at runtime (e.g. to resolve to Settles of Catan).

What I'd be happy enough with:
  1. (User) "Alexa, ask Board Game Bot to teach me game rules"
  2. (Alexa) "What game would you like me to teach?"
  3. (User) "Catan"
  4. (Alexa) "Catan is played by..."

## Current Behavior

The only way I have seen to get the dynamic entities loaded in is from the following interaction:
  1. (User) "Alexa, open Board Game Bot"
  2. (Alexa) "Welcome! To learn the rules of a game, say teach me the rules of any game."
  3. (User) "Teach me the rules of Chess"
  4. (Alexa) "Chess is played by..."

Where saying "open Board Game Bot" triggers the launch intent that updates the game type entities.

## Possible Solution

For the ideal use case: I'd want an interaction similar to what IFTTT uses where I can provide an endpoint to return a list of options at runtime specific to a user.

For the good enough use case: Perhaps load in the entities when the dialogState === STARTED then use addDelegateDirective(currentIntent) to transition to the next dialog phase. 

## Steps to Reproduce (for bugs)

See: [Example at bottom of this page](https://developer.amazon.com/docs/custom-skills/use-dynamic-entities-for-customized-interactions.html#how-dynamic-entities-work)

**Comment by broadhu2** [comment]
Not sure if it's possible (if you're eliciting a slot in the other intent). I tried the following workaround using a [response interceptor](https://ask-sdk-for-nodejs.readthedocs.io/en/latest/Processing-Request.html#request-and-response-interceptors) to add the "Dialog.UpdateDynamicEntities" directive to the original response (which already has a "Dialog.ElicitSlot" directive), but I got an error from Alexa:

```
"error": {
  "type": "INVALID_RESPONSE",
  "message": "No other directives are allowed to be specified with a Dialog directive. The following Dialog Directives were returned: [Dialog.UpdateDynamicEntities]"
}
```

Here's the code I tried, in case it helps you come up with an alternative idea:

```
import get from "lodash/get";

function getSlot(handlerInput, slotName) {
  return get(handlerInput, `requestEnvelope.request.intent.slots.${slotName}`);
}

const DynamicEntityResolver = {
  process(handlerInput, response) {
    const { attributesManager } = handlerInput;
    const sessionAttributes = attributesManager.getSessionAttributes();
    const { initialized } = sessionAttributes;
    const airportSlotTypePresent = getSlot(handlerInput, "AirportName");

    if (!initialized && airportSlotTypePresent) {
      response.directives = [
        ...response.directives,
        {
          type: "Dialog.UpdateDynamicEntities",
          updateBehavior: "REPLACE",
          types: [
            {
              name: "AirportSlotType",
              values: [
                {
                  id: "SJC",
                  name: {
                    value: "San Jose International Airport",
                    synonyms: ["San Jose", "SJC"]
                  }
                },
                {
                  id: "JFK",
                  name: {
                    value: "John F. Kennedy International Airport",
                    synonyms: ["New York", "LGA"]
                  }
                },
                {
                  id: "BOS",
                  name: {
                    value: "Logan International Airport",
                    synonyms: ["beantown", "bean town", "the hub", "logan"]
                  }
                }
              ]
            }
          ]
        }
      ];

      attributesManager.setSessionAttributes({
        ...sessionAttributes,
        initialized: true
      });
    }
  }
};

export default DynamicEntityResolver;

```

**Comment by chia-labradorsystems** [comment]
I'm running into the same problem, is it possible to achieve this now?

**Comment by ShenChen93** [comment]
Sorry guys for late response. The dialog directive so far cannot working together with other directives such as dynamic entities. If you really need this feature, would be great if you could post this request on [Alexa forum](https://forums.developer.amazon.com/spaces/23/Alexa+Skills+Kit.html) and vote for it.
