### ISSUE TITLE
Can not retrieve my ISP products from serviceClient

### ISSUE THREAD

**Issue by hideokamoto** [alexa/alexa-skills-kit-sdk-for-nodejs#555]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

I've made curl command to get expected response.

```bash
curl https://api.amazonalexa.com/v1/users/~current/skills/~current/inSkillProducts \
 -H "Content-type: application/json" \
 -H "Accept-Language: en-US" \
 -H "Authorization: Bearer XXXXXX" \
 -XGET

{
  "inSkillProducts": [
    {
      "productId": "amzn1.adg.product.xxxx",
      "referenceName": "Game_Continue",
      "type": "CONSUMABLE",
      "name": "Continue coin",
      "summary": "You can continue the quiz game.\n When you get a wrong answer, you will lost your bonus point.\n But purchase it, you can keep your bonus point.",
      "entitled": "NOT_ENTITLED",
      "entitlementReason": "NOT_PURCHASED",
      "purchasable": "PURCHASABLE",
      "activeEntitlementCount": 0,
      "purchaseMode": "TEST"
    }
  ],
  "nextToken": null,
  "truncated": false
}
```

I think we can get same props by the following command.

```typescript

const locale = 'en-US'
const ms = serviceClientFactory.getMonetizationServiceClient()
ms.getInSkillProducts(locale)
    .then(result => console.log(result))
    .catch(err => console.log(err))
```

## Current Behavior

I got a HTML HTTP 400 error page from the API client.

```
SyntaxError: Failed trying to parse the response body: <!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}A.name {color : black;}HR {color : #525D76;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class="line" /></body></html>
    at t.<anonymous> (/var/task/lib/webpack:/node_modules/ask-sdk-model/index.js:145:1)
    at call (/var/task/lib/webpack:/node_modules/ask-sdk-model/index.js:42:1)
    at Object.step (/var/task/lib/webpack:/node_modules/ask-sdk-model/index.js:23:45)
    at next (/var/task/lib/webpack:/node_modules/ask-sdk-model/index.js:14:42)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

And I've tried to capture the request props to add `console.log` into the ask-sdk-model.
Here is the request props.
<img width="900" alt="スクリーンショット 2019-05-29 15 29 07" src="https://user-images.githubusercontent.com/6883571/58534529-89932200-8226-11e9-9632-5342f89e735a.png">

```
{ method: 'GET',
  endpoint: 'https://api.amazonalexa.com',
  path: '/v1/users/~current/skills/~current/inSkillProducts',
  pathParams: Map {},
  queryParams: Map {},
  headerParams: 
   [ { key: 'Content-type', value: 'application/json' },
     { key: 'Accept-Language', value: 'en-US' },
     { key: 'Authorization',
       value: 'Bearer XXXXX' } ],
  bodyParam: null,
  errors: 
   Map {
     200 => 'Returns a list of In-Skill products on success.',
     400 => 'Invalid request',
     401 => 'The authentication token is invalid or doesn&#39;t have access to make this request',
     500 => 'Internal Server Error' },
  nonJsonBody: undefined }
```

And I've tried to get ISP items by curl to use the captured props. It works.

## Possible Solution
I don't know why the serviceClient got the HTTP 400 HTML document.
But my curl request is succeeded.
So I think the Authorization has no problems.

Do you have any idea to fix it?
Thanks.

## Steps to Reproduce (for bugs)

Run the following code in Lambda (Nodejs8.10 / us-east-1).

```typescript
const locale = 'en-US'
const ms = serviceClientFactory.getMonetizationServiceClient()
ms.getInSkillProducts(locale)
    .then(result => console.log(result))
    .catch(err => console.log(err))
```

## Your Environment

```
    "ask-sdk": "^2.5.2",
    "ask-sdk-core": "^2.5.2",
    "ask-sdk-model": "^1.15.1",
    "ask-sdk-runtime": "^2.4.0",
    "ask-sdk-s3-persistence-adapter": "^2.5.2",
```

On AWS Lambda (Node8.10) at us-east-1.

## Node.js and NPM Info
* Node.js version used for development: Node8.10
* NPM version used for development: 6.1.0

**Comment by ShenChen93** [comment]
Hi @hideokamoto,
Thanks for posting this issue. I created a new skill and tested it following the way you mentioned above, and I can get the correct responses from both curl way and SDK serviceClient way. Therefore, I want to collect more info to help me narrow down the problem. So, when you create the custom skill, what apiClient did you provide to SDK? Are you using the DefaultApiClient from ask-sdk-core or your customized apiClient?

**Comment by ShenChen93** [comment]
Hi @hideokamoto Just want to follow up. Are you still having this issue ?

**Comment by hideokamoto** [comment]
I’m sorry to late.
I always to use DefaultAPIClient and custom skill builder like this.

```typescript

      .withPersistenceAdapter(
          new S3PersistenceAdapter({
              bucketName: this.config.BUCKET_NAME,
              pathPrefix: this.config.PATH_PREFIX
          })
      )
      .withApiClient(new DefaultApiClient())
```

**Comment by ShenChen93** [comment]
@hideokamoto 

Sorry for responding late. It's really weird behavior, and I cannot reproduce this issue. Therefore, I need to reach out to service team to figure it out. Could you please provide your requestEnvelope so we can get required customer info. 

Thanks,
Shen

**Comment by hideokamoto** [comment]
Now I've replaced all ISP service client by own.
https://github.com/ask-utils/ask-utils/blob/master/packages/isp/libs/client.ts#L8-L49

I'm not sure why, but the my client works well.
Do you have any idea why to call the ISP API by using axios is works well and core client does not work?

**Comment by ShenChen93** [comment]
Hi @hideokamoto ,

Thanks for being patient. I went through all kinds of way to reproduce it but failed. Could you try to use our default api client again and see if the issue still exist ? If you still have this problem, could you please provide us with your request ID or the requestEnvelope so we can trace from service side. 

Thanks,
Shen

**Comment by ultradian** [comment]
I think I have a similar problem.  I put the code into a repo at https://github.com/ultradian/basic-alexa-isp/blob/master/src/index.js.  It is basically a stripped down version of the Amazon sample code at https://github.com/alexa/skill-sample-nodejs-fact-in-skill-purchases/blob/master/lambda/custom/index.js, using the `standard` SkillBuilder.  Running it produces an error as soon as it hits the call to `getMonetizationServiceClient`: `Error calling InSkillProducts API: TypeError: Cannot read property 'endsWith' of undefined `.  I'd guess that the API client isn't getting passed somewhere inside the SDK calls.

**Comment by hideokamoto** [comment]
Thanks for a reply.
But unfortunately, we decided to un-use the serviceClient to get the ISP products.
Now we're using own API Client to call the ISP API endpoint.

Could you help @ultradian 's problem?
regards.

**Comment by ShenChen93** [comment]
Hi @ultradian,
To make an API call, you need to first register your api client to the builder. Here is the doc for [API client](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-nodejs/call-alexa-service-apis.html#apiclient).  Our SDK provides [defaultApiClient](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-nodejs/call-alexa-service-apis.html#defaultapiclient), you could easily add it to your repo from [this line](https://github.com/ultradian/basic-alexa-isp/blob/master/src/index.js#L83), E.G.
```javascript
exports.handler = Alexa.SkillBuilders.standard()
    .addRequestHandlers(
        LaunchRequestHandler,
        SessionEndedHandler,
    )
    .addRequestInterceptors(
        EntitledProductsCheck,
    )
    .withApiClient(new Alexa.DefaultApiClient()) // register api client
    .addErrorHandlers(ErrorHandler)
    .lambda();
```
Could you try this and see if it works. Also, according to your post, I found our doc haven't explain the usage clearly, I will improve the doc in the meantime.

Thanks,
Shen

**Comment by ultradian** [comment]
Hi @ShenChen-Amazon ,

Adding your change to the code above generates the error:
```
"errorType": "TypeError", "errorMessage": 
"Alexa.SkillBuilders.standard(...).addRequestHandlers(...).addRequestInterceptors(...).withApiClient is not a function",
```
It seems that the `withApiClient` only is a method for the `custom` SkillBuilder.  I find it hard to discover what is contained in the Standard SkillBuilder and how to access it, although the docs say that ApiClient should be automatically included (which is why I guess it is unnecessary to have the function).

I'll use the `custom` SkillBuilder, although this would mean that the sample code at https://github.com/alexa/skill-sample-nodejs-fact-in-skill-purchases/blob/master/lambda/custom/index.js, doesn't work.  (have not tested it myself)

**Comment by ShenChen93** [comment]
Hi @ultradian 

Sorry it was my mistake as I just realized you are using the standard SkillBuilder. And yes you are right, `withApiClient` fucntion is only for `custom Skillbuilder`, the `DefaultApiClient` is registered to your `standard SkillBuilder` by default.

For your issue, I tried to reproduce by follwing steps: I copied [your code](https://raw.githubusercontent.com/ultradian/basic-alexa-isp/master/src/index.js), and used it in my testing skills which is just the sample skill you mentioned above. When I invoke the skill, I can get expected response back.
![image](https://user-images.githubusercontent.com/45435608/65016685-bd7b7b80-d8d9-11e9-99cf-d9d87c6255b1.png)

I also checked the aws clould watch for log info, and found that `getAllEntitledProducts` function is not defined in your code. Therefore, I copied the definition of that function from [here](https://github.com/alexa/skill-sample-nodejs-fact-in-skill-purchases/blob/master/lambda/custom/index.js#L55) and added it to my lambda code. When I trigger the lambda function again, the log info looks good: 
![image](https://user-images.githubusercontent.com/45435608/65017001-8063b900-d8da-11e9-8a62-2ebd2f032092.png).

Since I cannot reproduce your issue, I may need more info. Could you try to log the [handlerInput](https://github.com/ultradian/basic-alexa-isp/blob/master/src/index.js#L7) in your IntentHandler and paste here ? And could you try to re-install our sdk and see if the problem still exist ?

Thanks,
Shen

**Comment by ShenChen93** [comment]
I did more research based on the error message you provide. I wonder how you test your skill code. Cause when you invoke your skill, there's one property called `apiEndpoint` in the request which Alexa send to your lambda function. Following is the request my lambda function received from Alexa:
![image](https://user-images.githubusercontent.com/45435608/65021965-f66d1d80-d8e4-11e9-8462-7c010ee21a92.png)

When I remove this property from original request, and trigger my lambda with modified request, I can get the same error message as you.
![image](https://user-images.githubusercontent.com/45435608/65022087-2e746080-d8e5-11e9-81b1-cb2d452c3726.png).

Therefore, could you please check if this property exist in the reuqest you receive ? You can eaisly get it by 
```ts 
console.log(handlerInput.requestEnvelope)
```

**Comment by ultradian** [comment]
@ShenChen-Amazon Thanks for your efforts.  I updated the code in the [repo](https://github.com/ultradian/basic-alexa-isp/blob/master/src/index.js) to include the `getAllEntitledProducts` function and to use the `custom` Skillbuilder. Here is one `handlerInput` from logging `intentHandler`:
```
{ requestEnvelope:
{ version: '1.0',
session:
{ new: true,
sessionId: 'amzn1.echo-api.session.123456789012',
application: [Object],
user: [Object],
attributes: {} },
context: { AudioPlayer: [Object], System: [Object] },
request:
{ type: 'LaunchRequest',
requestId: 'amzn1.echo-api.request.1234',
timestamp: '2016-10-27T18:21:44Z',
locale: 'en-US' } },
context:
{ callbackWaitsForEmptyEventLoop: [Getter/Setter],
succeed: [Function],
fail: [Function],
done: [Function],
functionVersion: '$LATEST',
functionName: 'basicISP',
memoryLimitInMB: '128',
logGroupName: '/aws/lambda/basicISP',
logStreamName: '2019/09/27/[$LATEST]9e5f4253c087488ea683ef43a6daa48f',
clientContext: undefined,
identity: undefined,
invokedFunctionArn: 'arn:aws:lambda:us-east-1:XXXXXXXXXX:function:basicISP',
awsRequestId: 'bd9c068e-94f9-49c0-aec9-6d50bc589e93',
getRemainingTimeInMillis: [Function: getRemainingTimeInMillis] },
attributesManager:
{ getRequestAttributes: [Function: getRequestAttributes],
getSessionAttributes: [Function: getSessionAttributes],
getPersistentAttributes: [Function: getPersistentAttributes],
setRequestAttributes: [Function: setRequestAttributes],
setSessionAttributes: [Function: setSessionAttributes],
setPersistentAttributes: [Function: setPersistentAttributes],
savePersistentAttributes: [Function: savePersistentAttributes],
deletePersistentAttributes: [Function: deletePersistentAttributes] },
responseBuilder:
{ speak: [Function: speak],
reprompt: [Function: reprompt],
withSimpleCard: [Function: withSimpleCard],
withStandardCard: [Function: withStandardCard],
withLinkAccountCard: [Function: withLinkAccountCard],
withAskForPermissionsConsentCard: [Function: withAskForPermissionsConsentCard],
addDelegateDirective: [Function: addDelegateDirective],
addElicitSlotDirective: [Function: addElicitSlotDirective],
addConfirmSlotDirective: [Function: addConfirmSlotDirective],
addConfirmIntentDirective: [Function: addConfirmIntentDirective],
addAudioPlayerPlayDirective: [Function: addAudioPlayerPlayDirective],
addAudioPlayerStopDirective: [Function: addAudioPlayerStopDirective],
addAudioPlayerClearQueueDirective: [Function: addAudioPlayerClearQueueDirective],
addRenderTemplateDirective: [Function: addRenderTemplateDirective],
addHintDirective: [Function: addHintDirective],
addVideoAppLaunchDirective: [Function: addVideoAppLaunchDirective],
withCanFulfillIntent: [Function: withCanFulfillIntent],
withShouldEndSession: [Function: withShouldEndSession],
addDirective: [Function: addDirective],
getResponse: [Function: getResponse] },
serviceClientFactory:
ServiceClientFactory {
apiConfiguration:
{ apiClient: DefaultApiClient {},
apiEndpoint: 'https://api.amazonalexa.com',
authorizationValue: undefined } } }
```
I got it from using the Simulator in the dev panel.

The error in the log has has changed.
```
2019-09-27T04:12:53.993Z bd9c068e-94f9-49c0-aec9-6d50bc589e93 INFO Error calling InSkillProducts API: ServiceError: Unknown error

```
I'm not sure if this is due to updating my node modules.  Current versions are:
```
├── ask-sdk-core@2.7.0
├── ask-sdk-model@1.19.0
├── eslint@6.4.0
└── eslint-config-google@0.14.0
```
To help you more exactly replicate what I might be doing wrong, the [repo](https://github.com/ultradian/basic-alexa-isp/blob/master/src/index.js) contains all the node modules I use as well the [zipped file](https://github.com/ultradian/basic-alexa-isp/blob/master/src/basicisp.zip) so you could just upload that to lambda.

**Comment by ShenChen93** [comment]
Hi @ultradian ,

I guess you modified the logging a little bit ? Cause the timestamp, requestId looks werid. Also, the value of authorizationValue is undefined. As you can see from our code base [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/lib/skill/CustomSkill.ts#L85), the autorizationValue is just a copy of apiAccessToken in alexa request. Therefore, could you please paste your json input you get from dev console ? Such as 
![image](https://user-images.githubusercontent.com/45435608/65804828-1a77fc80-e138-11e9-8049-c07bb19ad5a8.png)


Thanks,
Shen

**Comment by ultradian** [comment]
Hi @ShenChen-Amazon ,
This is really weird, but when I just ran the code again, it worked without errors.  I added a little more logging code to be sure the entire product list was passed, and it looks good.  I'll see if I can backtrack and generate the error again.

**Comment by Daniyaldehleh** [comment]
Hi @ShenChen-Amazon 
I am facing the same error 
`ask_sdk_model.services.service_exception.ServiceException: The authentication token is invalid or doesn&#39;t have access to make this`
you can vie a sample of the code [here](https://github.com/danieldhz/Alexa_Timer/blob/master/lambda/ISP.py).

**Comment by ShenChen93** [comment]
Hi @danieldhz ,

Could you simply introduce how you test your skill ? Are U testing it on developer console ? And what version of SDK and SDK Model are u using ? Also it would be great if you could provide the requestEnvelope of the turn you meet this error.

Thanks,
Shen

**Comment by Daniyaldehleh** [comment]
@ShenChen-Amazon Hi Shen!
Sorry if original comment wasn't detailed enough.

1. Lambda
2. ask-sdk-core==1.13.0
3. request:
```
{
	"version": "1.0",
	"session": {
		"new": false,
		"sessionId": "amzn1.echo-api.session.f8b",
		"application": {
			"applicationId": "amzn1.ask.skill.78fc60-1"
		},
		"user": {
			"userId": "amzn1.ask.account.AEWEMZVR2KOBMB",
			"permissions": {
				"consentToken": "eyJ0eXAiOiJKV1QiL",
				"scopes": {
					"payments:autopay_consent": {
						"status": "DENIED"
					}
				}
			}
		}
	},
	"context": {
		"Viewports": [
			{
				"type": "APL",
				"id": "main",
				"shape": "RECTANGLE",
				"dpi": 160,
				"presentationType": "STANDARD",
				"canRotate": false,
				"configuration": {
					"current": {
						"video": {
							"codecs": [
								"H_264_42",
								"H_264_41"
							]
						},
						"size": {
							"type": "DISCRETE",
							"pixelWidth": 1024,
							"pixelHeight": 600
						}
					}
				}
			}
		],
		"Viewport": {
			"experiences": [
				{
					"arcMinuteWidth": 246,
					"arcMinuteHeight": 144,
					"canRotate": false,
					"canResize": false
				}
			],
			"shape": "RECTANGLE",
			"pixelWidth": 1024,
			"pixelHeight": 600,
			"dpi": 160,
			"currentPixelWidth": 1024,
			"currentPixelHeight": 600,
			"touch": [
				"SINGLE"
			],
			"video": {
				"codecs": [
					"H_264_42",
					"H_264_41"
				]
			}
		},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.78f63c60-13"
			},
			"user": {
				"userId": "amzn1.ask.account.AEWEMZVR2KOBNPF3MBEFWHAJIAT6BMLT7PSM4LHQLZNSQL4DLRPUXC572PS23QMAGRAAXTAHXT7RXS6WMQOPENXDVOHHXC2EUNPL3KGBEAWYBUPGHENJAXDHNZXBNIFXUR4PWD6KZCAYL35NMCW2N7D6VSKM5WJAXWOGHQ3Z2KUG3WCUHKTKFTWSWJJUJSIBXEWE746CCCGZIHY",
				"permissions": {
					"consentToken": "eyJ0eXAiOiJbGc",
					"scopes": {
						"payments:autopay_consent": {
							"status": "DENIED"
						}
					}
				}
			},
			"device": {
				"deviceId": "amzn1.ask.device.AHIJXM2SUIUVIHH2ZJN",
				"supportedInterfaces": {}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "eyJ0eXAiOiJKV1"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.2d4b1",
		"locale": "en-US",
		"timestamp": "2020-08-27T02:43:30Z",
		"intent": {
			"name": "GoogleIntent",
			"confirmationStatus": "NONE"
		}
	}
}
```
output:
```

estamp': datetime.datetime(2020, 8, 27, 2, 43, 30, tzinfo=tzlocal())},
 'session': {'application': {'application_id': 'amzn1.ask.skill.78f63c60-18ac-4'},
             'attributes': None,
             'new': False,
             'session_id': 'amzn1.echo-api.session.f8b83889-',
             'user': {'access_token': None,
                      'permissions': {'consent_token': 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiI',
                                      'scopes': {'payments:autopay_consent': {'status': 'DENIED'}}},
                      'user_id': 'amzn1.ask.account.AEWEMZVR2'}},
 'version': '1.0'}
```

**Comment by ShenChen93** [comment]
@danieldhz ,

Thanks for providing the info. From the requestEnvelope, it seems the voice purchasing is not enable for this account. 
```json
"user": {
				"userId": "amzn1.ask.account.AEWEMZVR2KOBNPF3MBEFWHAJIAT6BMLT7PSM4LHQLZNSQL4DLRPUXC572PS23QMAGRAAXTAHXT7RXS6WMQOPENXDVOHHXC2EUNPL3KGBEAWYBUPGHENJAXDHNZXBNIFXUR4PWD6KZCAYL35NMCW2N7D6VSKM5WJAXWOGHQ3Z2KUG3WCUHKTKFTWSWJJUJSIBXEWE746CCCGZIHY",
				"permissions": {
					"consentToken": "eyJ0eXAiOiJbGc",
					"scopes": {
						"payments:autopay_consent": {
							"status": "DENIED"
						}
					}
				}
			},
```

Thus could you check whether the voice purchasing is enabled ? Here is the doc might help: https://www.pcmag.com/how-to/how-to-shop-on-amazon-with-alexa-voice-shopping#:~:text=To%20start%2C%20open%20the%20Alexa,1%2DClick%20ordering%20be%20enabled.

Thanks,
Shen

**Comment by Daniyaldehleh** [comment]
@ShenChen-Amazon  I test it using dev console. Thus, there is not voice purchasing for me to enable. As well as, my phone's voice purchasing is already enabled. Nonetheless, the error persists.

**Comment by Shreyas-vgr** [comment]
Hi @danieldhz, based on your [repo](https://github.com/danieldhz/Alexa_Timer/blob/master/lambda/ISP.py), I see that you are using ASK SDK Python for your ISP skill, can you please raise an issue [here](https://github.com/alexa/alexa-skills-kit-sdk-for-python/issues/new) following the template with description and steps to reproduce your issue ?
It would help us a lot to get an understanding on what your issue is.

I apologize for the confusion and jumps to different repos.

**Comment by Daniyaldehleh** [comment]
@Shreyas-vgr Hi Sherya! Nice to see you again. I would definitely follow the template and raise the issue. Btw any news from the timer investigation?

**Comment by Shreyas-vgr** [comment]
@danieldhz, Sorry for the delay but service team found an underlying issue on their side and are working on it to fix them, will update the open python issue once I get a response back.

--  **Shreyas**

**Comment by Daniyaldehleh** [comment]
@Shreyas-vgr Is there any hope that I can get back from before the hackathon? as that was the sole purpose why i took on this journey.
