### ISSUE TITLE
Provide function for escaping rich text

### ISSUE THREAD

**Issue by jacobweber** [alexa/alexa-skills-kit-sdk-for-nodejs#559]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

It would be useful to have a utility function for escaping rich text, for constructing strings to pass into `Alexa.RichTextContentHelper.withPrimaryText()`.

## Expected Behavior
Something like `escapeRichText("a & \\ b")`, which would return `"a &amp; \\\\ b"`. It would implement the rules [here](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html#xml-special-characters).

## Current Behavior
We can't use `escapeXmlCharacters` from `SsmlUtils`. It tries to prevent characters from being encoded twice, which would mess with valid text, e.g. if you wanted to display a sample of HTML code to the user like `&amp;`.

In any case, this isn't a standard HTML-encode, because of the `\\` requirement.

## Possible Solution
See above.

## Context
Nice to have, but not essential.

## Your Environment

* ASK SDK for Node.js used: 2.5.1
* Operating System and version: Mac OS 10.14.5

## Node.js and NPM Info
* Node.js version used for development: 8.12.0
* NPM version used for development: 6.4.1

**Comment by ShenChen93** [comment]
Looks like this util function is already exist in ask-sdk-core: https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/lib/index.ts#L49.

Closing this issue for now, please feel free free to reopen if it dosn't solve your problem :)

**Comment by jacobweber** [comment]
I don't think escapeXmlCharacters solves the problem, due to the issue I mentioned above. But I'm not working on this anymore, so I don't personally need it.
