### ISSUE TITLE
Add ASK SDK Utilities code snippets to the SDK documentation

### ISSUE THREAD

**Issue by germanviscuso** [alexa/alexa-skills-kit-sdk-for-nodejs#562]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[X] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

There are no code snippets so developers can see how to use ASK Utilities in this page https://ask-sdk-for-nodejs.readthedocs.io/en/latest/ASK-SDK-Utilities.html
Here's a very nice example of how code could be added to support the docs (by the JP team): https://dev.classmethod.jp/voice-assistant/introduce-to-ask-sdk-utilities/ (3rd code snippet, one line of code)

**Comment by ShenChen93** [comment]
Hi @germanviscuso ,

Thanks for reporting this problem and providing good materials. I have reached out to docs team to work on it.

Thanks,
Shen
