### ISSUE TITLE
Custom Slot Type UI Does not save Alexa speech prompts or User utterances

### ISSUE THREAD

**Issue by piqueen314** [alexa/alexa-skills-kit-sdk-for-nodejs#563]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

If I create a Slot Type using the UI that auto generates the JSON code for the interaction model, in the section Slot Filling the Alexa speech prompts and the User utterances text boxes do not save their values.  This causes the interaction model to fail. 
## Expected Behavior

The json for "prompts" should be saved E.I.
        "prompts": [
            {
                "id": "Elicit.Slot.44886977106.1123439538026",
                "variations": [
                    {
                        "type": "PlainText",
                        "value": "Do you want to turn your led on or off"
                    }
                ]
            }
        ]

## Current Behavior

the "prompts" json is not generated and the interaction model fails with the following error:

Build Failed

Prompt id "" for slot "CustomSlotName" is not present in prompts, but is referenced in the dialog model for intent "CustomSlotIntent". Error code: MissingDialogIntentSlotPrompt

## Context

I could not build an Alexa Skill with a custom Slot Type until I hand entered the json in the json editor

## Your Environment

Firefox browser 67.0.1 (64-bit)
* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by ShenChen93** [comment]
Hi @piqueen314 

I tested the UI with my own skill but didn't find the same problem. All the texts I put in the text boxes are saved correctly after I clicked the + button. Could you please try re-login and see if the problem still exist ?

Thanks,
Shen

**Comment by ShenChen93** [comment]
Close this issue for now. Please feel free to reopen it.
