### ISSUE TITLE
JSDoc is wrong for `getSlotValue`

### ISSUE THREAD

**Issue by chearmstrong** [alexa/alexa-skills-kit-sdk-for-nodejs#566]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Hi.

The JSDoc is wrong on the `getSlotValue` function:

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/4941344aa62b84895b560f49561ebad301f6eb85/ask-sdk-core/lib/util/RequestEnvelopeUtils.ts#L184

Looks like it's a copy/paste from `getSlot` - it states that it returns `null` if it's not found, but this one throws.

**Comment by ShenChen93** [comment]
@chearmstrong 

Thanks for reporting this issue. Will fix it soon :)
