### ISSUE TITLE
Is it possible to not install Python for Alexa?

### ISSUE THREAD

**Issue by radinet-zoe** [alexa/alexa-skills-kit-sdk-for-nodejs#569]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Context

As title, I want to know if Alexa needs Python necessarily, because I got an error 'genConfig.sh: line 78: python: not found' when I ran the authorized step. However, Python doesn't in the required list in the web "https://github.com/alexa/avs-device-sdk/wiki/Dependencies".

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:
Generic Linux

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by ShenChen93** [comment]
Hi @radinet-zoe 

Are using the avs-device-sdk(https://github.com/alexa/avs-device-sdk) or alexa-skills-kit-sdk-for-nodejs(https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs) ? If you are using the avs-device-sdk, maybe it's not the right place to post this issue :). If you are using our sdk, we don't have any dependencies on Python.

Thanks,
Shen

**Comment by ShenChen93** [comment]
Closed this issue for now. please feel free to reopen it if you have any questions.
