### ISSUE TITLE
Update "Next Steps" in Readme

### ISSUE THREAD

**Issue by mattonomics** [alexa/alexa-skills-kit-sdk-for-nodejs#57]
Currently, the "Next Steps" sections contains links to Intro to "Alexa Skills On Demand" and "Voice Design 101 On Demand." These links appear to no longer point to valid content. If the content has moved, I recommend updating the links. If the content is simply no longer available, it may be optimal to remove those items from the Readme.

**Comment by bclement-amazon** [comment]
tracking in #83
