### ISSUE TITLE
audio player not start

### ISSUE THREAD

**Issue by spham** [alexa/alexa-skills-kit-sdk-for-nodejs#570]
hi

i try this without success for play a single audio file ,in test

```
<speak>
    <audio src="https://pham.es/sap/osemaine.mp3" />
</speak>
```

i see this

```
Error retrieving text to speech
The input was incompatible.

```

and also, when i change

```js
const LaunchRequestHandler = {
    canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
    },
    handle(handlerInput) {
        const speechText = 'Sortir a paris c\'est top. que voulez vous essayer ? <audio src="https://pham.es/sap/osemaine.mp3" />';
        return handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .getResponse();
    }
};
````

![Screenshot at juil  10 00-21-04](https://user-images.githubusercontent.com/1083631/60927026-a6505a00-a2a8-11e9-878c-b0ae9f6f6ddc.png)

can you suggest a quick curse for make a audio player ?

**Comment by rmtuckerphx** [comment]
Just trying the URL in the browser, I get an Access Denied. That means that the item in the S3 bucket is not public. The audio file must be publicly accessible.

**Comment by spham** [comment]
i have replace for url https://pham.es/sap/osemaine.mp3 @rmtuckerphx

**Comment by rmtuckerphx** [comment]
I see that the file is 48kbps and 16000Hz so that is fine. 

There are 2 forms of audio: short form is 240 seconds or less and long form is longer. The SSML audio tag only accepts audio that is short form. So the problem could be that the audio is too long. If that is not it, maybe changing the audio from stereo to mono.

If you want to play long-form audio, you need to use the audio player and not SSML.

Here is a sample project:
https://github.com/alexa/skill-sample-nodejs-audio-player

**Comment by spham** [comment]
ok
but i have same issue with https://pham.es/sap/oweek.mp3 < 240 s @rmtuckerphx

**Comment by spham** [comment]
I check exemple but it seems not clear

**Comment by ShenChen93** [comment]
Hi @spham 

Sorry for responding late. I used the LaunchRequestHandler you provided, but just changed the mp3 src to  https://pham.es/sap/oweek.mp3. 
```js
const LaunchRequestHandler = {
    canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
    },
    handle(handlerInput) {
        const speechText = 'Sortir a paris c\'est top. que voulez vous essayer ? <audio src="https://pham.es/sap/oweek.mp3" />';
        return handlerInput.responseBuilder
            .speak(speechText)
            .reprompt(speechText)
            .getResponse();
    }
};
```
And I tested it on developer console, it works well with my test skill.
![image](https://user-images.githubusercontent.com/45435608/61818990-ed8d2d80-ae06-11e9-8d8e-efc1dee40079.png)

From the screenshot you provided, even the sentence 'Sortir a paris c\'est top. que voulez vous essayer ?'  doesn't show up, hence I guess you didn't invoke your skill successfully. It would be great if you can change the invokation name and try to test it again

**Comment by spham** [comment]
i always have same issue

![Screenshot at juil  26 00-48-51](https://user-images.githubusercontent.com/1083631/61913978-2a5c4000-af3f-11e9-9436-6fcdcdb37b82.png)

**Comment by ShenChen93** [comment]
@spham,

This time you successfully invoke the skill, however, the skill may fails due to the audio. Since I cannot reproduce your issue, could you please paste your whole lambda function here ? 

Thanks,
Shen

**Comment by spham** [comment]
here the complete code
https://gist.github.com/spham/e4eb451770ad42f5e7c2a76d588bf402

**Comment by spham** [comment]
it's ok for me, thanks you
