### ISSUE TITLE
Alexa Device Serial Identification with Lambda Skill query from AVS server

### ISSUE THREAD

**Issue by iamartificialhuman** [alexa/alexa-skills-kit-sdk-for-nodejs#572]
Hello AVS Team,

We have a project where in AVS is enabled on multiple devices having unique serial id. As per our business requirement, we have enabled custom alexa skill which can be used to get status and control certain features in these devices.

Now as per our design of solution, we need to identify, a way as to which device was used by the user to invoke our custom skill. We looked into possible solutions but could not figure out a unique ID which the device can register itself to our cloud solution and then the same ID can be used in every intent invocation request received in our Lambda function , so that we can map which device was used for invocation of our skill.

Is there any way in avs-device-sdk client to send the device serial id to the AVS server?
If not then is there any way to get the device serial from lambda function?

Thanks,
Arvind

**Comment by ShenChen93** [comment]
Hi @iamartificialhuman ,

I want to make sure the sdk you are using is avs-device-sdk right? If so, it might be the wrong place to post this issue. Here is the github link for avs sdk (https://github.com/alexa/avs-device-sdk), it would be great if you can re-post this issue there. Let me know if you have any problems.

Thanks,
Shen

**Comment by iamartificialhuman** [comment]
Hello Team, 

I  already raised a issue in avs-device-sdk and they suggested to raise here only. 

**Below are the comments from amazon team(avs-device-sdk) :**

The avs-device-sdk does share the Device's serial number with the AVS server as part of authentication using the CBLAuthDelegate. However, I am not sure if it is exposed on the lambda.

Since this is a specific question regarding alexa-skills, could you please open an issue on the Alexa Skills Kit SDK github forum to understand if accessing the device serial number is possible?

**Comment by ShenChen93** [comment]
Hi @iamartificialhuman 

So you are looking for an unique ID for each device right ? If so, you could retrieve the device Id from lambda function. You can get it by context.System.device.deviceId. If you use our sdk, it is wrapped in the handlerinput, you can get it through handlerInput.requestEnvelope.context.System.device.deviceId. Let me know if this is the thing you are looking for.

Thanks,
Shen

**Comment by iamartificialhuman** [comment]
Yes I are looking for an unique ID for each device just after skill enable(before invoking my skill for first time).
Is there any service or way to get this device id by using access token or authorization code or anything else?

**Comment by ShenChen93** [comment]
@iamartificialhuman 

From our SDK, it's the only way we can get the device Id. It would be great if you can post this issue on our community(https://forums.developer.amazon.com/spaces/165/index.html), alexa support team will help you with that. Close this issue from our side for now. Please feel free to reopen if you have any questions. 

Thanks,
Shen

**Comment by Genoil** [comment]
I have the same issue. The context.System.device.deviceId you are referring to appears to be identical even if the devices have a different serial number.

**Comment by tejak85** [comment]
Also  device id  is changing. Would be great if there is a unique id in the json request.
