### ISSUE TITLE
Use Lambda callback parameter instead of context.fail context.succeed ?

### ISSUE THREAD

**Issue by phimar** [alexa/alexa-skills-kit-sdk-for-nodejs#58]
I wondered, why I got no logs on CloudWatch for my alexa skill lambda function. Especially for the errors from my function. 

As mentioned in the lambda documentation for nodejs handlers here: http://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html#nodejs-prog-model-handler-callback one should use the callback parameter to propagate the error to the CloudWatch logging.

At the moment the callback parameter is passed to the alexa handler function and saved into the `_callback` property, but it is never used. I think we should replace the `_context.fail` and `_context.succeed` function calls with the appropriate `_callback` calls.

Do you agree? 
I will try to provide a PR for that, soon.

Best regards.

**Comment by phimar** [comment]
#59

**Comment by bclement-amazon** [comment]
Thank you for the PR, i'll track this via #59

closing #58
