### ISSUE TITLE
Update an Alexa skill model from a server

### ISSUE THREAD

**Issue by dorian-marchal** [alexa/alexa-skills-kit-sdk-for-nodejs#581]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Is there a way to publish a new Alexa model from a server (e.g. an AWS lambda or a GC function)?

I have a custom `Product` slot with values based on a `product` database table. When a new product is added to this table, I would like to automatically update my model.

Currently, I update it manually with `ask deploy` but this is far from ideal and it requires a credentials file in `~/.ask/cli_config` that can only be created with `ask init` (which require a manual authentication in the browser).

I tried to create `~/.ask/cli_config` manually but when I run `ask` from a locally installed `ask-cli`, I get "`Cannot find module '@src/utils/constants'`" so I guess `ask-cli` should only be installed globally. 

I was looking for a version of `ask-cli` that can be used locally with some kind of app/server auth token but could not find anything.

Is there a better way to do this?

**Comment by SleepyDeveloper** [comment]
I've never configured the CLI to work on a lambda function, but you can use `ask init --no-browser` for cases where you're running in environment that doesn't have a browser. 

There's a way to configure the ask cli to work in Cloud9. https://github.com/alexa/alexa-cookbook/blob/master/guides/cli/cli-cloud9.md

Hopefully this helps.

**Comment by dorian-marchal** [comment]
Thanks but the `--no-browser` flag still requires me to login manually. It just prints the login URL instead of opening my browser. 

I'll look into the setup instructions for Cloud9 but it looks like it's based on this `--no-browser` flag.

**Comment by ShenChen93** [comment]
Hi @dorian-marchal ,

Currently CLI only be used globally due to the limitation of module-alias package. https://github.com/ilearnio/module-alias/issues/66

For your feature request, I want to know more details. Like which Database are you using (If you are using s3 or dynamo, it would be much easier) ? 

Thanks,
Shen

**Comment by dorian-marchal** [comment]
I'm building an Alexa Skill for an existing app with Firebase Firestore as a database. I would like to publish a new model when the `onWrite` [Firebase event](https://firebase.google.com/docs/functions/firestore-events) is triggered.

These triggers are written as Cloud Functions (akin to AWS Lambdas) so I can't really install a package globally, there.

I can't create `~/.ask/cli_config` manually neither because Cloud Functions file system is read only.

**Comment by dorian-marchal** [comment]
Is `ask-cli` open source? Maybe I can fork it for my needs.

**Comment by ShenChen93** [comment]
Hi @dorian-marchal ,

The current CLI you are using is not open sourced. But we just open sourced our [CLI v2](https://github.com/alexa-labs/ask-cli) last week and it's still in public beta. It slightly change the deploy behavior and use cloud formation to deploy aws resources. But you can still reuse the [deploy skillMeta logic](https://github.com/alexa-labs/ask-cli/blob/master/lib/commands/deploy/index.js#L75). Let me know if you meet any problems while making your own fork and I am here to help :)

Thanks,
Shen

**Comment by ShenChen93** [comment]
Since CLI is open sourced right now, will track all cli issues in [CLI Repo](https://github.com/alexa-labs/ask-cli) in the future. Close this issue for now.
