### ISSUE TITLE
tslint dose not check tst dir files

### ISSUE THREAD

**Issue by hideokamoto** [alexa/alexa-skills-kit-sdk-for-nodejs#585]
Probably the tslint script `$ npm run gulp -- tslint` does not check the `tst` dir files.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When we wrote a un allowed code by tslint on the tst directory files, the tslint script should show error or warning.

## Current Behavior

The gulp command will pass, but when running the tslint command directly, some error will be shown.

## Possible Solution
Probably currently lint config does not reference the tst directory.

### Prepare

```bash$
 git checkout 2.0.x
Switched to branch '2.0.x'
Your branch is up-to-date with 'origin/2.0.x'.

$ git pull base 2.0.x
From github.com:alexa/alexa-skills-kit-sdk-for-nodejs
 * branch            2.0.x      -> FETCH_HEAD
Already up-to-date.
```

### tslint from gulp

```
$ lerna --scope ask-sdk-core run gulp -- tslint
info cli using local version of lerna
lerna notice cli v3.16.4
lerna info filter [ 'ask-sdk-core' ]
lerna info Executing command in 1 package: "npm run gulp tslint"
lerna info run Ran npm script 'gulp' in 'ask-sdk-core' in 3.3s:

> ask-sdk-core@2.7.0 gulp /Users/develop/npm/alexa-skills-kit-sdk-for-nodejs/ask-sdk-core
> gulp "tslint"

[11:49:24] Using gulpfile ~/npm/alexa-skills-kit-sdk-for-nodejs/ask-sdk-core/gulpfile.js
[11:49:24] Starting 'tslint'...
[11:49:27] Finished 'tslint' after 2.31 s
lerna success run Ran npm script 'gulp' in 1 package in 3.3s:
lerna success - ask-sdk-core
```

### `./node_modules/tslint`

```bash
$ ./node_modules/.bin/tslint ./tst/util/RequestEnvelopeUtil.spec.ts 

ERROR: tst/util/RequestEnvelopeUtil.spec.ts:24:5 - Named imports must be alphabetized.
ERROR: tst/util/RequestEnvelopeUtil.spec.ts:48:62 - Missing semicolon
ERROR: tst/util/RequestEnvelopeUtil.spec.ts:111:43 - Use the object spread operator instead.
ERROR: tst/util/RequestEnvelopeUtil.spec.ts:111:77 - Missing semicolon
ERROR: tst/util/RequestEnvelopeUtil.spec.ts:112:61 - Missing semicolon

```
## Context
Sometimes I made a new feature request, but sometimes my test code includes unallowed code by the tslint rule.
But just run `gulp` command, the command does not found the problem.

https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/582#pullrequestreview-294548441

## Your Environment

```
$ cat ask-sdk-core/package.json  | jq .version
"2.7.0"
```

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

```
$ node -v
v10.5.0

$ npm -v
6.1.0
```

**Comment by ShenChen93** [comment]
Hi @hideokamoto ,

The issue you post is a known behavior of current SDK. The tslint cli only take specific file such as the use case you mentioned above, or a directory which contains tsconfig file. In our [tsconfig file](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/tsconfig.json#L16), we just include 'lib' folder without 'tst' folder, hence the lint doesn't cover all the test files. The reason why we don't include tst folder is we want to have better structure of the output folder (dist) after running 'tsc', which directly expose the index.d.ts. I would appreciate if you have any good ideas to fix this problem :)

Thanks,
Shen

**Comment by hideokamoto** [comment]
I try to update the `gulpfile-base.js`, and it works fine, probably.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/587/files

How do you think the idea?
If you think OK, we can start to fix tslint errors in all `tst` dir files.
