### ISSUE TITLE
Provide sample code for an express based Skill using the v2 SDK and Signature verification

### ISSUE THREAD

**Issue by lucidokr** [alexa/alexa-skills-kit-sdk-for-nodejs#591]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Could you please create an example Alexa skill that's built as an express app, which shows how to pass request / context to handlers and how to verify the signature, instead of a lambda-only example? I'm dependent upon using Express to power my Skill (handling incoming https requests). So, it'd be helpful to see a best practices for building a skill this way.

## Possible Solution

```js
skill = Alexa.SkillBuilders.custom().addRequestHandlers(
      ...
    )
    .addErrorHandlers(ErrorHandler)
    .create();

   try {
    await new expressAdapter.SkillRequestSignatureVerifier().verify(textBody, requestHeaders);
    await new expressAdapter.TimestampVerifier().verify(textBody);
  } catch (err) {
    // server return err message
  }

  skill.invoke(req.body)
    .then(function(responseBody) {
      res.json(responseBody);
    })
    .catch(function(error) {
      console.log(error);
      res.status(500).send('Error during the request');
    });
```

**What does it mean: "This code snippet assumes you have already consumed the request body as text and headers"??**

## Context

I'm trying to integrate a new skill with V2 SDK in my Express app executed on a node server.

## Your Environment

* ASK SDK for Node.js used: ^2.7.0
* ASK SDK Express Adapter for Node.js used: ^2.0.0
* Operating System and version: macOS 10.15.1 Catalina

## Node.js and NPM Info
* Node.js version used for development: 10.16.3
* NPM version used for development: 6.9.0

**Comment by nikhilym** [comment]
Hey @lucidokr , thanks for raising the issue. We have a backlog item for this request and will provide you with a code sample soon.

**Comment by sjames1958gm** [comment]
One issue I had trouble with the adaptor is that my boilerplate express app had `app.use(bodyParser.json());` 
which caused a error in the first of the three request handlers pushed onto the array in the adaptor. A note to not add this middleware before adding the request handlers should be included.

**Comment by ShenChen93** [comment]
Hi @lucidokr 

Thanks for being patience and using our new ExpressAdapter package ! Your request is reasonable and we will work on sample skills in near future. 

To answer your question: if you are using express and try to build an express app, you can ignore [this part](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-nodejs/host-web-service.html#for-web-application-without-express-framework) as it shows how to use SignatureVerifier and TimeStampVerifier without express. For user who don't use express, they cannot directly use our adapter class and need to figure out a way to parse the request body and request Header themselves. Therefore, for your case you just need to follow [this tab](https://developer.amazon.com/docs/alexa-skills-kit-sdk-for-nodejs/host-web-service.html#for-web-application-with-express-framework). Please be aware don't use any other middleware before adding the request handlers just as @sjames1958gm mentioned.

Let me know if you met any problems while using our SDK !

Thanks,
Shen

**Comment by ShenChen93** [comment]
Hi @sjames1958gm ,

Thanks for reaching out. And yes you're right, as you can see in our [code base](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-express-adapter/lib/adapter/ExpressAdapter.ts#L69), the express adapter will send error response if other middleware is registered before the handler. Due to your report, I think only a error response might not be enough. I will reach out to the doc team to update our doc to avoid similar issues in the future. 

Thanks,
Shen

**Comment by NicoWeio** [comment]
Hey there, 
I just created a little [repo with an example](https://github.com/NicoWeio/ask-express-adapter-example). Hope this helps!
