### ISSUE TITLE
Alexa custom Skill getting auto exit after 30 seconds of inactivity (In Echo Cube 1st Gen Device, post upgrade to Fire OS 6.2.xx)

### ISSUE THREAD

**Issue by nishanth-pvn** [alexa/alexa-skills-kit-sdk-for-nodejs#592]
Hello,

I have developed a custom alexa skill using APL to display product sales information for business users based on their voice query for different products.

Prior upgrading Echo Cube (1st Gen) to Fire OS version 6.2.xx, in older versions custom skill and displayed APL screen in TV will remain active without any time limit based on user query till we close the skill calling closeintent our self. It was the expected behavior since users have enough time to view information and have discussions between them.

But after OS upgrade, custom skill and displayed APL screen gets auto closed after 30 seconds of inactivity. We expect screen to stay longer as before since time frame of 30 seconds to view information is very less and users are totally unhappy now.

There are no recent changes in code, i have set parameter .withShouldEndSession(undefined) to keep custom skill intent to remain active for expecting reply from user. I have tried changing it to .withShouldEndSession(false) but still skill gets auto exit after 30 seconds.

We have also Echo Cube (2nd Gen) running Fire TV OS 7.2.xx, its also experiencing same issue mentioned above.

Can you please help with any suggestions to fix this issue asap since it started badly affecting our user's interest to use developed Alexa Skill.

Please let me know if you require any additional info.

Thanks,
Nishanth

**Comment by nikhilym** [comment]
Hey @nishanth-pvn , since this is not related to SDK, I suggest you to check through the [developer forums](https://forums.developer.amazon.com/spaces/165/index.html) with the APL team on the behavior. Please link the forum post later to this issue for community contribution.

I am closing this issue for now. Please reopen in case you have problems with the SDK. Thanks.
