### ISSUE TITLE
Getting 401 when sending Progressive Response | Alexa 

### ISSUE THREAD

**Issue by guruprasaad123** [alexa/alexa-skills-kit-sdk-for-nodejs#594]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

As mentioned this [article](https://developer.amazon.com/blogs/alexa/post/f952eca8-7f6f-4490-85d8-a805b50f6d25/alexa-skill-recipe-improving-the-perceived-latency-of-api-calls-using-the-progressive-response-api) on Progressive response .
I have implemented my code to send progressive response.
#### DirectiveService to loader response
```
function callDirectiveService(handlerInput) {
 // Call Alexa Directive Service.
const requestEnvelope = handlerInput.requestEnvelope;
const directiveServiceClient = handlerInput.serviceClientFactory.getDirectiveServiceClient();
  
const requestId = requestEnvelope.request.requestId;
const endpoint = requestEnvelope.context.System.apiEndpoint;
const token = requestEnvelope.context.System.apiAccessToken;
  
 // build the progressive response directive
const directive = {
      header: {
        requestId,
      },
      directive: {
        type: 'VoicePlayer.Speak',
        speech: `please wait till we fetch providers for you `,
      },
    };
  
    // send directive
    return directiveServiceClient.enqueue(directive, endpoint, token);
  }   
 ```
#### Sending progressive response while fetching GET response ( Intent Handler )
```
const Alexa = require('ask-sdk-core');
const axios = require('axios');
 
const TestIntentHandler = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'IntentRequest'
      && handlerInput.requestEnvelope.request.intent.name === 'TestIntent';
  },
  handle(handlerInput) {
    let name = handlerInput.requestEnvelope.request.intent.slots.name.value;
    
    const directivePromise = callDirectiveService(handleInput);
    const promise = axios.get('https://someurl.com');
    return Promise.all([directivePromise, promise ]).then((data)=>{
          const speechText = `Fetch successful thanks for waiting `;
    return handlerInput.responseBuilder
      .speak(speechText)
      .getResponse();
    })
  
  },
};
exports.handler = skillBuilder
  .addRequestHandlers(
    LaunchRequestHandler,
    TestIntentHandler,
    HelpIntentHandler,
    CancelAndStopIntentHandler,
    SessionEndedRequestHandler
  ).withApiClient(new Alexa.DefaultApiClient())
  .addErrorHandlers(ErrorHandler)
  .lambda();
```
## Current Behavior

Instead of sending the progressive Response as mentioned in the [article](https://developer.amazon.com/blogs/alexa/post/f952eca8-7f6f-4490-85d8-a805b50f6d25/alexa-skill-recipe-improving-the-perceived-latency-of-api-calls-using-the-progressive-response-api) <break/>
am getting this below mentioned Error :
```
{ ServiceError: Not Authorized.
    at DirectiveServiceClient.<anonymous> (/var/task/node_modules/ask-sdk-model/index.js:149:35)
    at step (/var/task/node_modules/ask-sdk-model/index.js:42:23)
    at Object.next (/var/task/node_modules/ask-sdk-model/index.js:23:53)
    at fulfilled (/var/task/node_modules/ask-sdk-model/index.js:14:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'ServiceError',
  statusCode: 401,
  response:
   {
 type: 'EXPIRED_AUTHENTICATION_TOKEN',
 message: 'The authentication token has expired.' } 
}
```
## Possible Solution

For now am unable to deduce an solution yet.
## Steps to Reproduce (for bugs)

Run the following code in Lambda (Nodejs10.x / us-east-1).
## Your Environment

```
  "dependencies": {
    "axios": "0.19.0",
    "moment": "^2.24.0",
    "redis": "^2.8.0",
    "crypto-js": "^3.1.9-1",
    "ask-sdk-core": "~2.7.0",
    "ask-sdk-model": "~1.23.1"
  }
```
* ASK SDK for Node.js used: 10.x
* Operating System and version:  aws lambda

## Node.js and NPM Info
* Node.js version used for development:10.x
* NPM version used for development: 6.12.0

**Comment by ShenChen93** [comment]
Hi @guruprasaad123 ,

Sorry for responding late. I fetch out your code base and found some issues:
* For the custom skillBuilder, there's no apiClient registered to it. Thus, your code 
```js 
const directiveServiceClient = handlerInput.serviceClientFactory.getDirectiveServiceClient();
```
can not return expected  directiveServiceClient as serviceClientFactory is undefined. To solve this problem, you could register our DefaultApiClient to your custom skill builder by following
```
exports.handler = Alexa.SkillBuilders.custom()
    .addRequestHandlers(
        LaunchRequestHandler,
        HelloWorldIntentHandler,
        HelpIntentHandler,
        CancelAndStopIntentHandler,
        FallbackIntentHandler,
        SessionEndedRequestHandler,
        IntentReflectorHandler)
    .addErrorHandlers(
        ErrorHandler)
    .addRequestInterceptors(
        LocalisationRequestInterceptor)
    .withApiClient(new Alexa.DefaultApiClient())   // The missing part
    .withCustomUserAgent('sample/hello-world/v1.2')
    .lambda();
```  
* Second, the enqueue function only takes directive as parameter, as you can see the function signature [here](https://github.com/alexa/alexa-apis-for-nodejs/blob/master/ask-sdk-model/index.ts#L5432). Thus token and endpoint are not needed. 

Could you please try above suggestions and see if the issue still exist ? 

Thanks,
Shen

**Comment by ShenChen93** [comment]
Also, from the error message you provided. I guess you copy the request body from somewhere(maybe the developer console) and create a new lambda test event to test your lambda code. If that is the case, you probably need to use the console to get the latest request and then update the lambda test event.

**Comment by ShenChen93** [comment]
Close for now, feel free to reopen if issues still exist
