### ISSUE TITLE
Struggling to get AudioPlayer directives and Pause/Play to be recognised.

### ISSUE THREAD

**Issue by mfizz1** [alexa/alexa-skills-kit-sdk-for-nodejs#595]
I am trying to do this in a self hosted skill on amazon. My package.json is as follows:

Is there anything else to be considered?

Package.json:

`{
  "name": "hello-world",
  "version": "1.1.0",
  "description": "alexa utility for quickly building skills",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "Amazon Alexa",
  "license": "ISC",
  "dependencies": {
    "ask-sdk-core": "^2.7.0",
    "ask-sdk-model": "^1.19.0",
    "aws-sdk": "^2.326.0",
    "ask-sdk-s3-persistence-adapter": "^2.0.0"
  }
}`

**Comment by ShenChen93** [comment]
Hi @mfizz1 

Sorry for responding late. It would be great if you could use our issue template, cause with the current info you provided, it would be hard for me to reduplicate your issue. 

So far, I can see you are trying to build a self hosted skill with AudioPlayer feature. I wonder if the skill response correctly to other intent such as LaunchIntent. If the issue only happen while handling the audioPlayer intent, could you please provide me with your skill code for reference ? 

Thanks,
Shen

**Comment by mfizz1** [comment]
I must apologise, I was looking at multiple issues at the same time. I meant to post in the audio player repo. I later changed the issue to be more representative of what I thought the issues was since I couldn't delete the comment. I managed to debug the problem
