### ISSUE TITLE
System.ExceptionEncountered Handling

### ISSUE THREAD

**Issue by mcalvo** [alexa/alexa-skills-kit-sdk-for-nodejs#60]
I'm not seeing anything in the sdk to handle System.ExceptionEncountered requests. As I'm working on a skill with the AudioPlayer, it'd be nice to see the errors with Audio directives or responses.

**Comment by bclement-amazon** [comment]
@mcalvo 
Good callout, this is something we need to add. I'll leave this issue open to track this request.

**Comment by JoshTumath** [comment]
Hello! What is the progress on this ticket? Because I notice you can set a handler called `System.ExceptionEncountered` and you can access the error object by calling `this.event.request.error`.

**Comment by Amazon-tianrenz** [comment]
Thanks Josh, that's the current solution for handling System Errors.
I'm closing this issue for now. Please feel free to reopen this if further problems occur.
