### ISSUE TITLE
[Market-all] create flatlist 2 column #6

### ISSUE THREAD

**Issue by phitq1** [alexa/alexa-skills-kit-sdk-for-nodejs#603]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
- create list 2 column

## Current Behavior
- set properties numColumn = 2
- set style for item list

**Comment by hideokamoto** [comment]
Is it a feature request of APL?

**Comment by khoivva** [comment]
Hi hideokamoto.
i saw this feature in your picture sent me [Market-all] screen.
flatlist 2 column inside tabs

**Comment by khoivva** [comment]
i'm so sorry about this.
i create issue wrong place

**Comment by ShenChen93** [comment]
Since it's not our issue, close all the four.  :)
