### ISSUE TITLE
Will there be an Alexa Skills Kit SDK for C#?

### ISSUE THREAD

**Issue by MaxHorstmann** [alexa/alexa-skills-kit-sdk-for-nodejs#61]
Since [AWS Lambda now supports C#](https://aws.amazon.com/about-aws/whats-new/2016/12/aws-lambda-supports-c-sharp) - is there a similar Skills Kit SDK for C# in the making?

**Comment by nstublen** [comment]
There are some C# resources being contributed by the community.

https://soundcloud.com/user-652822799/episode-009-alexa-skills-with-c-and-azure-with-bob-lautenbach

**Comment by MaxHorstmann** [comment]
thanks!

**Comment by bclement-amazon** [comment]
Closing this as off-topic

+1 for .net SDK though
