### ISSUE TITLE
API docs sample code is not using the ASK SDK utils

### ISSUE THREAD

**Issue by germanviscuso** [alexa/alexa-skills-kit-sdk-for-nodejs#613]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

In this page https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-nodejs/develop-your-first-skill.html all the code samples are not suing the ASK SDK Utilities.
In most handlers you could use:

```
Alexa.getRequestType(handlerInput.requestEnvelope)
Alexa.getIntentName(handlerInput.requestEnvelope)
```

in the `canHandle()`

## Your Environment

* ASK SDK for Node.js used: x.x.x
* Operating System and version:

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by ShenChen93** [comment]
Hi @germanviscuso ,

Thanks for reporting those doc issues. Will reach out to doc team to update the doc !

Thanks,
Shen

**Comment by hideokamoto** [comment]
Is the doc's code is OpenSource?
If yes, we can create a new Pull Request to update it.

Thanks.
@ShenChen-Amazon

**Comment by ShenChen93** [comment]
@hideokamoto 

Nah, the doc is not OpenSource. Let me check with doc team for updates.

Thanks,
Shen

**Comment by ShenChen93** [comment]
The doc is now updated after long delay, thanks again for posting the issue and being patient. Closing this issue now :)
