### ISSUE TITLE
LambdaHandler is not exported

### ISSUE THREAD

**Issue by mikelid-zz** [alexa/alexa-skills-kit-sdk-for-nodejs#614]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
LambdaHandler is the public type produced by CustomSkillBuilder.lambda() but the type is not exported which causes trouble for skills using Typescript. Specifically the following should be legal
```
export const handler: LambdaHandler;
```

## Possible Solution
add LambdaHandler to ask-sdk-core/index.ts

## Steps to Reproduce (for bugs)
```
const handler: LambdaHandler
-> Cannot find 'LambdaHandler'
```

alternatively:
```
export const handler = SkillBuilders.custom().lambda();
-> Error TS2742: The inferred type of 'handler' cannot be named without a reference to 'ask-sdk-ui/node_modules/ask-sdk-core/dist/skill/factory/BaseSkillFactory'. This is likely not portable. A type annotation is necessary.
```

## Your Environment

* ASK SDK for Node.js used: 2.7.0
* Operating System and version: Ubuntu on WSL

**Comment by ShenChen93** [comment]
Hi @mikelid ,

Thanks for reporting this issue. Made the PR #615 to fix. Closed this issue as the fix commit already merged. 

Thanks,
Shen
