### ISSUE TITLE
Add documentation for Timers support to SDK api reference docs

### ISSUE THREAD

**Issue by germanviscuso** [alexa/alexa-skills-kit-sdk-for-nodejs#616]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Add Timers API documentation as it's supported in the SDK (both for en and ja)
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.0.x/docs
Sample for code snippets available here:
https://github.com/alexa/alexa-cookbook/tree/master/feature-demos/skill-demo-timers

**Comment by ShenChen93** [comment]
HI @germanviscuso 

The doc folder in this repo is actually deprecated, and we moved all docs to developer portal. Sorry for the long delay, the doc team add the timer api link in the Nodejs SDK overview: https://developer.amazon.com/en-US/docs/alexa/alexa-skills-kit-sdk-for-nodejs/overview.html. Closing this issue now :)

Thanks,
Shen
