### ISSUE TITLE
Reminders API SSML not working with Audio Tag

### ISSUE THREAD

**Issue by sholkay** [alexa/alexa-skills-kit-sdk-for-nodejs#618]
## I'm submitting a...
<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[x ] Other... Please describe:
</code></pre>

Audio tag not working in Reminders API SSML tags,
```
<speak>
          Testing 1
          <audio src="https://vishalsholkaybucket.s3.amazonaws.com/uk_21042020.mp3" />
          Testing 2
</speak>
```

## Expected Behavior

This would return a reminder in which Alexa will first speak in the following order: 

- Testing 1
- The audio file will run
- Testing 2

## Current Behavior
But in this scenario, the audio file doesn't run and` Testing 1` and `Testing 2` runs and also there is a gap of some time in both these, I guess the `audio is running but it is mute or inaudible to the user`, but Alexa speaks `testing 2 only after the audio finishes in the background`.

## Possible Solution
The audio file should run in the Reminders API SSML.

## Steps to Reproduce (for bugs)
```
const reminderRequest = {
                trigger: {
                    type: 'SCHEDULED_RELATIVE',
                    offsetInSeconds: '10',
                },
                alertInfo: {
                    spokenInfo: {
                        content: [{
                            locale: "en-US",
                            text: "Testing", 
                            ssml:  '<speak>Testing 1<audio src="https://vishalsholkaybucket.s3.amazonaws.com/uk_21042020.mp3" /> Testing 2</speak>'
                        }],
                    },
                },
                pushNotification: {
                    status: 'ENABLED',
                },
            };
```
I am making this reminder request to the `Reminders API` and then pushing it to the `createReminder` method.
`const reminderResponse = await client.createReminder(reminderRequest);`

I am using Alexa's [skill reminders demo](https://github.com/alexa/alexa-cookbook/blob/master/feature-demos/reminders-api/skill-demo-reminders/lambda/custom/index.js). Nothing else is changed just trying to push the above request in the Reminders API.

## Context

- I am trying to create a reminder in which Alexa can remind the user to do something at a certain time lets say 5 PM in the evening along with a audio file related to that activity.
- Reminding the user to do something is good, but playing an audio file related to that particular activity will become more customized in the real world sense.

## Your Environment

* ASK SDK for Node.js used: 2.7.0
* Operating System and version: Windows 10 Pro

## Node.js and NPM Info
* Node.js version used for development: 12.14.0
* NPM version used for development: 6.13.4

**Comment by ShenChen93** [comment]
Hi @sholkay ,

Thanks for reporting this issue. I used the code you provided above and could reproduced the issue. However, the behavior is slightly different as there's no gap between 'testing1' and 'testing2' when I triggered my demo skill. I will report this issue to service team and will update status here once got their reply. 

Thanks,
Shen

**Comment by ShenChen93** [comment]
Hi @sholkay ,

Got the response from the service team. Unfortunately, audio tag is not supported yet in reminder, the public doc is misleading. The service team will correct the doc and give a list of supported tag.

I also checked with them if there are any way to attach audio in reminder, but it seems this feature is not available right now.

Since it's the feature request on service side, I will close the tt on SDK side. 

Thanks,
Shen

**Comment by rat** [comment]
This feature is extremely important for engaging with reminders. I am developing a skill to help autistic children, but without audio tags, their engagement is quite bad.

Is there a possibility that the team has already released this resource? @ShenChen-Amazon

**Comment by mohamed-arradi** [comment]
This feature is indeed very important where we would like reminders to be customized and catered to a specific audience. All my users are asking me this feature, and therefore they put bad rating as it seems logical for them :).

**Comment by hqawasmi** [comment]
@ShenChen-Amazon , Hi , is there any updates on the above issue please

**Comment by zohaibkhan502** [comment]
Hi @ShenChen-Amazon and @sholkay,

I think the workaround would be if we get the event when the reminder starts beeping we can use the speak tag outside of the reminder Api. Referring to this docs. I gave it a one shot but didn't got any event fired at that time. 
https://developer.amazon.com/en-US/docs/alexa/smapi/alexa-reminders-api-reference.html#reminderstarted
