### ISSUE TITLE
ask clone command not working

### ISSUE THREAD

**Issue by sravankumarreddy9** [alexa/alexa-skills-kit-sdk-for-nodejs#620]
I'm trying to clone the skill from the developer console. when i run the below command. I'm getting the error.
ask clone "skills"
Command not recognized. Please run "ask" to check the user instructions.
If i try to deploy the skill to developer console i'm getting error as below:
C:\Users\reddymv\proactive-event-starter-api>ask deploy
[Warn]: Please make sure you are in the root directory of the project.
These issues happened after upgrading nodejs 10 to nodejs 12 and upgrading cli.
I'm thinking some installation files and settings have been misplaced. 
Can anyone give info from starting to ending for the setup of ask-cli.

**Comment by RonWang** [comment]
Hi @sravankumarreddy9 ,

ask-cli is open sourced now, I've created a new issue with your problem at https://github.com/alexa/ask-cli/issues/153. Will close this one and we can explain over there.
