### ISSUE TITLE
ASK SDK Controls Framework for other platforms?

### ISSUE THREAD

**Issue by kkocel** [alexa/alexa-skills-kit-sdk-for-nodejs#634]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

Will ASK SDK Controls Framework will be ported to non-JS platforms? Eg. Java?

**Comment by ShenChen93** [comment]
Hi @kkocel ,

Thanks for being interested in using the new control framework. The control framework currently under beta and it only support node.js for now. We will consider to support it for other languages once it turns out the framework is useful and people like to use it.

Thanks,
Shen
