### ISSUE TITLE
shouldEndSession is not required so it should be overridable

### ISSUE THREAD

**Issue by theluk** [alexa/alexa-skills-kit-sdk-for-nodejs#64]
the shouldEndSession is set to true in :tell and cannot be overridden. In the JSON Reference it is marked as optional. there should be a way to override it simply.

**Comment by sharepointalex** [comment]
@theluk is there a way around this currently? I am emitting a 'tell' but I don't want to end the session - with other nodejs Alexa APIs it appears you can do this.

Cheers

**Comment by gabrielkaputa** [comment]
@sharepointalex i'm using :ask as a workaround

**Comment by bclement-amazon** [comment]
`:tell` with `shouldEndSession = false` is equivalent to `:ask`

You cannot persist a session across invocations, setting shouldEndSession to true will have Alexa wait roughly 8 seconds for an answer from the user. If nothing is said during those 8 seconds the session ends.

closing this for now, please re-open if you have any further questions
