### ISSUE TITLE
skipOnEnablement field is missed in the AccountLinkingRequest type

### ISSUE THREAD

**Issue by z4o4z** [alexa/alexa-skills-kit-sdk-for-nodejs#653]
`skipOnEnablement` is missed in the `v1.skill.accountLinking.AccountLinkingRequest` type

P.S. 
issue in `alexa-apis-for-nodejs`: https://github.com/alexa/alexa-apis-for-nodejs/issues/12
PR in `alexa-apis-for-nodejs`: https://github.com/alexa/alexa-apis-for-nodejs/pull/13

**Comment by ShenChen93** [comment]
Hi @z4o4z 

Thanks again for pointing this issue in model. Will fix it in next model release.

Thanks,
Shen

**Comment by ShenChen93** [comment]
As mentioned in #652 , patch release of smapi sdk model is done to add skipOnEnablement property as well. Closing this issue for now, please reopen if you have any questions and concerns :) 

Thanks,
Shen
