### ISSUE TITLE
Does not work with beta ASK-SDK

### ISSUE THREAD

**Issue by CraigVella** [alexa/alexa-skills-kit-sdk-for-nodejs#670]
skill.appendAdditionalUserAgent('ask-express-adapter');
              ^
TypeError: skill.appendAdditionalUserAgent is not a function

**Comment by ShenChen93** [comment]
Hi @ChaseHQ ,

Thanks for using our SDK! May I know which verison of SDK are you using ? I am not clear what is the beta ASK-SDK.

Thanks,
Shen

**Comment by CraigVella** [comment]
I'm trying to utilize name free interactions, so i'm using the public preview/beta as directed by alexa documentation. However the express adapter does not seem to work with the public preview/beta, I get the error posted above within node.

**Comment by ShenChen93** [comment]
Hi @ChaseHQ,

Are you using any preview/beta codebase provided by Alexa ? If so, could you please provide me a link so I can take a look. Also I would like to know how you build the skill object. It seems the skill object you passed into express-adapter is not a valida skill object as appendAdditionalUserAgent function was missing. 

Thanks,
Shen

**Comment by ghost** [comment]
I think @ChaseHQ might be looking at https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/tree/2.x_public-beta

It's very confusing - it was last updated in 2018 but says

"This branch is 8 commits *ahead*, 204 commits behind 2.0.x."

It might be an idea to remove it and references to it from the docs if it's not relevant.

**Comment by ShenChen93** [comment]
Hi @digitaltoast ,

Thanks for the info. 2.x_public-beta branch was used when our v2 sdk was in public beta stage, as far as I know this branch is not used anymore. I will confirm with my team and delete this branch to reduce confusion.

And, It can explain why appendAdditionalUserAgent is missing, cause this function is added in ask-sdk-core v2.7.0. @ChaseHQ , if you are using the beta branch, could you please switch to use the default branch 2.0.x. 

Thanks,
Shen

**Comment by ShenChen93** [comment]
Close this issue for now since no response from requester. Please feel free to reopen if you still have the issue
