### ISSUE TITLE
Use this library to create smart-home skills?

### ISSUE THREAD

**Issue by jamesrusso** [alexa/alexa-skills-kit-sdk-for-nodejs#672]
I've spent the evening looking, but is there any Amazon provided library for the development of smart home skills? This library seems to only apply to custom skills?

I'd even be happy with just types for the smart home skill request and responses but can't seem to find them anywhere?

Are they not available? 

I don't want to re-invent the wheel especially when this implementation seems so elegant.

**Comment by haruharuharuby** [comment]
Hi, @jamesrusso 

Currently, ASK SDK is not compatible with smart home skill. 
You are right. ASK SDK is only compatible with custom skills now.

The smart home skill has a big difference to handle the request from Alexa Device. (except top frame)

There is the unofficial and conceptual library for Alexa Smart Home Skill. 
https://github.com/secual/alexa-smart-home-controller
for your reference.

**Comment by jamesrusso** [comment]
Thank you for the link to https://github.com/secual/alexa-smart-home-controller. I'll check it out. I just felt like I was re-inventing the wheel crafting responses, had no typings, etc.

**Comment by rdgomt** [comment]
Hey guys. Any news regarding the official smart home SDK?
