### ISSUE TITLE
Export services.skillManagement.SkillManagementServiceClient from ask-smapi-sdk.

### ISSUE THREAD

**Issue by sam-goodwin** [alexa/alexa-skills-kit-sdk-for-nodejs#678]
Why isn't the type of the client exported from `ask-smapi-sdk`? 

I am using the `ask-smapi-sdk` and noticed that the `CustomSmapiClientBuilder` exposes a private type.

```ts
export declare class CustomSmapiClientBuilder extends StandardSmapiClientBuilder {
    private apiClient;
    private apiEndpoint;
    private authEndpoint?;
    withApiEndpoint(apiEndpoint: string): CustomSmapiClientBuilder;
    withAuthEndpoint(authEndpoint: string): CustomSmapiClientBuilder;
    withApiClient(apiClient: ApiClient): CustomSmapiClientBuilder;
    /**
     * Function used to generate SkillManagementService instance.
     */
    client(): services.skillManagement.SkillManagementServiceClient;
}
```

Specifically:
```ts
client(): services.skillManagement.SkillManagementServiceClient;
```

But `SkillManagementServiceClient` is not exported:
```ts
export declare namespace services.skillManagement {
    /**
     *
     */
    class SkillManagementServiceClient extends BaseServiceClient {
    ..
```

I'm trying to write a class that wraps the client:
```ts
export class MySmapi {
  constructor(client: ????) {}
}
```

If the type is private, what type am i supposed to put here?

The only way to use the client is with TypeScript type inference. That's unfortunate.

**Comment by ShenChen93** [comment]
Hi Sam,
The services.skillManagement.SkillManagementServiceClient is exported in the smapi sdk model: https://github.com/alexa/alexa-apis-for-nodejs/blob/master/ask-smapi-model/index.ts#L6772. Thus for now developer need to import the type from model seperately.

To better improve the user experience, I think we could re-export  SkillManagementServiceClient in smapi sdk. Do you think it would be good enough for developers to use this type ?

Thanks,
Shen

**Comment by sam-goodwin** [comment]
I'd prefer to avoid re-exporting types since it breaks jump-to-definition and confuses auto import.

**Comment by doiron** [comment]
closing as this is exposed in the model.
