### ISSUE TITLE
APL video onPause event inconsistently returns event.currentTime (milliseconds)

### ISSUE THREAD

**Issue by voiceactivity** [alexa/alexa-skills-kit-sdk-for-nodejs#688]
**Expected behavior**:
  According to the doc the onPause callback should return a current playback position in the current video track, expressed in milliseconds (currentTime):
https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-video.html#onpause

That means, when you trigger a Pause event multiple times (e.g. during multiple time intervals), the APL video player should consistently return a current playback position in the current track.

**Actual behavior**:
APL video onPause event inconsistently returns event.currentTime (milliseconds). 
Tested devices:
- Echo show 5
- Amazon Fire Stick 4k

Cloud Watch log (lambda function as a skill back-end):

`2021-05-08T00:42:30.204Z	b39b6d2a-42e2-433b-a6ac-8897eea0a0df	INFO	*** INFO: VideoOnPauseEventHandler:
{
    "currentTime": 57301,
    "paused": true,
    "ended": false
}`
...
`2021-05-08T00:43:23.877Z	86729a78-a376-4b33-b13a-0f01ada704b4	INFO	*** INFO: VideoOnPauseEventHandler:
{
    "currentTime": 92997,
    "paused": true,
    "ended": false
}`
...
`2021-05-08T00:44:23.531Z	18a2e568-3172-408e-b43e-dc2f4d20d04d	INFO	*** INFO: VideoOnPauseEventHandler:
{
    "currentTime": 131791,
    "paused": true,
    "ended": false
}`
...
`2021-05-08T00:46:45.335Z	adad34ea-e960-4555-874e-f518034969ac	INFO	*** INFO: VideoOnPauseEventHandler:
{
    "currentTime": 51302,
    "paused": true,
    "ended": false
}`

The APL document:
`
        "type": "APL",
        "version": "1.6",
        "import": [
            {
                "name": "alexa-layouts",
                "version": "1.2.0"
            },
            {
                "name": "alexa-viewport-profiles",
                "version": "1.2.0"
            }            
        ],
        "mainTemplate": {...}`

It's not a one-off case, it consistently happens during multiple triggers of the Pause event. 

Your help is very much appreciated.

Paul

**Comment by ShenChen93** [comment]
Hi Paul, our SDK is a pass through layer and we can not help on the data consistency issue. Could you please provide me with your Skill Id thus I could help reach out to APL team to further investigate.

Thanks,
Shen

**Comment by voiceactivity** [comment]
Sure. Thank you.
amzn1.ask.skill.c811a066-3e2c-4a19-b237-ae5026eafb9c

**Comment by ShenChen93** [comment]
Hi @voiceactivity ,

Got reply from service side. Seems you misunderstand the currenttime,
>The currentTime: current playback position in the current video track, expressed in milliseconds.
It will be different depending on when you press the pause button, and the currentTime is how long the Video has been played

Thanks,
Shen

**Comment by voiceactivity** [comment]
Thank you for your feedback, very much appreciated!

According to the documentation: https://developer.amazon.com/en-US/docs/alexa/alexa-presentation-language/apl-video.html
`"currentTime": Integer, // Current playback position in the current track, expressed in milliseconds`
There is no other definition there. 

Just to clarify, are they saying that the `current playback position in the current video track` and the `how long the Video has been played` are different things?? The `currentTime`is just a cursor. It reflects the current position of the video track in milliseconds. 

If we have `currentTime:60000` it means that the video played 60 seconds, right? The point of the issue here is that `currentTime` returned with every subsequent `onPause` event should be `consistently incremented`. It looks like it doesn't happen all the times. It seems that sometimes, despite video playback continues, the `currentTime` going back in time!! That is the issue.

**Comment by ShenChen93** [comment]
Hi @voiceactivity ,

Thanks for your patient. I just got some update from service team: the service team did some update as of July 15th. And they could not repdroduce this issue after the service update. 

I wonder if this issue still exist at your end ? If so could you please provide your device serial number thus the service team could help with next step investigation.

Thanks,
Shen

**Comment by voiceactivity** [comment]
Hi @ShenChen-Amazon ,

It looks good now. I cannot reproduce it anymore.

Thank you and the Service Team for your help in investigation and fixing the issue!
