### ISSUE TITLE
Session is not cleared by setting this.handler.state = ''

### ISSUE THREAD

**Issue by richboyde** [alexa/alexa-skills-kit-sdk-for-nodejs#69]
if you set this.handler.state = '' and persist the state into DynamoDB the state will never get cleared, this is due to the following code:

':saveState': function(forceSave) {
            if (this.isOverridden()) {
                return;
            }

            **if(forceSave && this.handler.state){
                this.attributes['STATE'] = this.handler.state;
            }**

notice that if you assign this.handler.state = '', then the if will not succeed.   I am not sure exactly why this code is here. It may be that the && needs to be an ||.  I believe the author is trying to prevent this.handler.state from being null (because Dynamo can't persist an empty string) or if state's aren't being used, then there isn't a reason to save the state.  Maybe there needs to be a function to clear state or resetState, or maybe a parameter to saveState that is boolean for clearState. so something like this.

':saveState': function(forceSave, clearState) {
    if (this.isOverridden()) {
        return;
    }

   if (clearState) {
    this.attributes['STATE'] = undefined;
  } else {
    if (forceSave && this.handler.state) {
        this.attributes['STATE'] = this.handler.state;
    }
 }
  
I believe the above would be the least intrusive as many developers may already be working around this issue and may rely on this to function this way.

**Comment by MerryOscar** [comment]
I'm also observing this issue that the state can't be switched back to `''`

I also know that it's [not currently possible to persist an empty string value into DynamoDB](https://github.com/aws/aws-sdk-js/issues/833) - so this may be why the code is structured like that.

I think it's probably best just to use the `''` state for the first ever use for a user and not try and go back to it.

So your states could be something like:

```
var states = {
  FIRST_EVER_USE: ''
  MAIN_STATE: '_MAIN_STATE',
  SOME_OTHER_STATE: '_SOME_OTHER_STATE'
};
```

And in the `FIRST_EVER_USE` state you could just have a `NewSession` handler that gave some kind of welcome message and then switched to your `MAIN_STATE`:

```
var firstEverUseHandlers = Alexa.CreateStateHandler(states.FIRST_EVER_USE, {

  'NewSession': function () {
    this.handler.state = states.MAIN_STATE;
    this.emit(':ask', 'First ever use welcome message.', 'First ever use re-prompt.');
  }

});
```

**Comment by richboyde** [comment]
As an UPDATE:  In my code i just set this.attributes['STATE'] = undefined and that seemed to resolve the issue, but feel this is a work around.   Also, MerryOscar posted above will also work, but again, it seems like working around the issue.   There should be a way to clear state and start over.   Maybe just need a ':clearState' even that just sets this.attributes['STATE'] = undefined.

**Comment by knowlsie** [comment]
I'm also experiencing this issue: `this.handler.state = ''` doesn't reset the state like it should, whereas putting anything but an empty string does... This is annoying given that if you want to use the 'LaunchRequest' model rather than the 'NewSession' model you need to have quite a few intents in your "blank" state anyway; not being able to go back to that "blank" state is annoying...

**Comment by tdoyle3** [comment]
I also ran into this issue. I made the following change to response.js:

       ':saveState': function(forceSave) {
            if (this.isOverridden()) {
                return;
            }

            if(forceSave && this.handler.state){
                this.attributes['STATE'] = this.handler.state;
            }

            // Added this to enable clearing a state
            if ( this.handler.state == '' ) {
                this.attributes['STATE'] = undefined;
            }

**Comment by Ethereality-Associates-Admin** [comment]
I have also noticed the STATE: value cannot be reset, but also seems to be being ignored totally.  I have the states...

var states = {
    NOTINGAME: '',
    INGAME: '_INGAME'
}

... and am finding...

'AMAZON.StartOverIntent': function ( ) {
        this.emit('NewGameRequest');

...is actually invoking the NewGameHandler not NewGameHandler_INGAME as it should. Dumping the Session object clearly shows STATE: is set to '_INGAME" ...

attributes: 
{ questionsAsked: [ 19, 35, [length]: 2 ],
qsWrong: 1,
questionNum: 2,
STATE: '_INGAME',
qsCorrect: 0,
correctAnswer: 3 },

...the only way I can invoke the right version of NewGameHandler is to code...

AMAZON.StartOverIntent': function ( ) {
        console.log('*** StartOverIntent - INGAME ***');
        initSessionState(this.event.session);
        this.emit('NewGameRequest_INGAME');

...which works OK, but is a workaround.

**Comment by flanaganpaulf** [comment]
Fwiw I got this working with:  

delete this.handler.state; 
delete this.attributes['STATE'];
this.emit(':saveState', true);

This is with some intents in one state handler, and lots of others stateless. However, even if no state is set, I'm still seeing 'stateful' intents getting triggered, even though that should not happen I thought. Easy enough to duplicate the intent name, but not ideal. Also seeing weird behaviour in error cases: e.g. stateless error triggering stateful error handler. Seems that mixing of statefulness and statelessness is not really supported.

**Comment by allthepies** [comment]
Doesn't work for me.

However the following does:

`          this.handler.state = '';
          delete this.attributes.STATE;`

**Comment by blueshirts** [comment]
@Amazon-tianrenz , your post above seems to make sense and that setting the state to empty string is not supported.  Should this be updated in the documentation, or at least removed from the readme and other examples to avoid confusion.  I only tried this because I saw it in the readme examples.

    var guessModeHandlers = Alexa.CreateStateHandler(states.GUESSMODE, {

        'NewSession': function () {
            this.handler.state = '';
            this.emitWithState('NewSession'); // Equivalent to the Start Mode NewSession handler
        },

**Comment by Amazon-tianrenz** [comment]
@blueshirts 
Yes, we are working on a new draft of ReadMe document that should address all existing problems.

**Comment by talkingnews** [comment]
@Amazon-tianrenz That would be great - I've found a few doc problems myself. Will the work-in-progress draft be on its own branch for now? In other words, is there a way we can see an comment?

**Comment by Amazon-tianrenz** [comment]
Hi @talkingnews,
We are currently working on a private repository. All the published documents have to go through a review process so we can't make it public until the final revision is approved. 
At the meantime, you can post ideas/suggestions for the documents here. We are actively tracking GitHub issues now and will take into consideration feedback from our developer community. 

Regards

**Comment by monikakoerdt** [comment]
Had the same issue.  Finally resolved by adding a new LAUNCH state handler similar to the guessmode described above.  This took care of taking the user to a default/launch mode.  Not ideal, but seems to do the job.

**Comment by tschuege** [comment]
@Amazon-tianrenz
What's is the state on this?
I tried all the suggestions I found here but non of them worked. The state stays in the response and on the next request the intent handler won't be found because it does not exist on the state the skill was in before.

In the docs I read about the 'NewSession' intent, but that does not solve my issues - again, the state stays at the response.

Any help on this?

**Comment by Amazon-tianrenz** [comment]
@tschuege,

Have you tried the method mentioned at the end of this [section](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#skill-state-management) in readme.md?

Regards,

**Comment by tschuege** [comment]
@Amazon-tianrenz
Yes, I did, but I could not get rid of a state once set.

**Comment by Amazon-tianrenz** [comment]
@tschuege , 

Could you attach the your code for clearing state please?

Regards

**Comment by tschuege** [comment]
@Amazon-tianrenz
I'm using ES6 classes for the handlers that have a method called to handle the intent. Since the alexa-sdk binds the call to the handler function replacing `this` I have to wrap it in a closure to save the handler (that has `emit` etc.). I store the alexa handler in the member `alexaHandler` - I think that should work because tests emitting speech works just fine.
So the method to reset the state simpli looks like this:

```
protected resetState() {
        this.alexaHandler.handler.state = '';
        delete this.alexaHandler.handler['STATE'];
 }
```

When debugging I can see, that alexaHandler.handler.state has the correct state but when I reset it it won't be reflected in the response. Therefore the next call will still contain the state and fail because there is no matching handler for that state. 

Any Idea?

**Comment by tschuege** [comment]
@Amazon-tianrenz
it seems to work if i set it on session.attributes. In my case like that:
```
this.event.session.attributes.state = '';
delete this.event.session.attributes['STATE'];
```
I hope that won't have any other unexpected side effect...

**Comment by Amazon-tianrenz** [comment]
Hi @tschuege,

``State`` is stored in the attributes of handler. So if you change your code to the following then it should work: 
````JavaScript
protected resetState() {
        this.alexaHandler.handler.state = '';
        delete this.alexaHandler.attributes['STATE'];
 }
````
And the workaround you have should work just fine.

Cheers!

**Comment by PrithiviRajG** [comment]
I am also facing a strange issue that session is not persisting in DynamoDB on Stop Intent. But when user tries to launch the skill again, old session is saving to dynamoDB. This is happening only in the skill where I use state events `this.handler.state`

```
"AMAZON.StopIntent": function() {
        console.log(this.attributes);
         delete this.attributes["quizitem"];
        delete this.attributes["quizproperty"];
        delete this.attributes["previousIntent"];
        delete this.attributes["counter"];
        this.handler.state = '';
        delete this.event.session.attributes['STATE'];
        delete this.attributes['STATE'];
        delete this.attributes['response'];
        delete this.attributes['quizscore'];
        delete this.attributes['quizCode'];
        //this.response.shouldEndSession(true);
        console.log("Stop Intent 2");
        console.log(this.attributes);
        this.response.speak(EXIT_SKILL_MESSAGE);
        this.emit(":responseReady");
    }
```

**Comment by blueshirts** [comment]
I got around this using the steps mentioned above and providing a NewSession handler in each of my lists of state handlers.  My common NewSession is below.

https://github.com/blueshirts/alexa-who-said-meow/blob/master/index.js#L43
```javascript
const commonNewSession = function () {
  this.handler.state = ''
  this.emit('NewSession')
}
```

I have a list of common handlers that should be implemented in all of my state handlers.  This is both for this issue and to ensure I pass certification.  

https://github.com/blueshirts/alexa-who-said-meow/blob/master/index.js#L43
```javascript
const commonHandlers = {
  'NewSession': commonNewSession,
  'Unhandled': Unhandled,
  'SessionEndedRequest': SessionEndedRequest,
  'AMAZON.HelpIntent': HelpIntent,
  'AMAZON.CancelIntent': CancelIntent,
  'AMAZON.StopIntent': CancelIntent
}
```

I create my state handlers using a utility that extends the common list of handlers.  Any duplicates are overridden.

https://github.com/blueshirts/alexa-who-said-meow/blob/master/index.js#L43
```javascript
const continueHandlers = createStateHandler(states.CONTINUE, {
  'AMAZON.YesIntent': continueYes,
  'AMAZON.NoIntent': continueNo
})
```

Here is the utility code.  It may not be optimized though it works fine for my usage. If a state is left in the attributes when a new session is created the commonNewSession is fired and sends the user back to the default NewSession.

https://github.com/blueshirts/alexa-who-said-meow/blob/master/index.js#L43
```javascript
function extend(o = {}) {
  for (let k of Object.keys(commonHandlers)) {
    if (!o[k]) {
      o[k] = commonHandlers[k]
    }
  }
  return o
}

function createStateHandler(state, handlers) {
  return Alexa.CreateStateHandler(state, extend(handlers))
}
```

**Comment by allthepies** [comment]
That's pretty cool :+1:

**Comment by Amazon-tianrenz** [comment]
Hi all, 

Thanks for your support for the SDK. We've released ASK SDK v2 for Node.js yesterday, which aims to address many of the issues here. We encourage you to check out our wiki [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki).

**Comment by McGern** [comment]
Hi,

Could you please show how v2 solves this issue? Would it be possible to post a link showing the migration path for state handling from v1 to v2 please?

I ended up here because I have the same issue, and hoped to see some fixes in v2, but instead have been presented with a complete rewrite of the sdk which makes my current code null and void because the adapter doesn't work correctly and I don't have enough in-depth knowledge to know what the issue is.

Thanks,
Jarrod

**Comment by Aashrith1** [comment]
@tianrenz Hello I am not able to clear the state . I have written the entire skill in SDK v1 , I do not want to migrate to V2 SDK only for this . 
I am using this.handler.state = `` and in my response.js , this is the change i made but it does not work . Any help is appreciated. thanks in advance !!

 var _this = this;
        if (this.isOverridden()) {
            return;
        }
        if (forceSave && this.handler.state) {
            this.attributes.STATE = this.handler.state;
        }
        if ( this.handler.state == '' ) {
            this.attributes['STATE'] = undefined;
        }
        var response = this.handler.response.response;
        if (response.shouldEndSession || forceSave || this.handler.saveBeforeResponse) {
            if (!dynamoDbPersistenceAdapter) {
                dynamoDbPersistenceAdapter = new ask_sdk_1.DynamoDbPersistenceAdapter({
                    createTable: true,
                    dynamoDBClient: this.handler.dynamoDBClient,
                    partitionKeyName: 'userId',
                    attributesName: 'mapAttr',
                    tableName: this.handler.dynamoDBTableName,
                });
            }
            dynamoDbPersistenceAdapter.saveAttributes(this.event, this.attributes).then(function () {
                _this.handler.promiseResolve(response);
            }).catch(function (error) {
                if (error) {
                    return _this.emit(':saveStateError', error);
                }
            });
        }
        else {
            this.handler.promiseResolve(response);
        }

**Comment by tianrenz** [comment]
Hi @Aashrith1 , 

Could you try replacing ``this.attributes['STATE'] = undefined`` with ``delete this.attributes['STATE']``?

Regards

**Comment by allthepies** [comment]
This works for me.

```
this.handler.state = '';
delete this.attributes.STATE;
```

**Comment by dgreene1** [comment]
Thanks @tianrenz :)
