### ISSUE TITLE
old context model dooms callbacks to fail

### ISSUE THREAD

**Issue by PeterMitrano** [alexa/alexa-skills-kit-sdk-for-nodejs#7]
The alexa sdk doesn't use the Lambda callback. Instead, it uses the old context.(succeed|fail) methods. This works fine in a lot of cases, but dooms a few fairly simple use cases.

For instance, if your skill wants to increment a number every time the user launches the app, and persist in dynamodb, you would try to set an attribute on launch and then maybe do

```
this.handler.state  = "SOME_STATE";
emit(":ask", "Welcome. What is your name?");
this.attributes.invocations = 1
```

Unless you have `saveBeforeResponse` on, this won't call `saveState` and so you have to do that yourself. So now we have

```
this.handler.state  = "SOME_STATE";
emit(":ask", "Welcome. What is your name?");
this.attributes.invocations = 1
emit(":saveState", true);
```

This will not work. Ask will `emit(":responseReady")`, which will call `context.succeed`, and **poof**, sucks to suck for your saveState request. It's callback is likely doomed to fail. Your database won't update and you'll be sad. This is extra confusing because you might happen to use a tell instead.

```
this.handler.state  = "SOME_STATE";
emit(":tell", "This is my skill. Goodbye!");
this.attributes.invocations = 1
emit(":saveState", true);
```

This will _appear_ to work because tell automatically persists, see #8 for a fix for that. However, all you'll see in your database is the state, because you set `invocations` after the tell. And of course the callback for saveState is doomed to fail and so you're screwed.

I propose a switch the use callback. You already have a object property for it! I found it in `alexa.js`, it's set and everything! But y'all need to use it instead of the context calls.

I am totally open to being wrong about all this, but after several days of testing and hacking I'm pretty sure this is what's going on. If I can get a response here that this is correct I will gladly make the PR for this change.

**Comment by PeterMitrano** [comment]
After lots more testing, I've even gotten the `ask` emit to fail. Seems that saveState is in general very inconsistent

**Comment by PeterMitrano** [comment]
So it seems the only way to get 100% consistent persisting is to override the `context.succeed` method. Of course this breaks everything else and results in no alexa response being sent. But it does seem to make sure my data always persists

**Comment by deegles** [comment]
Hi Peter, we are working on some enhancements that will address this issue and others. Please stay tuned.

For now I recommend structuring your code to emit the :ask or :tell event last.

**Comment by PeterMitrano** [comment]
Glad to hear it, and to know that you guys are actually planning to maintain and improve this sdk--It's an excellent start. I've been hacking the hell out of this, so I've gone ahead and implemented the callback() based model. If that's useful you can check it out [here](https://github.com/PeterMitrano/my_cookbook/tree/master/src). I make no claims to it's brilliance.

For instance, it's entirely possibly that callback will get called multiple times, which in practice doesn't seem to matter but is conceptually confusing.

**Comment by adnopars** [comment]
@deegles I never see my SessionEndedEvent listener getting invoked.  The :ask of the Unhandled gets invoked if there is no utterance .  Unhandled gets invoked twice upon silence and then Alexa falls silent. The SessionEndedEvent does not get called.   What might I be missing ?

**Comment by PeterMitrano** [comment]
@adnopars You can hack it yourself to use callback() properly.
[this commit](https://github.com/PeterMitrano/my_cookbook/commit/b1b75efe7d8e370ee55d46517420ac8de89ea584) probably contains a working version of the concept. I used it a while ago, but have since switched to python

**Comment by PeterMitrano** [comment]
it should be SessionEndedRequest not SessionEndedEvent.

[example](https://github.com/PeterMitrano/my_cookbook/commit/b1b75efe7d8e370ee55d46517420ac8de89ea584#diff-1fdf421c05c1140f6d71444ea2b27638R34)

**Comment by sadranyi** [comment]
how do i force the saveState when I emit  :ask ?

**Comment by bclement-amazon** [comment]
You can force saveState by setting the saveBeforeResponse property on the alexa handler.

```javascript
exports.handler = function(event, context, callback) {
    var alexa = Alexa.handler(event, context);
    alexa.saveBeforeResponse = true; // <-- add this
    alexa.registerHandlers(handlers);
    alexa.execute();
};
```
