### ISSUE TITLE
Testing Skills Locally

### ISSUE THREAD

**Issue by tlovett1** [alexa/alexa-skills-kit-sdk-for-nodejs#70]
Hey all, I built a utility for testing Alexa skills built with this SDK locally. The tool starts up an Express server so you can test various requests/intents/slots. Hopefully this helps some people.

https://www.npmjs.com/package/alexa-skill-test

**Comment by mvdivotfixer** [comment]
Cool beans, @tlovett1.   Tip for others coming to this from Lambda or Lambda-Local testing, if you are setting the AppID for security as recommended by the SDK, this will initially cause failures when testing with this tool.   It obviously provides a different AppID in the request than Lambda does, so for local testing I just set my AppId to undefined.

**Comment by bclement-amazon** [comment]
Very cool @tlovett1! Thanks for this.

**Comment by muneebaahmad** [comment]
After hours of research, I was finally able to test my alexa skill locally. I thought it would be a good idea to put all the instructions in one place. So here you go:

[How to test alexa skill locally](https://medium.com/@moonahmad/how-to-test-alexa-locally-6d498e307a8)
