### ISSUE TITLE
Debugging doesn't work 

### ISSUE THREAD

**Issue by Betatester777** [alexa/alexa-skills-kit-sdk-for-nodejs#718]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I've followed all the steps to debug in VS Code, but still receiving the message: "There was a problem communicating with the requested skill" as well in local as in console simulator.

I've created NA-Account to with same result. 
Debugging starts with success, but simulatar have thoble to connect to backend.

## Expected Behavior

Simulator should work, while lambda is running in debugger

## Current Behavior

Simulator shows: "There was a problem communicating with the requested skill" on start of skill

## Your Environment

* ASK SDK for Node.js used: x.x.x
* ASK Skill Kit vor VS Code: v2.11.0
* Operating System and version: 2.27.0
Ubuntu 20.04 64 bit

## Node.js and NPM Info
* Node.js version used for development: v16.15.0
* NPM version used for development: 8.5.5
![bug](https://user-images.githubusercontent.com/73201837/172313442-7d13f6e6-a97b-4342-a461-558a536a7a2c.png)

**Comment by Betatester777** [comment]
No relevant CloudWatch Logs found, while debugger is running

**Comment by kevinmarrec** [comment]
I'm having the same issue on `EU` region. The skill won't be reached when debugged.

`ask dialog`
![image](https://user-images.githubusercontent.com/25272043/173163614-8dbdb39f-dd80-443c-a403-2d3aa4fdf6e1.png)

`VS Code Alexa Skill Simulator (FR locale)`
![image](https://user-images.githubusercontent.com/25272043/173163630-f6e204c3-4cb3-4042-89cf-b2240f4bde26.png)

**Comment by javierAlo** [comment]
Do you have the same problem with all skills? I have verified that it only happens with some of my skills, I think with the last ones that I have created, but not with the oldest ones.

**Comment by Betatester777** [comment]
I've the same issue with all skills. 
Old, new, NA,EU hosted. 
It's frustrating;-(.

**Comment by betomadrazo** [comment]
Same problem here with all skills, old and new. Windows and Linux.

**Comment by Betatester777** [comment]
@ShenChen93 any idea why debugging has stopped to work?

**Comment by fernandaBonaldo** [comment]
Same problem here will all skills too, in NA and EU.

**Comment by CarlosMed** [comment]
We are also getting an issue with local dev in NA. Sadly it just breaks with no way of knowing what's causing the issue since there are no logs or anything. We are sadly reverting to uploading manually. Uploading manually causes issues with our development process as it gets slowed down significantly. 

It was working perfectly fine several days ago and like when OP initially posted is when we had the same issue. We thought it was from our end but we have exhausted any potential solution. Any update on this issue?

**Comment by abpatel** [comment]
This issue has been resolved. Please give it a spin. Would appreciate ya'll reporting back  here

**Comment by betomadrazo** [comment]
I'ts been resolved, I tried with EU and still didn't work, but for NA it did. Many thanks.
Is it possible to know how it was fixed?

**Comment by Betatester777** [comment]
Now it works as expected with the EU account.
Thanks a lot;-)

**Comment by Betatester777** [comment]
Tested with both EU and NA accounts.
Debugging works perfectly.

**Comment by ankitrex31** [comment]
I am facing the same issue, Does anyone know how to fix this..?
I am using the EU region.

**Comment by ktssr** [comment]
Getting the issue with EU region again. My account has recently migrated to India
