### ISSUE TITLE
Email 

### ISSUE THREAD

**Issue by kingbrell** [alexa/alexa-skills-kit-sdk-for-nodejs#722]
CXVGJGDSVVACGEBPTGTJBQXVNBOJJISVCHCVORPKOGWFWZCVSVOUTJBJUPDYUXYJQELPAPFNPCALPCTHIKNJAODJXCEBQLVCULKRLLTXCNNMPQJQIRNWQRCGDZPQMGLCDKLFLILEFNGTLACYCBSYYRKPUVQYCEIWGRPKYYAEVFJPUZFYUMISVJGADEYFYUQTQVWYXCNWZCUKGDZETRVXZYNSNJFAHPZZSBHULFWYZNXLUVTAIJOQQZ

**Comment by tydonelson** [comment]
Spam? Closing.
