### ISSUE TITLE
buildSpeechletResponse doesn't output cardContent text for Standard cards

### ISSUE THREAD

**Issue by scifi76** [alexa/alexa-skills-kit-sdk-for-nodejs#76]
It appeasts that when emitting a ":tellWithCard" response the cardContent text is never output.

Line 172 of response.js reads:
alexaResponse.card.text = options.content;

but should be:
alexaResponse.card.text = options.cardContent;

**Comment by bclement-amazon** [comment]
Hi sciFi76,

It appears this got fixed back in July 2016 with [this commit](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/87a76c5781d7dd1f681ccf0cd58fa9e776c2445a)

You may be using a version of alexa-sdk from before this commit, please grab our latest version (1.0.7)
