### ISSUE TITLE
Testing skill with Card

### ISSUE THREAD

**Issue by benedekh** [alexa/alexa-skills-kit-sdk-for-nodejs#78]
Hi,

Maybe it is an irrelevant question here, but how can I test the cards sent by my Alexa application implemented using this NodeJS SDK?

For localhost testing I found several app servers ([Alexa-app-server](https://github.com/alexa-js/alexa-app-server), [Alexa skill test](https://github.com/voiyse/alexa-skill-test)), but none of them supports this new SDK nor can I see the cards.

For online solutions, I have not found any websites or tools yet, which would show also the cards. For voice testing multiple options are available, that's not a problem.

Thank you for help in advance.

**Comment by bclement-amazon** [comment]
Hey Benedek,

For integration tests I typically just validate the response sent out from the skill and ensure the "Card" part of the body is well-formed. See the [Alexa JSON Interface Reference](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/alexa-skills-kit-interface-reference#response-format).

But perhaps you had a different use case in mind? What are you trying to test?

**Comment by benedekh** [comment]
Hey Brendan,

Thank you for the quick response. In almost every Amazon tutorial / documentation that deal with Cards there are some screenshots provided as illustration. E.g. [Including a Card in Your Skill's Response](https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/providing-home-cards-for-the-amazon-alexa-app). I was wondering whether I need to download the Android / iOS app for Alexa and find my (not-production-ready) application in that to show the cards which appear on some responses, or is there any tool to test them (how they look, is there too much text on the card, etc)?

**Comment by bclement-amazon** [comment]
Great question. You can download the Alexa app on your phone by visiting http://alexa.amazon.com on your mobile device/

Any cards sent from the development version of your skill will appear in the app.
They'll also appear on the web interface at http://alexa.amazon.com on non mobile devices.

**Comment by benedekh** [comment]
Yes, it works perfectly. :-) Thank you.

**Comment by sanju03** [comment]
Hi Can i use the cards to get some input from User ?

**Comment by tianrenz** [comment]
Hi @sanju03 ,

At the current moment, the answer is no. You can use PermissionCard to asking user to grant permission to your skill. Or account linking card to prompt user to link their account. 

Regards
