### ISSUE TITLE
Unanswered open issues and pull requests

### ISSUE THREAD

**Issue by feedm3** [alexa/alexa-skills-kit-sdk-for-nodejs#81]
Hi guys,
this repo has currently 18 open issues and 13 open pull request and on half of them you didn't respond although some of them are open since months. Sadly, your other repos don't look better (for example the [skill-sample-nodejs-fact](https://github.com/alexa/skill-sample-nodejs-fact), the first project most upcoming alexa developers will see). Seeing this is pretty frustrating to me. 

Please consider taking more care about this. It's very discouraging to participate in these alexa repos if you don't respond. I really believe better response times (like at maximum 3 days) could help improve the product and also your support by the community. 

Nevertheless, thanks for making everything open source, all those nice t-shirts and free echo dot devices 🙂

**Comment by bclement-amazon** [comment]
Hi @feedm3 

Thank you for the feedback and I agree wholeheartedly with your comments and since taking over this project i've been doing my best to go through the issues & pull requests. In the past 3 days we've closed 19 issues and counting.

I'll be working through the rest so stay tuned.
