### ISSUE TITLE
Regarding account linking

### ISSUE THREAD

**Issue by SomaSharathSurya** [alexa/alexa-skills-kit-sdk-for-nodejs#82]
hey,

 I successfully linked amazon account to my custom skill and tested it ,its working fine . But I am unable to see the access token in the request JSON .What should I do to see the access token ? 

Please help !

**Comment by gabrielkaputa** [comment]
@SomaSharathSurya what access token do you have in mind?

**Comment by benedekh** [comment]
@SomaSharathSurya As soon as you get the access token from the authentication server, it shall be in `session.user.accessToken`. Example:

```
{
  "session": {
    "sessionId": "..",
    "application": {
      "applicationId": "..."
    },
    "attributes": {
     ...
    },
    "user": {
      "userId": "....",
      "accessToken": "..."
    },
    "new": false
  },
  "request": {
    ...
    }
  },
  "version": "1.0"
}
```

**Comment by SomaSharathSurya** [comment]
Thanks for the reply guys! 

@gabrielkaputa I am talking about the access token which I receive in every request from Alexa after successfull authentication. 


@benedekh : yeah I know that it will be in session.user.accessToken ...but in my case the account linking is happening through Alexa web app perfectly but after successfully authentication also session.user.acessToken is null....

Please help with this issue!

**Comment by benedekh** [comment]
@SomaSharathSurya Are you using Amazon.com for authentication? I just followed the tutorial [here](https://developer.amazon.com/blogs/post/Tx3CX1ETRZZ2NPC/Alexa-Account-Linking-5-Steps-to-Seamlessly-Link-Your-Alexa-Skill-with-Login-wit) and it worked fine for me.

I don't know if it matters, but I put the redirect URI after the authorization URL also, as shown in Figure 5.

**Comment by SomaSharathSurya** [comment]
hey @benedekh 

 Are you using alexa companion mobile app during account linking or using alexa web app for account linking?

**Comment by benedekh** [comment]
@SomaSharathSurya I use Alexa Web App, because for companion client I have been using java client which does not support cards yet. I have no experience with the mobile app.

But what is the matter exactly? You ask the user to authenticate by showing them the link account card. Thereafter they (successfully) authenticate and move on in the conversation, but you are not able to see the access token in the request? Could you see if you ask for the LinkAccountCard correctly?

```
context.emit(':askWithLinkAccountCard', 'Please authenticate.', 'Please authenticate.');
```

**Comment by SomaSharathSurya** [comment]
@benedekh 

Yeah exactly after successful authentication I am redirected to the page where it displays "Your skill was successfully linked"


![image](https://cloud.githubusercontent.com/assets/25243569/24287486/fb554a3a-109f-11e7-87ee-35df6e2d474e.png)
 

Next when I go into alexa developer portal and navigate to "Test" option  for my skill and test in service simulator the request JSON shows me user id but I cannot see accessToken. I am not understanding how to procced now since I need to validate that accessToken in my lambda function. I hope you understood the problem. You want any other info please ask me.

Please help!

**Comment by bgcherry** [comment]
Hello @benedekh, I am seeing the same problem for my skill. Did you got any solution for this. Please help me if possible.

**Comment by benedekh** [comment]
Hi @bgcherry, I don't know what the solution was for @SomaSharathSurya, no message was sent since the last one before closing the ticket.

**Comment by bgcherry** [comment]
Hello @SomaSharathSurya, did you got any solution for this. I am seeing the same with my skill. Please help me if you see any solution.

**Comment by akshar001** [comment]
Hello this is not related to this issue but i have one problem when i connect alexa all thingss happen right but at the end alexa error for skill linking is shown. I am using my own oauth server to link alexa use to my system..actually i can see access token has being granted but alexa is not getting ...if anyone could tell me how can i debug this thing than it would be helpfull..

**Comment by 311711** [comment]
Hi,
in my code i am linking account card but in response i didnt see the card type as linkAccount 
my code in lambda:
response.linkAccountCard('type', 'LinkAccount');
response.speak(speechOutput);

response in test console:
"card": {},
    "speechletResponse": {
      "outputSpeech": {
        "ssml": "<speak>  xyz </speak>"
      },
      "card": {},
      "shouldEndSession": true

can any one help on this?
