### ISSUE TITLE
Broken links in README.md

### ISSUE THREAD

**Issue by mschilli** [alexa/alexa-skills-kit-sdk-for-nodejs#83]
Links to "Intro to Alexa Skills On Demand" and "Voice Design 101 On Demand" no longer point to valid locations.

**Comment by bclement-amazon** [comment]
Thank you for catching this. We'll get these updated

**Comment by bclement-amazon** [comment]
fixed with commit 4ec1272374bc65cc6f7e355af177c503b7a7a451
