### ISSUE TITLE
Smart home devices discovery

### ISSUE THREAD

**Issue by Kinjalk** [alexa/alexa-skills-kit-sdk-for-nodejs#84]
Hello,
I have followed amazon's documentation on creating Alexa smart home devices and i am successfully able to add devices in my Alexa app using Echosim.io or directly scanning in Alexa app. Also i am able to control devices using Echosim but unable to discover devices using Alexa on raspberry pi. Alexa always says "Could not find any smart home devices" even though all the devices are already in my Alexa app.

Is there any way to control devices using Alexa on raspberry pi ? I know i can use Alexa Skill and AWSIot but then i would have to use invocation. Can i use it without invocation ?
![screenshot_2017-03-24-06-48-50-814](https://cloud.githubusercontent.com/assets/5174221/24289275/91f2575c-10a6-11e7-87b2-eb1ea8a55206.jpeg)

**Comment by bclement-amazon** [comment]
Hi @Kinjalk,

Thanks for reaching out. Can you help me understand what you mean by using it without invocation?  Alexa is a conversational platform, so to interact with devices on your network you'll need to invoke Alexa and give it a command.
