### ISSUE TITLE
will this api work on react native?

### ISSUE THREAD

**Issue by foobar8675** [alexa/alexa-skills-kit-sdk-for-nodejs#85]
I'm building a React Native app for iOS and Android and was looking for a way to make calls right from the client, instead of going through my backend. Thanks.

**Comment by nstublen** [comment]
I'm not sure what you're intending to do by "making calls right from the client."

This SDK helps you write skills that will be invoked from an Amazon Echo.

Are you looking for something to work with the Amazon Voice Service (AVS) by enabling voice capabilities within your mobile app?

**Comment by foobar8675** [comment]
Yes, that is exactly what I am looking into. Do you have any suggestions?

**Comment by nstublen** [comment]
I don't have any experience with AVS and I'm not aware of anything that attempts to wrap the APIs for JavaScript. You may just need to build your own solution by calling the endpoints directly from within your application.

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/content/avs-api-overview

**Comment by foobar8675** [comment]
thanks @nstublen
