### ISSUE TITLE
SaveState calls context.succeed()

### ISSUE THREAD

**Issue by Fabse333** [alexa/alexa-skills-kit-sdk-for-nodejs#88]
SaveState will currently call context.succeed even if a response is not ready.
A simple example where db is a DynamoDB connection:
`this.emit(':savestate');`
`db.get(params).promise().then((data) => { this.emit(':tell', 'I will not be called' }`

Because saveState calls `context.succeed()` the lambda function maybe ends and do not call the promise. This results in an empty response. From my point of view, the SDK should only call `context.suceed()` when an output to Alexa is emitted and not when saving the attributes. This leads to headache for developers why the promise is not called 😉 
Maybe you should not call `context.suceed()` in `saveState` or at least add this unexpected behaviour to the documentation.

**Comment by feedm3** [comment]
This behaviour is covered in the documentation, checkout "Tips" https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs#tips

`this.emit(...)` should always be your last call when handling an intent, so just connect to the database before the emit, or even better: do it at the lambda startup and not in an intent at all.

But to be fair I also had this kind of problem where I did a calculation which would be cached at the end, but due to the `context.succeed()` it didn't. Because the calculation would be cached to user would not run into an error twice. So having an options object to every `this.emit(...)` where we could tune some params like not calling `context.succeed()` would be nice!

**Comment by Fabse333** [comment]
You mean this tip?

> When any of the response events are emitted :ask, :tell, :askWithCard, etc. The lambda context.succeed() method is called, which immediately stops processing of any further background tasks. Any asynchronous jobs that are still will not be completed and any lines of code below the response emit statement will not be executed. This is not the case for non responding events like :saveState.

It exactly states the opposite (:saveState will not call context.succeed()).

**Comment by feedm3** [comment]
Oh sorry, my mistake. You are right. Either the documentation or the sdk needs to be updated.

**Comment by Fabse333** [comment]
Hopefully they update the SDK because it is completely unintuitive that saving a state would end the session. I planned to create a pull request which not calls context.succeed() but removing this line would maybe cause some issues with the AudioPlayer Requests.
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/lib/response.js#L133

**Comment by knowlsie** [comment]
I totally agree with this issue; I've been using workarounds to get around it. I was planning to fix it a few days ago, but I think it maybe might be best to wait for https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/59 to be finalised and merged before fixing ourselves? I don't want horrible merge issues if any further changes are added to that PR.

At least to my knowledge, changes to this won't cause problems with the Audio Player response; the current code is pretty much just a way of getting it not to send a real response, and is a bit of a workaround. As the docs say "Also note that your service is not required to return a response to the AudioPlayer requests." The code'll actually make a lot more sense without it to be honest. 

Anyway, I'm on this too, and will fix it as soon as callback is implemented.

**Comment by bclement-amazon** [comment]
Quick update guys:
I'm still working on #59. This process can take some time, hope to have it approved soon.

**Comment by knowlsie** [comment]
Got it. Thanks for the work and handling issues Brendan - we appreciate it as skill developers.
