### ISSUE TITLE
What's the point of this.response / ResponseBuilder?

### ISSUE THREAD

**Issue by knowlsie** [alexa/alexa-skills-kit-sdk-for-nodejs#89]
Let's talk about this property - particularly I am wondering why it's included, and whether it needs some changes. It's found [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/0f8f14a961852413b935b594c4fda0223b5fb278/lib/alexa.js#L240) and [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/0f8f14a961852413b935b594c4fda0223b5fb278/lib/alexa.js#L256) in alexa.js.

**Here's a quick explanation of what it does:** `ResponseBuilder` is a closure that you can access through `this.response`; this closure returns an object with functions that allow you to edit a responseObject variable that is private to the closure. This basically allows one to automate the manual set-up of a response object, and store that in the `responseObject` variable. It's also chainable, as each of the object's functions returns `this`. So for example `this.response.speak("Hello").listen("World");`, creates a response object which is pretty much equivalent to the one sent by `this.emit(":ask", "Hello", "World");` - but instead of emitting that object it stores that object in the responseObject variable.

**Here's what I don't get:** The responseObject variable is private to the closure, so can't actually be retrieved without some significant edits/workarounds. It also doesn't mutate the actual `this.handler.response` object (even though responseObject it is a copy of that object.) Therefore, this function seems kinda pointless. It can edit responseObject to make a functional response, but you can't actually then retrieve it... Moreover, ResponseBuilder is totally unused by the SDK at present, and is totally undocumented, at least to my knowledge. It's therefore just confusing at the moment, as beginners might think it's the same as `this.handler.response`.

Assuming I'm right on the above stuff, there are two options: remove it, or fix it. I think you could fix it by just adding a new getter property to the object that ResponseBuilder returns:

```
'getResponseObject': function () {
  return responseObject;
}
```

Then `this.response` is suddenly useful. For example you can bypass `this.emit(':ask')`:

```
this.handler.response = this.response.speak('Hello').listen('World').getResponseObject();
this.emit(':responseReady');
```

More importantly, this change suddenly gives the SDK decent Audio Player support, as ResponseBuilder can handle that with, for example  `this.response.audioPlayerStop`

I wanted to discuss this before making a PR to check that I'm understanding everything correctly, and to discuss whether we want to remove or fix it. If I do make a PR I will simultaneously update documentation to try to explain it.

**Comment by knowlsie** [comment]
So I'm thinking a property that sets `this.handler.response` might be better. For example:

```
'setResponse': function () {
  this.handler.response = responseObject;
}
```

Then our code above becomes:

```
this.response.speak('Hello').listen('World').setResponse();
this.emit(':responseReady')
```

**Comment by knowlsie** [comment]
As it's probably easier to just discuss a pull, I made PR https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/93 to deal with this; please move any discussion over there!

**Comment by KrishFuriaAmazon** [comment]
I have few comments on the PR #93. When you call speak and listen method they already set `this.handler.response`.

**Comment by KrishFuriaAmazon** [comment]
Thanks @knowlsie. PR accepted!
