### ISSUE TITLE
PT #74: Add OnRequest, :forward, and this.data

### ISSUE THREAD

**Issue by shazaml** [alexa/alexa-skills-kit-sdk-for-nodejs#90]
What is the process that would determine if PR #74 will be included or not?
https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/74

Is there anything else other than the PR that I need to complete to have it be considered?

**Comment by knowlsie** [comment]
I'm not Amazon, but I know they're only just getting back to work on this SDK after a fairly passive period, and from my work on the SDK there are a bunch of quite important updates and bug fixes that they're working on getting approved. Your PR is more subjective and less necessary than the updates, so I suspect they'll get back to you eventually, but they're busy doing other stuff right now. 👍

**Comment by shazaml** [comment]
Thanks for the comment. The process is a bit of a mystery to me. Is there a list of the updates and bugs they are currently working?

**Comment by knowlsie** [comment]
Not that I know of... If you just look through the PRs and Issues lists, and see the ones that Brendan has replied to, that'll give you some idea. I'd guess https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/59, https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/26, and https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/65 are a few fairly important issues in progress.

**Comment by bclement-amazon** [comment]
Hey @shazaml,

Thank you for the PR! I or a member of my team will get to it.  At the moment we're prioritizing bug fixes over new features.

I do have a few preliminary questions on your PR. I will send them in #74

**Comment by bclement-amazon** [comment]
Closing this, will address comments in #74
