### ISSUE TITLE
Callback / Event handling after emit was fired

### ISSUE THREAD

**Issue by linslin** [alexa/alexa-skills-kit-sdk-for-nodejs#91]
We need to know if a emit was fired or not e.g. to avoid timeout handling on lambda functions. Could you provide some way to achieve this? A callback, event or status variable would be nice. Thanks guys!

**Comment by bclement-amazon** [comment]
Hey Linslin, 
Thanks for reaching out. By "to avoid timeout handling on lambda functions", do you mean you are creating a setTimeout() function which executes at some point before reaching your lambda timeout expiry time?

Lets walk through this:
Currently the SDK will delegate a request to a particular handler (based on state). Are you looking for status/callback function when you call this.emit(':ask/:tell') ?

**Comment by linslin** [comment]
Yes, I need some callback or event when `this.emit()` was fired.

**Comment by KrishFuriaAmazon** [comment]
Hey @linslin, can you please explain how will providing a callback when an event is emitted, can avoid timeout handling on lambda function?
