### ISSUE TITLE
Style Guide

### ISSUE THREAD

**Issue by knowlsie** [alexa/alexa-skills-kit-sdk-for-nodejs#94]
I've been considering improving the code style and comments, as the current style isn't great. Is there a particular style guide that you would you like me to use?

**Comment by bclement-amazon** [comment]
This one: https://github.com/google/styleguide  👍 

Also thank you

**Comment by knowlsie** [comment]
Got it. I did a thing with Airbnb's because I had time to spare, but I'll move it over to Google's when I get time in the next couple days.

**Comment by knowlsie** [comment]
@bclement-amazon https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/96 is updated.

**Comment by feedm3** [comment]
Very good job @knowlsie 👍

**Comment by bclement-amazon** [comment]
@knowlsie  - wow. this is awesome! You're fast.
I'm going to take some time to play with this, and then we'll get your commit reviewed.

Cheers!
