### ISSUE TITLE
got error while installing

### ISSUE THREAD

**Issue by shaolinkhoa** [alexa/alexa-skills-kit-sdk-for-nodejs#95]
Hi,

This is the first time I use Nodejs so please help me.

If I didn't `git clone https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs.git` and run `npm install --save alexa-sdk`, it return:
```
npm WARN saveError ENOENT: no such file or directory, open '/home/ntuankhoa/Project/java/javascripting/package.json'
/home/ntuankhoa/Project/java/javascripting
└─┬ alexa-sdk@1.0.8 
  ├─┬ aws-sdk@2.38.0 
  │ ├─┬ buffer@4.9.1 
  │ │ ├── base64-js@1.2.0 
  │ │ ├── ieee754@1.1.8 
  │ │ └── isarray@1.0.0 
  │ ├── crypto-browserify@1.0.9 
  │ ├── jmespath@0.15.0 
  │ ├── querystring@0.2.0 
  │ ├── sax@1.2.1 
  │ ├─┬ url@0.10.3 
  │ │ └── punycode@1.3.2 
  │ ├── uuid@3.0.1 
  │ ├── xml2js@0.4.17 
  │ └─┬ xmlbuilder@4.2.1 
  │   └── lodash@4.17.4 
  ├── i18next@3.5.2 
  └── i18next-sprintf-postprocessor@0.2.2 

npm WARN enoent ENOENT: no such file or directory, open '/home/ntuankhoa/Project/java/javascripting/package.json'
npm WARN javascripting No description
npm WARN javascripting No repository field.
npm WARN javascripting No README data
npm WARN javascripting No license field.
```

if I `git clone https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs.git` and run `npm install --save alexa-sdk`, it return:
```
npm ERR! Linux 4.8.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "--save" "alexa-sdk"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install alexa-sdk as a dependency of itself
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ntuankhoa/Project/java/javascripting/alexa-skills-kit-sdk-for-nodejs/npm-debug.log
```

would you mind helping me ?

**Comment by michaelborchardt** [comment]
In the first image, it appears you're attempting to save to a directory that does not exist. This means that your .json file is not referenced correctly in the path. In the second image you're trying to install the alexa sdk as a dependency of it's self, which basically means you've targeted the Alexa SDK in your path, and you're trying to install Alexa SDK. What code editor are you using?

**Comment by knowlsie** [comment]
So the first one is not actually an error. It's just saying that you don't have a package.json to save the dependency in. It has correctly installed, it's just not logged the dependency in your package.json.

**Comment by knowlsie** [comment]
Sorry, Michael was right. Not sure how I missed that first line.

**Comment by michaelborchardt** [comment]
@knowlsie 
Good catch. It's been awhile since I've developed with Node.js, picked it back up again solely for building out a skill with this SDK.

**Comment by shaolinkhoa** [comment]
Hi @michaelborchardt , hi @knowlsie ,

So the 1st case is right ? 
I ran `npm init` and it created `package.json`. After that , the warning only show 
```
npm WARN java@1.0.0 No description
npm WARN java@1.0.0 No repository field
```
But it doesn't matter, right ?

Thank you for your help

**Comment by michaelborchardt** [comment]
Can you compile the file using `npm file.js`? And what code editor are you using to build your files? That would help us debug your scenario.

**Comment by michaelborchardt** [comment]
I'm sorry I mean, `node file.js'.

**Comment by bclement-amazon** [comment]
Hey @shaolinkhoa ,

I think you're on the right track!  Those are warnings on your package java , I'd expect that you didn't fill in the description & repository fields when running npm init.

If you've ran npm install --save alexa-sdk on your java@1.0.0 package directory, then npm should download the sdk and its dependencies to your node_modules folder.

Check out the [NodeJS Trivia Skill Sample](https://github.com/alexa/skill-sample-nodejs-trivia) for some boilerplate code which uses the alexa-sdk module. 👍

**Comment by michaelborchardt** [comment]
@shaolinkhoa 

@bclement-amazon  is entirely correct in the diagnosis of your issue. All though if you continue to have problems building and running your files, may I recommend you try using [Visual Studio Code](https://code.visualstudio.com/docs/nodejs/nodejs-tutorial). It's a light-weight, code editor built by Microsoft, portable to every OS platform, and it's excellent when used with node. It has a built in console and everything you need to operate. Jet Brains also makes a great node IDE, but that may cost you more than you're willing to spend.

**Comment by bclement-amazon** [comment]
@michaelborchardt  +1 for VSCode
They just had an impressive changelog today with their 1.11 update.

**Comment by michaelborchardt** [comment]
@bclement-amazon I've installed the update, haven't gone through the changelog extensively yet. All though I did take note of the [node debugging](https://code.visualstudio.com/updates/v1_11#_node-debugging) features that they've updated/implemented. The team over at Microsoft who manages the project really does a phenomenal job, I've thought highly of the tool since beta.

**Comment by bclement-amazon** [comment]
I'm going to close this for now @shaolinkhoa , please let me know if you have any further questions

**Comment by shaolinkhoa** [comment]
Hi @michaelborchardt , hi @bclement-amazon ,

I'm using ubuntu and just write code on sublime. I haven't learnt nodejs yet.

Would you mind if I ask some question ?

I made alexa echo on raspberry follow [alexa-avs-sample-app](https://github.com/alexa/alexa-avs-sample-app) and ran 2 projects follow 2 tutorials : 

- [particle-light-alexa](https://github.com/drejkim/particle-light-alexa)
- [Alexa Skill Quick Start: Make an Alexa skill in 5 minutes or less](https://developer.amazon.com/alexa-skills-kit/alexa-skill-quick-start-tutorial)

I have read code python in the quick start and code nodejs in particle-light but I can't find or understand the standard code to put in Lambda function code.
What I don't understand is how to code in **_Lambda function code_** .

So I found [Alexa Skills Kit SDK for Node.js](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs).

1. Is this the standard way to code in Lambda function and other AWS services ?
2. If I want to use python, i have to use the code in the Quick Start, right ? or there is another way to code with python ?

thank you

**Comment by kevinkey619b** [comment]
Where did i18next and all the other dependencies go? This current build isn't working anymore and I'm getting all kinds of errors regarding i18next and many other files missing?
