### ISSUE TITLE
Bring up to date with 1.0.8 with Device Address Api support

### ISSUE THREAD

**Issue by seanfisher** [alexa/alexa-skills-kit-sdk-for-nodejs#98]
It looks like this Github repo has the 1.0.6 version, but NPM has the 1.0.8 version with [Device Address API](https://developer.amazon.com/blogs/alexa/post/75db99e4-dc77-42d1-89d1-aa8b41301324/build-more-engaging-skills-with-device-address-api-and-gain-insights-with-the-new-metrics-dashboard) support.

**Comment by rmtuckerphx** [comment]
I am surprised that the Device Address API does not include timezone. All I need is the timezone in a format that can be used with Moment Timezone (https://momentjs.com/timezone/). I don't want the zipcode just to make a call to convert the zipcode to a timezone.

**Comment by michaelborchardt** [comment]
You can use timezone-js to create a timezone object from the date, state, and country.

`var x = new timezoneJS.Date('10/31/2008', 'America/New_York');`

package: https://www.npmjs.com/package/timezone-js

**Comment by knowlsie** [comment]
(If you wanna go really hardcore there's a [Google Maps Timezone API](https://developers.google.com/maps/documentation/timezone/intro). 💯 )

**Comment by michaelborchardt** [comment]
IMO Google updates their API's on too frequent of a basis for the code to have the longevity it needs. I hate making any of my work dependent on something they've constructed.

**Comment by knowlsie** [comment]
Yeah, I kinda agree - just mentioning it for a bit of a laugh really. Timezones would be nice, Amazon! Think on it.

**Comment by michaelborchardt** [comment]
My bad, I don't catch sarcasm well without facial expressions and tone.

**Comment by bclement-amazon** [comment]
@rmtuckerphx Great feedback with timezone. I've sent this feedback internally.

**Comment by EJAtPhunWare** [comment]
Absolutely, in my case it would avoid 2 additional calls to Google APIs... the funny part is that all this latency is incurred just because we want to speak back "Today's, Yesterday's" etc

**Comment by michaelborchardt** [comment]
I am now realizing that this thread is for suggesting implementations, not requesting help on implementations. Sorry guys, I'm too used to StackOverflow. This is my first time participating in a development sequence of this kind on a public forum.

**Comment by bclement-amazon** [comment]
Closing this as we've updated to 1.0.8 with [this commit](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/commit/103d623f9677d024a9950af1513779c1ce3ba2d0)
